### ISSUE TITLE
command line too long

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1157]
This issue was originally created at: 2005-05-06 02:12:37.
This issue was reported by: `chaarmeijer`.
chaarmeijer said at 2005-05-06 02:12:37
>When generating our SDK on Windows using the latest 
>Scons, python 2.4.1 and MSVC 6, the command line 
>got too long and the compile terminates. This could be 
>prevented via the use of response files with MSVC.

issues@scons said at 2005-05-06 02:12:37
>Converted from SourceForge tracker item 1196445

stevenknight said at 2006-11-08 15:28:56
>A fix has been integrated for next release that executes command lines on
>Windows directly when possible, and only uses cmd (the source of the line length
>limitation) when a command line contains a pipe or file redirection or other
>character that requires interpretation.

**Comment by adul2020** [comment]
Hello 

I am using the latest scons . but still I am getting this error.
Varsion details below
        script: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
        engine: v2.5.0.rel_2.5.0:3642:1201f1727768, 2016/06/29 17:42:26, by dholth on cardamom
        engine path: ['C:\\Python27\\lib\\site-packages\\SCons']

**Comment by bdbaddog** [comment]
@adul2020  - Please bring your issue to the users mailing list. Likely there's other issues at play. Also looks like your scons install is broken.. script 3.0.1... and engine 2.5.0...
