### ISSUE TITLE
Patches for cygwin support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1261]
This issue was originally created at: 2005-10-14 09:13:20.
This issue was reported by: `habacker`.
habacker said at 2005-10-14 09:13:20
>Hi, 
> 
>appended is a patch which completes cygwin support on windows.
> 
>The reason for this patch is, that shared libraries on cygwin has a specific 'cyg' prefix and the import library a specific '.dll.a' suffix. 
> 
>To archive this I've added the IMPLIBPREFIX and IMPLIBSUFFIX variables to distinct this settings from the static library settings, which aren't usable in that case (at least the LIBSUFFIX, the IMPLIBPREFIX is added  for completeness)   
> 
>Regards
>Ralf

habacker said at 2005-10-15 01:26:15
>I've updated the patch because of a little installation issue relating to def file.  Using def files on cygwin is optional, so I've added a USEDEFFILE env var to activate this support. 
> 
>Regards
>Ralf

issues@scons said at 2005-10-15 01:26:15
>Converted from SourceForge tracker item 1326929

stevenknight said at 2006-05-26 04:26:23
>Created an attachment (id=38)
>Patch, copied from SourceForge tracker.

gregnoel said at 2008-10-19 23:57:22
>Bug party triage.

gregnoel said at 2008-11-21 16:38:28
>Consolidate toolchain issues as 2.x p3.

gregnoel said at 2008-12-26 13:20:20
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

stevenknight attached [scons-cygwin-support.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/1261/38/scons-cygwin-support.patch) at 2008-03-25 11:08:15.
>Patch, copied from SourceForge tracker.

**Comment by mwichmann** [comment]
How does this relate to PR #3848?

**Comment by bdbaddog** [comment]
I think these patches are obsolete. Pretty sure all the logic already exists.

**Comment by bdbaddog** [comment]
Closing. obsolete.
