### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1388]
This issue was originally created at: 2006-04-15 02:09:52.
This issue was reported by: `issues@scons`.
issues@scons said at 2006-04-15 02:09:52
>(Submitted by CtengCtsh cteng@dislab.nju.edu.cn)
>Environment: Windows SP2(Simply-Chinese), Python2.4,VC6+SP5
>Source Code: helloworld.cpp(in path "d:\C_ProgremTest");
>#include<iostream>
>using namespace std;
> 
>int main(){
>	cout<<"helloworld"<<endl;
>	return 0;
>}
> 
>When execute scons, the error occurs like this:
>---------- SCons ----------
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>cl /nologo /TP /c helloworld.cpp /Fohelloworld.obj
>scons: building terminated because of errors.
>scons: *** [helloworld.obj] Exception
>Traceback (most recent call last):
>  File "C:\Python24\scons-0.96.92\SCons\Taskmaster.py",
>line 135, in execute
>    self.targets[0].build()
>  File
>"C:\Python24\scons-0.96.92\SCons\Node\__init__.py",
>line 297, in build
>    apply(executor, (self, exitstatfunc), kw)
>  File "C:\Python24\scons-0.96.92\SCons\Executor.py",
>line 125, in __call__
>    self.do_execute(target, exitstatfunc, kw)
>  File "C:\Python24\scons-0.96.92\SCons\Executor.py",
>line 118, in do_execute
>    kw)
>  File "C:\Python24\scons-0.96.92\SCons\Action.py",
>line 524, in __call__
>    show, execute, chdir)
>  File "C:\Python24\scons-0.96.92\SCons\Action.py",
>line 584, in __call__
>    return apply(c.__call__, args, kw)
>  File "C:\Python24\scons-0.96.92\SCons\Action.py",
>line 342, in __call__
>    stat = self.execute(target, source, env)
>  File "C:\Python24\scons-0.96.92\SCons\Action.py",
>line 471, in execute
>    result = spawn(shell, escape, cmd_line[0],
>cmd_line, ENV)
>  File
>"C:\Python24\scons-0.96.92\SCons\Platform\win32.py",
>line 125, in spawn
>    return exec_spawn([sh, '/C',
>escape(string.join(args))], env)
>  File
>"C:\Python24\scons-0.96.92\SCons\Platform\win32.py",
>line 115, in exec_spawn
>    result = os.spawnve(os.P_WAIT, l[0], l, env)
>UnicodeEncodeError: 'ascii' codec can't encode
>characters in position 136-140: ordinal not in range(128)

issues@scons said at 2006-04-15 02:09:52
>Converted from SourceForge tracker item 1470734

gregnoel said at 2008-08-19 13:25:17
>Bug party triage.  Needs Python 2.3.

**Comment by ajf58** [comment]
Unicode support has been greatly improved with SCons 3.0.1 and Python 3.5+. I suggest closing as fixed.

**Comment by bdbaddog** [comment]
Very old bug. No workable reproducer. Closing.
