### ISSUE TITLE
SUN C compiler

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1468]
This issue was originally created at: 2006-09-17 11:07:58.
This issue was reported by: `mrjean`.
mrjean said at 2006-09-17 11:07:58
>The SUN C compiler on Solaris is called 'cc' and not 'CC'.  Both occurences of string 'CC' in that file 
>should be changed to 'cc' in file .../SCons/Tool/suncc.py in SCons 0.96.92.
> 
>In addition, the first occurance of that string should be bound the env['CC'] and *not* to env['CXX'] as 
>currently done in that same file.

mrjean said at 2006-09-18 08:32:58
>Created an attachment (id=72)
>This is the corrected .../Tool/suncc.py file

issues@scons said at 2007-01-04 10:51:42
>Created an attachment (id=114)
>More complete detection of suncc, lifted from sunc++.py

stevenknight said at 2008-07-01 11:38:57
>Target milestone and priority per bug party triage.

garyo said at 2008-08-20 04:21:48
>Bug party triage: move to 1.x, not a regression in 1.0.

gregnoel said at 2008-09-09 14:13:35
>Bug party triage.

gregnoel said at 2008-09-27 00:21:24
>This patch is a shar archive of three files: suncc.py, sunc++.py, and a new
>file, sun_pkg.py.  Jean, could you test them?  I don't have access to a Sun
>system, but as best as I can determine by simulating pkginfo and pkgchk with
>shell scripts, these should pick up the C and C++ compilers correctly.  If you
>can check them out quickly, they should be able to be released in 1.1.
> 
>What is the Forte compiler referred to in one of the comments and how does it
>relate to the SUNpro compiler?  They both appear to be Sun products.  Should we
>be doing something for it as well?

gregnoel said at 2008-09-27 00:23:33
>Created an attachment (id=504)
>Shar archive of Sun Tools

bdbaddog said at 2008-09-27 12:34:01
>Greg,
> 
>Forte was the old name for the sun compilers, I think they may have acquired a
>company at some point.
>Eventually they relabeled it SUNpro compilers.
>(Assuming my memory doesn't fail me on this item)
> 
>-Bill

russel said at 2008-09-28 07:15:58
>Forte was the Java IDE and tool set that Sun bought in 1999.  I assume that it
>was enabled to run C and C++ projects à la NetBeans.  I would not have
>associated the term Forte with the Sun C and C++ compilers, linker and archiver,
>whereas I would associate the label SunPro with them.  Perhaps the comments in
>the sunXX.py files are misleading, i.e. g/Forte/s//SunPro/g ?
> 
>Though isn't it all called Sun Studio now?
> 
>I have a Solaris 10 machine but I do not have the Sun compiler packages
>installed.  It used to be that you got Binutils for free and had to pay for the
>C and C++ compiler, so I always just loaded the GCC toolset and used that.

gregnoel said at 2008-10-04 07:42:27
>New patch follows, with the logic cleaned up a bit.

gregnoel said at 2008-10-04 07:44:31
>Created an attachment (id=512)
>Cleaner patch 2008-10-04

mrjean said at 2008-10-04 13:31:31
>I downloaded the latest sun-tools.shar patches and installed those in a fresh copy of SCons version 
>scons-1.0.1.d20081001 on a Solaris 10 system.
> 
>As expected 2 files .../Tools/sun{cc,c++}.py were overwritten and 1 file .../Tools/sun_pkg.py was 
>added.
> 
>I ran a fresh build using this patched SCons version and the C compilers were found and ran correctly.  There are several build issues however, which are unrelated to SCons or the pathces.  Resolving those 
>will take more time.
> 
>Lastly, SUN's compilers are now all called SUN Studio something, see for 
>example<http://developers.sun.com/sunstudio/index.jsp>.  The name Forte mentioned in the SCons 
>.../Tools/sun{cc,c++}.py files appears to be obsolete.
> 
>Hope this is helpful.
> 

mrjean said at 2008-10-04 14:29:16
>A simply fix resolved all build failures occuring earlier.  This confirms that the sun-tools.shar patch works 
>correctly at least to compile C code.

stevenknight said at 2008-10-17 05:59:04
>Update target milestone to 1.2.

gregnoel said at 2008-12-04 17:41:09
>1.2 is frozen; issues that didn't make it into 1.2 are moved to 1.3.

gregnoel said at 2009-12-29 15:27:47
>This is partially implemented, but needs to be completed.  Move to 2.1 so it
>doesn't block the 1.3 release.

gregnoel said at 2009-12-29 15:40:14
>Oops, actually change the milestone.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

mrjean attached [suncc.py](https://github.com/SCons/tigris-issue-attachments/blob/master/1468/72/suncc.py) at 2006-09-18 08:32:58.
>This is the corrected .../Tool/suncc.py file

An anonymous user attached [suncc.py](https://github.com/SCons/tigris-issue-attachments/blob/master/1468/114/suncc.py) at 2007-01-04 10:51:42.
>More complete detection of suncc, lifted from sunc++.py

gregnoel attached [sun.shar](https://github.com/SCons/tigris-issue-attachments/blob/master/1468/504/sun.shar) at 2008-09-27 00:23:32.
>Shar archive of Sun Tools

gregnoel attached [sun-tools.shar](https://github.com/SCons/tigris-issue-attachments/blob/master/1468/512/sun-tools.shar) at 2008-10-04 07:44:31.
>Cleaner patch 2008-10-04

**Comment by ajf58** [comment]
Looks like what's at https://github.com/SCons/scons/blob/master/src/engine/SCons/Tool/suncc.py doesn't match `mrjean`'s version. Anyone running Solaris? I could spin up a VM, but  the attachments look correct to me when comparing against https://docs.oracle.com/cd/E37069_01/html/E37073/gjfhp.html

**Comment by bdbaddog** [comment]
Closing.   Please reopen if still an issue.
