### ISSUE TITLE
Installer fails (with registry privileges problem?)

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1490]
This issue was originally created at: 2006-11-07 17:04:41.
This issue was reported by: `jdpipe`.
jdpipe said at 2006-11-07 17:04:41
>Hi there
> 
>I've got Python installed as a 'power user' in WinXP. I installed the newest
>SCons and I get Windows registry errors about 'could not open key' then another
>error about 'could not create key'.
> 
>I logged out and then logged in using an administrator, but this time the SCons
>installer failed to locate Python in the registry (and didn't provide a way for
>me to indicate where Python was location).
> 
>This may well be a problem with py2exe, but I wanted to report the problem here
>as I haven't seen it with any of the other Python packages that I've installed
>on this machine (as 'power user').
> 
>Cheers
>JP

jdpipe said at 2006-11-07 17:05:35
>Created an attachment (id=84)
>First error dialog box

jdpipe said at 2006-11-07 17:06:04
>Created an attachment (id=85)
>Second error dialog box

stevenknight said at 2007-02-09 09:47:43
>Hi John--
> 
>You mentioned py2exe, which we don't use (yet) as part of the normal SCons
>packaging.  Did you get these errors from trying to install from the standard
>SCons self-installer (scons-0.96.93.win32.exe) or from another package that
>someone else produced?  (I vaguely recall that someone has made available a
>package from running SCons through py2exe...)
> 
>Thanks,
> 
>        --SK

jdpipe said at 2007-02-09 14:43:21
>Hi Steve,
> 
>No special packages: I used the package from the scons website. I was just
>assuming that SCons was packaged using py2exe (it had that 'look').
> 
>I should note that this was Python 2.4, which, as I recall (can't check from
>where I am ATM), I installed 'only for the current user'.
> 
>JP

gregnoel said at 2008-08-05 07:17:00
>Bug party triage.  We probably can't solve this issue; the "right" solution is
>to use some installer other than distutils.  Keep it open for now and try to
>find an installer guru who can figure out what to do.

gregnoel said at 2008-12-26 13:29:11
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

jdpipe attached [scons-install-error.png](https://github.com/SCons/tigris-issue-attachments/blob/master/1490/84/scons-install-error.png) at 2008-03-25 11:08:19.
>First error dialog box

jdpipe attached [scons-install-error-2.png](https://github.com/SCons/tigris-issue-attachments/blob/master/1490/85/scons-install-error-2.png) at 2008-03-25 11:08:19.
>Second error dialog box

**Comment by mwichmann** [comment]
The windows installer is no longer supported.
