### ISSUE TITLE
Ada (GNAT) support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1546]
This issue was originally created at: 2007-02-08 09:23:54.
This issue was reported by: `ogro`.
ogro said at 2007-02-08 09:23:54
>Hey there.
> 
>    It'd be wonderful if SCons had Ada (mainly using GNAT compiler) built in.
> 
>    In most linux system it's far easy because GNAT is part of GCC. But in some
>other systems - like Gentoo Linux - it's not this easy because GNAT is not
>integrated with GCC: it's impossible to compile Ada source using gcc
>my_source.adb simply because GCC doesn't know about any Ada compiler installed.
> 
>    For this reason I'd have to say GNAT support is required for users willing
>to build Ada sources on those operating systems.
> 
>    I'm working on this issue right now and I intend to provide a patch or
>something so the next releases can have this feature (if SCons dev's think it's
>a good thing to add to their product).
> 
>    I'm posting this feature request in the hope someone might find this useful
>and be willing to help me - I'm a nOOb both in python and naturally SCons.

stevenknight said at 2008-06-26 17:51:18
>Set priority and target milestone per bug party.
> 
>Can be moved earlier or raised in priority if additional people request Ada
>support, or someone supplies a patch.

gregnoel said at 2008-12-26 13:20:22
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

dirkbaechle said at 2014-05-18 11:48:27
>In the meantime, external Tools for Ada support have been developed in the 
>following two places:
> 
>  https://code.google.com/p/scons-ada/
> 
>and
> 
>  https://github.com/terazini/scons-gnat
> 
>.

**Comment by mwichmann** [comment]
Seems like due to low demand this might be better off as a user-contrib feature.  Two links to external resources are provided, the github one leads to a 404 and the google code one does bring up the archived page, but there are no more resources attached to it, so both "patches" are unavailable.

**Comment by bdbaddog** [comment]
Closing.
