### ISSUE TITLE
Uncleaned generated implicit dependencies and Alias

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1741]
This issue was originally created at: 2007-10-03 09:17:57.
This issue was reported by: `llasram`.
>llasram said at 2007-10-03 09:17:57

I have observed in the most recent checkpoint some almost surreal behavior on cleaning when combining implicit dependencies and Aliases.
 
In my minimal example I have two generated header files, an object file produced from a C source file which includes both headers, and an Alias referring to the object file and one of the generated headers.  Building then cleaning for the Alias results in the header not referred to by the Alias only being removed on a second clean:

```
$ ( scons example1; scons -c example1 ) | grep bheader
Touch("bheader_aliased.h")
Touch("bheader.h")
Removed bheader_aliased.h
$ scons -c example1 | grep bheader
Removed bheader.h
```

More strangely, if the C source file does /not/ include the header referred to by the Alias, then everything works as expected:

```
$ ( scons example2; scons -c example2 ) | grep bheader
Touch("bheader_aliased.h")
Touch("bheader.h")
Removed bheader_aliased.h
Removed bheader.h
```

SConstruct (which writes out minimal C source files) to follow.

>llasram said at 2007-10-03 09:18:56

Created an attachment (id=231)
Minimal issue reproduction SConscript

>stevenknight said at 2008-05-27 14:03:10

Might be related to issue #2015.

>gregnoel said at 2008-05-28 22:36:37

Bug party triage.  May be related to issue 2015.

>gregnoel said at 2008-12-26 13:29:17

Adjust triage of issues.

>stevenknight said at 2009-11-10 18:00:19

stevenknight => issues@scons

>llasram attached [SConstruct](https://github.com/SCons/tigris-issue-attachments/blob/master/1741/231/SConstruct) at 2007-10-03 09:18:56.

Minimal issue reproduction SConscript

**Comment by mwichmann** [comment]
This doesn't happen now - running the example gives the same behavior between the two. So closing.
