### ISSUE TITLE
Aliased Install fails with "Is a directory" when trying to install directories

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1751]
This issue was originally created at: 2007-10-10 17:41:40.
This issue was reported by: `benmwebb`.
benmwebb said at 2007-10-10 17:41:40
>Given a simple SConscript:
```python
Install('/tmp/scons-test/', 'testdir')
Alias('install', '/tmp/scons-test/')
```
>where 'testdir' is a directory, the following fails every time with the v0.97.0d20070918.r2446 build:
```
$ rm -rf /tmp/scons-test/; scons install
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Install directory: "testdir" as "/tmp/scons-test/testdir"
scons: *** [install] /tmp/scons-test/testdir: Is a directory
scons: building terminated because of errors.
```
> 
>However, the directory is in fact successfully installed. "scons install" also reports no errors if the target /tmp/scons-test/ directory already exists.
> 
>Oddly, specifying the target explicitly works just fine:
```
$ rm -rf /tmp/scons-test/; scons /tmp/scons-test
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Install directory: "testdir" as "/tmp/scons-test/testdir"
scons: done building targets.
```
>"scons install" also works just fine using scons v0.96.96.D001.

stevenknight said at 2008-05-27 14:15:49
>Might be related to issue #2015 and/or #1741.
> 

gregnoel said at 2008-05-30 13:10:28
>Bug party triage.  May be related to issue 2015.

gregnoel said at 2008-12-26 13:29:09
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

ajf58 said at 2014-07-07 14:56:43
>Works for me (SCons 2.3.0 on Linux).
> 
>$ scons -Q install
>Install directory: "testdir" as "/tmp/scons-test/testdir"
> 
>Suggest mark as resolved (fixed).

**Comment by mwichmann** [comment]
It's working with recent SCons as well, so closing as resolved.
