### ISSUE TITLE
waitpid - OSError: [Errno 10] No child processes

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1839]
This issue was originally created at: 2007-11-20 14:17:56.
This issue was reported by: `tom_culliton`.
tom_culliton said at 2007-11-20 14:17:56
>Looks like this may be related to Python bug tracker id 1731717 or an
>interrupted system call.  Really kind of a disconcerting issue.
> 
>Traceback (most recent call last):
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Taskmaster.py", line 194, in execute
>    self.targets[0].build()
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Node/__init__.py", line 365, in build
>    stat = apply(executor, (self,), kw)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Executor.py", line 139, in __call__
>    return self.do_execute(target, kw)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Executor.py", line 129, in do_execute
>    status = apply(act, (self.targets, self.sources, env), kw)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Action.py", line 332, in __call__
>    stat = self.execute(target, source, env)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Action.py", line 479, in execute
>    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Platform/posix.py", line 104, in
>spawnvpe_spawn
>    return exec_spawnvpe([sh, '-c', string.join(args)], env)
>  File "/usr/lib/scons-0.97.0d20070918/SCons/Platform/posix.py", line 68, in
>exec_spawnvpe
>    stat = os.spawnvpe(os.P_WAIT, l[0], l, env)
>  File "/sw/pkgs/python-2.3.5_00/lib/python2.3/os.py", line 553, in spawnvpe
>    return _spawnvef(mode, file, args, env, execvpe)
>  File "/sw/pkgs/python-2.3.5_00/lib/python2.3/os.py", line 504, in _spawnvef
>    wpid, sts = waitpid(pid, 0)
>OSError: [Errno 10] No child processes
>scons: building terminated because of errors.

tom_culliton said at 2007-11-27 14:06:41
>Among other things it looks like scons has inherited a multithread bug from the
>Python subprocess.py module in _scons_subprocess.py and added a couple instances
>of it's own in posix.py.
> 
>- The return values of os.fork are never checked for an error (-1).
>- This means that later waitpid() is called with a -1 causing "bad things" to
>happen (waiting for any process in the group).
>- Finally, the pid returned by waitpid is never checked against the input one to
>make sure that they match, meaning that this error is undetected.
> 
>This issue is preventing me from replacing a cmake/gmake based build with an
>otherwise far superior scons based build.

stevenknight said at 2007-12-09 06:33:33
>An update to Tom's previous comment:  an exchange he had with Guido at:
> 
>http://bugs.python.org/issue1731717
> 
>Indicates that the -1 issue isn't a problem in Python because the system calls
>raise exceptions on error, not return -1.
> 
>Even then, the above-referenced Python bug may be a red herring.  It discusses a
>race condition in the subprocess.py module, but as the stack trace above
>indicates, SCons invokes commands with os.spawnvpe() (which uses fork() and
>exec() directly), not with subprocess.py.  The only time right now that SCons
>uses anything from subprocess.py is in the env.backtick() method, which would
>have to be called explicitly.
> 
>So it looks like the only way this is due to the subprocess.py race condition is
>if the configuration that causes this problem uses the env.backtick() method
>*and* subprocess.py is setting up state in some way that it causes problems when
>the os._spawnvef() function is trying to wait for its children.
> 
>What we really need here is a test case that can reproduce this problem
>consistently, even if it's sporadic (one out of every four or five times, for
>example).  Can you supply something like that?
> 
>Also, under what version of Python do you observe this problem?  2.4?  If this
>is really an underlying Python problem -- especially if it's fixed in a
>readily-available later Python version -- I'm inclined to just document this as
>a known problem.  But we need it more thoroughly characterized before leaping
>there, or to any other conclusion.

garyo said at 2008-03-17 20:27:51
>Milestone: 2.x.

gregnoel said at 2008-12-26 13:20:15
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

More information about this issue is at http://bugs.python.org/issue1731717.

Votes for this issue: 10.

**Comment by mwichmann** [comment]
Updated to use migrated cpython issues link.  Haven't heard of this issue since I've been around the project... do we think this is something we need to leave open?

**Comment by bdbaddog** [comment]
Closing.
Referenced issue was fixed in Python's 2.7, 3.2.
Since 3.6 is currently our floor version, we should be safe to assume this is resolved.
