### ISSUE TITLE
Start deprecation cycle for several issues

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1954]
This issue was originally created at: 2008-03-18 18:29:44.
This issue was reported by: `gregnoel`.
gregnoel said at 2008-03-18 18:29:44
>A number of issues need to be deprecated.  It wouldn't hurt to get them in the
>release candidate, but if not, they should be in 1.0.  Here's a list, probably
>not complete:
> 
>   --debug=dtree
>   --debug=nomemoizer
>   --debug=stree
>   --debug=tree
>   env.BuildDir
>   env.Copy
>   env.SourceSignatures
>   env.TargetSignatures
>   PDFCOM
>   WIN32_INSERT_DEF
>   WIN32DEFPREFIX
>   WIN32DEFSUFFIX
>   WIN32EXPPREFIX
>   WIN32EXPSUFFIX

gregnoel said at 2008-03-18 18:30:23
>Needs to be done ASAP.

stevenknight said at 2008-03-20 08:16:10
>env.Copy() deprecated with the following commit:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5259
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1264

stevenknight said at 2008-03-20 08:29:53
>--debug=nomemoizer already had a deprecation warning.  The following commit
>moved its test script into the test/Deprecated subdirectory:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5264
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1266

stevenknight said at 2008-03-20 08:43:27
>Warnings for --debug={dtree,stree,tree} added by the following commit:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5265
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1267

stevenknight said at 2008-03-24 17:43:41
>VariantDir() added by the following commit:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5270
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1268
> 
>BuildDir() is now a synonym for VariantDir().  No actual deprecation warning
>message is printed yet, but a section about the future deprecation has been
>added to the src/RELELASE.txt file.

stevenknight said at 2008-03-24 17:46:23
>"build_dir" keyword arguments in VariantDir() and SConscript() changed to
>"variant_dir" by the following checkin:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5280
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1269
> 
>No deprecation warning message, but a section in the src/RELEASE.txt file
>discusses the future deprecation and how to prepare for it.

stevenknight said at 2008-03-27 17:59:55
>{Target,Source}Signatures() deprecated by the following series of checkins:
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5291
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1272
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5295
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1275
> 
>This also required fixing use of SetOption('warn'):
> 
>http://scons.tigris.org/servlets/ReadMsg?list=dev&msgNo=5294
>http://scons.tigris.org/servlets/ReadMsg?list=commits&msgNo=1274

stevenknight said at 2008-03-27 18:03:18
>Declaring this finished (so we can get 0.98 out the door).
> 
>I'm not going to take on deprecation warnings for the construction variables
>because there doesn't seem to be a good way to do that without a really severe
>performance impact.  If we want to track the issue for future reference (either
>to eventual code a fix, or just document it), please open up another issue.

gregnoel said at 2008-03-28 00:24:38
>No, the idea is that we should revisit this issue late in the 1.x cycle for the
>next step, so this should be marked 1.x P4 instead of being closed.

gregnoel said at 2008-12-26 13:30:36
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

**Comment by mwichmann** [comment]
All the non cvars are gone. The cvars all exist, with depr wording. So the work seems to be complete -close? What should be done with the six cvars?

**Comment by bdbaddog** [comment]
I'd say go ahead and remove them all. Add a note with the list of what's removed in CHANGES.txt and RELEASE.txt
Hrm.. would we need to bump to new major version then?

**Comment by mwichmann** [comment]
I don't know... the bug notes there's really not a good way to issue deprecation warnings for construction variables, so that wasn't done (it's deprecated in the manpage wording).  I could prepare a PR and we could apply it when it seems like there won't be another release before SCons 5.0 if that's needed?

**Comment by bdbaddog** [comment]
hmm. I'd say PR it, we'll merge. and then when ready to release decide on what version bump is needed for contetn.

**Comment by mwichmann** [comment]
Everything was deprecated so I think we can close this.  PR #3912 will complete the removal of the construction vars.

**Comment by mwichmann** [comment]
Okay, all done.
