### ISSUE TITLE
Running Scons not possible on non-English Windows platforms

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1969]
This issue was originally created at: 2008-03-31 15:14:48.
This issue was reported by: `miohtama`.
miohtama said at 2008-03-31 15:14:48
>Scons does not understand non-ASCII characters in the environment variables. It
>makes scons to die on default tool setup if environment varibles contain
>international characters (example Finnish Windows XP).
> 
>Because set-uping tool (MSVC) cannot be disabled, it is impossible to run Scons.
> 
>C:\Symbian\Carbide\workspace\uikludges20>c:\python25\python
>c:\Python25\Scripts\scons SConstruct.py
>scons: Reading SConscript files ...
>USERPROFILE C:\Documents and Settings\Jõrjestelmõnvalvoja
>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 27: ordinal
>not in range(128):
>  File "C:\Symbian\Carbide\workspace\uikludges20\SConstruct", line 14:
>    Export('env')
>  File "C:\Python25\scons-0.97\SCons\Script\SConscript.py", line 581:
>    env = self.factory()
>  File "C:\Python25\scons-0.97\SCons\Script\SConscript.py", line 561:
>    default_env = SCons.Defaults.DefaultEnvironment()
>  File "C:\Python25\scons-0.97\SCons\Defaults.py", line 66:
>    _default_env = apply(SCons.Environment.Environment, args, kw)
>  File "C:\Python25\scons-0.97\SCons\Environment.py", line 794:
>    apply_tools(self, tools, toolpath)
>  File "C:\Python25\scons-0.97\SCons\Environment.py", line 137:
>    env.Tool(tool)
>  File "C:\Python25\scons-0.97\SCons\Environment.py", line 1340:
>    tool(self)
>  File "C:\Python25\scons-0.97\SCons\Tool\__init__.py", line 157:
>    apply(self.generate, ( env, ) + args, kw)
>  File "C:\Python25\scons-0.97\SCons\Tool\default.py", line 41:
>    SCons.Tool.Tool(t)(env)
>  File "C:\Python25\scons-0.97\SCons\Tool\__init__.py", line 157:
>    apply(self.generate, ( env, ) + args, kw)
>  File "C:\Python25\scons-0.97\SCons\Tool\mslink.py", line 200:
>    include_path, lib_path, exe_path = SCons.Tool.msvc.get_msvc_paths(env,version)
>  File "c:\python25\scons-0.97\SCons\Tool\msvc.py", line 565:
>    include_path = get_msvc_path(env, "include", version)
>  File "c:\python25\scons-0.97\SCons\Tool\msvc.py", line 350:
>    return _get_msvc8_path(path, str(version_num), platform, suite)
>  File "c:\python25\scons-0.97\SCons\Tool\msvc.py", line 292:
>    dirs = _parse_msvc8_overrides(version, platform, suite)
>  File "c:\python25\scons-0.97\SCons\Tool\msvc.py", line 195:
>    settings_path = settings_path.replace(r'%' + env_var + r'%', env_vars[env_var])
> 
>Due to shortcomings in Scons design, looks like default tool is run always and
>one cannot disable individual tools. Thus, it is impossible to get Scons running.
> 
>I tried to hack my way over MSVC, but more and more errors kept coming and I
>just lost all my faith.

gregnoel said at 2008-04-02 11:41:37
>Needs features not available in Python 1.5.2; release team triage to 2.x

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

**Comment by ajf58** [comment]
We seem to have good UTF-8 support these days. I suggest closing this as cannot reproduce.

**Comment by bdbaddog** [comment]
Closing. py3.5 should resolve this issue. No useful test.
