### ISSUE TITLE
Error with installing directory through Alias

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2015]
This issue was originally created at: 2008-04-17 09:13:20.
This issue was reported by: `rmn30`.
>rmn30 said at 2008-04-17 09:13:21

With the SConstruct file:
```python
Alias('do', 'install')
Install('install', 'dir')
```
with `dir` being an (empty) directory I get the following:
```
$ scons do
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Install directory: "dir" as "install/dir"
scons: *** [do] /home/rnorton/quick_tests/scons/install/dir: Is a directory
scons: building terminated because of errors.
```
`scons install` works as expected. Why does the alias make a difference?
```
$ scons --version
SCons by Steven Knight et al.:
        engine: v0.98.0.r2725, 2008/03/31 12:52:02, by knight on bangkok
```

>rmn30 said at 2008-04-17 09:23:43

As a (possibly separate) bug, installed directories are not re-installed when their contents changes. In the above example, if a file is added to dir `scons install` does not update install/dir.

>stevenknight said at 2008-05-22 09:45:50

Target milestone per bug party triage.

>stevenknight said at 2008-05-27 14:02:49

See also issue #1741, which might be related

>stevenknight said at 2008-06-17 10:31:31

More descriptive summary

>gregnoel said at 2008-12-26 13:29:16

Adjust triage of issues.

>stevenknight said at 2009-11-10 18:00:19

stevenknight => issues@scons

**Comment by mwichmann** [comment]
I was going to say: isn't this another instance of the case that making an alias namespace entry before the thing it's going to refer to is declared basically doesn't work?

But then I tried this specific case, and it seems to just work now. 
```
$ scons do
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Install directory: "dir" as "install/dir"
scons: done building targets.
$ 
```

Close?

**Comment by bdbaddog** [comment]
Yup. Seems to be fixed. Closing.
