### ISSUE TITLE
INSTALLSTR is always stripped ?

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2018]
This issue was originally created at: 2008-04-21 04:23:56.
This issue was reported by: `cournape`.
cournape said at 2008-04-21 04:23:56
>Hi,
> 
>    I noticed a strange behavior with custom strings for the Install builder:
```python
env = Environment(INSTALLSTR = "INSTALL      $SOURCE")       
 
obj = env.Object("youpla.c")
env.Install("youpla", obj)
``` 
>When run, the INSTALLSTR is taken into account, but the whitespaces are "stripped", and scons displays:
```
INSTALL youpla.o
```
>Instead of
```
INSTALL      youpla.o
```
>I did not observe this behavior with any other builders (CC, CXX, FORTRAN, etc... It seems the problem is linked to the fact that `Install` is not created through the `Action(action, actionstring)` idiom).

stevenknight said at 2008-05-22 09:48:07
>Target milestone and reassign per bug party triage.
> 
>Greg to investigate whether this behavior is consistent with other Builders.  If not, it may be a simple matter of performing a raw (white-space preserving) substitution on the string.
> 

gregnoel said at 2009-03-05 17:43:46
>Issue #1123 and issue #2018 are variants of the same basic problem, which would be solved when https://scons.org/wiki/SubstQuoteEscapeCache is implemented.  Suggest 2.x p3 +subst draft choice.

gregnoel said at 2009-03-19 00:26:16
>Bug party triage.  Collect issues involving substitution or quoting problems under a "subst" keyword.

**Comment by mwichmann** [comment]
Changing the way `strFunc` in `install.py` calls the subst package does allow it not to strip spaces, and thus can address this issue. However, is that what we want?  After suitable import statement:
```
     if installstr:
-        return env.subst_target_source(installstr, 0, target, source)
+        return env.subst_target_source(installstr, SUBST_RAW, target, source)
```

**Comment by bdbaddog** [comment]
That would match the default strFunction() in Action.py for CommandAction().
I think that's reasonable!
