### ISSUE TITLE
SCons child processes are hanging immediately after forking

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2050]
This issue was originally created at: 2008-05-14 08:15:05.
This issue was reported by: `belley`.
belley said at 2008-05-14 08:15:05
>Hi Steven,
> 
>Scons parallel builds are hanging sporadically. I believe that I have
>isolated the cause. I would need your advice concerning the most
>appropriate fix.
> 
>The problem goes as follows:
> 
> 
>PROBLEM DESCRIPTION
>===================
> 
>A) The Python's global module import lock
>-----------------------------------------
> 
>The python interpreter has a global lock that protects the data
>structures used while importing. From example:
> 
>(gdb) up
>#<span></span>2  0x0000002a9562e2f2 in PyImport_ImportModuleLevel (name=0x2a958037d4 "errno",
>globals=0x5321b0, locals=0x2a95799270, fromlist=0x2a95816878,
>    level=-1) at ../Python-2.5.1/Python/import.c:266
>266                     PyThread_acquire_lock(import_lock, 1);
>(gdb) l
>261                     return;
>262             }
>263             if (import_lock_thread != -1 ||
>!PyThread_acquire_lock(import_lock, 0))
>264             {
>265                     PyThreadState *tstate = PyEval_SaveThread();
>266                     PyThread_acquire_lock(import_lock, 1);
>267                     PyEval_RestoreThread(tstate);
>268             }
>269             import_lock_thread = me;
>270             import_lock_level = 1;
> 
> 
>B) SCons performs imports in functions
>---------------------------------------
> 
>For example, Action.py has the following lines:
> 
>    def strfunction(self, target, source, env):
>        if self.cmdstr is None:
>            return None
>        if not self.cmdstr is _null:
>            from SCons.Subst import SUBST_RAW
> 
>Therefore, one of the Taskmaster's worker thread might be executing an
>import statement while another thread is simultanously invoking popen.
> 
>In summary, the problem occurs if we ends-up in a situation similar
>to:
> 
>   -> Thread X is in:
>         (Holds the global module import locks)
>         - builtin___import__
>         - from SCons.Subst import SUBST_RAW 
>           (or any other import)
>         - FunctionAction.strfunction
>           (for example)
>         - ...
> 
>   -> Thread Y is in:
>         - fork()
>         - any version of popen
>         - CommandAction.execute_spawn()
>           (for example)
>         - ...
> 
> 
>C) Some thread forks
>--------------------
> 
>Now, thread Y forks. In the child process, the global module import
>lock is still held. But, thread X does not exists in the child process
>(the forked child has a single thread corresponding to a copy of
>thread Y). Therefore, the global module import lock will never be
>released.
> 
> 
> 
>D) The Python implementation of exec() performs some import
>-----------------------------------------------------------
> 
>After forking, the forked child tries to exec() another
>process. Unfortunately, the Python implementation of exec() performs
>some import. For example:
> 
>File os.py from the Python 2.5.1 distribution:
> 
>def _execvpe(file, args, env=None):
>    from errno import ENOENT, ENOTDIR   (<==== line 368)
> 
>    if env is not None:
>        func = execve
>        argrest = (args, env)
>    else:
>        func = execv
>        argrest = (args,)
>        env = environ
> 
>    head, tail = path.split(file)
>    if head:
>        func(file, *argrest)
>        return
>    if 'PATH' in env:
>        envpath = env['PATH']
>    else:
>        envpath = defpath
>    PATH = envpath.split(pathsep)
>    saved_exc = None
>    saved_tb = None
>    for dir in PATH:
>        fullname = path.join(dir, file)
>        try:
>            func(fullname, *argrest)
>        except error, e:
>            tb = sys.exc_info()[2]
>            if (e.errno != ENOENT and e.errno != ENOTDIR
>                and saved_exc is None):
>                saved_exc = e
>                saved_tb = tb
>    if saved_exc:
>        raise error, saved_exc, saved_tb
>    raise error, e, tb
> 
> 
>D) Dead-lock
>------------
> 
>This causes the child to dead-lock on the global module import lock as
>demonstrated by the following stack traces:
> 
>(gdb) where
>#<span></span>0  0x0000003b6b20a66f in sem_wait () from /lib64/tls/libpthread.so.0
>#<span></span>1  0x0000002a9564139c in PyThread_acquire_lock (lock=0x5133b0, waitflag=1) at
>../Python-2.5.1/Python/thread_pthread.h:334
>#<span></span>2  0x0000002a9562e2f2 in PyImport_ImportModuleLevel (name=0x2a958037d4 "errno",
>globals=0x5321b0, locals=0x2a95799270, fromlist=0x2a95816878,
>    level=-1) at ../Python-2.5.1/Python/import.c:266
>#<span></span>3  0x0000002a95609abd in builtin___import__ (self=Variable "self" is not available.
>) at ../Python-2.5.1/Python/bltinmodule.c:47
>#<span></span>4  0x0000002a955975d3 in PyObject_Call (func=Variable "func" is not available.
>) at ../Python-2.5.1/Objects/abstract.c:1860
>#<span></span>5  0x0000002a9560e739 in PyEval_CallObjectWithKeywords (func=0x2a958005f0,
>arg=0x2a9e4de788, kw=0x0) at ../Python-2.5.1/Python/ceval.c:3433
>#<span></span>6  0x0000002a95611b4b in PyEval_EvalFrameEx (f=0x78eaa10, throwflag=Variable
>"throwflag" is not available.
>) at ../Python-2.5.1/Python/ceval.c:2063
> 
> 
>(gdb) up
>#<span></span>6  0x0000002a95611b4b in PyEval_EvalFrameEx (f=0x78eaa10, throwflag=Variable
>"throwflag" is not available.
>) at ../Python-2.5.1/Python/ceval.c:2063
>2063                            x = PyEval_CallObject(x, w);
>(gdb) p *f->f_code
>$3 = {ob_refcnt = 2, ob_type = 0x2a9578b960, co_argcount = 3, co_nlocals = 17,
>co_stacksize = 8, co_flags = 67, co_code = 0x5303c0,
>  co_consts = 0x2a95827050, co_names = 0x2a9581b310, co_varnames = 0x2a9581d350,
>co_freevars = 0x2a957f4050, co_cellvars = 0x2a957f4050,
>  co_filename = 0x2a95827090, co_name = 0x2a95825660, co_firstlineno = 367,
>co_lnotab = 0x2a95808bf8, co_zombieframe = 0x0}
>(gdb) x/s ((PyStringObject*)f->f_code->co_filename)->ob_sval
>0x2a958270b4:    "/DLlocal/belley/python2.5.1_x86_64/lib/python2.5/os.py"
> 
> 
>POTENTIAL SOLUTIONS
>===================
> 
>I think of many potential solutions:
> 
>a) Make sure that Scons never execute any import statement while
>building. I.e., all imports are executed:
>   
>   - When initializing SCons
>   - When reading SConscripts
>   - When applying SCons Tools
> 
>One the Taskmaster starts executing, no further imports should be
>performed.
> 
>This also means that anyone who writes an Action or a Builder should
>be careful to not execute any import statement inside the body of the
>Action/Builder.
> 
> 
>b) Modify _execvpe in os.py from the Python distribution to perform
>the import when os.py is loaded, instead of when _execpve is
>invoked. The issue with that approach is that we do not control the
>version of Python used to invoked scons.
> 
> 
>c) Override execvpe() in os.py with our own implementation from the
>SCons compatibility layer. It might be difficult to implement a
>version of execvpe() that works will at version of Python.
> 
> 
>Any preferences, suggestions, comments ?
> 
>Benoit

stevenknight said at 2008-05-21 17:25:10
>Hi Benoit--
> 
>Your analysis seems exactly on target.  I just did a search and found the 
>following thread from the Python-Dev mailing list describing the problem:
> 
>http://mail.python.org/pipermail/python-dev/2006-May/064983.html
> 
>Unfortunately, it looks like the thread just faded away without any action or 
>resolution.
> 
>Guido weighed in saying that he thinks "imports inside functions are overused," 
>so that suggests we should avoid the practice after Taskmaster has started, and 
>should document the problem for people writing their own stuff.
> 
>Unfortunately, *some* of the imports-within-functions occur because they were 
>the only way I found to get around some weird scoping of names, at least in some 
>early Python versions.  But my suggestion is that either you or I add a c 
>statement that will replace the "import" statement with a thrown exception right 
>before starting Taskmaster, and then run the whole test suite to see what breaks 
>under various Python versions.  In fact, I think I can kick that off pretty 
>readily.  That should identify the places that we must, at a minimum, clean up.  
>We would, of course, just comment out that statement or otherwise disable it for 
>production.
> 
>I'll start taking a look at that, but it won't hurt if we work in parallel.  Let 
>me know what you think,
> 

stevenknight said at 2008-05-21 17:54:20
>Okay, well right away I hit a serious snag in (basically) circular dependencies 
>in the way we import things.  Executor.py does an import of SCons.Defaults in 
>one of its functions.  Trying to move its import to the top of the module 
>doesn't work because SCons.Node imports SCons.Executor imports SCons.Defaults, 
>which does a *lot* of initialization right away, including trying to initialize 
>things from SCons.Builder, which pulls in SCons.Node, which pulls in 
>SCons.Node.Alias, which in turn imports SCons.Node.  Since that started the 
>circle, we get a name error.
> 
>Fixing this is going to be hairy.  Basically, we're doing way too much 
>initialization of stuff at module-import time, and have way too many places 
>where modules reach into other modules for initialization.  It's a precarious 
>rat's nest, and fixing this properly to get rid of the import statements within 
>functions is going to require cleaning it up.
> 
>The real irony is that this is happening just when QMTest/TestSCons.py tries to 
>import SCons.Node.FS, so it can introspect on some things it needs for the test 
>harness.
> 
>Feel free to take a crack at this, of course.  Based on the track record, it's 
>very possible you may hit on some ingenious solution that I'm not seeing right 
>now.
> 
>In the meantime, I'm going to mark this as 1.x, p1 so we try to take a look at 
>it sooner rather than later once 1.0 is out the door.
> 

stevenknight said at 2008-05-27 15:32:22
>IMPORTANT:  The following email message from Jamie Kirkpatrick:
> 
>    http://scons.tigris.org/servlets/ReadMsg?list=users&msgNo=13494
> 
>Indicates that this problem is not as severe in Python 2.5.2:
> 
>Date: Tue, 27 May 2008 21:52:03 +0100
>From: Jamie Kirkpatrick <jkp@kirkconsulting.co.uk>
>Subject: IMPORTANT: fix for hanging / deadlocked subprocesses
> 
>All
> 
>I've just spend and wasted a whole day trying to debug an issue that has
>previously been reported:
>http://www.nabble.com/-Issue-2050--New---SCons-child-processes-are-hanging-
>immediately-after-forking-td17233951.html.
>I would not normally have wasted any time on it, but the stack traces I was
>seeing were not the same as those shown in the bug report.  The sympoms and
>the situation were very similar to my own however.
> 
>Anyway, what I can say is that the fix for this issue, whilst the SCons
>developers refactor the code to prevent the issue internally, is to upgrade
>your python installation to 2.5.2.  In 2.5.1 they have removed the import
>statement in __execvpe that causes the problem.  This is the first thing
>anyone experiencing unexplainable, inconsitent subprocess hangs should try:
>it may well save you a serious amount of pain.
> 
>Jamie
> 

gregnoel said at 2008-12-26 13:36:52
>Adjust triage of issues.

gregnoel said at 2010-01-10 23:07:59
>I have a patch that _may_ (strong emphasis on the "may") help with this case,
>but it requires a feature from Python 2.3.  Reassign to me at 2.1 p1 and see if
>the patch fixes the race.  If it doesn't, see about importing the errno module
>in compat to see if that will avoid the race on the lock.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

**Comment by chubin** [comment]
@bdbaddog I have the same problem too. Strange enough, I had millions of builds with the same configuration before, and it never happened. And now immediately it happens almost every night build. Is there probably any quick workaround for that? That's really strange, what could be the reason for that that it started happening in an old configuration?

**Comment by mwichmann** [comment]
any changes at all?  new python version, etc.?

**Comment by chubin** [comment]
Nothing that I am aware of

**Comment by bdbaddog** [comment]
> @bdbaddog I have the same problem too. Strange enough, I had millions of builds with the same configuration before, and it never happened. And now immediately it happens almost every night build. Is there probably any quick workaround for that? That's really strange, what could be the reason for that that it started happening in an old configuration?

What version of scons, python, which platform, any info about your build. Also probably worth bringing the discussion to the users mailing list to flesh this out.. rather than adding to this issue.

**Comment by chubin** [comment]
@bdbaddog Probably you are right, I've just googled around and found this issue. I will try to debug my problem deeper; maybe it is something else, not exactly that problem that is described here. Thank you very much for answering back

**Comment by bdbaddog** [comment]
I'm going to close this as it only affects pre python 2.7 which is now the floor.
