### ISSUE TITLE
Variables: Inconsistent calls to Option.converter

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2064]
This issue was originally created at: 2008-05-21 20:44:17.
This issue was reported by: `leeus`.
leeus said at 2008-05-21 20:44:17
>The problem is that converter callable is treated differently in two places (at least), here specifically:
> 
> 
>(line 258 of `SCons/Variables/__init__.py`):
```python
defaultVal = env.subst(SCons.Util.to_String(option.default))
if option.converter:
    defaultVal = option.converter(defaultVal)
``` 
>When it should be treated in the same fashion as was treated on line 203 (same file):
```python
try:
    env[option.key] = option.converter(value)
except TypeError:
    env[option.key] = option.converter(value, env)
``` 
> 
>  The first call gives no access to the construction environment for options that really needs it (for example: for using env.Dir to construct Paths)

leeus said at 2008-05-21 21:05:11
>Created an attachment (id=417)
>Simple PATCH for the issue

gregnoel said at 2008-05-28 16:25:14
>Bug party triage.

gregnoel said at 2008-12-26 13:29:15
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

leeus attached [scons.diff](https://github.com/SCons/tigris-issue-attachments/blob/master/2064/417/scons.diff) at 2008-05-21 21:05:11.
>Simple PATCH for the issue

ipatrol said this issue blocks #2763 at 2011-05-14 12:29:10.

**Comment by mwichmann** [comment]
Is there anything broken by this problem?  It seems like the patch is easy enough to apply, but the context of a real problem isn't here and it's been over a decade since the original report....

**Comment by mwichmann** [comment]
Okay, not getting this: took a quick look, some of the variables have converter funcs, some use a lambda, and none seem to take two arguments as in the "good" example above, and none seem to take an "env".
