### ISSUE TITLE
env.Alias doesnt stick

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2110]
This issue was originally created at: 2008-06-19 15:02:28.
This issue was reported by: `jaredgrubb`.
>jaredgrubb said at 2008-06-19 15:02:28

An alias gets nodes, but then dispatches them to the wrong environment. For example, notice how building the alias 'x' causes both source files to be scanned under `env1`, even though the second source file was attached to the alias under `env2`. (I added `scons y` as an example to show that the error is not in that `env1` and `env2` are not different)
```
[(Z) jaredgrubb@jgrubb pts/3 <build> ]% scons x
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
[env1] source1.x
[env1] source2.x
scons: `x' is up to date.
scons: done building targets.
[(Z) jaredgrubb@jgrubb pts/3 <build> ]% scons y
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
[env2] source1.x
[env2] source2.x
scons: `y' is up to date.
scons: done building targets.
```

```python
# ----------- SConstruct ---------------
def printit(node, env, path):
    # Show where we are getting called from
    print "[%s] %s" % (env.name, node.path)
    return []
 
env1 = Environment()
env1.Append(SCANNERS = Scanner(function=printit, skeys=['.x'], recursive=1))
env1.name = 'env1'
 
env2 = env1.Clone()
env2.name = 'env2'
 
# One file per environment
file1 = env1.File('source1.x')
env1.Alias('x',file1)
 
file2 = env2.File('source2.x')
env2.Alias('x',file2)
 
# Just to show that env1 and env2 are different...
env2.Alias('y', file1) # malformed, but just for show
env2.Alias('y', file2)
```

>stevenknight said at 2008-06-26 17:40:37

Set priority and target milestone per bug party.  Consider delaying to 2.x if it looks complicated or highly impactive.

>gregnoel said at 2008-12-26 13:29:19

Adjust triage of issues.

>stevenknight said at 2009-11-10 18:00:19

stevenknight => issues@scons

**Comment by mwichmann** [comment]
deleted comment where I claimed it was fixed, misread things, and we're not even sure this is even valid.

**Comment by bdbaddog** [comment]
Pretty sure this issue's assertion is incorrect.
If you change the SConstruct to the following, you get the expected behavior.

`env1.Alias()` doesn't tie the builder which reads any of the .x files to a given environment.
Neither does `env1.File()
`

```
# ----------- SConstruct ---------------
def printit(node, env, path):
    # Show where we are getting called from
    print("[%s] %s" % (env.name, node.path))
    return []
 
env1 = Environment()
env1.Append(SCANNERS = Scanner(function=printit, skeys=['.x'], recursive=1))
env1.name = 'env1'
 
env2 = env1.Clone()
env2.name = 'env2'

t1 = env1.Command('t1.y','source1.x','cp $SOURCE $TARGET')
env1.Alias('x',t1)

t2 = env2.Command('t2.y','source2.x','cp $SOURCE $TARGET')
env2.Alias('x',t2)
 
# Just to show that env1 and env2 are different...
env2.Alias('y', t1) # malformed, but just for show
env2.Alias('y', t2)
```

@mwichmann - thoughts?

**Comment by mwichmann** [comment]
I'd say let's close as invalid, or as wontfix

**Comment by bdbaddog** [comment]
Closing as invalid

**Comment by bdbaddog** [comment]
Closing as invalid.
