### ISSUE TITLE
Fix faulty documentation for FORTRANCOM variable

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2128]
This issue was originally created at: 2008-07-04 08:03:19.
This issue was reported by: `aknuds_1`.
aknuds_1 said at 2008-07-04 08:03:20
>The `FORTRANCOM` variable documentation erroneously states that it includes `CPPFLAGS` and `_CPPFLAGS`.

aknuds_1 said at 2008-07-04 08:04:06
>Created an attachment (id=444)
>Fix

gregnoel said at 2008-07-15 20:08:03
>Bug party triage.  It's not clear if the documentation or the implementation is correct.  If the implementation is correct, this is a doc bug that should be fixed for 1.0 (i.e., apply the patch); if the documentation is correct, this is to be fixed in the 1.x timeframe.  David to determine which and assign to the correct milestone (and then do the needed work).

gregnoel said at 2010-07-21 16:58:12
>Bug party triage.  Bump this issue to P1 so it will be reviewed at next bug party.

gregnoel said at 2010-08-08 13:04:45
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

aknuds_1 attached [FORTRANCOM.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2128/444/FORTRANCOM.patch) at 2008-07-04 08:04:06.
>Fix

**Comment by mwichmann** [comment]
Anybody ever figure out what was correct? At the moment, `FortranCommon.py` sets `CPPFLAGS` and `_CPPDEFFLAGS` in each Fortran dialect's *PPCOM but not in the *COM construction variable. The .xml files for all these seem to differ quite a bit, however.

**Comment by mwichmann** [comment]
Okay, on the basis that "the code is the spec" absent evidence otherwise, I've pushed a PR to align the docs.  If people disagree, we cah make a change later, but fixing the docs here has no effect on existing behavior.
