### ISSUE TITLE
Not all tasks run with --jobs=2 and SideEffect

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2154]
This issue was originally created at: 2008-07-26 13:42:35.
This issue was reported by: `gregnoel`.
gregnoel said at 2008-07-26 13:42:35
>Consider this SConstruct:
> 
>    env = Environment()
>    env.Command('file2', 'log', 'cat >$TARGET $SOURCE')
>    env.SideEffect('log', env.Command('file1', [],
>	'echo >$TARGET data1; echo >log updated file1'))
> 
>Running 'scons -Q' produces the desired result (although the space after the '>'
>is unexpected):
> 
>    echo > file1 data1; echo >log updated file1
>    cat > file2 log
> 
>Running 'scons -Qc' also produces the desired result:
> 
>    Removed file1
>    Removed log
>    Removed file2
> 
>However, running 'scons -Q --jobs=2' produces an unexpected result:
> 
>    echo > file1 data1; echo >log updated file1
> 
>and the second command is MIA.  Running 'scons -Q --jobs=2' again finds the
>second command:
> 
>    cat > file2 log
> 
>This SConscript is used as an example in the Users' Guide; fixing it would be a
>really good thing...

stevenknight said at 2008-07-26 14:42:43
>Created an attachment (id=457)
>Update test/SideEffect/parallel.py script demonstrating bug

stevenknight said at 2008-07-26 14:56:00
>Okay, this is a definite bug.
> 
>It would have been caught if our test/SideEffect/parallel.py script had been a
>little more real.  The SConstruct configuration in that script was already
>configured in a way that triggers this bug, but the script itself didn't check
>to see if the build of "log.out" actually succeeded, it only checked to see if
>the entries in "log.txt" indicated things happened in the right order... :-( 
>I've attached a copy of the script that contains modifications demonstrating the
>bug.
> 
>The issue here is that if you use a SideEffect() file as the source of another
>Builder, it works fine in -j1 but not in parallel.  I'm assigning this to
>Benoit, since he has deeper knowledge of how the Taskmaster should handle
>parallel builds.
> 
>By way of a head start, I'm appending a context diff below of the
>taskmastertrace output from running Greg's configuration with -j1 (the first,
>longer, successful run) and -j2.  In the failing -j2 case, the SideEffect() file
>(log) is already in "executing" state, which means we later treat it as already
>handled.  This apparently means that the ref_count of the "file2" target that
>depends on "log" never gets decremented, and it drops out of the search for
>another node to execute, making Taskmaster think everything has finished.
> 
>I'm escalating this to 1.0.x P2.  For 1.0, I'll probably just comment out the
>relevant section of Greg's new SideEffect() chapter in the User's Guide, in
>favor of just documenting the current safe use as an interlock when multiple
>commands might update the same file.
> 
>*** trace.1     Sat Jul 26 14:07:30 2008
>--- trace.2     Sat Jul 26 14:07:42 2008
>***************
>*** 19,53 ****
>  
>  Taskmaster: Looking for a node to evaluate
>  Taskmaster:     Considering node <no_state   0   'file2'> and its children:
>! Taskmaster:        <no_state   0   'log'>
>  Taskmaster:        <no_state   0   '/bin/cat'>
>  Taskmaster:  ['log', '/bin/cat']
>  Taskmaster:      adjusting ref count: <pending    1   'file2'>
>  Taskmaster:      adjusting ref count: <pending    2   'file2'>
>- Taskmaster:     Considering node <no_state   0   'log'> and its children:
>- Taskmaster:        <executed   0   'file1'>
>- Taskmaster: Evaluating <pending    0   'log'>
>- 
>- Taskmaster: Looking for a node to evaluate
>  Taskmaster:     Considering node <no_state   0   '/bin/cat'> and its children:
>  Taskmaster: Evaluating <pending    0   '/bin/cat'>
>  
>  Taskmaster: Looking for a node to evaluate
>! Taskmaster:     Considering node <pending    0   'file2'> and its children:
>! Taskmaster:        <up_to_date 0   'log'>
>! Taskmaster:        <up_to_date 0   '/bin/cat'>
>! Taskmaster: Evaluating <pending    0   'file2'>
>  
>- Taskmaster: Looking for a node to evaluate
>- Taskmaster:     Considering node <pending    0   '.'> and its children:
>- Taskmaster:        <up_to_date 0   'SConstruct'>
>- Taskmaster:        <executed   0   'file1'>
>- Taskmaster:        <executed   0   'file2'>
>- Taskmaster:        <up_to_date 0   'log'>
>- Taskmaster: Evaluating <pending    0   '.'>
>  
>  Taskmaster: Looking for a node to evaluate
>- Taskmaster:     Considering node <up_to_date 0   'log'> and its children:
>- Taskmaster:        already handled (executed)
>  Taskmaster: No candidate anymore.
>  
>--- 19,38 ----
>  
>  Taskmaster: Looking for a node to evaluate
>  Taskmaster:     Considering node <no_state   0   'file2'> and its children:
>! Taskmaster:        <executing  0   'log'>
>  Taskmaster:        <no_state   0   '/bin/cat'>
>  Taskmaster:  ['log', '/bin/cat']
>  Taskmaster:      adjusting ref count: <pending    1   'file2'>
>  Taskmaster:      adjusting ref count: <pending    2   'file2'>
>  Taskmaster:     Considering node <no_state   0   '/bin/cat'> and its children:
>  Taskmaster: Evaluating <pending    0   '/bin/cat'>
>  
>  Taskmaster: Looking for a node to evaluate
>! Taskmaster:     Considering node <executing  0   'log'> and its children:
>! Taskmaster:        already handled (executed)
>! Taskmaster: No candidate anymore.
>  
>  
>  Taskmaster: Looking for a node to evaluate
>  Taskmaster: No candidate anymore.

stevenknight said at 2008-07-26 14:56:34
>Actually updating the Priority and Target milestone fields like I said I would.

gregnoel said at 2008-09-02 15:23:01
>Move unfinished 1.0.x issues to 1.1.

stevenknight said at 2008-10-17 05:59:03
>Update target milestone to 1.2.

gregnoel said at 2008-12-04 17:41:09
>1.2 is frozen; issues that didn't make it into 1.2 are moved to 1.3.

gregnoel said at 2010-01-20 03:36:10
>Not completed in time for the 1.3 release; move to 2.1 p1.

garyo said at 2011-03-10 18:03:13
>Benoit is no longer involved with the SCons project, reassigning his issues back 
>to triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

ajf58 said at 2014-07-07 11:21:02
>Works for me using SCons 2.3.0 on Linux.
> 
>$ scons -Q
>echo > file1 data1; echo >log updated file1
>cat > file2 log
>$ scons -Qc
>Removed file1
>Removed log
>Removed file2
>$ scons -Q --jobs=2
>echo > file1 data1; echo >log updated file1
>cat > file2 log
> 
>Suggest marking as resolved (fixed).

dirkbaechle said at 2014-07-12 03:43:38
>When patching the test/SideEffect/parallel.py as suggested by Steven, it fails on 
>my system (Ubuntu LTS 14.04 LTS, Python 2.7, SCons 2.3.2). So we can't close this 
>right now, it definitely needs further investigation and a fix that lets the 
>extended test pass.

stevenknight attached [parallel.py](https://github.com/SCons/tigris-issue-attachments/blob/master/2154/457/parallel.py) at 2008-07-26 14:42:43.
>Update test/SideEffect/parallel.py script demonstrating bug

**Comment by mwichmann** [comment]
I just tried this, because it's the same example that is in a User Guide chapter (as noted in the initial filing), which is being excluded from the guide presumably because of this issue.  It seems to work fine.  What's more, the extended testcase, if ported to Python3, also passes. How to proceed?  Close-as-fixed? Update the testcase and close? Other?  And in particular - what to do with the userguide chapter?  I don't know where in the order it was intended to be.

**Comment by bdbaddog** [comment]
Yes. 
I think update the extended testcase attach to this issue.
Then close as fixed in 4.0.1+
