### ISSUE TITLE
Glob() should not return leaf nodes

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2188]
This issue was originally created at: 2008-08-27 16:50:20.
This issue was reported by: `gregnoel`.
gregnoel said at 2008-08-27 16:50:20

>Consider this SConscript:
```
    File('foo')
    print([str(s) for s in Glob('foo')]
```
>`Glob()` reports the existence of `foo` despite the fact it does not exist and cannot be built.  The equivalent SConscript using `FindFile()`:
```
    File('foo')
    print FindFile('foo', '.')
```
>returns None.
> 
>I think `Glob()` should follow the same convention and only return derived files (i.e., files with an attached Builder).

gregnoel said at 2008-09-02 14:32:36
>Bug party triage.

gregnoel said at 2008-12-26 13:30:37
>Adjust triage of issues.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

**Comment by mwichmann** [comment]
There are two questions here for me:

1. Should `Glob` return anything that doesn't exist in the file system.  Note that at least one other build system does not: https://docs.bazel.build/versions/master/be/functions.html#glob which includes this comment: "_looks only for source files (not generated files nor other targets_"
2. Should `Glob` return files that cannot be made by SCons, as this issue asks.

**Comment by bdbaddog** [comment]
1. Yes
2. Yes

Any files SCons knows how to build whether they're currently exist or not, as well as files which aren't built by SCons but exist on the filesystem.

**Comment by bdbaddog** [comment]
I'm going to close this issue.
Changing the existing behavior wouldn't be an improvement.
This issue is from 2008, Glob() was introduced to SCons in 2007.
