### ISSUE TITLE
Installer fails to detect Python 2.5.2 64-bit on Windows

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2191]
This issue was originally created at: 2008-09-02 21:20:25.
This issue was reported by: `kirr`.
kirr said at 2008-09-02 21:20:30
>OS: Windows Vista Business Edition 64-bit
>Python: "Python 2.5.2 Windows AMD64 installer"
>( http://www.python.org/ftp/python/2.5.2/python-2.5.2.amd64.msi )
> 
>I downloaded "scons-1.0.0.d20080826.win32.exe". Running it, it sais it can't
>find any Python registered in registry. Also there is no way to select it manually.
> 
>Uninstalled Python 2.5.2 Windows AMD64, installed normal 32-bit Python 2.5.2.
>Re-running scons installer, all is fine.
> 
>I do however like to use the 64-bit Python. Hopefully it's easy to fix. Thanks.

gregnoel said at 2008-09-09 11:55:17
>Bug party triage.

gregnoel said at 2008-12-26 13:30:39
>Adjust triage of issues.

tareqsiraj said at 2010-03-18 10:53:01
>I'm having the same problem.
> 
>SCons version: 1.2.0.d20100306
>Windows Server 2008 x64
>ActivePython 2.6.4.10 64bit

garyo said at 2012-07-22 14:07:20
>I tracked this down to a registry issue; 32 bit python stores its info in the 32 
>bit registry (SYSWOW64) and 64 bit uses the regular (64 bit) registry.  The 
>distutils win32 installer stub isn't smart enough to look in both registry trees 
>so it fails to find 64-bit pythons.  It's a known problem apparently; one bug 
>report is at http://bugs.python.org/issue6792.
> 
>Also the distutils code on Linux makes it nearly impossible to build a 64-bit 
>Windows installer (we do all builds on Linux) without patching distutils itself.  
>The simplest workaround for now is for 64-bit Windows python users to use the zip 
>file rather than the installer.

Votes for this issue: 1.

**Comment by mwichmann** [comment]
The windows installer is no longer supported.
