### ISSUE TITLE
Add HeapMonitor to SCons

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2197]
This issue was originally created at: 2008-09-05 13:17:19.
This issue was reported by: `gregnoel`.
gregnoel said at 2008-09-05 13:17:19
>Apply the HeapMonitor branch to the trunk.  There are several things that must
>be done:
> 
> - Create a blurb (or more than one?) about the new features being added and
>post them to the (user) mailing list.
> 
> - Make any changes based on user feedback.
> 
> - Break the HeapMonitor changes down into a set of reviewable patches.
> 
> - Post the reviews for comments on the (developer) mailing list
> 
> - If the review is acceptable, apply the patches to the trunk
> 
> - Close any issues that are fixed by the changes
> 
>And any other items that may be added in subsequent comments.

gregnoel said at 2008-09-09 14:03:00
>Bug party triage.  Congratulations on finishing the project so well.

**Comment by mwichmann** [comment]
What is the status of this? Applied? Lost in the weeds? There is no heapmonitor branch on github anyway.

**Comment by bdbaddog** [comment]
Lost. Closing.
