### ISSUE TITLE
Created Builder for Motif Uil files

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2222]
This issue was originally created at: 2008-09-26 08:38:11.
This issue was reported by: `rlogel`.
rlogel said at 2008-09-26 08:38:11
>Created a build for Motif Uil files which will also scan for included files.

rlogel said at 2008-09-26 08:39:10
>Created an attachment (id=503)
>SVN diff from the trunk/src/engine/SCons directory

rlogel said at 2008-09-26 08:40:19
>The swig and m4 builders were used as a template

gregnoel said at 2008-10-01 22:44:40
>Bug party triage.  Needs docs and tests, and probably shouldn't be generated in
>every Environment by default (we already have too many).  Gary to monitor and
>help out; once the doc and tests are ready, he will take the patch and apply it.

gregnoel said at 2008-12-26 13:30:38
>Adjust triage of issues.

rlogel attached [uil.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2222/503/uil.patch) at 2008-09-26 08:39:10.
>SVN diff from the trunk/src/engine/SCons directory

**Comment by mwichmann** [comment]
Anybody still uses Motif?

**Comment by bdbaddog** [comment]
Closing.
No one's asked for or about this in a very long time.
