### ISSUE TITLE
Tests fail on Windows when file path to python contains \t

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2254]
This issue was originally created at: 2008-11-10 22:44:08.
This issue was reported by: `gspencer`.
gspencer said at 2008-11-10 22:44:08
>Because of the quoting that occurs in some of the tests (specifically `tests\Command.py`), if your python exists in a directory tree that has a name that starts with a 't' as one of its components, then that "\t" gets converted to a tab, and that test can't find python anymore.
> 
>For instance, if you have python installed in C:\bin\test\python.exe, it will look for "C:\bin est\python.exe" (where the space is really a tab), and the test will fail.
> 
>My fix simply escapes all backslashes in the python executable path inside of TestSCons.py.
> 
>10 more test pass on Windows with this fix (assuming a vulnerable installation
>path).

gspencer said at 2008-11-10 22:46:42
>Created an attachment (id=533)
>Patch for issue

gspencer said at 2008-11-10 23:41:13
>Reassigning to Steven

gspencer said at 2008-11-12 18:37:19
>Created an attachment (id=536)
>This is a better patch, which also fixes a lot of tests that fail on Win32.

gregnoel said at 2008-11-21 17:33:40
>Bug party triage.  Maybe use a quoting function that handles other conditions as
>well, like spaces?

gregnoel said at 2008-12-26 13:30:36
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

Votes for this issue: 1.

gspencer attached [TestSCons.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2254/533/TestSCons.patch) at 2008-11-10 22:46:42.
>Patch for issue

gspencer attached [fix_tests.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2254/536/fix_tests.patch) at 2008-11-12 18:37:19.
>This is a better patch, which also fixes a lot of tests that fail on Win32.

**Comment by mwichmann** [comment]
I'll self-assign this one for a look eventually, but think there's been a fair bit of attention to how the path to Python is supplied, so maybe not an issue any more?

**Comment by bdbaddog** [comment]
Interesting so this is in the runtest.py,etc logic.
It's possible it's still an issue.

**Comment by mwichmann** [comment]
Well, I *think* all the troublesome instances of pasting the path to the Python interpreter have been converted to enter raw strings.  I can't prove it - grepping isn't informative enough, as `_python_` and `python` from TestCmd are also used in "expect" strings, so would have to go look at dozens of locations manually to be sure.

**Comment by bdbaddog** [comment]
I was thinking just install a version of python into c:\test\python... and run the tests?

**Comment by mwichmann** [comment]
I finally got a non-compromised run with a setup which has Python in a path that has both a `\t` and a `\b` in it, and there were no new problems.

**Comment by bdbaddog** [comment]
@mwichmann - so bug is resolved then? Should I close?

**Comment by mwichmann** [comment]
I think so.  Can always reopen if there's proof of a problem.

**Comment by bdbaddog** [comment]
O.k. Closing
