### ISSUE TITLE
FORTRANFLAGS not included when compiling .f90 files

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2257]
This issue was originally created at: 2008-11-11 22:48:13.
This issue was reported by: `audiofanatic`.
audiofanatic said at 2008-11-11 22:48:13

>We have a mix of fortran files with file extensions .F .f and .f90. In all cases, the SCons man page says the contents of the `FORTRANFLAGS` variable will be included, but (in scons v1.1.0 at least), the `FORTRANFLAGS` contents are not getting added to the compile line for .f90 files (confirmed under linux and Windows). I cannot be sure if this has always been the case or if it only changed between version 0.98.5 and 1.1.0, but we've only just encountered this issue now when building under Windows and I'm fairly sure it used to build okay with 0.98.5.

gregnoel said at 2008-11-21 17:42:46
>Bug party triage.

gregnoel said at 2010-01-20 03:37:53
>Not completed in time for the 1.3 release; move to 2.1 p2.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by dnwillia** [comment]
Would be great if this could be fixed, despite not many of us compiling Fortran using SCons.

**Comment by james-thunes** [comment]
Bump from me as well. Hopefully this can get sorted. Or, at the very least, have the doc updated to match the current behavior. I spent a couple hours tracking down an issue related to FORTRANFLAGS not getting added when compiling F90 source files.

**Comment by bdbaddog** [comment]
@dnwillia & @james-thunes - Is this still the case with 4.3.0 and/or current development version?

**Comment by james-thunes** [comment]
@bdbaddog I'm using version 4.0.1. 
Here's the full version info:
`SCons: v4.0.1.c289977f8b34786ab6c334311e232886da7e8df1, 2020-07-17 01:50:03, by bdbaddog on ProDog2020`

Was this fixed in more recent versions?

**Comment by mwichmann** [comment]
Don't think any of this has been touched recently, it's just a "standard question" to help narrow things down.

If I dump the environment and look at the command-string values, they look like the following paste.  The Fortran stuff is weird, it's supposed to have a common piece, and then some specialization for specific dialects, such that if you specifically use a .f90 file it would get special treatment. the 'PP' lines are for use if the sources are expected to run through the C preprocessor. 
```python
  'F03COM': '$F03 -o $TARGET -c $F03FLAGS $_F03INCFLAGS $_FORTRANMODFLAG ' '$SOURCES',
  'F03PPCOM': '$F03 -o $TARGET -c $F03FLAGS $CPPFLAGS $_CPPDEFFLAGS ' '$_F03INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F08COM': '$F08 -o $TARGET -c $F08FLAGS $_F08INCFLAGS $_FORTRANMODFLAG ' '$SOURCES',
  'F08PPCOM': '$F08 -o $TARGET -c $F08FLAGS $CPPFLAGS $_CPPDEFFLAGS ' '$_F08INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F77COM': '$F77 -o $TARGET -c $F77FLAGS $_F77INCFLAGS $SOURCES',
  'F77PPCOM': '$F77 -o $TARGET -c $F77FLAGS $CPPFLAGS $_CPPDEFFLAGS ' '$_F77INCFLAGS $SOURCES',
  'F90COM': '$F90 -o $TARGET -c $F90FLAGS $_F90INCFLAGS $_FORTRANMODFLAG ' '$SOURCES',
  'F90PPCOM': '$F90 -o $TARGET -c $F90FLAGS $CPPFLAGS $_CPPDEFFLAGS ' '$_F90INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'F95COM': '$F95 -o $TARGET -c $F95FLAGS $_F95INCFLAGS $_FORTRANMODFLAG ' '$SOURCES',
  'F95PPCOM': '$F95 -o $TARGET -c $F95FLAGS $CPPFLAGS $_CPPDEFFLAGS ' '$_F95INCFLAGS $_FORTRANMODFLAG $SOURCES',
  'FORTRANCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $_FORTRANINCFLAGS ' '$_FORTRANMODFLAG $SOURCES',
  'FORTRANPPCOM': '$FORTRAN -o $TARGET -c $FORTRANFLAGS $CPPFLAGS ' '$_CPPDEFFLAGS $_FORTRANINCFLAGS $_FORTRANMODFLAG $SOURCES',
```
*None* of the specialized versions include `FORTRANFLAGS`, instead they use their own dialect-specific flag.

Any further information - like a simple example that trips over this - might help track things down.

**Comment by james-thunes** [comment]
I set up a minimal example with four files called hello77.f, hello77v2.f, hello90.f90, hello90v2.f90. All had the same contents (shown at the bottom of the comment). I then made a minimal SConstruct with four programs:
```py
fortranFlags = ['-Wall']
f77Flags = ['-Werror']
f90Flags = ['-Werror']

# f77 with fortranFlags
Program('h77', 'hello77.f',  FORTRANFLAGS=fortranFlags)

# f77 with f77Flags
Program('h77v2', 'hello77v2.f', F77FLAGS=f77Flags)

# f90 with fortranFlags
Program('h90', 'hello90.f90', FORTRANFLAGS=fortranFlags)

# f90 with f90Flags
Program('h90v2', 'hello90v2.f90', F90FLAGS=f90Flags)
```

As you can see, the programs are compiled with either `FORTRANFLAGS` or `F77FLAGS`|`F90FLAGS` (depending on the format). 

The output of compiling with scons is
```console
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gfortran -o hello77.o -c -Wall hello77.f
gfortran -o hello77v2.o -c hello77v2.f
gfortran -o hello90.o -c hello90.f90
gfortran -o hello90v2.o -c -Werror hello90v2.f90
scons: done building targets.
```
The output clearly shows that `FORTRANFLAGS` are applied to the *.f file and `F90FLAGS` are applied to the *.f90 file. 

Incidentally, I did also try explicitly setting `F77='ifort'` to set the compiler for program h77v2. The compiler was ignored in favor of `gfortran`

source file:
```fortran
      program hello
        print *, "Hello"
      end program hello
```

**Comment by mwichmann** [comment]
Thanks for the sample.  As mentioned on DIscord, it doesn't look like SCons' "other" Fortran tools make any effort to account for `FORTRANFLAGS` and any other ostensibly generic-Fortran construction variables.  We'll have to figure out what the way forward is.

**Comment by james-thunes** [comment]
> Thanks for the sample. As mentioned on DIscord, it doesn't look like SCons' "other" Fortran tools make any effort to account for `FORTRANFLAGS` and any other ostensibly generic-Fortran construction variables. We'll have to figure out what the way forward is.

No problem. It would be nice to have a common set of flags I can apply to all fortran source files, but I'd be happy with setting separately if that's the way that you decide to go. As long as the doc is consistent with the behavior either seem acceptable solutions.

**Comment by dnwillia-work** [comment]
At the very least the documentation is incorrect as it does not document the current behavior.  eg:

https://scons.org/doc/4.3.0/HTML/scons-user/apa.html#cv-F90FLAGS

Until you figure out what to do maybe that should be updated.

**Comment by mwichmann** [comment]
Will certainly clarify.  I'm a little worried that "I don't think this means what you think it means", but the people involved with what the code looks like now are not available to ask their intent - unless @bdbaddog has some memory (I don't think he worked on Fortran support though, back in the day).

It seems that gfortran - and possibly other compilers - consider file suffixes from `.f95` on to be free-form whereas `.f` is fixed-form, unless you say otherwise by use of flags.  This kind of suggests against SCons itself trying to detect "different compilers" based on file suffixes, but I guess that's a different question.

Per this from the above:

> Incidentally, I did also try explicitly setting `F77='ifort'` to set the compiler for program h77v2. The compiler was ignored in favor of gfortran

I think you actually have to specify the tool to get that to work, something similar to:
```py
env = Environment(tools=['ifort', 'defaults'])
```

**Comment by mwichmann** [comment]
> > Incidentally, I did also try explicitly setting `F77='ifort'` to set the compiler for program h77v2. The compiler was ignored in favor of gfortran
> 
> I think you actually have to specify the tool to get that to work

Or... make sure gfortran/g77 aren't available so the autodetection goes on and finds ifort.

**Comment by james-thunes** [comment]
yeah, makes sense. Believe me, I understand trying to decipher code long past the original developers worked on it. 

Thanks for the comment about setting the compiler.

**Comment by dnwillia-work** [comment]
I agree about using the tool, however, regarding the ifort tool, it's quite out of date w.r.t. the latest compilers (last time I looked).  

That's a separate issue I suppose.

**Comment by mwichmann** [comment]
#2143 would appear somewhat related.

**Comment by mwichmann** [comment]
>...regarding the ifort tool, it's quite out of date w.r.t. the latest compilers (last time I looked).
> 
> That's a separate issue I suppose.

It is.  That *may* be what #2752 is about. In any case, there is a related issue on this - #3962 - I have the current Intel compiler suite installed on one box, it's been rebranded OneAPI and completely restructured from "the old days", and I assume SCons won't find anything at all related to its use - that's not specific to Fortran; I'm not even sure if Fortran is included in that, because I didn't make any attempt to install it at the time.

**Comment by mwichmann** [comment]
Yes, Fortran is now part of the OneAPI suite: https://www.intel.com/content/www/us/en/developer/tools/oneapi/fortran-compiler.html

**Comment by dnwillia-work** [comment]
Yes, it's included into that for the latest releases.  

At some point I took the existing tool (~7-8 years ago) and hacked it up to support the ifort compilers as we've upgraded over the years.  I certainly don't mind sharing this if you want.

**Comment by mwichmann** [comment]
Contribution certainly welcome!

**Comment by mwichmann** [comment]
There's new documentation, not published yet, but in docbook form you can see it at: https://github.com/SCons/scons/blob/067e290d832e17158aeb068bddb39dc9ad46d5cc/doc/man/scons.xml#L7493.  This should hopefully make some of the behavior of "dialects" a bit more clear.  It's not as clear as it could be, because I still don't entirely understand things.

Since available evidence is that `FORTRANFLAGS` is intended not to propagate to other dialects (each dialect-specific flags testcase specifically sets a flag in `FORTRANFLAGS` and makes sure it does not appear on the issued command line), the linked PR #4180 proposes a new `FORTRANCOMMONFLAGS` instead, which does propagate.

**Comment by james-thunes** [comment]
Thanks @mwichmann. Glad we could get a solution. I think `FORTRANCOMMONFLAGS` should give us what we were looking for.

**Comment by dnwillia** [comment]
Thanks for sharing the PR, FORTRANCOMMONFLAGS does the expected thing now, thanks @mwichmann.
