### ISSUE TITLE
Thread-safe model

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2263]
This issue was originally created at: 2008-11-21 17:15:32.
This issue was reported by: `gregnoel`.
gregnoel said at 2008-11-21 17:15:32
>Write a wiki page under the design docs about a thread-safe model for SCons.

gregnoel said at 2008-11-21 17:17:16
>Set milestone and priority, also peanut gallery.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

**Comment by ajf58** [comment]
The wiki's description of [TaskMaster](https://github.com/SCons/scons/wiki/TaskMaster) includes what happens with concurrent jobs. I suggest resolving as fixed.
