### ISSUE TITLE
scons -h should print new options

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2356]
This issue was originally created at: 2009-02-24 13:54:13.
This issue was reported by: `stevenknight`.

>stevenknight said at 2009-02-24 13:54:13

If you add options to SCons via `AddOption()`, SCons will print them in its optparse-style help shown by `scons -h`.
 
However, if you also add help text via `Help()`, SCons no longer prints the optparse-style help.  You can still see help on SCons's built-in command line options using `scons -H`, but since that doesn't parse the SConscript files it doesn't show any of the added options.
 
The feature request is for SCons to maintain a second optparse instance containing only the options added via `AddOption()`.  If help text has been added via `Help()`, SCons could print only the optparse help for this second optparse instance, followed by the text added via `Help()`.
 
The text of the final line of help: 'Use scons -H for help about command-line options.' should also be changed to something like  'Use scons -H for help about scons built-in command-line options.' since it doesn't print help about ALL command line options, only those built into SCons.

>gregnoel said at 2009-03-05 15:16:13

Bug party triage.

>stevenknight said at 2009-11-10 18:00:20

stevenknight => issues@scons

**Comment by mwichmann** [comment]
Adding comments to let github linking work: see also #2611, #2258, #2831.  Since two of those are closed (one as a dup, one resolved), is this still an issue?

**Comment by mwichmann** [comment]
The current behavior is documented, but I don't like it either.  All options added via `AddOption` already go into a separate option group (`local_option_group`, which is a `SConsOptionGroup`), so it should be possible to fish them out separately... it's not trivial because of the way help is processed, but should be doable.

**Comment by mwichmann** [comment]
I have an implementation that fishes the help out of the local option group. The question now is what the right way to present this is. 

```py
Help(txt)  # all existing help text is tossed
Help(txt, append=True)  # full help is saved, SCons + AddOption
Help(txt, local_only=True)  # SCons help is tossed, but AddOption text is saved
```

It feels to me that the primary behavior should be that of the tentatively-named `local_only` (that is, that's what should happen when the longer-standing `append=True` is given), and the less-common option should be to also save the SCons help.

Also the sense of the flags could change:  in the experimental version you need `append` False and `local_only` True to save the local help, but that could easily be both-True.
