### ISSUE TITLE
bug in _defines() method in Defaults.py

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2363]
This issue was originally created at: 2009-03-03 17:44:03.
This issue was reported by: `drowley`.
drowley said at 2009-03-03 17:44:03

>The following SConstruct executes the wrong compile command:
```python
env = Environment()
env.Replace(CPPDEFINES="${DEFS}", DEFS=["foo1", "foo2"])
objects = env.Program("test", env.Glob("main.cpp"))
``` 
> 
>Expected command:  `g++ -o main.o -c -Dfoo1 -Dfoo2 main.cpp`
> 
>Actual command:    `g++ -o main.o -c "-Dfoo1 foo2" main.cpp`
> 
> 
>I think the bug is in the following line in Defaults.py:
```python
    return c(prefix, env.subst_path(l), suffix, env)
```
> 
>should probably be:
```python
    return c(prefix, env.subst_list(l), suffix, env)
``` 
>However, `subst_list()` returns `[["foo1", "foo2"]]` and the `_concat_ixes()` method doesn't handle nested lists. So the following line should probably also be added at the beginning of `_concat_ixes()`:
```python
    list = SCons.Util.flatten(list)
```
gregnoel said at 2009-04-10 08:02:31
>Bug party triage.  Gary to apply patch and see if breaks anything.

**Comment by mwichmann** [comment]
I wonder if this is still a problem?  If it's the same line (not a lot of reference in the above) it now looks like:
```
    return c(prefix, env.subst_path(processDefines(defs)), suffix, env)
```
Where processDefines does what looks like the required cleanup. Perhaps fixed?

**Comment by bdbaddog** [comment]
Looks like not fixed.

```
% python ../../as_scons/scripts/scons.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o main.o -c "-Dfoo1 foo2" main.cpp
g++ -o test main.o
scons: done building targets.
```

**Comment by mwichmann** [comment]
and if making the proposed change (`subst_paths` to `subst_list`) we get a new result:
```
g++ -o main.o -c "-D['foo1', 'foo2']" main.cpp
```

that's not right either. But adding the additional `Flatten` does make it turn out as expected:
```
g++ -o main.o -c -Dfoo1 -Dfoo2 main.cpp
```

**Comment by mwichmann** [comment]
So this patch, then, would yield the desired result. But is it correct? (I renamed the parameter named _list_ since it's usually a poor name as it overwrites the builtin). SCons testsuite still passes...

[Defaults.txt](https://github.com/SCons/scons/files/5793271/Defaults.txt)

**Comment by bdbaddog** [comment]
Hmm.. I can see expecting the results the original reporter expects..

**Comment by bdbaddog** [comment]
I'd guess you could get away with a unit test to test it rather than a system test if you wanted to PR it.. ;)

**Comment by mwichmann** [comment]
I can't seem to make one that works. I thought something like this:
```python
env.Replace(CPPDEFINES="${DEFS}", DEFS=["foo", "bar"])
macros = env.subst('$_CPPDEFFLAGS', raw=1)
print(f"\nDEBUG: {env['CPPDEFINES']=}, {env['DEFS']=}, {macros=}\n")
expect = ["-Dfoo", "-Dbar"]
assert macros == expect, macros
```
But that appears to expand to... nothing (thus the debug print)... I'm doing something wrong, obviously. Similar sort of thing externally - just an SConstruct - does expand.
