### ISSUE TITLE
Document checkout patterns

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2366]
This issue was originally created at: 2009-03-05 09:56:07.
This issue was reported by: `gregnoel`.
gregnoel said at 2009-03-05 09:56:07
>Document patterns to allow a VCS tree to be checked out and used.  See issue
>1905 for some possible starting points.

gregnoel said at 2009-03-19 02:32:15
>Bug party triage.  Document the serial pattern using Requires(), then reassign
>the milestone to be the same as the TaskmasterNG issues and revise the pattern
>to use whatever API is used for before/after serialization.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

**Comment by mwichmann** [comment]
Move to github didn't preserve links to other issues, adding one back: see #1905

**Comment by mwichmann** [comment]
Find this issue a bit confusing... it doesn't say so explicitly, but this has to do with having a project using SCons be able to do checkouts when building, right (and not working on SCons itself)?  But then I didn't understand the initial response - why is such usage tied to TaskmasterNG, which did not hatch into existence anyway?  What would we document? What does "serial pattern using `Requires`" translate into in documentation-ese?

**Comment by bdbaddog** [comment]
There used to be env methods to checkout from revision control systems.
They've been long removed.

```# Will fetch foo/bar/src.c
# from /usr/local/CVSROOT/foo/bar/src.c.
env.SourceCode('.', env.CVS('/usr/local/CVSROOT'))
```

This issue can be closed.
