### ISSUE TITLE
Change --cache-<option> flags into --cache=<option>

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2375]
This issue was originally created at: 2009-03-19 00:47:47.
This issue was reported by: `gregnoel`.
gregnoel said at 2009-03-19 00:47:47
>With the exception of --cache-debug=<file>, none of the flags that control the
>cache subsystem take a value.  Instead of a clutter of flags, combine them into
>one form: --cache=<option> so there are only two command-line flags.
> 
>After this is implemented, the --cache-<option> flags should be deprecated out.

gregnoel said at 2009-04-10 09:05:36
>Bug party triage.

gregnoel said at 2010-07-16 07:19:20
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

ipatrol said this issue depends on #2763 at 2011-05-14 12:29:10.

**Comment by mwichmann** [comment]
Should this include the **implicit** options too?
```
  --implicit-cache            Cache implicit dependencies
  --implicit-deps-changed     Ignore cached implicit dependencies.
  --implicit-deps-unchanged   Ignore changes in implicit dependencies.
```

**Comment by mwichmann** [comment]
and I'm going to answer myself: despite unfortunately including the word "cache" this is something completely unrelated to the build cache. The question still exists - would people prefer to see this recast as `--implicit=cache` from `--implicit-cache`?

Is this work overall even worthwhile?

**Comment by bdbaddog** [comment]
I'm going to say no, and close this.
