### ISSUE TITLE
Inconsistent treatment of strings as CXXFLAGS

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2399]
This issue was originally created at: 2009-04-10 23:48:43.
This issue was reported by: `russel`.
russel said at 2009-04-10 23:48:43
>The following raised on the email lists was responded to with a number of replies saying "its a bug", hence this issue.
> 
>I am seeing a difference in behaviour of SCons (Subversion Trunk) on Ubuntu 8.10 and Mac OS X 10.5.  In the SConscript (well actually a subsidiary SConstruct but I don't think that matters) I have:
```python
environment['CXXFLAGS'] += '-O3 -W -Wall -Wundef  -Wcast-align -Wno-unused-parameter -Wshadow -Wredundant-decls'
```
> 
>This works fine on Ubuntu but fails on Mac OS X.  On Mac OS X I have to have:
```python
environment['CXXFLAGS'] += ['-O3' , '-W' , '-Wall' , '-Wundef' , '-Wcast-align' , '-Wno-unused-parameter' , '-Wshadow' , '-Wredundant-decls']
```
> 
>which also works fine on Ubuntu.  Now in some sense the latter is clearly more correct, so the question is whether it is a bug that the former works at all on Ubuntu.
> 
>Thanks.

gregnoel said at 2009-04-15 20:31:11
>Bug party triage.

dirkbaechle said at 2014-07-13 09:08:32
>It would be cool if someone with access to a Mac could confirm whether this is still an issue in SCons >= 2.3.2, or not.
> 
>My suspicion is, that this got fixed in the meantime by initializing CXXFLAGS to a CLVar(''). Otherwise this could probably get marked as duplicate of issue #2962, and resolved that way.

bdbaddog said at 2014-07-20 18:33:10
>Still an issue on mac.

bdbaddog said at 2014-07-20 19:54:58
>Here's a dummy SConstruct to try this out.
> 
>Fails on both mac and ubuntu for me:

```python
import os.path
 
if not os.path.exists('test2399.cxx'):
    open('test2399.cxx','w').write("""
 
#include <stdio.h>
 
main()
{
    printf("Hello World");
}
""")
 
env=Environment()
 
if True:
    env['CXXFLAGS'] += '-O3 -W -Wall -Wundef  -Wcast-align -Wno-unused-parameter -Wshadow -Wredundant-decls'
else:
    env['CXXFLAGS'] += ['-O3' , '-W' , '-Wall' , '-Wundef' ,  '-Wcast-align', '-Wno-unused-parameter' , '-Wshadow' , '-Wredundant-decls']
 
env.Program('blah','test2399.cxx')
```

**Comment by mwichmann** [comment]
This is because `CLVar` has no `__iadd__` dunder method, which what's called for `+=`.  Thus it falls back to `UserList.__iadd__`, which has the irritating characteristic of if the RHS doesn't match the LHS type it converts to list - and that's what we're getting - a list made from a string, thus one-letter-per-element - before adding.
