### ISSUE TITLE
Code cleanup: ensure "is/is not None"

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2401]
This issue was originally created at: 2009-04-16 18:46:17.
This issue was reported by: `jaredgrubb`.
jaredgrubb said at 2009-04-16 18:46:17
>A quick glance through the code reveals there are a couple "==None" (and perhaps
>"!=None" too?). These should be changed to "is None"/"is not None" respectively.
>This is a simple search/replace issue and should be quick to do.

gregnoel said at 2009-04-30 17:26:03
>Bug party triage.  See if '2to3' can be adapted to search for comparisons with
>None; if so, create a test to be run regularly as a part of packaging.  In any
>event, search for any occurrences manually and get rid of them.
> 
>Jared, thanks for the idea.

jaredgrubb said at 2009-05-02 17:36:50
>Created an attachment (id=606)
>Patch for this issue

gregnoel said at 2009-05-02 23:27:53
>Patch applied as revision 4170.  Many thanks, Jared.  I'm leaving the issue open
>to continue to consider an automated checker to find any future occurrences.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

jaredgrubb attached [IsNonePatch.txt](https://github.com/SCons/tigris-issue-attachments/blob/master/2401/606/IsNonePatch.txt) at 2009-05-02 17:36:50.
>Patch for this issue

**Comment by mwichmann** [comment]
This is now done.  There is one left, in `SCons/Tool/docbook/docbook-xsl-1.76.1/extensions/docbook.py`, leaving that unchanged as it's upstream code and want to keep any future merges as easy as possible.
