### ISSUE TITLE
Allow customisation of tempfile extension

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2431]
This issue was originally created at: 2009-06-05 15:50:01.
This issue was reported by: `jbl`.
jbl said at 2009-06-05 15:50:01
>Hi,
> 
>attached is a patch that allows the customisation of temp file name extension
>used through the Platform module's TempFileMunge class by using a new
>TEMPFILEEXTENSION Environment variable.
> 
>The patch also changes slightly the behaviour of the TEMPFILEPREFIX
>interpretation. Today, the code will assume that an environment on which the call:
> 
>env.subst('$TEMPFILEPREFIX')
> 
>returns '' (the empty string) must use '@' as a TEMPFILEPREFIX value. This means
>that it is impossible to specify the empty string as a TEMPFILEPREFIX which some
>tools (PC Lint is one of them) expects. The patch simply checks whether the
>given environment has the TEMPFILEPREFIX key and if not then falls back on the
>'@' default value. This allows the empty string to be used, much like the way
>CPPDEFPREFIX/CPPDEFSUFFIX and friends allow.
> 
>The same reasonning is applied to the TEMPFILEEXTENSION  variable
> 
>I've updated the "documentation" in the Platform/__init__.py file but I couldn't
>find any other reference to the TEMPFILEPREFIX variable.
> 
>Thanks,
> 
>JB

jbl said at 2009-06-05 15:51:11
>Created an attachment (id=615)
>TEMPFILEEXTENSION patch

gregnoel said at 2009-08-27 15:39:53
>Bug party triage.

jbl attached [tempfile.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2431/615/tempfile.patch) at 2009-06-05 15:51:11.
>TEMPFILEEXTENSION patch

**Comment by pasdVn** [comment]
I'd like to see this patch in the mainline!

I have the following use case:
I'm using a greenhills toolchain at windows, which obviously has problems when using an options file with an .lnk suffix. I don't know, if he is trying to resolve the link or so. Anyways - if I rename the options file somehow else, it works.

One more comment to the patch: Maybe the default values of `TEMPFILEEXTENSION` and `TEMPFILEPREFIX`should be added to the platform-specific `generate`methods (e.g. in Platform/win32.py and so on). I could provide an updated patch, if the original author is not active anymore.

**Comment by bdbaddog** [comment]
Please a pull request would be welcome. (With a test(s))

**Comment by mwichmann** [comment]
Open to suggestions for how to deal with the Green Hills (they still exist? wow! I dealt with them >30 years ago) setup, and for tests. I'll look at docs in a bit.

**Comment by mwichmann** [comment]
Hmmm, that didn't automatically make the linkage I thought. So: see PR #3273

**Comment by mwichmann** [comment]
Now this is in, @pasdVn if you'd like to work up a PR that moved the defaulting to a somewhat more natural (or at least more findable) place in Platform, that would be welcome.

**Comment by pasdVn** [comment]
Just noticed: In the doc string of `class TempFileMunge` the variable is called `TEMPFILEEXTENSION` while `TEMPFILESUFFIX`is used in the code...

**Comment by mwichmann** [comment]
Yes, you're right. I changed the name for reasons of consistency with other vars in use, all the rest were of the *SUFFIX form, and didn't change the docstring... hey, no tests failed because I forgot :)

**Comment by bdbaddog** [comment]
@mwichmann  - Shoot me a PR with a fix (and don't forget the no ci tag), and I"ll merge it straightaway.

**Comment by bdbaddog** [comment]
Fixed in #3308
