### ISSUE TITLE
Added basic support for the LDC D compiler on Linux

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2469]
This issue was originally created at: 2009-08-23 12:23:17.
This issue was reported by: `funto`.
funto said at 2009-08-23 12:23:17
>This patch only modifies src/engine/Tool/dmd.py by adding basic support for LDC,
>the LLVM D compiler.
>I only tested it on Linux, x86 32 bits.
> 
>It relies on the "ldmd" wrapper, as does gdmd for gdc, so that SCons still
>misses support for directly invoking ldc.
>There is no support for .di files either...

funto said at 2009-08-23 12:24:00
>Created an attachment (id=627)
>Patch to apply to src/engine/Tool/dmd.py

funto said at 2009-08-23 12:24:34
>Created an attachment (id=628)
>Unit test for compiling a Tango-based "Hello World" with ldmd

funto said at 2009-08-29 02:16:16
>Created an attachment (id=629)
>Correct version of the patch for dmd.py

funto said at 2009-08-29 02:17:38
>Oops, we should invert the lines adding tango-user-ldc and tango-base-ldc.
> 
>I joined another patch, which should be correct, please use this one instead.

gregnoel said at 2009-12-09 11:37:44
>Bug party triage.  Patch and test need some minor work, but apply as soon as
>some time is available.

funto attached [patch_dmd](https://github.com/SCons/tigris-issue-attachments/blob/master/2469/627/patch_dmd) at 2009-08-23 12:24:00.
>Patch to apply to src/engine/Tool/dmd.py

funto attached [ldmd.py](https://github.com/SCons/tigris-issue-attachments/blob/master/2469/628/ldmd.py) at 2009-08-23 12:24:34.
>Unit test for compiling a Tango-based "Hello World" with ldmd

funto attached [patch_dmd_corrected](https://github.com/SCons/tigris-issue-attachments/blob/master/2469/629/patch_dmd_corrected) at 2009-08-29 02:16:16.
>Correct version of the patch for dmd.py

**Comment by ajf58** [comment]
Support for LDC and GDC is currently present. I suggest closing as implemented.

**Comment by bdbaddog** [comment]
Working in 3.0.1 (and older.)
