### ISSUE TITLE
DefaultEnvironment man page entry unclear

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2477]
This issue was originally created at: 2009-09-08 14:43:46.
This issue was reported by: `wiedeman`.
wiedeman said at 2009-09-08 14:43:46
>From the man page entry for DefaultEnvironment, it is not clear that a singleton
>is being used. It should be pointed out, that only the first call creates the
>default environment, while successive calls only return the reference to it.
> 
>See also issue #<span></span>2476.

gregnoel said at 2009-12-09 12:14:26
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
There seems to be more to this question - we also don't describe the relationship between `DefaultEnvironment` and `Environment`. Not sure I entirely understand this either.

**Comment by mwichmann** [comment]
How about this as the manpage wording?

> 
> DefaultEnvironment([**kwargs])
> 
> Creates and returns a default construction environment object. The default construction environment is used internally by SCons in order to execute many of the global functions in this list (i.e. those not called as methods of a specific construction environment), and to fetch source files transparently from source code management systems. The default environment is a singleton, so the keyword arguments affect it only on the first call, on subsequent calls the already-constructed object is returned. The default environment can be modified in the same way as any construction environment.

**Comment by mwichmann** [comment]
Would GlobalEnvironment have been a better name for this?
