### ISSUE TITLE
API HTML documentation download link

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2491]
This issue was originally created at: 2009-09-25 19:06:30.
This issue was reported by: `revragnarok`.
revragnarok said at 2009-09-25 19:06:31
>Unfortunately, not everybody has constant net access. I've downloaded the PDF
>version of the API, along with the single-file HTML version. I could not find a
>version of the cross-referenced API (
>http://scons.org/doc/1.2.0.d20090919/HTML/scons-api/index.html ) that I could
>download to use locally. How hard would that be to generate? It would be nice to
>have.

gregnoel said at 2009-12-09 15:03:22
>Bug party triage.

dirkbaechle said at 2010-09-25 03:22:34
>Created an attachment (id=799)
>Doc patch (diff against r5176 of trunk)

dirkbaechle said at 2010-09-25 03:28:00
>Sorry,
> 
>this patch was/is intended for issue 2444. I forgot to "go back" in the browser
>first...
> 
>Dirk

dirkbaechle said at 2010-09-25 04:52:10
>Since I touched this issue already, I decided to investigate a little...such
>that I can add a more useful comment now. ;)
> 
>During the bootstrap process (python bootstrap.py) an "scons-doc*.tar.gz"
>archive gets created. It should contain all documentation in the various formats
>(PDF, HTML, MAN) and also a copy of the epydoc output.
> 
>The problem I see is, that this very archive is not available to a user for
>direct download at the moment. Neither on the Sourceforge download page, nor on
>the SCons homepage. 
> 
>All together, generating the doc files is already in place...we just need to put
>them somewhere. Personally, I would favour SF.
> 
>Best regards,
> 
>Dirk

dirkbaechle attached [doc_environment_patch_r5176.diff](https://github.com/SCons/tigris-issue-attachments/blob/master/2491/799/doc_environment_patch_r5176.diff) at 2010-09-25 03:22:34.
>Doc patch (diff against r5176 of trunk)

**Comment by ajf58** [comment]
Documentation is available in many formats at http://scons.org/documentation.html, and users could simply download the HTML versions using a tool of their choice. I suggest closing this as fixed.

**Comment by bdbaddog** [comment]
Fixed.
