### ISSUE TITLE
add performance and memory graphs to the buildbot

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2525]
This issue was originally created at: 2009-12-01 13:10:16.
This issue was reported by: `stevenknight`.
stevenknight said at 2009-12-01 13:10:16
>Add buildbot infrastructure to run performance tests at every checkin and graph 
>the results.

stevenknight said at 2009-12-01 13:10:47
>Task, not defect.

stevenknight said at 2009-12-01 13:12:41
>Performance and memory graphs should come at the same time.  Priority => P2.

stevenknight said at 2009-12-01 13:19:27
>"milestone 1" => "anytime"

stevenknight said at 2009-12-27 15:15:16
>Enough infrastructure is open to close this.  Additional enhancements should be 
>tracked and prioritized by opening additional TASK issues.

gregnoel said at 2010-07-16 04:28:20
>The 'anytime' milestone should only be used for scons core; moving this issue to
>'research'.

stevenknight said at 2010-07-16 08:46:17
>Does the milestone really matter on this one?  It's already RESOLVED FIXED.

**Comment by techtonik** [comment]
@bdbaddog ![image](https://user-images.githubusercontent.com/515889/50950372-cac6a780-14ba-11e9-86ca-7207b7c94db8.png) label can be removed https://github.com/SCons/scons/issues?utf8=%E2%9C%93&q=label%3A%22Component%3A+buildbot%22+ or replaced with redish CI.

I think this ticket should be reopened.
