### ISSUE TITLE
Wiki upgrade + OpenID

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2564]
This issue was originally created at: 2010-02-02 07:07:36.
This issue was reported by: `techtonik`.
techtonik said at 2010-02-02 07:07:36
>Seems like from version 1.7 MoinMoin has support for OpenID. Would be convenient 
>to get this for SCons Wiki.

gregnoel said at 2010-07-16 06:41:44
>Bug party triage.  Gary+Greg to complete this summer.

gregnoel said at 2010-07-21 17:01:50
>Bug party triage.  Bump the priority of this issue.

garyo said at 2014-05-24 11:25:19
>Wiki has been upgraded several times now, but don't think we've enabled OpenID.

bdbaddog said at 2014-05-29 11:57:23
>I tried with google open id support using:
>https://www.google.com/accounts/o8/id 
> 
>As the open ID url. It seems to have worked.
>I'm not sure if a bunch of pre-populated URL's for openID signin would be the
>best way to complete this bug, or just mark it fixed now?

**Comment by ajf58** [comment]
The wiki is now on GitHub, so this issue is no longer rellevant.
