### ISSUE TITLE
SHCXXCOMSTR and CXXCOMSTR

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2565]
This issue was originally created at: 2010-02-03 07:22:53.
This issue was reported by: `oodini`.
oodini said at 2010-02-03 07:22:53
>Hello,
> 
>I tried to use CXXCOMSTR for a shared library.
>Greg Noel told me in the mailing list to use SHCXXCOMSTR, but it also told me to
>open an issue here, because he thinks it should have the CXXCOMSTR's value as
>default value.

garyo said at 2010-02-13 09:51:09
>Here's oodini's original email:
> 
>I try to use the CXXCOMSTR to make SCons less verbose :
> 
>AddOption("--verbose", action="store_true", dest="verbose_flag", default=False,
>help="verbose output")
>if not GetOption("verbose_flag"):
>        print 'test'
>        env['CXXCOMSTR'] = "Compiling test"
>        env['LINKCOMSTR'] = "Linking $TARGET"
>print env.Dump()
> 
>env.SharedLibrary(...
> 
>I do go in the if test, CXXCOMSTR and LINKCOMSTR are set (checked with the
>dump), but it seems that SCons just doesn't care : it prints the full
>compilation command line.
> 
>I use thast *stable* version of SCons.

gregnoel said at 2010-02-19 11:08:32
>Bug party triage.  Better treated as a documentation issue.  Ammend man page so
>that fooCOMSTR and SHfooCOMSTR refer to each other.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
The last real comment says:
> Ammend (sic) man page so that `fooCOMSTR` and `SHfooCOMSTR` refer to each other.

Is this as simple as "see also `SHfooCOMSTR`, or do these need to be tied together more explicitly, like "note if shared objects are being built, SCons will use `SHfooCOMSTR` instead (see)". Or something different?

**Comment by mwichmann** [comment]
Also, are we going to ignore the comment that SHCXXCOMSTR ought to get CXXCOMSTR's value as a default, and leave this as a doc-only issue?

**Comment by bdbaddog** [comment]
Yes. I think see also would be sufficient.
I don't think it's safe to automatically set SHCXXCOMSTR if CXXCOMSTR is set..
