### ISSUE TITLE
Integrate installer in trunk

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2567]
This issue was originally created at: 2010-02-03 13:21:47.
This issue was reported by: `gregnoel`.
gregnoel said at 2010-02-03 13:21:47
>Lukas to integrate installer as soon as 2.0 is published.  Gary to monitor.

gregnoel said at 2010-02-03 13:22:46
>Set milestone and priority.

gregnoel said at 2010-02-03 13:23:44
>*** Issue 1883 has been marked as a duplicate of this issue. ***

erluk said at 2010-02-26 09:02:33
>Changes to the trunk up to revision 4679 have been merged into the installer branch.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
What does this refer to?  Is this work that was done? Or lost?  Can we close?

**Comment by bdbaddog** [comment]
Ah. We can close this. There was a GSOC student (If I remember correctly) who build a windows installer.
