### ISSUE TITLE
When VC2010 is installed, manually setting version by setting env MSVS to a specific version doesn't work

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2570]
This issue was originally created at: 2010-02-10 14:53:44.
This issue was reported by: `pcxod`.
pcxod said at 2010-02-10 14:53:44
>Hi sorry to bother you again, but just have installed Visual Studio 2010 and every build, disregarding the chosen tool is done using the newly installed compilers... I have this options in my Sconstruct file:
```python
if env['TOOL'] == 'vc8:
  env["MSVS"] = {'VERSION': '8.0'}
  env['MSVS_VERSION'] = '8.0'
  Tool('msvc')(env)
elif env['TOOL'] == 'vc9':
  env['MSVS'] = {'VERSION': "9.0"} 
  env['MSVS_VERSION'] = '9.0'
  Tool('msvc')(env)
```
>however, disregarding the tool chosen, I get my product compiled by the compiler version as 160021003, which is the newly installed beta VS2010... Am I doing wrong initialisation of version or there is something new about the VS2010?
> 
>o

bdbaddog said at 2010-02-10 22:39:32
>Please do the following prior to running your scons and attach the output (will be in a file named bug_2570.txt)  to this bug:
```console
set SCONS_MSCOMMON_DEBUG=bug_2570.txt
```
>I'm not sure we've been able to test on VS2010 yet. Hopefully it's not that different to configure than vs2008. I'm downloading the release candidate now and will set up a virtual machine to test on.

bdbaddog said at 2010-02-10 23:03:47
>Also, can you dump the
```
LOCAL_MACHINE\Software\Microsoft registry tree and attach that as well?
```

pcxod said at 2010-02-11 03:41:46
>Created an attachment (id=687) HKEY_LOCAL_MACHINE.SOFTWARE.Microsoft.VisualStudio.reg

pcxod said at 2010-02-11 03:43:27
>Created an attachment (id=688) HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VCSExpress.reg

pcxod said at 2010-02-11 03:45:36
>Created an attachment (id=689) HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VisualStudio.reg

pcxod said at 2010-02-11 03:47:43
>Here is the debug output, I have specified the vc9 tools and my scripts does not have a handler for vc10 and actually would not allow it to be chosen by the user; also please note that VC8 (look at the registry entries) is installed but not listed as the one:
```
DEBUG:root:trying to find VC 10.0
DEBUG:root:find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
DEBUG:root:found VC 10.0
DEBUG:root:trying to find VC 9.0
DEBUG:root:find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\
DEBUG:root:found VC 9.0
DEBUG:root:trying to find VC 8.0
DEBUG:root:find_vc_dir(): no VC registry key 'Software\\Wow6432Node\\Microsoft\\VisualStudio\\8.0\\Setup\\VC\\ProductDir'
DEBUG:root:find_vc_dir(): no VC registry key 'Software\\Wow6432Node\\Microsoft\\VCExpress\\8.0\\Setup\\VC\\ProductDir'
DEBUG:root:find_vc_pdir return None for ver 8.0
DEBUG:root:trying to find VC 7.1
DEBUG:root:find_vc_dir(): no VC registry key 'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.1\\Setup\\VC\\ProductDir'
DEBUG:root:find_vc_pdir return None for ver 7.1
DEBUG:root:trying to find VC 7.0
DEBUG:root:find_vc_dir(): no VC registry key 'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.0\\Setup\\VC\\ProductDir'
DEBUG:root:find_vc_pdir return None for ver 7.0
DEBUG:root:trying to find VC 6.0
DEBUG:root:find_vc_dir(): no VC registry key 'Software\\Wow6432Node\\Microsoft\\VisualStudio\\6.0\\Setup\\Microsoft Visual C++\\ProductDir'
DEBUG:root:find_vc_pdir return None for ver 6.0
DEBUG:root:msvc_setup_env()
DEBUG:root:get_default_version()
DEBUG:root:installed_vcs:['10.0', '9.0']
DEBUG:root:msvc_setup_env: using default installed MSVC version '10.0'
DEBUG:root:msvc_setup_env: using specified MSVC version '10.0'
DEBUG:root:find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
DEBUG:root:use_script 2 u'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat', args:x86
DEBUG:root:Calling 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat x86'
DEBUG:root:msvc_setup_env()
DEBUG:root:get_default_version()
DEBUG:root:installed_vcs:['10.0', '9.0']
DEBUG:root:msvc_setup_env: using default installed MSVC version '10.0'
DEBUG:root:msvc_setup_env: using specified MSVC version '10.0'
DEBUG:root:find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
DEBUG:root:use_script 2 u'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat', args:amd64
DEBUG:root:Calling 'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat amd64'
```

bdbaddog said at 2010-02-15 23:33:36
>Can you post more of your SConstruct? Specifically a small testcase demonstrating your issue would be helpful.
> 
>If not, then at least the initialization of your Environment()
> 
>It may be that by the time you're setting your MSVS_VERSION, the environment has already loaded and set the version.

pcxod said at 2010-02-16 12:47:30
>Please take a look here:
>http://olex2.svn.sourceforge.net/viewvc/olex2/trunk/SConstruct?revision=1050&view=markup
>just for a note on Linux swapping gcc and intel compilers work just fine this way... Please let me know what you want in a smaller script and I will try it (because if I have anything wrong with initialisation, then making a smaller script will not help).

gregnoel said at 2010-02-19 11:15:03
>Bug party triage.

bdbaddog said at 2010-03-14 18:53:11
>Can you try again with trunk? I just added some more debugging code to the VC/SDK/VS initialization, which may provide additional hints to the problem.

pcxod said at 2010-03-16 05:17:31
>Created an attachment (id=700)
>scons debug output

pcxod said at 2010-03-16 05:19:35
>There seems to be similar problem with choosing the MSVC version as with the choice of the architecture... Unless the version is specified in the environment constructor, like:
```python
env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch, MSVS_VERSION='9.0')
```
>the most recently installed version will be chosen as default... This however not the case when changing gcc and intel compilers on Linux...
> 
>I have attached the scons debug output for the case when the default environment >was created and the tool was chosen like:
```python
  env['MSVS'] = {'VERSION': "9.0"} 
  env['MSVS_VERSION'] = '9.0'
  Tool('msvc')(env)
```
>and that incorrectly chose latest installed VC (2010 in this case). Later, the MSVS_VERSION was placed into the constructor arguments (as above) and that did the job. So this is the way around, but would force to create different environment for Windows and other platforms...

gregnoel said at 2010-07-16 04:09:06
>Bug party triage.  Steven to provide information from one of his contacts, Gary to integrate.

garyo said at 2012-09-01 10:01:48
>Bumping all old issues targeted for past releases to 2.x.

bdbaddog said at 2016-01-13 16:54:41
>Is this still an issue?
> 
>From a quick review it looks like you were trying to reinitialize MSVS after the environment was initialized. If so, then for MSVS that's not currently supported.
> 
>I took a quick look at the current stat of your svn repo and it looks like you've changed to initialize the environment in your if logic which chooses which compiler to use.

pcxod attached [HKEY_LOCAL_MACHINE.SOFTWARE.Microsoft.VisualStudio.reg](https://github.com/SCons/tigris-issue-attachments/blob/master/2570/687/HKEY_LOCAL_MACHINE.SOFTWARE.Microsoft.VisualStudio.reg) at 2010-02-11 03:41:46.
>HKEY_LOCAL_MACHINE.SOFTWARE.Microsoft.VisualStudio.reg

pcxod attached [HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VCSExpress.reg](https://github.com/SCons/tigris-issue-attachments/blob/master/2570/688/HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VCSExpress.reg) at 2010-02-11 03:43:27.
>HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VCSExpress.reg

pcxod attached [HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VisualStudio.reg.7z](https://github.com/SCons/tigris-issue-attachments/blob/master/2570/689/HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VisualStudio.reg.7z) at 2010-02-11 03:45:36.
>HKEY_LOCAL_MACHINE.SOFTWARE.Wow6432Node.Microsoft.VisualStudio.reg

pcxod attached [bug_2570.txt](https://github.com/SCons/tigris-issue-attachments/blob/master/2570/700/bug_2570.txt) at 2010-03-16 05:17:31.
>scons debug output

**Comment by jcbrill** [comment]
Based on a date of 2010-02-10, this must go back to 1.2-ish.

I'm pretty sure @bdbaddog nailed it:

> bdbaddog said at 2016-01-13 16:54:41
>
> Is this still an issue?
>
> From a quick review it looks like you were trying to reinitialize MSVS after the environment was initialized. If so, then for MSVS that's not currently supported.
>
> I took a quick look at the current stat of your svn repo and it looks like you've changed to initialize the environment in your if logic which chooses which compiler to use.
>

I believe the behavior exhibited supports that conclusion: the newer compilers are being used because when the environment is constructed there is no version which defaults to the latest/newest version detected.

SConstruct fragments from two revisions from the OP's repository before and after the issue report are shown below.  It appears that the environment variables are in fact being overwritten after construction in the first revision.  The second revision was reworked to pass the version in the environment constructor.

revision r1077 (2010-02-09)
```python
env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch)
Help(variables.GenerateHelpText(env))

if env['TOOL'] == 'vc8':
  env["MSVS"] = {'VERSION': '8.0'}
  env['MSVS_VERSION'] = '8.0'
  Tool('msvc')(env)
elif env['TOOL'] == 'vc9':
  env['MSVS'] = {'VERSION': "9.0"} 
  env['MSVS_VERSION'] = '9.0'
  Tool('msvc')(env)
elif env['TOOL'] == 'gnu':
  Tool('g++')(env)
elif env['TOOL'] == 'intel':
  Tool('intelc')(env)
```

revision r1133 (2010-03-18): updating issue is fixed by double checking the MD5 hash; scons script is modified to explicitly specify the MSVC version;
```python
env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch)
Help(variables.GenerateHelpText(env))

if env['TOOL'] == 'vc8':
  env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch, MSVC_VERSION='8.0')
  #env["MSVS"] = {'VERSION': '8.0'}
  #env['MSVS_VERSION'] = '8.0'
  #Tool('msvc')(env)
elif env['TOOL'] == 'vc9':
  env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch, MSVC_VERSION='9.0')
  #env['MSVS'] = {'VERSION': "9.0"} 
  #env['MSVS_VERSION'] = '9.0'
  #Tool('msvc')(env)
elif env['TOOL'] == 'vc10':
  env = Environment(ENV = os.environ, variables = variables, TARGET_ARCH=env_arch, MSVC_VERSION='10.0')
  #env['MSVS'] = {'VERSION': "10.0"} 
  #env['MSVS_VERSION'] = '10.0'
  #Tool('msvc')(env)
elif env['TOOL'] == 'gnu':
    Tool('g++')(env)
elif env['TOOL'] == 'intel':
    Tool('intelc')(env)
```

I think that this one can be closed.

**Comment by mwichmann** [comment]
Thanks. Closing.
