### ISSUE TITLE
Commands with parenthesis in a file name

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2577]
This issue was originally created at: 2010-03-11 06:17:17.
This issue was reported by: `wrwrwr`.
wrwrwr said at 2010-03-11 06:17:17
>Something is wrong with how SCons escapes parentheses in filenames when
>expanding variables in a Command.
> 
>For example:
> 
>	Command('t', 'a(', 'ls $SOURCE')
> 
>fails due to not finding an existing file.
> 
>When a path contains spaces and parentheses it seems the latter get double
>escaped (quotes around the whole path and backslashes).
> 
> 
>Tested on Ubuntu 9.04 with v1.2.0.r3842 and v1.2.0.d20100306.r4691.

wrwrwr said at 2010-03-11 06:18:44
>Created an attachment (id=697)
>.A short example that creates a file with paranthesis and tries to execute a Command on it

garyo said at 2010-04-01 18:58:04
>Thanks for the report.  Bug triage: schedule for 2.x with other subst-related bugs.

wrwrwr attached [SConstruct](https://github.com/SCons/tigris-issue-attachments/blob/master/2577/697/SConstruct) at 2010-03-11 06:18:44.
>.A short example that creates a file with paranthesis and tries to execute a Command on it

**Comment by mwichmann** [comment]
I just tried the attached SConstruct, and after fixing one syntax error (a stray double-quote char in the first Command call), it works without complaint:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cat a(
I have a "(" in my name.
cat "a ("
I have a space and "(" in my name.
```

Close as fixed?

**Comment by bdbaddog** [comment]
yup. fixed.
