### ISSUE TITLE
Hash mark in framework path variable is unparsed

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2580]
This issue was originally created at: 2010-03-17 15:23:58.
This issue was reported by: `ludovicsilvestre`.
ludovicsilvestre said at 2010-03-17 15:23:58
>Scons is not parsing the hash mark (#) in the framework path variable 
>(FRAMEWORKPATH). This behavior doesn't happen with objects or programs.
> 
>My project have the following structure:
>ROOT/
>   SConstruct
>   frameworks/
>       Ogre.framework
>   src/
>       SConscript
>       main.cpp
> 
>The output given by scons:
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>g++ -o main.o -c -F#frameworks src/main.cpp
>src/main.cpp:2:23: error: Ogre/Ogre.h: No such file or directory
>scons: *** [main.o] Error 1
>scons: building terminated because of errors.

ludovicsilvestre said at 2010-03-17 15:26:05
>Created an attachment (id=701)
>Project SConsctruct

ludovicsilvestre said at 2010-03-17 15:26:31
>Created an attachment (id=702)
>Source folder SConscript

garyo said at 2010-04-01 19:02:04
>Thanks for the report.  Scheduled for 2.x.

ludovicsilvestre attached [SConstruct](https://github.com/SCons/tigris-issue-attachments/blob/master/2580/701/SConstruct) at 2010-03-17 15:26:05.
>Project SConsctruct

ludovicsilvestre attached [SConscript](https://github.com/SCons/tigris-issue-attachments/blob/master/2580/702/SConscript) at 2010-03-17 15:26:31.
>Source folder SConscript

**Comment by acmorrow** [comment]
I encountered this problem as well.

I believe it is due to a missing `RDirs` in the definition of `_FRAMEWORKPATH` in `SCons\Tool\applelink.py`.

The fixes the issue for me (applied against a vendored copy of SCons 2.5.0), which is why the paths look a little odd.

```
--- a/src/third_party/scons-2.5.0/scons-local-2.5.0/SCons/Tool/applelink.py
+++ b/src/third_party/scons-2.5.0/scons-local-2.5.0/SCons/Tool/applelink.py
@@ -45,7 +45,7 @@ def generate(env):
     link.generate(env)

     env['FRAMEWORKPATHPREFIX'] = '-F'
-    env['_FRAMEWORKPATH'] = '${_concat(FRAMEWORKPATHPREFIX, FRAMEWORKPATH, "", __env__)}'
+    env['_FRAMEWORKPATH'] = '${_concat(FRAMEWORKPATHPREFIX, FRAMEWORKPATH, "", __env__, RDirs)}'
     env['_FRAMEWORKS'] = '${_concat("-framework ", FRAMEWORKS, "", __env__)}'
     env['LINKCOM'] = env['LINKCOM'] + ' $_FRAMEWORKPATH $_FRAMEWORKS $FRAMEWORKSFLAGS'
     env['SHLINKFLAGS'] = SCons.Util.CLVar('$LINKFLAGS -dynamiclib')
```

The `applelink.py` file on the master branch does not appear to contain a fix.

**Comment by bdbaddog** [comment]
Shouldn't be too hard to work up a test for this.
Then a pull request should be simple.
Good catch!

**Comment by bdbaddog** [comment]
Fixed with pull request 3199
