### ISSUE TITLE
command not executed when args > 8191

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2600]
This issue was originally created at: 2010-04-01 16:19:26.
This issue was reported by: `witkamp`.
witkamp said at 2010-04-01 16:19:26
>When using windows and a command argument > 8191 characters, the command is not 
>executed.
>Windows will allow for about 32k for arguments but a workaround is needed.
> 
>http://support.microsoft.com/kb/830473
> 
>SCons should automatically use the workaround so that it is transparent to the 
>user for all commands.

simonsonc said at 2010-04-07 17:45:15
>Have a look at TEMPFILE.

garyo said at 2010-04-25 12:21:58
>What command or builder are you using?  C/C++ compilation and linking
>automatically use TEMPFILE.  Custom actions would have to be coded to use it.

garyo said at 2010-04-26 09:50:50
>Note from Theodore:
> 
>===
>I have had this issue when compiling C++ on windows using  RVCT 3.0
>ARM compiler.
>It was dieing on the final linking of the executable.
> 
>I hope this helps.
>===

gregnoel said at 2010-04-30 17:03:36
>Bug party triage.  The workaround is to set the (undocumented) MAXLINELENGTH
>environment variable to a value less than 8191.  Gary to correct this oversight
>in the man page and add a description for MAXLINELENGTH (and its relationship to
>TEMPFILE?).

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by ajf58** [comment]
Fixed. See http://www.scons.org/doc/latest/HTML/scons-user.html#cv-MAXLINELENGTH
