### ISSUE TITLE
-h flag does not print local option help if Help(vars.GenerateHelpText(env)) used

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2611]
This issue was originally created at: 2010-04-14 12:56:14.
This issue was reported by: `richardcranium`.
richardcranium said at 2010-04-14 12:56:14
>The following SConstruct file will print the local options help when you run
>"scons -h" but not when you run "scons -H":
> 

```py
AddOption('--dblatex', dest='use_dblatex', action="store_true", default=False,
          help="Use dblatex to generate PDF instead of Apache FOP.")
 
vars = Variables()
env = Environment(variables = vars)
# Help(vars.GenerateHelpText(env))
```

> 
>If you correctly uncomment the "Help()" function call, there is no way to display the local options help text.  "scons -h" will not do it any more.  If "scons -H" always displayed the local options help text, this would not be an issue.

stevenknight said at 2010-05-11 13:58:37
>`-H` is specifically intended to display SCons options *without* reading the SConscript files.  There must  be a way to display help without reading the SConscript files, because otherwise a syntax error (e.g.) in  a SConscript file would interfere with being able to display the SCons options that might help you debug your problem.

>The other piece here is a definite problem.  Calling the Help() function at all currently replaces the default help text, wiping out the local options added via AddOption().  (This is largely because AddOption() is a much more recent feature and we didn't identify this interaction.)  

>We should change the default behavior of -n to always print the AddOption() options in addition to the Help() text, and probably make it configurable via a keyword argument to Help().
> 
>I'm changing the Summary line to remove the -H reference, and otherwise leaving this open to discuss at the next bug triage party.

gregnoel said at 2010-05-19 06:41:08
>Bug party triage: Steven to put in a quick fix; the real solution will be part
>of adding the IAPAT infrastructure.

mortoray said at 2012-05-13 01:52:18
>Related, if not a duplicate of issue #2258 -- likely a fix there would resolve this.

**Comment by mwichmann** [comment]
Adding comments to let github linking work: see also #2356, #2258, #2831.  Since two of those are closed (one as a dup, one resolved), is this still an issue?

**Comment by bdbaddog** [comment]
I think  we can close this.
If they use

```py
AddOption('--dblatex', dest='use_dblatex', action="store_true", default=False,
          help="Use dblatex to generate PDF instead of Apache FOP.")
 
vars = Variables()
env = Environment(variables = vars)
Help(vars.GenerateHelpText(env), append=True)
```
