### ISSUE TITLE
basic build fails on amd_x64 with MSVC 9.0Exp

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2612]
This issue was originally created at: 2010-04-14 19:38:01.
This issue was reported by: `hebd`.
hebd said at 2010-04-14 19:38:01
>i am having trouble useing scons...
> 
>hello.c:
> 
>int
>main()
>{
>    printf("Hello, world!\n");
>}
> 
>SConstruct:
> 
>Program('hello.c')
> 
>>python -V
>Python 2.6.2
> 
>>scons -v
>SCons by Steven Knight et al.:
>        engine: v1.3.0.r4720, 2010/03/24 03:14:11, by jars on jars-desktop
>Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010 The
>SCons Foundation
> 
>>scons
>scons: Reading SConscript files ...
>ValueError: Unrecognized version 9.0Exp:
>  File "C:\Programming\sctest\SConstruct", line 2:
>    Program('hello.c')
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Script\SConscript.py", line 614:
>    env = self.factory()
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Script\SConscript.py", line 594:
>    default_env = SCons.Defaults.DefaultEnvironment()
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Defaults.py", line 91:
>    _default_env = apply(SCons.Environment.Environment, args, kw)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Environment.py", line 1008:
>    apply_tools(self, tools, toolpath)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Environment.py", line 107:
>    env.Tool(tool)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Environment.py", line 1707:
>    tool(self)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\__init__.py", line 181:
>    apply(self.generate, ( env, ) + args, kw)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\default.py", line 41:
>    SCons.Tool.Tool(t)(env)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\__init__.py", line 181:
>    apply(self.generate, ( env, ) + args, kw)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\mslink.py", line 242:
>    msvc_setup_env_once(env)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\MSCommon\vc.py", line 333:
>    msvc_setup_env(env)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\MSCommon\vc.py", line 374:
>    if not is_host_target_supported(host_target, version):
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\MSCommon\vc.py", line 173:
>    maj, min = msvc_version_to_maj_min(msvc_version)
>  File "C:\Program Files (x86)\Python26\Scripts\..\Lib\site-packages\scons-1.3.0
>\SCons\Tool\MSCommon\vc.py", line 152:
>    raise ValueError("Unrecognized version %s" % msvc_version)
> 
>i fixed this as directed on this page: http://www.nmr-relax.com/windows_devel.html
> 
>>scons
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>cl /Fohello.obj /c hello.c /nologo
>'cl' is not recognized as an internal or external command,
>operable program or batch file.
>scons: *** [hello.obj] Error 1
>scons: building terminated because of errors.
> 
> 
>>set SCONS_MSCOMMON_DEBUG=-
>>scons
>scons: Reading SConscript files ...
>trying to find VC 10.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\10.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 10.0
>trying to find VC 9.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\9.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 9.0
>trying to find VC 9.0Exp
>find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\
>found VC 9.0Exp
>trying to find VC 8.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\8.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 8.0
>trying to find VC 8.0Exp
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VCExpress\\8.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 8.0Exp
>trying to find VC 7.1
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.1\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 7.1
>trying to find VC 7.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 7.0
>trying to find VC 6.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\6.0\\Setup\\Microsoft Visual
>C++\\ProductDir'
>find_vc_pdir return None for ver 6.0
>msvc_setup_env()
>get_default_version()
>get_default_version(): msvc_version:None msvs_version:None
>installed_vcs:['9.0Exp']
>msvc_setup_env: using default installed MSVC version '9.0Exp'
> 
>msvc_setup_env: using specified MSVC version '9.0Exp'
> 
>find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\
>vc.py: find_batch_file() pdir:C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\
>sdk.py:get_installed_sdks()
>MSCommon/sdk.py: trying to find SDK 7.0
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v7.0\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v7.0\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 6.1
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.1\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v6.1\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 6.0A
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.0A\InstallationFolder
>find_sdk_dir(): Trying SDK Dir: C:\Program Files\Microsoft
>SDKs\Windows\v6.0A\MSCommon/sdk.py:found SDK 6.0A
>MSCommon/sdk.py: trying to find SDK 6.0
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.0\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v6.0\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 2003R2
>find_sdk_dir(): checking
>registry:Software\Microsoft\MicrosoftSDK\InstalledSDKS\D2FF9F89-8AA2-4373-8A31-C838BF4DBBE1\Install
>Dir
>find_sdk_dir(): no SDK registry key
>'Software\\Microsoft\\MicrosoftSDK\\InstalledSDKS\\D2FF9F89-8AA2-4373-8A31-C838BF4DBBE1\\Install
>Dir'
>MSCommon/sdk.py: trying to find SDK 2003R1
>find_sdk_dir(): checking
>registry:Software\Microsoft\MicrosoftSDK\InstalledSDKS\8F9E5EF3-A9A5-491B-A889-C58EFFECE8B3\Install
>Dir
>find_sdk_dir(): no SDK registry key
>'Software\\Microsoft\\MicrosoftSDK\\InstalledSDKS\\8F9E5EF3-A9A5-491B-A889-C58EFFECE8B3\\Install
>Dir'
>sdk.py: get_sdk_vc_script():arch_string:amd64 host_arch:amd64 target_arch:amd64
>sdk.py: get_sdk_vc_script():file:bin\vcvarsamd64.bat
>vc.py:find_batch_file() sdk_bat_file_path:C:\Program Files (x86)\Microsoft
>Visual Studio 9.0\VC\bin\vcvarsamd64.bat
>vc.py:find_batch_file() not found:C:\Program Files (x86)\Microsoft Visual Studio
>9.0\VC\bin\vcvarsamd64.bat
>vc.py:msvc_setup_env() vc_script:C:\Program Files (x86)\Microsoft Visual
>Studio9.0\VC\vcvarsall.bat sdk_script:None
>vc.py:msvc_setup_env() vc_script:C:\Program Files (x86)\Microsoft Visual
>Studio9.0\VC\vcvarsall.bat sdk_script:None
>use_script 2 u'C:\\Program Files (x86)\\Microsoft Visual Studio
>9.0\\VC\\vcvarsall.bat', args:amd64
> 
>Calling 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat amd64'
>use_script 3: failed running VC script u'C:\\Program Files (x86)\\Microsoft
>Visual Studio 9.0\\VC\\vcvarsall.bat': amd64: Error:The specified configuration type
> is missing.  The tools for the
>configuration might not be installed.
>use_script 6: Neither VC script nor SDK script found
>scons: done reading SConscript files.
>scons: Building targets ...
>cl /Fohello.obj /c hello.c /nologo
>'cl' is not recognized as an internal or external command,
>operable program or batch file.
>scons: *** [hello.obj] Error 1
>scons: building terminated because of errors.
> 
>i beleve SCons\Tool\MSCommon\vc.py:is_host_target_supported should return false
>for x64 targets if Exp is found in msvc_version.
>forcing target_platform = "x86" in SCons\Tool\MSCommon\vc.py:get_host_targe 
> 
>>scons
>scons: Reading SConscript files ...
>trying to find VC 10.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\10.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 10.0
>trying to find VC 9.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\9.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 9.0
>trying to find VC 9.0Exp
>find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\
>found VC 9.0Exp
>trying to find VC 8.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\8.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 8.0
>trying to find VC 8.0Exp
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VCExpress\\8.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 8.0Exp
>trying to find VC 7.1
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.1\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 7.1
>trying to find VC 7.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\7.0\\Setup\\VC\\ProductDir'
>find_vc_pdir return None for ver 7.0
>trying to find VC 6.0
>find_vc_dir(): no VC registry key
>'Software\\Wow6432Node\\Microsoft\\VisualStudio\\6.0\\Setup\\Microsoft Visual
>C++\\ProductDir'
>find_vc_pdir return None for ver 6.0
>msvc_setup_env()
>get_default_version()
>get_default_version(): msvc_version:None msvs_version:None
>installed_vcs:['9.0Exp']
>msvc_setup_env: using default installed MSVC version '9.0Exp'
> 
>msvc_setup_env: using specified MSVC version '9.0Exp'
> 
>find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\
>vc.py: find_batch_file() pdir:C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\
>sdk.py:get_installed_sdks()
>MSCommon/sdk.py: trying to find SDK 7.0
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v7.0\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v7.0\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 6.1
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.1\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v6.1\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 6.0A
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.0A\InstallationFolder
>find_sdk_dir(): Trying SDK Dir: C:\Program Files\Microsoft
>SDKs\Windows\v6.0A\MSCommon/sdk.py:found SDK 6.0A
>MSCommon/sdk.py: trying to find SDK 6.0
>find_sdk_dir(): checking registry:Software\Microsoft\Microsoft
>SDKs\Windows\v6.0\InstallationFolder
>find_sdk_dir(): no SDK registry key 'Software\\Microsoft\\Microsoft
>SDKs\\Windows\\v6.0\\InstallationFolder'
>MSCommon/sdk.py: trying to find SDK 2003R2
>find_sdk_dir(): checking
>registry:Software\Microsoft\MicrosoftSDK\InstalledSDKS\D2FF9F89-8AA2-4373-8A31-C838BF4DBBE1\Install
>Dir
>find_sdk_dir(): no SDK registry key
>'Software\\Microsoft\\MicrosoftSDK\\InstalledSDKS\\D2FF9F89-8AA2-4373-8A31-C838BF4DBBE1\\Install
>Dir'
>MSCommon/sdk.py: trying to find SDK 2003R1
>find_sdk_dir(): checking
>registry:Software\Microsoft\MicrosoftSDK\InstalledSDKS\8F9E5EF3-A9A5-491B-A889-C58EFFECE8B3\Install
>Dir
>find_sdk_dir(): no SDK registry key
>'Software\\Microsoft\\MicrosoftSDK\\InstalledSDKS\\8F9E5EF3-A9A5-491B-A889-C58EFFECE8B3\\Install
>Dir'
>sdk.py: get_sdk_vc_script():arch_string:x86 host_arch:x86 target_arch:x86
>sdk.py: get_sdk_vc_script():file:bin\vcvars32.bat
>vc.py:find_batch_file() sdk_bat_file_path:C:\Program Files (x86)\Microsoft
>Visual Studio 9.0\VC\bin\vcvars32.bat
>vc.py:msvc_setup_env() vc_script:C:\Program Files (x86)\Microsoft Visual
>Studio9.0\VC\vcvarsall.bat sdk_script:C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\bin\vcvars32.bat
>vc.py:msvc_setup_env() vc_script:C:\Program Files (x86)\Microsoft Visual
>Studio9.0\VC\vcvarsall.bat sdk_script:C:\Program Files (x86)\Microsoft Visual
>Studio 9.0\VC\bin\vcvars32.bat
>use_script 2 u'C:\\Program Files (x86)\\Microsoft Visual Studio
>9.0\\VC\\vcvarsall.bat', args:x86
> 
>Calling 'C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat x86'
>vc.py:msvc_setup_env() env:PATH -> ['C:\\Program Files (x86)\\Microsoft Visual S
>tudio 9.0\\Common7\\IDE', 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\
>\VC\\BIN', 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\Common7\\Tools
>', 'C:\\Windows\\Microsoft.NET\\Framework\\v3.5', 'C:\\Windows\\Microsoft.NET\\F
>ramework\\v2.0.50727', 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC
>\\VCPackages', 'C:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A\\bin', 'C:\\Pr
>ogram Files (x86)\\Python26\\Scripts\\', 'C:\\Program Files (x86)\\Python26\\Scr
>ipts\\..', 'C:\\Program Files (x86)\\GTK2-Runtime\\bin', 'C:\\Program Files\\gtk
>+-bundle_2.16.2-20090602_win64\\bin', 'C:\\Program Files (x86)\\GnuWin32\\bin',
>'C:\\Program Files (x86)\\OpenLibraries\\bin', 'C:\\Windows\\System32\\Wbem', 'C
>:\\Windows', 'C:\\Windows\\system32', 'C:\\Program Files (x86)\\ATI Technologies
>\\ATI.ACE\\Core-Static', 'C:\\Program Files (x86)\\Ruby19\\bin', 'C:\\Program Fi
>les (x86)\\PHP\\', 'C:\\Program Files\\ActivePerl\\site\\bin', 'C:\\Program File
>s\\ActivePerl\\bin', 'C:\\Program Files\\TortoiseSVN\\bin', 'C:\\Program Files (
>x86)\\ImageMagick-6.5.5-Q16', 'C:\\Program Files (x86)\\Aqsis\\bin', 'C:\\Progra
>m Files (x86)\\Common Files\\Roxio Shared\\10.0\\DLLShared\\', 'C:\\Program File
>s (x86)\\Common Files\\Roxio Shared\\DLLShared\\', 'C:\\Program Files\\Common Fi
>les\\Autodesk Shared\\', 'C:\\Program Files (x86)\\PC Connectivity Solution\\',
>'C:\\Program Files (x86)\\Python26', 'C:\\Program Files (x86)\\Python26\\Scripts']
>vc.py:msvc_setup_env() env:INCLUDE -> ['C:\\Program Files (x86)\\Microsoft
>Visual Studio 9.0\\VC\\INCLUDE', 'C:\\Program Files\\Microsoft
>SDKs\\Windows\\v6.0A\\include']
>vc.py:msvc_setup_env() env:LIB -> ['C:\\Program Files (x86)\\Microsoft Visual
>Studio 9.0\\VC\\LIB', 'C:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A\\lib']
>vc.py:msvc_setup_env() env:LIBPATH ->
>['C:\\Windows\\Microsoft.NET\\Framework\\v3.5',
>'C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727', 'C:\\Program Files
>(x86)\\Microsoft Visual Studio 9.0\\VC\\LIB']
>scons: done reading SConscript files.
>scons: Building targets ...
>cl /Fohello.obj /c hello.c /nologo
>hello.c
>link /nologo /OUT:hello.exe hello.obj
>scons: done building targets.
> 
>so there is some kind of issue with the target not being set corectly in msvc
>9.0Exp.
>msvc Express tools only support x86 targets even on x64 platforms :(

gregnoel said at 2010-05-19 06:44:51
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by ajf58** [comment]
This issue is ancient, and relates to old compilers and versions of SCons. I suggest closing as "won't fix".

**Comment by bdbaddog** [comment]
Marking won't fix.
This is for Visual Studio 2008 Express which is ancient.
Simplest work around is to upgrade to newer visual studio.
If this is not a valid work around please reopen the issue.
