### ISSUE TITLE
Cache directory error is silent

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2615]
This issue was originally created at: 2010-04-22 05:44:56.
This issue was reported by: `ounim`.
ounim said at 2010-04-22 05:44:56
>If scons cannot create the cache directory, no error is reported, the process just stop after the first compilation and the error code is 2. Could a message by printed on the command line to ease to understand the problem?

gregnoel said at 2010-05-19 07:17:07
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
Maybe this isn't a problem any longer? @bdbaddog okay to close this?

Currrent code:
```py
        try:
            # still use a try block even with exist_ok, might have other fails
            os.makedirs(path, exist_ok=True)
        except OSError:
            msg = "Failed to create cache directory " + path
            raise SCons.Errors.SConsEnvironmentError(msg)
```

**Comment by bdbaddog** [comment]
Closing per @mwichmann 's investigation.
