### ISSUE TITLE
update Getting Started for 2.0

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2633]
This issue was originally created at: 2010-05-18 15:34:44.
This issue was reported by: `techtonik`.
techtonik said at 2010-05-18 15:34:44
>Wiki Getting Started section can be improved for 2.0 release. It is often the
>main entrypoint to start using SCons. It is important to keep it up-to-date.

gregnoel said at 2010-05-22 22:05:03
>Documentation can always be improved.  Can you be more specific?  What pages
>need to be updated and what should they say?

techtonik said at 2010-05-24 09:01:18
>Getting Started is currently aimed at people who know Make. Windows folks 
>usually don't. http://scons.org/wiki/SConsCrashCourse is the first page 
>immediately refers to Make. Then you'll see that SCons "imports an Environment" 
>and that's confusing. Without first explaining that SCons actually builds 
>dependency tree.
> 
>SCons documentation should not be C-oriented. There are plenty of tasks to 
>automate. Even Makefiles are nowadays more often used for things irrelevant to 
>compiling, so IMO 2.0 should be oriented as "general purpose build tool". With 
>this in mind the first SCons Tutorial should be more generic and not user 
>specific at all. As an example we may port a PEP building process.
> 
>Then we need MakeToSCons1 tutorials with Makefiles explained and their SCons 
>equivalents. There show advantages of SCons build trees (the only thing I know 
>about), and other features (would be nice to see in pictures).

gregnoel said at 2010-06-05 19:18:41
>Bug party triage.  You've done such a good job on the wiki that you've been made
>a developer, so you now have commit rights on the SVN archive.  Go ahead and fix
>the documentation however you see fit, but we'd appreciate it if you'd run any
>changes by a native English proofreader before you commit.  (Don't get us wrong;
>your English is excellent, but occasionally a Belarusan word order will creap
>in.)  Steven, Gary, or I would be good candidates; we're all very good editors.
> 
>We've put this issue down for 2.0 p1; if you can get the changes in before the
>final 2.0.0 candidate checkpoint, please do.  If not, go ahead and change the
>milestone to 2.1.
> 
>Lest we don't mention it otherwise, thanks for all your work on getting our
>documentation squared away.  It's really been helpful.

techtonik said at 2011-06-12 13:25:20
>Moving to 2.1

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

bdbaddog said at 2016-01-13 16:29:58
>Anatoly - Any interest in working on this one?
>I've changed this from a defect to an enhancement because that seems more
>appropriate..

**Comment by ajf58** [comment]
Various changes have been made to the wiki, and https://github.com/SCons/scons/wiki/SConsCrashCourse doesn't look like how it's described here. Open-ended enhancements like this aren't useful IMHO ("make things better" is easy to suggets, but too vague). I suggest closing this issue as fixed.

**Comment by bdbaddog** [comment]
Marking wontfix.
Please feel free to update the wiki if you see useful changes.
