### ISSUE TITLE
remove Aegis references in HOWTO and README files

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2639]
This issue was originally created at: 2010-05-26 08:39:00.
This issue was reported by: `stevenknight`.
stevenknight said at 2010-05-26 08:39:00
>These references are old and should be removed.
> 
>If you spot any, please add a comment to this issue identifying the area(s) that need attention, or even add 
>patches with suggested edits.  This will help make it happen faster than waiting for someone else to do a 
>thorough search.

gregnoel said at 2010-05-26 09:33:28
>Obligatory comment to add myself as CC.

gregnoel said at 2010-06-21 11:33:24
>Bug party triage.  Anatoly, would you be willing to look at this?  If you don't
>know, AEgis was the version control system used by SCons (although, in truth,
>only Steven really used it as it was supposed to be used) four or five years
>ago.  The procedures have evolved, but the documentation has not kept up.
> 
>This issue focuses on HOWTO and README, but there are probably some references
>in other documentation as well.  If you could scan them and fix them, too, we'd
>appreciate it.
> 
>If you can't take on this issue, just set the milestone back to -unspecified-
>and we'll review it again at the next bug party.

gregnoel said at 2010-06-24 14:05:42
>Humpf.  Got the milestone and priority, but forgot to make Anatoly the owner.
>Sorry about that...

techtonik said at 2010-07-06 11:08:27
>Should we remove Aegis from project SVN tree altogether?

stevenknight said at 2010-07-06 11:21:11
>No reason not to remove it.  I don't know if it's high priority relative to other 
>stuff, though, so I'm personally okay with doing it incrementally as people 
>stumble on things.  If you have a real itch to scratch and want to spend the time 
>on making a pass through all the files to do the necessary surgery, though, I 
>certainly won't veto it.

techtonik said at 2010-07-06 12:29:49
>Ok. I am reading SCons codebase anyway and spotting dead source and outdated 
>information does't add anything to clarity, so I'll start with README and descend 
>to referenced spots marking commits with the number of this issue on the way.

stevenknight said at 2010-07-06 14:56:08
>I just replied to the commit message on the CL for this.  I think the -Y code 
>should stay, but the comment can be changed to get rid of the Aegis reference.  
>Any use of -Y, for Aegis or otherwise, would need to perform the same search 
>logic to find source files in a repository.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
There are still quite a few Aegis references. Many are in out of the way places: tools (in `bin`) that don't really seem to be in use, in an unused doc bit (`doc/python10`), in the `scons-time` script in support of a commandline option (and in the manpage for said script), in an Aegis-specific testcase, and some support in the test harness.  `git grep` shows no hits in the two files that are the subject of the issue.  Does the bug need to stay open just to track the remaining mentions? Are those important to clean up?

**Comment by bdbaddog** [comment]
Fixed in #3439
