### ISSUE TITLE
fortran03 support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2645]
This issue was originally created at: 2010-06-05 01:14:16.
This issue was reported by: `dktrkranz`.
dktrkranz said at 2010-06-05 01:14:16
>Forwarded from http://bugs.debian.org/583658
> 
>This patch provides support for fortran03, already tested by a fellow Debian
>Developer.

dktrkranz said at 2010-06-05 01:14:53
>Created an attachment (id=754)
>fortran03 support

gregnoel said at 2010-06-21 11:59:15
>Bug party triage.

garyo said at 2010-07-04 11:05:26
>This looks good, Luca -- any chance you could provide the needed doc patch to go
>with it?  src/engine/SCons/Tool/f95.xml could be the starting point, and
>possibly gfortran.xml too.  I don't know Fortran at all but once the doc patch
>is in I'll integrate it for 2.1.
> 
>Thanks!

dktrkranz said at 2010-07-29 14:05:38
>Created an attachment (id=778)
>FORTRAN03 support, with documentation

garyo said at 2010-07-29 18:23:16
>Integrated for 2.1; thanks!

garyo said at 2010-07-30 05:36:07
>Hi Luca; as I was integrating your patch I had a couple of questions.  I noticed 
>you didn't include f03 in the default set of Fortran compilers in tool_list in 
>Tool/__init__.py nor the list in tool/fortran.py; is that because it's non-
>standard or for some other reason it shouldn't be included there?  If you want 
>to include it (on certain platforms) just let me know or attach another patch.
> 
>Also, it's not included in the list of standard tools in doc/man/scons.1.  
>Again, deliberate, or an oversight?
> 
>I just did a grep of f95 in the whole src tree and tried to see where f03 should 
>match up with it, but realized I didn't have enough info to make sensible 
>decisions.

dktrkranz said at 2010-08-01 07:08:05
>I have to admit my knowledge is weak too, so I just thought it deserves more testing 
>before being included into default set, that's why I didn't include it wider.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

More information about this issue is at http://bugs.debian.org/583658.

dktrkranz attached [fortran03.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2645/754/fortran03.patch) at 2010-06-05 01:14:52.
>fortran03 support

dktrkranz attached [fortran03.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2645/778/fortran03.patch) at 2010-07-29 14:05:38.
>FORTRAN03 support, with documentation

**Comment by mwichmann** [comment]
Is this still an issue? I thought we had F03 and F08 support these days...

**Comment by bdbaddog** [comment]
Yup. Closing
