### ISSUE TITLE
SCons start script gets confused on *nix 64bit...

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2657]
This issue was originally created at: 2010-06-28 03:23:41.
This issue was reported by: `dirkbaechle`.
dirkbaechle said at 2010-06-28 03:23:41
>Hi,
> 
>I installed the latest scons-2.0.0-final (source tarball) on a 64bit machine with SuSE 10.1.
> 
>The system has python 2.4.2 in "/usr/bin/python" and "/usr/lib64/python2.4". SCons got installed (python setup.py install) to "/usr/local/bin/scons" and "/usr/local/lib64/scons-2.0.0.final.0".
> 
>One problem with the current start script is, that it only checks for the 32bit folder "lib" in l. 140:
```python
        temp = [os.path.join(x, 'lib') for x in prefs]
```
>so I get an import error for SCons.Script right away:
```console
  project@io:~/projects/trunk> scons -v
  Traceback (most recent call last):
    File "/usr/local/bin/scons", line 187, in ?
      import SCons.Script
  ImportError: No module named SCons.Script
```
>My first enhancement request is, to extend this to a:
```python
        temp = [os.path.join(x, 'lib') for x in prefs]
        temp = [os.path.join(x, 'lib64') for x in prefs]
```
>This is what gets SCons going on my system, for a quick start. However, I am not sure about the possible implications of this fix...another point to attack might be the install routine. It thinks that "/usr/local/lib64" is a good place to put the scripts. Maybe some synchronization between "install"<->"call" should take place? At least that's why I did not mark this post as bug...your mileage may vary.
> 
>Additionally, all possible SCons paths get appended to sys.path at the moment (l. 180). It would be nice to have a small loop here, that checks which possible paths do really exist in the system...and filters all other stuff out, in order to keep sys.path as clean as possible.
> 
>Best regards,
> 
>Dirk

dirkbaechle said at 2010-06-28 03:30:50
>Ok,
> 
>the second line should read
```python
  temp.extend([os.path.join(x, 'lib64') for x in prefs])
```
>,of course...sorry.
> 

russel said at 2010-06-28 07:04:35
>I am not sure you should search both lib and lib64.  There should be one and only one path to search for a given Python on a given platform.
> 
>In the Debian/Ubuntu world lib is for the native word length and on 64-bit platforms lib32 is for the 32-bit libraries.  However Python is 64-bit on 64-bit platforms and so only needs lib.  Conversely on a 32-bit platform lib is 32-bit and if you need 64-bit they are in lib64.
> 
>If SUSE always puts the word length as part of the lib then it should not even be trying lib on that platform.

dirkbaechle said at 2010-06-28 10:30:21
>Hi Russel,
> 
>you are probably right about the "default" paths. But isn't it possible to have more than one Python installed? I wonder what happens, when an evil user (that's me) takes his 64bit SuSE 10.1, with the 64bit Python 2.4.2, and decides to
>install a 32bit Python 2.6.5 on top of it all (to /usr/local/bin/...).
> 
>I think, I'll give this a try tomorrow. ;)
> 

russel said at 2010-06-28 11:14:15
>I have just had a quick look at the script as released on Debian Squeeze (SCons reports itself as 2.0.0.final.0).  I am wondering why the SCons script has all this guesswork trying to find the library.  The implication is that not every Python installation has the package distutils.sysconfig since that has the function get_python_lib which will give the library location expected by the currently executing Python.
> 
>If SCons is not installed in the place Python expects it shouldn't it be mandatory to set SCONS_LIB_DIR.  This would enable removal of all the guesswork?

stevenknight said at 2010-06-28 12:44:06
>The library guesswork comes from an early design decision to have SCons look more like an independent application that happens to be implemented in Python, and not a Python package per se.  The idea is that you should be able to upgrade Python and *not* have to worry about re-installing SCons in order to have the packages installed in /usr/lib/python2.6/site-packages instead of /usr/lib/python2.5/site-packages (e.g.).
> 
>We also wanted to support the ability to install multiple versions of SCons side-by-side, which is important in enterprises to support side-by-side experimentation with old and new versions when contemplating upgrading.
> 
>These criteria meant installing the SCons library modules in the system library directory, not in Python's library directory.  Unfortunately, because we still used distutils for installation, we ended up with this inappropriate dependence on the 64-bit vs. 32-bit library location when that started becoming reality.  (The original design and intention predate the prominence of 64-bit systems.)  At the time that first started rearing its head, the simplest solution was just to hack in looking for "lib64" (e.g.) in addition to "lib".
> 
>But yes, that makes the whole thing creaky.  Since SCons doesn't use any compiled code (not yet, anyway), I don't see any reason why we should have to care.  Perhaps the most effective solution here would be to change the installation so it just always installs in /usr/lib (e.g.).

gregnoel said at 2010-07-20 10:08:59
>Python 2.5 introduces the concept of relative imports, so once our floor Python version is 2.5, this problem should (mostly) go away (only the initial import of 'SCons' will need to have the Python path set).  In other words, a band-aid that gets it working in the short term, creaky or not, should be fine.

gregnoel said at 2010-07-21 17:28:20
>Bug party triage.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

dirkbaechle said at 2014-05-18 09:09:36
>*** Issue 1488 has been marked as a duplicate of this issue. ***

dirkbaechle said this issue is duplicated by #1488 at 2014-05-18 09:09:44.

**Comment by mwichmann** [comment]
Wondering if this is still a problem?  Haven't heard of people having trouble using 64-bit Python for SCons on Linux, and most Linux distros have dropped 32-bit versions by now (not Debian, but all the others I regularly follow).  The "architectural decision" mentioned above was.... interesting. But in any case we're well beyond Python 2.5 as a floor, so the last comment should suggest that this could be fixed - if it hasn't already been, which I expect, since there's been fiddling in the startup scripts.  Also, we now fully think of SCons as an actual Python package, afaik.

**Comment by bdbaddog** [comment]
Closing. Obsolete.
Package creation has been totally replaced so this is very unlikely to still be an issue.
