### ISSUE TITLE
Bad command line generated when using MergeFlags, ParseConfig, Append

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2671]
This issue was originally created at: 2010-07-29 02:15:32.
This issue was reported by: `jbl`.
jbl said at 2010-07-29 02:15:32
>According to the SCons man page, the `CPPDEFINES` variable accepts 3 input types:
>- a string
>- a list
>- a dictionary
> 
>When setting CPPDEFINES to a dictionary like so:
```py
env = Environment(CPPDEFINES={'DEBUG':1, 'TEST':None})
```
>and thereafter using, e.g., `ParseConfig` with a `.pc` file that adds macros to the command line (which typically will generate a string that get parsed into SCons construction variables through the `MergeFlags` method, resulting in a list of some kind), SCons will generate an invalid compiler command line.
> 
>For instance, to illustrate the issue through a simple test case (a more complete test case with a patch will follow ;)):
```py
env = Environment(CPPDEFINES={'DEBUG':1, 'TEST':None})
env.MergeFlags('-DSOMETHING -DVARIABLE="test"')
env.Object('test','main.c')
```
>yields the following compiler command line:
```
gcc -o test.o -c "-D{'DEBUG': 1, 'TEST': None}" -DSOMETHING -DVARIABLE=test main.c <command-line>: error: macro names must be identifiers
scons: *** [test.o] Error 1
```
>The man page correctly states that `env.Append` ... "Otherwise, the construction variable and the value of the keyword argument are both coerced to lists, and the lists are added together", but in the `ParseConfig/MergeFlags` case, I would expect SCons to deal with the possible type differences between existing values of the construction variables and the ones that are added/merged, and perform a best attempt at creating a correct command line.
> 
>As far as I can see (but I might be wrong!), this is only an issue for `CPPDEFINES` as it is the only construction variable that accepts a mix of strings, lists and dictionaries, so the patch that follows handles this particular case explicitly...
> 
>I've checked SVN and the issue is still present.
> 
>Thanks for a great tool!

jbl said at 2010-07-29 02:16:22
>Created an attachment (id=776)
>Self contained SConstruct that exhibits the issue

jbl said at 2010-07-29 02:27:17
>Created an attachment (id=777)
>Proposed patch to MergeFlags

jbl said at 2010-07-29 06:54:25
>This seems to be related to #1738, #2300, #1152. (sorry for not having been more thorough in my searches for this before submitting an issue).
> 
>I'll see if my patch either improves some of this or if I can work on the patch further to see if it can help.

jbl said at 2010-07-30 03:27:34
>Created an attachment (id=779)
>Updated test case with all test cases from related issues

jbl said at 2010-07-30 03:28:10
>Created an attachment (id=780)
>New patch that addresses all issues mentioned in this report

jbl said at 2010-07-30 03:29:31
>I've updated both the test cases to include all the cases reported in #1738, #2300, #1152, and added a new patch that makes all those test cases pass.
> 
>Thanks,
> 
>JB

gregnoel said at 2010-08-08 12:58:16
>Bug party triage.  Apply patch and add test.

garyo said at 2010-08-11 19:03:44
>Hi JB; I'm looking at integrating this for the next release.  Unfortunately the patch no longer applies to trunk, probably due to all the python modernization stuff we did for 2.1. I get the general idea, but if you can respin the patch against trunk it would be extremely helpful.

jbl said at 2010-08-12 00:08:32
>Hi Gary,
> 
>I've been meaning to update my SCons version from 1.2.0.xxx to one of the 2.x series, so I will update the patch, expect something before the weekend.
> 
>Thanks,
> 
>JB

jbl said at 2010-08-12 22:52:17
>Created an attachment (id=785)
>Patch to trunk versions of Environment.py and Defaults.py

garyo said at 2010-08-15 15:07:14
>Integrated for 2.1.  Thanks!

jbl attached [SConstruct](https://github.com/SCons/tigris-issue-attachments/blob/master/2671/776/SConstruct) at 2010-07-29 02:16:22.
>Self contained SConstruct that exhibits the issue

jbl attached [Environment_MergeFlags.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2671/777/Environment_MergeFlags.patch) at 2010-07-29 02:27:17.
>Proposed patch to MergeFlags

jbl attached [SConstruct](https://github.com/SCons/tigris-issue-attachments/blob/master/2671/779/SConstruct) at 2010-07-30 03:27:34.
>Updated test case with all test cases from related issues

jbl attached [Environment_MergeFlags.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2671/780/Environment_MergeFlags.patch) at 2010-07-30 03:28:10.
>New patch that addresses all issues mentioned in this report

jbl attached [patch_against_trunk](https://github.com/SCons/tigris-issue-attachments/blob/master/2671/785/patch_against_trunk) at 2010-08-12 22:52:17.
>Patch to trunk versions of Environment.py and Defaults.py

**Comment by mwichmann** [comment]
This is "done" and closed long ago, but seems to have missed `Prepend`, which has no special-casing for `CPPDEFINES`. Not proposing to repoen, just leaving breadcrumbs for possible future searches.
