### ISSUE TITLE
'scons' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2688]
This issue was originally created at: 2010-09-03 12:42:03.
This issue was reported by: `davetaflin`.
davetaflin said at 2010-09-03 12:42:04
>I followed the installation instructions, attempted to follow a tutorial, and
>got the subj. error message. The documentation (installation instructions)
>should instruct the user to modify the PATH environment variable and give a
>sample of what to add to it. For example:
> 
>"Add the location of scons to your PATH environment variable. scons is located
>in the Scripts subdirectory of your Python installation, for example
>C:\Python25\Scripts."

garyo said at 2010-09-06 17:09:25
>Good idea.  Which install method did you use: Windows exe, zip, or tarball?

davetaflin said at 2010-09-06 20:43:12
>I used the Windows .exe installer.

gregnoel said at 2010-09-27 17:48:53
>Bug party triage.  See IRC log for complete information.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

**Comment by mwichmann** [comment]
Can we close this issue? The exe installer is no longer produced; the recommended method (pip install) ought not to have the path problem.

**Comment by bdbaddog** [comment]
Windows installer no longer supported. Closing.

**Comment by Wolfyxon** [comment]
I have same the problem

**Comment by mwichmann** [comment]
You can always try it as `py -m scons`, or figure out where the constructed scons.exe ended up and add it to your path.  In my case that was:

`/Users/xxxx/Appdata/Local/Programs/Python/Python39/Scripts`

For reasons we don't understand, this path is not added to the the path by the install of Python (it's the same place pip goes to), even if you tick the box to add Python to PATH, which only adds the directory above where the python executable itself is.
