### ISSUE TITLE
Atomically reproduce output of parallel processes

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2729]
This issue was originally created at: 2011-01-14 05:34:41.
This issue was reported by: `dobbelaj`.
dobbelaj said at 2011-01-14 05:34:41
>When using scons in parallel, it would be handy if the output of a command would
>only be reproduced after the command finishes, in such way that it does not
>interfere with other parallel running commands.
> 
>Maybe this can be a feature that can be enabled (or disabled) with a specific
>option.

Votes for this issue: 1.

**Comment by ajf58** [comment]
I've not noticed any problems with interleaving of command outputs when enabling concurrent 'jobs' in SCons, and no example is provided here. I suggest closing this as cannot reproduce.

**Comment by bdbaddog** [comment]
STDIO/STDERR from parallel running jobs can be output interleaved.
We have this as a P4 (low importance).
I'm going to leave this here for now, though I don't know when we might get around to this issue.
