### ISSUE TITLE
kconfig-like interface

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2750]
This issue was originally created at: 2011-04-03 07:29:21.
This issue was reported by: `ipatrol`.
ipatrol said at 2011-04-03 07:29:21
>I have been thinking of making a curses-based configuration script as used by kernel.org, buildroot, and busybox. I an a capable Python programmer and am willing to write this feature either as core or an add on. I only request your approval to proceed.

garyo said at 2011-04-04 05:23:05
>Sounds interesting, but I'm not sure what this would actually be like.  A SConstruct is an arbitrary python file; would your interface require a certain structure in the SConstruct?  Can you give a little more detail?

**Comment by mwichmann** [comment]
Nothing happened here, and there's not anything actionable in the issue, closing.
