### ISSUE TITLE
Scons doesn't work after running the installer

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2751]
This issue was originally created at: 2011-04-16 02:50:58.
This issue was reported by: `charlesli`.
charlesli said at 2011-04-16 02:50:58
>The Windows installer installs the scons scripts in the python directory (as it
>should), but then neglects to set the path to the batchfile that actually runs
>scons files.
> 
>This is annoying because then:
> (a) the whole thing doesn't work
> (b) the installer never tells you where it put the files, so you have to go and
>hunt for them
> (c) nowhere does it mention anything about setting paths (Windows installers
>often do that without prompting). 
> 
>Technically speaking a minor glitch, but from an end-user perspective it renders
>scons d.o.a.

**Comment by mwichmann** [comment]
The windows installer is no longer supported.
