### ISSUE TITLE
SConf marks files up-to-date while using them in checks

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2757]
This issue was originally created at: 2011-04-23 13:50:13.
This issue was reported by: `garyo`.
garyo said at 2011-04-23 13:50:13
>If you have a `Configure` (aka `SConf`) test that uses a header file, say `foo.h`, and `foo.h` is modified, what happens is the Configure test runs (it's like a mini-SCons run) and updates the `ninfo.csig` of `foo.h`'s node.  Then the rest of the SConstruct gets read, and `foo.h` appears unmodified, so none of its dependents get built.  Don't have a repro case handy here, will try to provide one soon.

**Comment by mwichmann** [comment]
#2485 is an example of this, it looks like.

**Comment by mwichmann** [comment]
See also this email thread: http://four.pairlist.net/pipermail/scons-users/2021-April/008527.html

**Comment by dmoody256** [comment]
Should SConf use a separate sconsign file and just stick in sconf_temp dir?

Not sure if that will really fix it, because the state may be in memory from just running the SConf checks.

**Comment by mwichmann** [comment]
That, on the surface, sounds like it could alleviate several of the interaction problems that people seem to have run into - there are a LOT of Configure bugs (of course the devil is in the details as you note).  Seems like a lot of the old bugs were handwaved away with "when we rewrite blah blah...." which didn't happen.

Funny thing is, I was just thinking about another reason why one might want to be able to specify an alternate sconsign file.
