### ISSUE TITLE
SConf.CheckLib does not support 'append' option.

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2767]
This issue was originally created at: 2011-05-27 09:48:37.
This issue was reported by: `jcoffland`.
jcoffland said at 2011-05-27 09:48:37

>The function `Conftest.py:CheckLib` supports an option `append`.  This option is inaccessible via `SConf.CheckLib` because it is not present.
> 
>I believe the code in `SConf.py` for `CheckLib` should just pass arbitrary keyword arguments on to `CheckLib` in `Conftest.py`.

**Comment by mwichmann** [comment]
This is kind of an odd option... but it seems like it would be easy enough to expose - tiny change in the code and an extra paragraph in the docs.  `append` defaults to True and says append when adding the library, if False, it prepends it instead. The library is added in any case.  Is it worth bothering?  Less inclined to open up the gates and pass on every kwarg, we have other instances in SCons already (environments) where everything is just passed on and it makes it hard to detect actual errors, like mis-spellings.
