### ISSUE TITLE
'Invalid argument' raised when reading a sconsign file > ~64MB from network using Windows

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2775]
This issue was originally created at: 2011-07-08 03:26:00.
This issue was reported by: `davidrobinsonsepura`.
davidrobinsonsepura said at 2011-07-08 03:26:00
>[This is a Python fault rather than SCons but needs to be handled in SCons]
> 
>Fault appears due to Python's file.read() method returning error 22 (invalid
>parameter) when dblite.__init__ () reads the pickle string from a large sconsign
>file (66MB) hosted on a network drive.
> 
>http://support.microsoft.com/kb/899149 reports a similar fault writing a large
>buffer to a network file.
> 
>Stack trace:
> 
>scons: Building targets ...
>scons: *** [------] Invalid argument
>scons: internal stack trace:
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Job.py", line 387, in
>start
>    task.prepare()
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Script\Main.py", line
>167, in prepare
>    return SCons.Taskmaster.OutOfDateTask.prepare(self)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Taskmaster.py", line
>170, in prepare
>    self.exception_raise()
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Taskmaster.py", line
>919, in next_task
>    task.make_ready()
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Script\Main.py", line
>298, in make_ready
>    SCons.Taskmaster.OutOfDateTask.make_ready(self)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Taskmaster.py", line
>400, in make_ready_current
>    t.visited()
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Node\FS.py", line
>2624, in visited
>    self.store_info()
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Node\FS.py", line
>2382, in store_info
>    self.dir.sconsign().store_info(self.name, self)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\Node\FS.py", line
>1704, in sconsign
>    self._sconsign = SCons.SConsign.ForDirectory(self)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\SConsign.py", line
>194, in __init__
>    db, mode = Get_DataBase(dir)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\SConsign.py", line 83,
>in Get_DataBase
>    db = DataBase[top] = DB_Module.open(DB_Name, "c")
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\dblite.py", line 173,
>in open
>    return dblite(file, flag, mode)
>  File "C:\temp\scons\scons-2.0.1\scons-local-2.0.1\SCons\dblite.py", line 98,
>in __init__
>    p = f.read()
>scons: building terminated because of errors.
> 
>Fix is to replace dblite.py line 98:
>        p = f.read()
>With:
>        p = ''
>        t = f.read(0x2000000) # read in 32MB chunks to avoid Win32 file read
>error code 22
>        while t:
>            p = p + t
>            t = f.read(0x2000000)   # read in 32MB chunks to avoid Win32 file
>read error code 22

**Comment by mwichmann** [comment]
Stumbling across old issues...  maybe a monolithic db file isn't the best idea and breaking it up would help? (note the link to the referenced Microsoft bug is no longer valid).

**Comment by bdbaddog** [comment]
Closing. Microsoft link is dead. No further reports of this issue.
Please reopen if still an issue.
