### ISSUE TITLE
Minor bug in msvs project generation

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2786]
This issue was originally created at: 2011-08-31 04:00:04.
This issue was reported by: `stopiccot`.
stopiccot said at 2011-08-31 04:00:05
>When project contains only one *.cpp or only one *.h file, incorrect paths are 
>generated. Caused by this code:
> 
># First remove any common prefix
>sources = self.sources[kind]
>commonprefix = None
>if len(sources) > 1:
>     s = list(map(os.path.normpath, sources))
>     # take the dirname because the prefix may include parts
>     # of the filenames (e.g. if you have 'dir\abcd' and
>     # 'dir\acde' then the cp will be 'dir\a' )
>     cp = os.path.dirname( os.path.commonprefix(s) )
>     if cp and s[0][len(cp)] == os.sep:
>          # +1 because the filename starts after the separator
>          sources = [s[len(cp)+1:] for s in sources]
>          commonprefix = cp
>elif len(sources) == 1:
>     commonprefix = os.path.dirname( sources[0] )
>     sources[0] = os.path.basename( sources[0] )
> 
>Why we need special case for len(sources) == 1 at all?

stopiccot said at 2011-08-31 04:01:19
>Created an attachment (id=866)
>SConstuct file in attached zip generates two projects: project1 and project2. project1 contains only one cpp file: main.cpp. After opening generated project in Visual Studio and double clickin on main.cpp you will get error message. project2 is ok

stopiccot attached [sconsbug.zip](https://github.com/SCons/tigris-issue-attachments/blob/master/2786/866/sconsbug.zip) at 2011-08-31 04:01:19.
>SConstuct file in attached zip generates two projects: project1 and project2. project1 contains only one cpp file: main.cpp. After opening generated project in Visual Studio and double clickin on main.cpp you will get error message. project2 is ok

**Comment by ajf58** [comment]
This block of code appears 3 times in msvs.py ([line 970](https://github.com/SCons/scons/blob/master/src/engine/SCons/Tool/msvs.py#L970), [line 1304](https://github.com/SCons/scons/blob/master/src/engine/SCons/Tool/msvs.py#L1304), and ([line 1327](https://github.com/SCons/scons/blob/master/src/engine/SCons/Tool/msvs.py#L1327). In all cases the special case for ``` len(sources) == 1``` has been removed.

I suggest resolving this as "fixed".

**Comment by mwichmann** [comment]
@bdbaddog - should this be closed?

**Comment by bdbaddog** [comment]
Sure.
