### ISSUE TITLE
MkdirFunc fails the build if something else create the directory underneath it

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2787]
This issue was originally created at: 2011-09-02 09:45:41.
This issue was reported by: `estanchev`.
estanchev said at 2011-09-02 09:45:41
>When scons tries to create a component of a path, it fails with "File Exists"
>error, if another process creates the directory in the meantime.
> 
>In SCons/Node/FS.py, in the _create method:
>	1) SCons.Node.Node.build(dirnode) calls MkdirFunc.
>	2) If MkdirFunc raises an OSError, it is catched by scons, packed as a
>BuildError and then that is raised, to fail the build.
>	3) Thus, the try: except: code around that code is useless.

estanchev said at 2011-09-02 09:46:11
>Created an attachment (id=868)
>This is the proposed patch.

thosrtanner said at 2013-12-11 09:21:23
>Just a thought - this could still throw an error if some other process creates
>the directory between the 'if not exists' test you added and the following mkdir.

Votes for this issue: 1.

estanchev attached [MkdirFunc-existing-directory-bug.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2787/868/MkdirFunc-existing-directory-bug.patch) at 2011-09-02 09:46:11.
>This is the proposed patch.

**Comment by ajf58** [comment]
I'm ok with the build failing if another process is changing the directory structure under my feet. The directory created by another process may have incorrect permissions, for example.

I suggest closing as "won't fix".

**Comment by grossag** [comment]
> I'm ok with the build failing if another process is changing the directory structure under my feet. The directory created by another process may have incorrect permissions, for example.
> 
> I suggest closing as "won't fix".

It's not that another process is changing the directory structure, it's that another thread is creating the directory too. So if two threads call MkdirFunc at about the same time, the code races and fails.

What is the correct behavior here? Are both actions supposed to set the Dir as a side effect? Do normal compile/link builders already set their output directory as a side effect?

**Comment by bdbaddog** [comment]
> > I'm ok with the build failing if another process is changing the directory structure under my feet. The directory created by another process may have incorrect permissions, for example.
> > I suggest closing as "won't fix".
> 
> It's not that another process is changing the directory structure, it's that another thread is creating the directory too. So if two threads call MkdirFunc at about the same time, the code races and fails.
> 
> What is the correct behavior here? Are both actions supposed to set the Dir as a side effect? Do normal compile/link builders already set their output directory as a side effect?

That's a different issue than this one, so likely bring it to users mailing list or discord.  That shouldn't be happening.

**Comment by mwichmann** [comment]
If there's a chance MkdirFunc can be called by multiple threads, then the existing code certainly isn't safe - a window between the check and the os.mkdir will always be there.  Can that happen?   The code in the first bit of the patch at least improves on that.
