### ISSUE TITLE
Mingw tool does not respect SHLINKCOMSTR and LDMODULECOMSTR

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2799]
This issue was originally created at: 2011-11-06 03:38:44.
This issue was reported by: `bmerry`.
bmerry said at 2011-11-06 03:38:44
>I use SHLINKCOMSTR (and *COMSTR generally) to produce one-line easily readable 
>output for each command. However, mingw.py sets up dynamic linking using
> 
>shlib_action = SCons.Action.Action(shlib_generator, generator=1)
> 
><snip>
> 
>    env['SHLINKCOM']   = shlib_action
>    env['LDMODULECOM'] = shlib_action
> 
>which means that SHLINKCOMSTR and LDMODULECOMSTR do not get used.

bmerry said at 2011-11-06 03:40:15
>Created an attachment (id=877)
>Patch to make SHLINKCOMSTR and LDMODULECOMSTR work with mingw

bmerry said at 2011-11-06 03:41:47
>Hopefully the issue should be self-evident from the attached patch, but if you'd 
>like me to knock together a test case to verify the fix then just let me know.

bdbaddog said at 2011-11-06 09:25:16
>A test case would be great.
>Our development methodology requires a test to be able to check in new code/fixes.

bmerry said at 2011-11-06 23:38:22
>Created an attachment (id=878)
>Test case (not yet tested under mingw)

bmerry said at 2011-11-06 23:41:41
>I've attached a draft testcase. I don't have mingw handy on this machine to
>actually test it (I'll do that when I'm at home), so you might want to hold off
>trying it out - but I give it a 75% chance of illustrating the issue.
> 
>On an Ubuntu 11.10 machine with scons 2.0.1.r5134, it outputs
> 
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>SHCC shlib.os
>SHLINK libtestlib.so
>SHCC module.os
>LDMODULE libtestmodule.so
>scons: done building targets.
> 
>My guess is that without the patch, 2.1.0 on mingw will emit the full gcc
>command line used for the linking steps.

bmerry said at 2011-11-08 10:53:54
>I found that scons was detecting MSVC ahead of Mingw on my machine; I'll upload 
>a new test case to fix that.
> 
>Without the patch, the output from mingw is:
> 
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>SHCC shlib.o
>gcc -shared -o testlib.dll shlib.o -Wl,--out-implib,libtestlib.a
>Creating library file: libtestlib.a
>SHCC module.o
>gcc -shared -o testmodule.dll module.o
>scons: done building targets.
> 
>with the patch applied, the output is:
> 
> 
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>SHCC shlib.o
>SHLINK testlib.dll
>Creating library file: libtestlib.a
>SHCC module.o
>LDMODULE testmodule.dll
>scons: done building targets.

bmerry said at 2011-11-08 10:55:18
>Created an attachment (id=879)
>Updated test case

bmerry attached [mingw-comstr.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2799/877/mingw-comstr.patch) at 2011-11-06 03:40:15.
>Patch to make SHLINKCOMSTR and LDMODULECOMSTR work with mingw

bmerry attached [scons-bug-2799.zip](https://github.com/SCons/tigris-issue-attachments/blob/master/2799/878/scons-bug-2799.zip) at 2011-11-06 23:38:22.
>Test case (not yet tested under mingw)

bmerry attached [scons-bug-2799.zip](https://github.com/SCons/tigris-issue-attachments/blob/master/2799/879/scons-bug-2799.zip) at 2011-11-08 10:55:18.
>Updated test case

**Comment by merovingien** [comment]
Hello,

I just tested this patch, it is ok on my platform (windows 7, mingw-w64).

It would be nice if correction was added to the next version. Thanks in advance.

Regards.

**Comment by bdbaddog** [comment]
Fixed in master.
