### ISSUE TITLE
Install page "details text" cut off

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2802]
This issue was originally created at: 2011-11-15 16:26:36.
This issue was reported by: `andersk`.
andersk said at 2011-11-15 16:26:36
>The path label is cut off, possibly some kind of word wrapping going on or a
>control size problem.

andersk said at 2011-11-15 16:30:09
>Created an attachment (id=881)
>Screenshot

andersk attached [sconsinst.png](https://github.com/SCons/tigris-issue-attachments/blob/master/2802/881/sconsinst.png) at 2011-11-15 16:30:09.
>Screenshot

**Comment by mwichmann** [comment]
This looks like a Windows installer thing, and since that no longer exists, maybe close?

**Comment by bdbaddog** [comment]
Closing.. installer no longer supported.
