### ISSUE TITLE
Missing 'scons' script in c:\Python27\Scripts

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2814]
This issue was originally created at: 2012-01-18 11:09:45.
This issue was reported by: `jdpipe`.
jdpipe said at 2012-01-18 11:09:45
>I attempted to build a bdist_wininst installer for SCons 1.2.0 on a 64-bit
>Windows machine (with Python 2.7.2 64-bit installed). The pre-built installer
>fails to detect Python 64-bit, so I needed to build my own (it seemed).
> 
>I downloaded the tarball and unpacked it then ran 'python setup.py
>bdist_wininst'. It worked. I installed the resulting scons-2.1.0-amd64.exe file
>using Administrator privileges.
> 
>But on attempting to use SCons, I found that the c:\Python27\Scripts folder
>contained 'scons.bat' and 'scons.py' but no simple 'scons' file with no
>extension as required for the MSYS/bash shell. This file was present in earlier
>versions of SCons that I have used on Windows, and it allows easy operation of
>SCons from the MSYS command prompt (and I presume also from Cygwin).
> 
>I believe that simple 'scons' file need only contain
> 
>#!/bin/sh
>python /c/Python27/Scripts/scons.py $*
> 
>Creating this file manually in c:/Python27/SCripts fixed my problems, but the
>installer should really contain the above file for completeness.
> 
>Cheers
>JP

**Comment by farox1** [comment]
Thanks
 i was searching for a method to run Scons under MinGW/MSYS and after created a file with your suggestion:
#!/bin/sh
python /c/Python27/Scripts/scons.py $*

it works, but i need to put on the root directory of my Python installation (C:\Python27 in my case), and not in /Scripts like you write, also with a changed name (i used sconss... as Windows do not permit to name a file if there are a directory with the same name).
So to invoke scons on my MSYS terminal i need to type
sconss 
and it works!
Tested on my Windows7 32bit with Python2.7.8, scons 3.1.1 and MinGW/MSYS (1.0)

Hope it helps.

**Comment by bdbaddog** [comment]
bdist_wininst is no longer supported. Closing
