### ISSUE TITLE
Impossible to define SWIG executable if not in the PATH

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2815]
This issue was originally created at: 2012-01-19 04:50:19.
This issue was reported by: `ysagon`.
ysagon said at 2012-01-19 04:50:19
>I would like to specify an alternate Swig executable, but it's not working if the binary "swig" is not present in the PATH. If the executable swig is in the path, then it's possible to specify the swig binary to use using env['SWIG'] but it's clearly wrong.
> 
>I think the problem lie in file SCons/Tool/swig.py in the exists function. It's not checking for Swig specified in env['SWIG'] but on the hardcoded string 'swig'.

klimkin said at 2012-04-27 11:48:55
>Here is a small patch to fix the problem. You can copy swig.py to
>site_scons/site_tools and edit it there.
```diff
*** src/engine/SCons/Tool/swig.py     Wed Sep  7 16:27:28 2011
--- site_scons/site_tools/swig.py       Fri Apr 27 11:46:32 2012
***************
*** 155,161 ****
      java_file.add_action('.i', SwigAction)
      java_file.add_emitter('.i', _swigEmitter)
 
!     env['SWIG']              = 'swig'
      env['SWIGVERSION']       = _get_swig_version(env)
      env['SWIGFLAGS']         = SCons.Util.CLVar('')
      env['SWIGDIRECTORSUFFIX'] = '_wrap.h'
--- 155,161 ----
      java_file.add_action('.i', SwigAction)
      java_file.add_emitter('.i', _swigEmitter)
 
!     env.SetDefault(SWIG      = 'swig')
      env['SWIGVERSION']       = _get_swig_version(env)
      env['SWIGFLAGS']         = SCons.Util.CLVar('')
      env['SWIGDIRECTORSUFFIX'] = '_wrap.h'
```

bdbaddog said at 2013-03-29 23:40:47
>Taking ownership of this bug.

**Comment by mwichmann** [comment]
I believe this issue has been resolved, though not exactly the way this proposed. Current tool:
```python
    if 'SWIG' not in env:
        env['SWIG'] = env.Detect(swigs) or swigs[0]
```

**Comment by mwichmann** [comment]
okay, that was the snip from `generate`.  From `exists`:
```python
    swig = env.get('SWIG') or env.Detect(['swig'])
```

**Comment by mwichmann** [comment]
okay, let's consider this done.
