### ISSUE TITLE
Support MSVC 11

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2820]
This issue was originally created at: 2012-02-26 04:14:06.
This issue was reported by: `milgner`.
milgner said at 2012-02-26 04:14:06
>With the Windows 8 Developer Preview available and the public Beta just around the 
>corner, it would be nice to have support for Visual Studio 11 in Scons.
>I'll do some experimentation on this myself but I'm totally inexperienced with 
>Scons and my knowledge of Python is cursory at best, so I thought it best to 
>submit a feature request. Maybe someone else is already working on this, although 
>I think it unlikely :)

**Comment by ajf58** [comment]
Implemented.

**Comment by bdbaddog** [comment]
Implemented in SCons 2.3.4
