### ISSUE TITLE
Variables validation should indicate which variable failed to validate

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2828]
This issue was originally created at: 2012-03-23 00:58:49.
This issue was reported by: `mortoray`.
mortoray said at 2012-03-23 00:58:49
>When a value for a variable doesn't validate (it fails validation) the user gets only a generic exception stack trace from the validator. The name of the variable which failed is nowhere in that output, thus it is not possible for the user to know which variable is invalid.
> 
>For example:	
```python
PathVariable('PREFIX','Installation prefix','',PathVariable.PathIsDirCreate),
```
> 
>If nothing is specified (use default), or the user gives an invalid directory the display is:
```
OSError: [Errno 2] No such file or directory: '':
  File "/safe/server/mortoray-main/analysis/SConstruct", line 27:
    tools=['default','qt4']
  File "/usr/local/lib/scons-2.1.0/SCons/Environment.py", line 982:
    variables.Update(self)
  File "/usr/local/lib/scons-2.1.0/SCons/Variables/__init__.py", line 216:
    option.validator(option.key, env.subst('${%s}'%option.key), env)
  File "/usr/local/lib/scons-2.1.0/SCons/Variables/PathVariable.py", line 102:
    os.makedirs(val)
  File "/usr/lib64/python2.6/os.py", line 157:
    mkdir(name, mode)
```
>The Ideal display would be something like:
```
Variable "PREFIX" is invalid: OSError: [Errno 2] No such file or directory: ''
```

**Comment by mwichmann** [comment]
Just looked at this... the question is whether the validator should be responsible for this or the code that call it.  Four of the validators (`PathIsDir`, `PathIsDirCreate`, `PathIsFile`, `PathExists`) *do* raise a `UserError` with the variable clearly indicated.  The example of this issue is the one case that doesn't - it raises if it's invalid because exists-and-is-a-file, but then there's nothing protecting the mkdir case that follows. Can we just add that and close? Or does something more general have to happen?

**Comment by bdbaddog** [comment]
> Just looked at this... the question is whether the validator should be responsible for this or the code that call it. Four of the validators (`PathIsDir`, `PathIsDirCreate`, `PathIsFile`, `PathExists`) _do_ raise a `UserError` with the variable clearly indicated. The example of this issue is the one case that doesn't - it raises if it's invalid because exists-and-is-a-file, but then there's nothing protecting the mkdir case that follows. Can we just add that and close? Or does something more general have to happen?

Yes handling that case should resolve this issue. Please add that?

**Comment by mwichmann** [comment]
that change is in PR #4031
