### ISSUE TITLE
if you do Default before you do Alias, scons doesn't recognise it

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2839]
This issue was originally created at: 2012-05-11 08:58:56.
This issue was reported by: `thosrtanner`.
thosrtanner said at 2012-05-11 08:58:56
> For instance:
```python
env = Environment()
o = env.Program('Hello.cc')
env.Default('all')
env.Alias('all', o)
```
then
```console
> scons -Q
scons: *** Do not know how to make File target `all' (/bbcm/ticker_plant/source/all).  Stop.
```
> Swap the Default and Alias lines round, it works fine.

**Comment by mwichmann** [comment]
How about a simple addition to the doc as a resolution?  Something like

>  `Default` will also accept a previously defined Alias as a target name.

**Comment by bdbaddog** [comment]
Perhaps extend with something like

> Any Alias defined after the Default statement will not be recognized, unlike a file or directory which will.

**Comment by bdbaddog** [comment]
Added example file to: https://github.com/bdbaddog/scons-bugswork/tree/main/2839

**Comment by mwichmann** [comment]
Potentially related to #2581
