### ISSUE TITLE
'-pg' option not handled correctly

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2861]
This issue was originally created at: 2012-07-30 12:47:01.
This issue was reported by: `elaeum`.
elaeum said at 2012-07-30 12:47:01
>The '-pg' option, used for enabling profiling support in GCC is not correctly 
>handled by MergeFlags().
> 
>'-pg' should to be included in the LINKFLAGS variable.
> 
>I can attach examples/code as necessary.

bdbaddog said at 2012-08-02 00:05:10
>Please attach examples/code/reproducible testcase.

**Comment by bdbaddog** [comment]
No Reproducer.
Closing.
Please reopen if you can provide one.

**Comment by mwichmann** [comment]
Not sure it needs a reproducer: any gcc flag to be handled by Parse/Mergeflags routines needs to be added explicitly and `-pg` is not.  However there doesn't seem to have been any activity on this for a very long time, so don't object to closing.
