### ISSUE TITLE
python modules in local path can cause conflicts

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2867]
This issue was originally created at: 2012-08-22 16:13:43.
This issue was reported by: `greengadgetz`.
greengadgetz said at 2012-08-22 16:13:43

Python modules in the local directory hide normal python models. If you run from a directory containing a python module that has the same name as one used by scons (i.e. "random") scons will import the local version instead of python's installed version. 

Here is an example that reproduces this behavior:
>---example start----
```console
$ mkdir random
$ touch random/__init__.py
$ scons
Traceback (most recent call last):
  File "/opt/local/bin/scons", line 187, in <module>
    import SCons.Script
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.2.0/SCons/Script/__init__.py", line 76, in <module>
    import SCons.Environment
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.2.0/SCons/Environment.py", line 54, in <module>
    import SCons.Platform
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.2.0/SCons/Platform/__init__.py", line 52, in <module>
    import tempfile
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 34, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```
>---example end----
>In this case there is no SConstruct file so the expected result is a different error:
```console
scons: *** No SConstruct file found.
```
Tested on OS X version 10.7.4, but likely affects other platforms
```console
$ python --version
Python 2.7.3
$ scons --version
SCons by Steven Knight et al.:
  script: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
  engine: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
  engine path: ['/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/scons-2.2.0/SCons']
Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012 The SCons Foundation
```

**Comment by mwichmann** [comment]
This is "just the way it is".  IDLE famously blows up this way, when a learner saves a file with an unfortunately chosen name, it's imported in favor of one IDLE needs, and breakage ensues.  Suggest we reject this - not even sure where one would document it.

**Comment by bdbaddog** [comment]
Sounds good.
I'll close.
