### ISSUE TITLE
SCons does not report cache error

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2868]
This issue was originally created at: 2012-08-22 23:09:30.
This issue was reported by: `vflashm`.
vflashm said at 2012-08-22 23:09:31

If you specify non-existent or unavailable folder as CacheDir, scons will fail on pushing file to cache, halt the build, but won't show any error. "done building targets" will be printed instead. Correct errorcode will be returned, though.
 
`EnvironmentError` raised by `CacheDir.py` will be silently converted to `BuildError` in `Action.py:FunctionAction:def execute`, then just as silently processed in `Script/Main.py:def main()`.
 
Found in 2.1.0, reproduced in 2.2.0.
 
Sample config used to reproduce the error (create in1 and in2 first).  Scons will create out1, fail to push it to cache, won't build out2 and display "done" message.

```python
CacheDir(r'\\incorrectdir\network\path')
node = InstallAs('out1', 'in1')
node = InstallAs('out2', 'in2')
Default(node)
```

vflashm said at 2012-08-22 23:12:48
I'm sorry found mistake in test script. Correct script:

```python
CacheDir(r'\\incorrectdir\network\path')
nodes = []
nodes += InstallAs('out1', 'in1')
nodes += InstallAs('out2', 'in2')
Default(nodes)
```

**Comment by mwichmann** [comment]
I think this has been fixed, I now see something like:
```console
SConsEnvironmentError: Failed to create cache directory /incorrectdir/network/path:
```
Tries on windows too... close?

**Comment by bdbaddog** [comment]
Yup. Closing.
