### ISSUE TITLE
SCons can't share cache files between different OSes

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2870]
This issue was originally created at: 2012-08-27 22:37:50.
This issue was reported by: `vflashm`.

>vflashm said at 2012-08-27 22:37:50

In function `"def get_cachedir_bsig(self)` (`Node/FS.py`), target file path added to file cache signature (which is bad by itself, by the way). The problem is that different OSes have different path separators. On Windows we have `path\file.ext`, on *nix we have `path/file.ext`. Because of that *nix machines can't use files built on Windows machines and other way around.
 
it's enough to replace `sigs.append(self.path` with `sigs.append(self.path.replace('\\', '/'))` to fix sharing between different OSes

>extrachrispy said at 2012-08-27 22:48:22

I would be surprised if you could share derived files between Windows and *nix even with the same path separators:  Windows uses PE format, and most *nix boxes use ELF (OS X uses Mach-O); thus, the hash digests won't match anyway.

>vflashm said at 2012-08-28 00:50:12

Well, then it's time to be surprised: there are other files apart form executables in this world.
 
For example, optimized PNGs will be the same regardless of OS if I use the very same tools to do optimization. Compressed textures can be compressed on any machine with the same result. Moreover, even binaries can be shared, if that's corsscompiled binaries (eg, built for third platform, other than *nix and windows).
 
Unfortunately, the fix I proposed is not enough: different versions of python on different platforms have different `executor.get_contents()` values. It's same for trivial actions, bot differs for more complex ones. I didn't dig very deep into that issue, maybe it worth investigating. For now to make use of shared cache you have to either disable adding executor content to cache signature or to make your action function trivial (for example, by delegating all work to
other function right away).

**Comment by mwichmann** [comment]
This looks like it's the same issue as #2666, maybe combine them?  This this a good target for 4.0 since the other one (#2666) suggests this is a change that's not just transparent?

**Comment by bdbaddog** [comment]
Yes. Duplicate of https://github.com/SCons/scons/issues/2666 
Closing.
