### ISSUE TITLE
Command example (with variable substitution) does not work

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2905]
This issue was originally created at: 2013-04-29 09:01:31.
This issue was reported by: `dsiroky`.
>dsiroky said at 2013-04-29 09:01:31

Example at the bottom of https://www.scons.org/doc/production/HTML/scons-user/c3895.html
 
thus
```py
env.Command('${SOURCE.basename}.out', 'foo.in', build)
```
or
```py
env.Command('${SOURCE.basename}.out', 'foo.in', "sed 's/x/y/' < $SOURCE > $TARGET")
```
 
kills the build process.
 
I tracked the reason, and it is an exception which is not printed, and it silently exits the scons. The exception is `AttributeError 'str' object has no attribute 'basename' trying to evaluate '${SOURCE.basename}'`.
 
It can be temporarily solved like this:
```py
env.Command('${SOURCE.basename}.out', File('foo.in'), build)
```

Votes for this issue: 1.

**Comment by ajf58** [comment]
This is fixed in the current 3.0.1 documentation (see http://scons.org/doc/production/HTML/scons-user.html#chap-builders-commands). I suggest closing as 'fixed'.

**Comment by bdbaddog** [comment]
Fixed.

**Comment by ompadu** [comment]
I'm still having this problem in 4.8.1

**Comment by mwichmann** [comment]
> I'm still having this problem in 4.8.1

Can you include a current example?

Not sure what was "fixed" in the docs, as they continue to have the reference for `basename`, and don't incldue the "trick" of converting the source to a Node first.

Can you try using `.filebase` instead? That's actually the documented attribute for this:

https://scons.org/doc/production/HTML/scons-man.html#special_attributes

There may still be a problem in evaluation order in `Command`, such that something is attempted before the conversion of filename strings to Nodes.

**Comment by mwichmann** [comment]
A little poking around and there's a path through here that doesn't work out right. Since this issue has been closed for almost seven years, I'm going to open a new one rather than reopening this one.

**Comment by mwichmann** [comment]
See #4660 for the new issue.

**Comment by bdbaddog** [comment]
@ompadu If you use:

`env.Command('${SOURCE.filebase}.out', File('foo.in') , "echo $TARGET $SOURCE")`

It should work. This should get you unstuck if you were stuck. Until such time as we can get it working as you'd expect.

**Comment by ompadu** [comment]
> @ompadu If you use:
> 
> `env.Command('${SOURCE.filebase}.out', File('foo.in') , "echo $TARGET $SOURCE")`
> 
> It should work. This should get you unstuck if you were stuck. Until such time as we can get it working as you'd expect.

Thank you for the quick fix. It goes pass the initial error but it seems that it only processes the first item of a list:

`env.Command('${SOURCE.filebase}.out', [File(file) for file in ['foo_1.in', 'foo_2.in']] , "echo $TARGET $SOURCE")`

output:
```
echo foo_1.out foo_1.in
"foo_1.out" "foo_1.in"
```

**Comment by bdbaddog** [comment]
That's what I'd expect, you've specified `${SOURCE.filebase}.out` (Singular).
Your example likewise only had a single source.

In your updated example,  are you expecting foo_1.out & foo_2.out?  Are both these files processed with a single command? "echo $TARGET $SOURCE" ? 
Or are you expecting it to be run multiple times? once per input source?
If the latter, then

`[ env.Command('${SOURCE.filebase}.out', File(file) , "echo $TARGET $SOURCE") for file in ['foo_1.in', 'foo_2.in' ]
`
Should do the trick.

**Comment by mwichmann** [comment]
`SOURCE` *is* only the first item, by definition. `SOURCES` is all the sources. Same for `TARGET` and `TARGETS`.  They're special cases, I guess the idea is it's so common to need SOURCES[0] and/or TARGETS[0] that way back when it was decided to include the singular forms as well.

**Comment by ompadu** [comment]
> That's what I'd expect, you've specified `${SOURCE.filebase}.out` (Singular). Your example likewise only had a single source.
> 
> In your updated example, are you expecting foo_1.out & foo_2.out? Are both these files processed with a single command? "echo $TARGET $SOURCE" ? Or are you expecting it to be run multiple times? once per input source? If the latter, then
> 
> `[ env.Command('${SOURCE.filebase}.out', File(file) , "echo $TARGET $SOURCE") for file in ['foo_1.in', 'foo_2.in' ] ` Should do the trick.

The second option was the case. I was processing a list of  files, each witch its own input, output and call to the external tool. Now it works how I expected. Thank you! 

> `SOURCE` _is_ only the first item, by definition. `SOURCES` is all the sources. Same for `TARGET` and `TARGETS`. They're special cases, I guess the idea is it's so common to need SOURCES[0] and/or TARGETS[0] that way back when it was decided to include the singular forms as well.

Thank you, now I understand better how this aspect works!
