### ISSUE TITLE
Python not recognized, path not modified

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2933]
This issue was originally created at: 2014-03-01 04:05:05.
This issue was reported by: `mrx23dot`.
mrx23dot said at 2014-03-01 04:05:05
>Scons Windows installer doesn't look for HKEY_LOCAL_MACHINE:
>[HKEY_LOCAL_MACHINE\Software\Python\PythonCore\2.7]
>only looks in: HKEY_CURRENT_USER
> 
>Also windows installer doesn't add Python\Scripts to PATH.
>So cmd> scons is not recognized
>We have to add manually.

bdbaddog said at 2014-03-01 12:01:26
>The windows installer is built using python setuptools.
>This may in fact be an issue with that.

**Comment by mwichmann** [comment]
Since the Windows installer is no longer supported, we could mark this Wontfix.
