### ISSUE TITLE
SConsCPPScannerWrapper crashes on directives involving digits

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2936]
This issue was originally created at: 2014-03-31 15:41:13.
This issue was reported by: `scottd`.
scottd said at 2014-03-31 15:41:13
>SConsCPPScannerWrapper crashes (and causes scons to exit) when encountering certain preprocessor directive patterns involving leading digits.  For example, given a SConstruct file like this:
```python
import SCons.Scanner
env = Environment(CPPPATH=['.'])
f = env.File("a.cpp")
scanner = SCons.Scanner.C.SConsCPPScannerWrapper('prescanner','.')
includes = scanner(f, env)
print "\na.cpp includes:"
for i in includes:
    print "  + %s" % str(i)
```
> 
>and a a.cpp file like this:
> 
```c++
#define USE(X) (defined WTF_USE_##X  && WTF_USE_##X)
#if USE(3D) 
#endif
```
>scons crashes thusly:
```console
scons: Reading SConscript files ...
  File "<string>", line 1
 
    USE(3D)
 
         ^
 
SyntaxError: invalid syntax
```
> 
>(The problem goes away if the source uses, say, "THREED" instead of "3D").

**Comment by mwichmann** [comment]
Just tried this example, and it doesn't show this problem (SConstruct needed modernizing for `print` -> `print()``). @bdbaddog okay to close?

**Comment by bdbaddog** [comment]
sure. if it's fixed, close away! :)

**Comment by mwichmann** [comment]
Closing - anyone can feel free to reopen if this is still an issue.

**Comment by mwichmann** [comment]
Hmmm, clicked close with comment and it didn't. try again...
