### ISSUE TITLE
Scanner docs say "path" instead of "path_function"

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2959]
This issue was originally created at: 2014-07-06 20:36:46.
This issue was reported by: `kostmo`.
kostmo said at 2014-07-06 20:36:46
>In this section of the documentation: 
>http://www.scons.org/doc/production/HTML/scons-user.html#idp2629424
> 
>kscan = Scanner(function = kfile_scan,
>                skeys = ['.k'],
>                path=FindPathDirs('KPATH'))
> 
>This throws an error:
> 
>TypeError: __init__() got an unexpected keyword argument 'path':
> 
>The kwarg in the example should be "path_function" instead.

dirkbaechle said at 2014-07-12 02:17:33
>added keyword

wblevins001 said at 2016-02-19 09:35:45
>Reassigned.

wblevins001 said at 2016-02-19 09:35:58
>Accepted.

**Comment by mwichmann** [comment]
I think this is fixed... the link no longer refers to a specific place in the user guide, but the three instances of `FindPathDirs` and `KPATH` together look ok:
```
$ git grep "FindPathDirs.*KPATH"
doc/user/scanners.xml:                path_function = FindPathDirs('KPATH'))
doc/user/scanners.xml:            path_function = FindPathDirs('KPATH'))
test/Scanner/FindPathDirs.py:                path_function = FindPathDirs('KPATH'))
```

**Comment by bdbaddog** [comment]
O.k. Closing.
