### ISSUE TITLE
Need error message for multiple Configure objects

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2975]
This issue was originally created at: 2014-09-13 11:25:51.
This issue was reported by: `bcatanzaro`.
bcatanzaro said at 2014-09-13 11:25:51
>SCons requires that only one Configure object exist at any time. This is somewhat confusing for users, but 
>it can be worked around with explicit .Finish() calls to Configure objects.
> 
>However, when the user creates two Configure objects, SCons throws a blank user error.
>For example, the following SConstruct
> 
>env = Environment()
>conf = Configure(env)
>clone = env.Clone()
>clone_conf = Configure(clone)
> 
>shows the following output:
>scons: Reading SConscript files ...
> 
>scons: ***
> 
>It would be much better if it said something like
> 
>scons: UserError: Only one Configure object can exist at any time. Use Configure.Finish() to close the 
>Configure object before constructing a new one.

**Comment by mwichmann** [comment]
Didn't this get a fix a while back?

**Comment by bdbaddog** [comment]
Fixed by #3557
