### ISSUE TITLE
LaTeX dependency scanner misses "imported" files

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2976]
This issue was originally created at: 2014-09-17 09:12:13.
This issue was reported by: `ricklupton`.
ricklupton said at 2014-09-17 09:12:13
>The LaTeX dependency scanner looks for \input{} and \include{} commands, but
>misses other common ways of including files provided by the import package [1].
>Specifically:
>  \import
>  \subimport
>  \includefrom
>  \subincludefrom
> 
>I have modified the scanner & tests check for these too and will post a patch
>when I figure out how to use mercurial.
> 
>But this doesn't completely fix the problem -- \import'd files are no longer
>recursively scanned. This turns out to be because there is code in
>src/engine/SCons/Tool/tex.py which repeats the dependency scanner logic, again
>only looking for \input and \include.
> 
>Setting recursive = True in the LaTeX Scanner works and seems to be reasonable,
>but I don't really understand why it is disabled in the first place. Any
>suggestions?
> 
>[1]: http://get-software.net/macros/latex/contrib/import/import.pdf

ricklupton said at 2014-09-17 09:35:51
>Created an attachment (id=948)
>Patch to scan \import etc in LaTeX files

ricklupton said at 2014-09-17 09:36:18
>Created an attachment (id=949)
>Patch to scan \import etc in LaTeX files, also enable recursion

dirkbaechle said at 2014-09-17 11:23:35
>Hi Rick,
> 
>for the Mercurial workflow, please follow the instructions at 
>http://www.scons.org/wiki/SconsMercurialWorkflows . If you get stuck, or things 
>are unclear, let us know...we're very interested in improving our documentation, 
>at every level.

ricklupton said at 2014-09-18 05:13:12
>Thanks for the link, that is helpful. I read the main page found at
>https://bitbucket.org/scons/scons but that doesn't have as much detail on using
>Mercurial. Maybe a link there would be useful. 
> 
>I've submitted a pull request with modified/new tests which fixes this for me:
>https://bitbucket.org/scons/scons/pull-request/185/find-dependencies-using-latex-import/diff
> 
>Thanks,
>Rick

ricklupton attached [latex_scanner_import.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2976/948/latex_scanner_import.patch) at 2014-09-17 09:35:51.
>Patch to scan \import etc in LaTeX files

ricklupton attached [latex_scanner_import_recursive.patch](https://github.com/SCons/tigris-issue-attachments/blob/master/2976/949/latex_scanner_import_recursive.patch) at 2014-09-17 09:36:18.
>Patch to scan \import etc in LaTeX files, also enable recursion

**Comment by luhk** [comment]
I think this should be closed as Bitbucket PR ~~185~~ 374 implements is a newer version of this, which has been merged.

**Comment by bdbaddog** [comment]
> I think this should be closed as Bitbucket PR 185 implements is a newer version of this, which has been merged.

This bit wasn't merged:
```
--- a/src/engine/SCons/Scanner/LaTeX.py	Fri Sep 12 19:59:39 2014 +0200
+++ b/src/engine/SCons/Scanner/LaTeX.py	Wed Sep 17 17:34:29 2014 +0100
@@ -101,7 +101,7 @@
                suffixes =  '$LATEXSUFFIXES',
                # in the search order, see below in LaTeX class docstring
                graphics_extensions = TexGraphics,
-               recursive = 0)
+               recursive = 1)
     return ds
 
 def PDFLaTeXScanner():
@@ -112,7 +112,7 @@
                suffixes =  '$LATEXSUFFIXES',
                # in the search order, see below in LaTeX class docstring
                graphics_extensions = LatexGraphics,
-               recursive = 0)
+               recursive = 1)
return ds
```
But looks like the rest of the patches were.

Any guess why?

**Comment by luhk** [comment]
In https://bitbucket.org/scons/scons/pull-requests/185/find-dependencies-using-latex-import/diff the author said that setting `recursive=1` is not necessary since the LaTeX scanner is internally recursive.
Also, there are `test/TEX/recursive_scanner_dependencies_{import,input}.py`, which, as far as I can see, check for this.

**Comment by bdbaddog** [comment]
Adding links to other related PRS

https://bitbucket.org/scons/scons/pull-requests/374

@luhk  - Thanks for bringing this to the project's attention. Closing!
