### ISSUE TITLE
Duplicate example in section 18.6 of the user guide

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2983]
This issue was originally created at: 2014-12-08 07:59:52.
This issue was reported by: `hmackenberg`.
hmackenberg said at 2014-12-08 07:59:52
>The example given below is given twice in 
>http://www.scons.org/doc/production/HTML/scons-user/ch18s06.html
> 
>Example:
> 
>bld = Builder(action = 'my_command $SOURCES > $TARGET',
>              suffix = '.foo',
>              src_suffix = '.input',
>              emitter = '$MY_EMITTER')
>def modify1(target, source, env):
>    return target, source + ['modify1.in']
>def modify2(target, source, env):
>    return target, source + ['modify2.in']
>env1 = Environment(BUILDERS = {'Foo' : bld},
>                   MY_EMITTER = modify1)
>env2 = Environment(BUILDERS = {'Foo' : bld},
>                   MY_EMITTER = modify2)
>env1.Foo('file1')
>env2.Foo('file2')

**Comment by ajfeatherstone** [comment]
This is stil an issue in 3.0.1 http://scons.org/doc/production/HTML/scons-user.html#idm139933295651056

**Comment by bdbaddog** [comment]
Hmm. Looks like a bad merge at some point.

**Comment by bdbaddog** [comment]
Just added pull request. Please review if you have a moment. Note that some generated files will contain updates from other changes as they haven't been updated in a while.
