### ISSUE TITLE
SCons command line empty quotes "" as "." targets

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2986]
This issue was originally created at: 2014-12-29 11:06:47.
This issue was reported by: `farmersez`.

farmersez said at 2014-12-29 11:06:47
>I messed around with this for about 5-6 days. We're compiling our project using SCons that's being run by another tool. Our tool's configurations can pass different flag to SCons, and the default value is an empty string (""). For instance, we can set the field to be `foobar` and the SCons call will be `scons --foobar`.
> 
>On one of our projects configurations we didn't specify any special flags, so the call to scons (from the SConstruct dir) was:
```
scons "" -j8
```
>This caused a rather annoying thing to happen - In this project configuration we only wanted a part of the source to be compiled, but this extra param was causing the whole tree to be compiled.
> 
>This will also reproduce in version 2.3.4 - the problem is in `SCons/Script/Main.py`:969 (in version 2.3.4).
> 
>The part that extracts targets from the args list does not evalueate if the current argument is an empty one or not:
```
    targets = []
    xmit_args = []
    for a in parser.largs:
        if a[:1] == '-':
            continue
        if '=' in a:
            xmit_args.append(a)
        else:
            targets.append(a)
```
>The last "else" should be changed to "elif a:", then empty strings will not be accounted for.
> 
>Another interesting part is that later on `targets` was a list containing only an empty string (`['']`), and the `fs.Dir` object converted '' to '.', meaning the current directory.
> 
>Cheers,
>S.

dirkbaechle said at 2015-02-12 13:58:03
>*** Issue 2919 has been marked as a duplicate of this issue. ***

dirkbaechle said this issue is duplicated by #2919 at 2015-02-12 13:58:03.

**Comment by mwichmann** [comment]
This seems a simple enough fix. I'd do it like this, I think:
```
     for a in parser.largs:
-        if a[:1] == '-':
+        if not a or a.startswith('-'):
             continue
```
worth pushing? don't have a specific test for it.

**Comment by bdbaddog** [comment]
> This seems a simple enough fix. I'd do it like this, I think:
> 
> ```
>      for a in parser.largs:
> -        if a[:1] == '-':
> +        if not a or a.startswith('-'):
>              continue
> ```
> 
> worth pushing? don't have a specific test for it.

Does "" end up being a False value, or does the string get '""' ?

**Comment by mwichmann** [comment]
an empty string is false, but I'm not sure what happens here - what if we get passed a string containing an empty string?  Guess it does need a repro.

**Comment by mwichmann** [comment]
Okay, this:
```python
q = Textfile(target="foo", source="foostuff")
Textfile(target="bar", source="barstuff")
Default(q)
```
```
$ scons -n
scons: done reading SConscript files.
scons: Building targets ...
Creating 'foo.txt'
scons: done building targets.
$ scons -n .
scons: done reading SConscript files.
scons: Building targets ...
Creating 'bar.txt'
Creating 'foo.txt'
scons: done building targets.
$ scons -n ""
scons: done reading SConscript files.
scons: Building targets ...
Creating 'bar.txt'
Creating 'foo.txt'
scons: done building targets.
```

After the suggested change the third version ... Sigh - edited. Comes out like the first, rather than the second.

**Comment by bdbaddog** [comment]
Is the title of this bug wrong? Shouldn't it be empty quotes?

**Comment by mwichmann** [comment]
seems like it, yes

**Comment by bdbaddog** [comment]
hmm. seems like "" should === all the Defaults()?

**Comment by mwichmann** [comment]
yeah, that's borne out by the test... the third version flips from behaving like the target was "." to none, thus picking up the target set by Deault.

**Comment by mwichmann** [comment]
I can't write an E2E test for this, apparently. 

The E2E framework seems to add extra quoting so the failure differs. `Do not know how to make file target '""'` (quote dblquote pair quote)
