### ISSUE TITLE
No f08 tool

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2987]
This issue was originally created at: 2015-01-06 09:57:03.
This issue was reported by: `russel`.
russel said at 2015-01-06 09:57:03
>There is no f08 tool to match all the tools associated with other Fortran (and 
>FORTRAN :-) standards.

**Comment by mwichmann** [comment]
There's an `SCons/Tool/f08.py` and matching `SCons/Tool/f08.xml` - is this actually an active issue?

**Comment by bdbaddog** [comment]
Closing.
Reopen if still an issue.
