### ISSUE TITLE
gfortran tool doesn't support F08

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2988]
This issue was originally created at: 2015-01-06 10:07:35.
This issue was reported by: `russel`.
russel said at 2015-01-06 10:07:35
>F08 is a valid extension to gfortran but the gfortran SCons tools does not 
>recognize this. There are other reasonable extensions not handled.

**Comment by bdbaddog** [comment]
Just needs to add F08 https://github.com/SCons/scons/blob/master/SCons/Tool/FortranCommon.py#L255 and add a test.

**Comment by bdbaddog** [comment]
or add in gfortran.py and add test.

**Comment by mwichmann** [comment]
Is this a current problem?  This seems to hav tests, and on a Linux system with `gfortran`,
```
$ python runtest.py test/Fortran/*FILESUFFIXES*.py
1/13 (7.69%) /usr/bin/python test/Fortran/F03FILESUFFIXES.py
PASSED
2/13 (15.38%) /usr/bin/python test/Fortran/F03FILESUFFIXES2.py
PASSED
3/13 (23.08%) /usr/bin/python test/Fortran/F08FILESUFFIXES.py
PASSED
4/13 (30.77%) /usr/bin/python test/Fortran/F08FILESUFFIXES2.py
PASSED
5/13 (38.46%) /usr/bin/python test/Fortran/F77FILESUFFIXES.py
PASSED
6/13 (46.15%) /usr/bin/python test/Fortran/F77FILESUFFIXES2.py
PASSED
7/13 (53.85%) /usr/bin/python test/Fortran/F90FILESUFFIXES.py
PASSED
8/13 (61.54%) /usr/bin/python test/Fortran/F90FILESUFFIXES2.py
PASSED
9/13 (69.23%) /usr/bin/python test/Fortran/F95FILESUFFIXES.py
PASSED
10/13 (76.92%) /usr/bin/python test/Fortran/F95FILESUFFIXES2.py
PASSED
11/13 (84.62%) /usr/bin/python test/Fortran/FORTRANFILESUFFIXES.py
PASSED
12/13 (92.31%) /usr/bin/python test/Fortran/FORTRANFILESUFFIXES2.py
PASSED
13/13 (100.00%) /usr/bin/python test/Fortran/FORTRANPPFILESUFFIXES.py
PASSED
```

**Comment by mwichmann** [comment]
Hmmm, just checked, the filesuffix tests don't use the actual fortran they use a mock/fixture.

**Comment by bdbaddog** [comment]
I read this issue as .F08 suffix isn't handled. We do handle .f08

**Comment by mwichmann** [comment]
They both *seem* to be handled. gfortran convention is with the uppercase letter it runs it through cpp first, but that's internal to gfortran afaik.

**Comment by lurobi** [comment]
The following can be used to check if the source file is truly being pre-processed, and additionally to ensure variables are actually being substituted.

sconstruct:
```python
env = Environment()
env.Append(CPPDEFINES={"TEST_VALUE":"AAA"})
env.Program(source="testF90.F90", target="testF90")
```

```fortran
program check_preprocessing
  ! implicit statements: anything begining with C-Z will be 4-character string (TEST_VALUE)
  ! implicit statements: anything begining with A-B will be 8-character string (AAA)
  implicit character(len=4) (c-z)
  implicit character(len=8) (a-b)
#if 1==0
  character(len=6) :: TEST_VALUE
#endif
  !print *,len(ABC),len(TTT),len(test_value),len(TEST_VALUE)
  if (len(AAA) == len(TEST_VALUE)) then
     print *,'SUCCESS: TEST_VALUE is AAA'
  ! Fortran is not case sensitive, but the C-Pre-Processor is,
  ! so only one of these will be replaced with AAA
  elseif (len(TEST_VALUE) == len(test_value))  then
     print *,'PARTIAL FAIL: preprocessing has happend, but not TEST_VALUE definition.  Need "-DTEST_VALUE=AAA"'
  elseif (len(TEST_VALUE) == 6) then
     print *,'FAIL: no preprocessing. Need "-cpp -DTEST_VALUE=AAA"'
  end if
end program check_preprocessing
```

When I run this, I get the PARTIAL FAIL result.

**Comment by mwichmann** [comment]
This is looking ok to me, unless I'm missing something.  I changed the name to `.F08` and duplicated the file and the `Program` call so it would build a `.f08` and a `.F08` file, and set up the variables to be more descriptive. Revised `SConstruct`:
```
env = Environment()
env.Append(CPPDEFINES={"TEST_VALUE": "AAA"})
env['F08COMSTR'] = "Using F08COMSTR to compile $TARGET"
env['F08PPCOMSTR'] = "Using F08PPCOMSTR to compile $TARGET"
env['LINKCOMSTR'] = "Using LINKCOMSTR to link $TARGET"

env.Program(source="testF08.F08", target="testF08")
env.Program(source="testf08.f08", target="testf08")
```
With that I get a build run like this:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Using F08PPCOMSTR to compile testF08.F08 to testF08.o
Using LINKCOMSTR to link testF08.o to testF08
Using F08COMSTR to compile testf08.f08 to testf08.o
testf08.f08:6:2:

    6 | #if 1==0
      |  1
Warning: Illegal preprocessor directive
testf08.f08:8:2:

    8 | #endif
      |  1
Warning: Illegal preprocessor directive
Using LINKCOMSTR to link testf08.o to testf08
scons: done building targets.
```
It seems to be using the right bits for each build, and the lower-case one throws warnings, showing it's not being preprocessed.

**Comment by lurobi** [comment]
Yes, you are correct.  I had forgotten `env.` in front of my `Program` last night.  With that fixed, it all seems to work for me too on Linux (WSL)

**Comment by lurobi** [comment]
Although on Linux there is no bug, on case-insensitive systems such as Windows, Cygwin, and Msys, the test still fails (PARTIAL FAIL).

The reason for this is that [Tool.FortranCommon.ComputeFortranSuffixes ](https://github.com/SCons/scons/blob/97dbf8d22b518a8f67cf670f8e3449990f3f5813/SCons/Tool/FortranCommon.py#L88) never adds the upper-case suffixes on these case-insensitive systems.

I would suspect the original reporter was running on such a case-insensitive system and therefore never observed scons to execute the pre-processing compilation.

I will see if I can verify that switching that function's behavior doesn't break any of the tests.

**Comment by bdbaddog** [comment]
ON case-insensitive filesystems, F vs f's never going to work. so a different suffix altogether would be the only solution, or setting the PP version to be f90 and something else for non PP version. But that's out of scope for this bug.

I think we can safely close this issue?
Thoughts @mwichmann  @lurobi ?

**Comment by mwichmann** [comment]
My non-Fortran brain (despite that Fortran was the first language I learned) thinks there's really nothing left here. Even the docs mention this last case https://scons.org/doc/4.0.1/HTML/scons-man.html#f_file_suffix although maybe "and variants" or something like that could be added.

**Comment by bdbaddog** [comment]
O.k. Closing.
