### ISSUE TITLE
html special characters are visible

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3003]
This issue was originally created at: 2015-03-30 03:43:52.
This issue was reported by: `knut3`.
knut3 said at 2015-03-30 03:43:52
>There are visible < and > text fragments especially in context of #include.
> 
>http://www.scons.org/doc/latest/HTML/scons-user.html
> 
>search for: lt;

wblevins001 said at 2015-07-25 09:53:18
>Request submitted.

wblevins001 said at 2015-07-25 09:55:26
>I wish Tigris didn't change Issue numbers on interactions.

**Comment by mwichmann** [comment]
There are no &lt; but plenty of &gt;. All, as far as I can tell, in example output, so it's probably a single fix. Current doc (3.1.1) showed 43 matches.

**Comment by mwichmann** [comment]
This is what's actually happening - all < and most > are correctly encoded in the generated examples, but some ended up like this - the leading `&` ended up itself encoded, so we have an incorrect entity.  Not sure where that's coming from...
```
'Dir': &lt;SCons.Defaults.Variable_Method_Caller object at 0x700000&amp;gt;,
```
