### ISSUE TITLE
Add MS Visual studio 2015 support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3012]
This issue was originally created at: 2015-10-23 08:47:09.
This issue was reported by: `wolgan`.
wolgan said at 2015-10-23 08:47:09
>Hi All,
>Trying to compile serf v.1.3.8 with the help of scons for MS Visual Studio 2015.
> 
>The error I'm gettring: scons: *** Invalid value for option MSVC_VERSION: 14.0.
> Valid values are: ('12.0', '11.0', '10.0', '9.0', '8.0', '6.0')
> 
>That means there is no support of MS VS 2015 in scons as I assume.
> 
>Scons version: 2.4.0

bdbaddog said at 2015-10-23 09:32:17
>Yes. VS 2015 should be supported since 2.3.6
> 
>https://bitbucket.org/scons/scons/src/9983e5d6e0bbbe5f2d3543e379e4a31e25cb3c71/src/CHANGES.txt?at=default&fileviewer=file-view-default
> 
>Can you set
> 
>set SCONS_MSCOMMON_DEBUG=%TEMPDIR%\MSVSDEBUG.log
>Run scons
>and then attach that output to this bug?

wolgan said at 2015-10-23 12:26:57
>Created an attachment (id=961)
>MSVSDEBUG.log

bdbaddog said at 2015-10-23 12:41:10
>Did you get the error below again on this last run via windows shell?

bdbaddog said at 2015-10-23 12:42:13
>BTW. Here's the SCons page on how to file bugs.
>http://scons.org/bugs.php
> 
>Generally we ask that people bring their issues to the mailing list first and
>then if we can't resolve, file a bug.

wolgan said at 2015-10-23 12:43:22
>Yes.
> 
>D:\cygwin\home\Oleg\serf>scons
>scons: Reading SConscript files ...
> 
>scons: *** Invalid value for option MSVC_VERSION: 14.0.  Valid values are: ('12.
>0', '11.0', '10.0', '9.0', '8.0', '6.0')
>File "D:\cygwin\home\Oleg\serf\SConstruct", line 151, in <module>
> 
>Python version is 2.7 

wolgan said at 2015-10-23 12:45:31
>Sorry. Didn't saw this link. I thried to search thru bugtracker but didn't find
>issue like that.

bdbaddog said at 2015-10-23 13:40:55
>Can you post a simple SConstruct which shows this issue?

bdbaddog said at 2015-10-23 13:45:37
>What are you trying to build?
> 
>This message: " scons: *** Invalid value for option MSVC_VERSION: 14.0.
> Valid values are: ('12.0', '11.0', '10.0', '9.0', '8.0', '6.0')"
> 
>Is only issued when an EnumVariable is used. So likely this is not SCons, but
>the SConstruct/SConscript logic in whatever package you've downloaded and are
>trying to build..
> 
>Here's a snippet from 'SCons/Variables/EnumVariable.py' where the message is output:
>def _validator(key, val, env, vals):
>    if not val in vals:
>        raise SCons.Errors.UserError(
>            'Invalid value for option %s: %s.  Valid values are: %s' % (key,
>val, vals))
> 

bdbaddog said at 2015-10-23 13:47:05
>If it was from the msvc logic the message would look like:
> 
>        debug("Unknown version of MSVC: %s" % msvc_version)
>        raise UnsupportedVersion("Unknown version %s" % msvc_version)

wolgan said at 2015-10-24 04:56:57
>I was trying to build serf library for svn. But as I see the last version of it
>(1.3.8) is from last year so maybe this is the problem. I will try to modify
>SConstruct to bypass this issue.
> 
>Thank you for advice. Sorry for disturbing you in wrong place. 

bdbaddog said at 2015-10-25 20:45:59
>If this is indeed an issue with the SConstruct/SConscripts you are using and not
>SCons itself, please mark this bug is invalid.

wolgan attached [MSVSDEBUG.log](https://github.com/SCons/tigris-issue-attachments/blob/master/3012/961/MSVSDEBUG.log) at 2015-10-23 12:26:57.
>MSVSDEBUG.log

**Comment by ajfeatherstone** [comment]
I think based on the comments on this issue and the lack of other issues with Visual Sutdio 2015 support this bug should be closed as not an issue.

**Comment by bdbaddog** [comment]
Per @ajfeatherstone  and lack of any updates closing
