### ISSUE TITLE
Side effects cause internal error with variant_dir

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3013]
This issue was originally created at: 2015-11-12 06:53:27.
This issue was reported by: `sross`.
sross said at 2015-11-12 06:53:27
>When including a SideEffect statement in a SConscript built with a variant_dir, 
>there is an internal error, e.g.:
> 
>>> scons 
>scons: Reading SConscript files ...
>scons: done reading SConscript files.
>scons: Building targets ...
>scons: building associated VariantDir targets: build
>scons: done building targets.
> 
>scons: *** Found dependency cycle(s):
>  Internal Error: no cycle found for node build (<SCons.Node.FS.Dir object at 
>0x20da620>) in state pending
>  build/output -> build/output
> 
>File "/usr/local/lib/scons-2.4.0/SCons/Taskmaster.py", line 1043, in cleanup

sross said at 2015-11-12 06:55:17
>Created an attachment (id=962)
>Demonstration of issue

sross said at 2015-11-12 06:56:21
>See the attached files for a demonstration of the problem...running scons 
>produces the error.

sross said at 2015-11-12 07:02:56
>Created an attachment (id=963)
>Demonstration of issue with parallel build

sross said at 2015-11-12 07:05:53
>Sorry, it looks like my first example was showing something slightly different 
>(but still a bug, it reports internal error).  Please see the second example, 
>fails_with_parallel_build.tar.gz.
> 
>The second example passed with scons, fails with scons -j2.

bernardb said at 2016-02-09 08:39:48
>I've also hit this same bug, and I think I've tracked it down to an error in Taskmaster's 
>logic around the handling of side-effects. A side-effect may cause its parent to be added 
>to the waiting_parents list, which increments the parent's ref_count.
> 
>The reference count for side-effects is only decremented by postprocess() if the side-
>effect node is in the state NODE_EXECUTING. However, in some cases, 
>executed_without_callbacks/executed_with_callbacks is called before postprocess(), which 
>sets the state of the side-effect nodes to NODE_NO_STATE. I confess I don't understand the 
>logic here, but I think the issue is that when postprocess() gets called, the reference 
>count does not get decremented because the side-effect nodes are not in the NODE_EXECUTING 
>state.
> 
>So my first attempt was to modify postprocess() to also iterate over a side-effect's 
>waiting_parents if it was in the state NODE_NO_STATE. This gave rise to a second issue 
>which is that side-effects may get generated more than once, and the waiting_parents set 
>was never cleared, nor were the nodes removed from pending_children. Fixing both of these 
>seems to resolve the issue for me, and also fixes the test case Stefan has attached.
> 
>Patch is attached. I'm not hugely confident in this, so please take this as a stab in the 
>right direction. I've tested the existing unit tests and it seems to pass. I don't know how 
>or have time to turn Stefan's test case into a unit test, but I hope some developer can 
>help there!

bernardb said at 2016-02-09 08:41:09
>Created an attachment (id=964)
>First stab at fixing this bug

bdbaddog said at 2016-02-09 18:05:58
>Could we ask you to submit a pull request on bitbucket?
> 
>https://bitbucket.org/scons/scons/wiki/DeveloperGuide/MercurialWorkflows
> 

bernardb said at 2016-02-09 20:45:41
>I've created a pull request at https://bitbucket.org/scons/scons/pull-requests/303/fix-handling-of-side-effects-in-taskmaster/diff

Votes for this issue: 11.

sross attached [side_effect_error.tar.gz](https://github.com/SCons/tigris-issue-attachments/blob/master/3013/962/side_effect_error.tar.gz) at 2015-11-12 06:55:17.
>Demonstration of issue

sross attached [fails_with_parallel_build.tar.gz](https://github.com/SCons/tigris-issue-attachments/blob/master/3013/963/fails_with_parallel_build.tar.gz) at 2015-11-12 07:02:56.
>Demonstration of issue with parallel build

bernardb attached [scons-3013-fix.diff](https://github.com/SCons/tigris-issue-attachments/blob/master/3013/964/scons-3013-fix.diff) at 2016-02-09 08:41:09.
>First stab at fixing this bug

**Comment by VerditeLabs** [comment]
Any chance that this, and the associated fix [here on bitbucket](https://bitbucket.org/scons/scons/pull-requests/303/fix-handling-of-side-effects-in-taskmaster/diff) can be merged? I'm seeing this exact same bug at work and it's preventing us from upgrading from scons 2.0.1. The linked pull request fixes it.

**Comment by bdbaddog** [comment]
Any chance you could migrate the pull request over to github?
A bit time constrained myself at the moment.
