### ISSUE TITLE
Mis-processing of GCC flags "--param arg1=val1 --param arg2=val2"

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3017]
This issue was originally created at: 2015-12-24 15:16:27.
This issue was reported by: `hartwork`.
hartwork said at 2015-12-24 15:16:27
>Hi!
> 
>When building libmypaint [1] I ran into a bug with valid gcc CFLAGS
> 
>  CFLAGS="--param l1-cache-size=32 --param l2-cache-size=6144"
> 
>that make otherwise happy compilation fail.  I wonder if we are dealing with a
>bug in the way that scons processes CFLAGS or with libmypaint's specific use of
>scons.  I am hoping for your help with answering that question.
> 
>libmypaint's build system is accessing CFLAGS like this:
> 
>  # fgrep -Rw CFLAGS .
>  ./SConstruct:if os.environ.has_key('CFLAGS'):
>  ./SConstruct:   env['CCFLAGS'] += SCons.Util.CLVar(os.environ['CFLAGS'])
>  ./SConstruct:env.Append(CFLAGS='-std=c99')
>  ./SConstruct:env.Append(CFLAGS='-D_POSIX_C_SOURCE=200809L')
>  ./SConscript:    env.Append(CFLAGS='-fopenmp')
> 
>To reproduce the error I get (ruther down) you could run the following:
> 
>  # git clone https://github.com/mypaint/libmypaint.git
> 
>  # cd libmypaint
> 
>  # git checkout -b mybranch 379dbba7897815d9bad8bb068560376f03dcd12b
> 
>  # CFLAGS="--param l1-cache-size=32 --param l2-cache-size=6144" scons
>enable_gegl="true"
>  scons: Reading SConscript files ...
>  scons: done reading SConscript files.
>  scons: Building targets ...
>  Creating 'mypaint-config.h'
>  gcc -o brushmodes.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3
>--param l1-cache-size=32 --param l2-cache-size=6144 -Wall -Wstrict-prototypes
>-Werror -g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -I. -I/usr/include/json-c brushmodes.c
>  generate_cheaders(["mypaint-brush-settings-gen.h", "brushsettings-gen.h"],
>["generate.py", "brushsettings.py", "brushsettings.json"])
>  python2.7 generate.py mypaint-brush-settings-gen.h brushsettings-gen.h
>  Writing mypaint-brush-settings-gen.h
>  Writing brushsettings-gen.h
>  gcc -o fifo.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 --param
>l1-cache-size=32 --param l2-cache-size=6144 -Wall -Wstrict-prototypes -Werror -g
>-fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -I. -I/usr/include/json-c fifo.c
>  gcc -o gegl/mypaint-gegl-surface.os -c -std=c99 -D_POSIX_C_SOURCE=200809L
>-fopenmp -O3 l1-cache-size=32 --param l2-cache-size=6144 -Wall
>-Wstrict-prototypes -Werror -g -pthread -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -I.
>-I/usr/include/json-c -I/usr/include/gegl-0.3 -I/usr/include/json-glib-1.0
>-I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0
>-I/usr/lib64/glib-2.0/include -I/usr/include/babl-0.1 gegl/mypaint-gegl-surface.c
>  gcc: error: l1-cache-size=32: No such file or directory
>  scons: *** [gegl/mypaint-gegl-surface.os] Error 1
>  scons: building terminated because of errors.
> 
>I am looking forward on your feedback.
> 
>Thanks and best, Sebastian
> 
>[1] https://github.com/mypaint/libmypaint
>[2] https://github.com/mypaint/libmypaint/issues/30

bdbaddog said at 2015-12-24 19:09:42
>Generally we ask users to bring their issues to the users mailing list to
>discuss the issue before filing a bug.
>You can see our bug policy here:
>http://scons.org/bugs.php
> 
>This will get far more eyes than filing the bug.
> 
>Can you try escaping the space between param and it's argument?

hartwork said at 2015-12-25 05:31:53
>When escaped I get this:
> 
># CFLAGS="--param\ l1-cache-size=32 --param\ l2-cache-size=6144" scons
>enable_gegl="true"                                                             
>                                                                
>scons: Reading SConscript files ...                                            
>                                                                               
>                                                       
>scons: done reading SConscript files.                                          
>                                                                               
>                                                       
>scons: Building targets ...
>gcc -o brushmodes.os -c -std=c99 -D_POSIX_C_SOURCE=200809L -fopenmp -O3 --param\
>l1-cache-size=32 --param\ l2-cache-size=6144 -Wall -Wstrict-prototypes -Werror
>-g -fPIC -DHAVE_JSON_C -DHAVE_GETTEXT -I. -I/usr/include/json-c brushmodes.c
>gcc: error: unrecognized command line option ‘--param l1-cache-size=32’
>gcc: error: unrecognized command line option ‘--param l2-cache-size=6144’
>scons: *** [brushmodes.os] Error 1
>scons: building terminated because of errors.
> 
> 
>Same with double back-slash.
> 
>(Since in some distros CFLAGS are configured system-wide, making the escaped
>version work would not be a real fix since it would break other build systems then.)

**Comment by mwichmann** [comment]
The linked PR would add recognition of `--param` to `ParseFlags`, and thus to the methods that invoke it - `MergeFlags` and `ParseConfig` - but would not affect trying push these directly into CCFLAGS as in the example above.

**Comment by hartwork** [comment]
Cool, thank you!
