### ISSUE TITLE
scons -j num causes dependency cycle, no cycle found for node

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3018]
This issue was originally created at: 2015-12-29 04:13:46.
This issue was reported by: `anticimex`.
anticimex said at 2015-12-29 04:13:46
>Referring to the scons-users thread at 
>https://pairlist4.pair.net/pipermail/scons-users/2015-November/004224.html , 
>there is a bug with parallel builds, provoked by all of variant_dir/SideEffect/parallel.
> 
>The bug:
```
$ scons -j 8
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
make_file(["build/output"], ["test.cpp"])
scons: done building targets.
 
scons: *** Found dependency cycle(s):
  Internal Error: no cycle found for node build (<SCons.Node.FS.Dir object at 
0x25eb210>) in state pending
 
File "/usr/lib/scons/SCons/Taskmaster.py", line 1026, in cleanup
```

> 
>The test code.
>SConstruct:
>==================
```
env = Environment()
 
def make_file(target, source, env):
    with open(str(target[0]), 'w') as f:
        f.write('gobldygook')
    with open(str(target[0]) + '_side_effect', 'w') as side_effect:
        side_effect.write('anything')
 
env.Append(BUILDERS =
    {'make_file': Builder(action=Action(make_file))})
 
SConscript('SConscript',
     variant_dir = 'build',
     exports={'env':env},
     duplicate=0)
```
>==================
> 
>SConscript:
>==================
```
Import('env')
 
primary = env.make_file('output', 'test.cpp')
this_causes_problems = env.SideEffect('output_side_effect', 'output')
```
>==================
> 
>test.cpp:
>==================
```
#include <iostream.h>
 
main()
{
    cout << "Hello World!";
    return 0;
}
```
>==================
> 
> 
>In our case, we're trying to build a project with ~200 SConscript files that 
>fails like this bug, when doing parallel build, and serial build just takes so 
>long (>45m).
>Our dev cycles would improve severely if we were able to properly do parallel 
>builds in the project.

Votes for this issue: 2.

**Comment by bblackham** [comment]
This looks like Issue #3013 and has a fix in a pull request that's been pending on bitbucket for over two years: https://bitbucket.org/scons/scons/pull-requests/303/fix-handling-of-side-effects-in-taskmaster/diff
