### ISSUE TITLE
Visual Studio >2012 builds

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3024]
This issue was originally created at: 2016-04-20 23:59:25.
This issue was reported by: `flow86`.
flow86 said at 2016-04-20 23:59:25
>Hi,
> 
>I ran into a problem with Visual Studio builds.
> 
>It seems that newer vcvars32.bat's need 2 Paths ( ProgramFiles and
>ProgramFiles(x86) ) inside its environment, otherwise i.e "msbuild" does not
>find the newer platform definitions
> 
>```
>Index: SCons/Tool/MSCommon/common.py
>===================================================================
>--- SCons/Tool/MSCommon/common.py	(revision 10149)
>+++ SCons/Tool/MSCommon/common.py	(revision 10150)
>@@ -146,9 +146,13 @@
>     # settings in vs.py.
>     vars = [
>         'COMSPEC',
>+        'ProgramFiles',
>+        'ProgramFiles(x86)',
> # VS100 and VS110: Still set, but modern MSVC setup scripts will
> # discard these if registry has values.  However Intel compiler setup
> # script still requires these as of 2013/2014.
>+        'VS140COMNTOOLS',
>+        'VS120COMNTOOLS',
>         'VS110COMNTOOLS',
>         'VS100COMNTOOLS',
>         'VS90COMNTOOLS',
>```

bdbaddog said at 2016-04-21 08:52:00
>Thanks for your bug report.
>However we request that users bring their issues to the users mailing list to
>confirm that it is a new bug and also that it's not user error.
>http://scons.org/bugs.html
> 
> 
>In addition we prefer pull requests on bitbucket.org
>(see https://bitbucket.org/scons/scons/wiki/DeveloperGuide )
>Also if you can create a simple testcase for each issue you've filed to put in
>your pull request along with your patch that would be ideal.

**Comment by ajfeatherstone** [comment]
I think this is issue can be closed. SCons has similar but different code in this file currently, and seems to work out of the box with Visual Studio 2015.

**Comment by bdbaddog** [comment]
VS up to 2017 builds work with current 3.0.1 scons. Closing.
