### ISSUE TITLE
scons --tree=status raises an exception

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3033]
This issue was originally created at: 2016-09-29 06:59:55.
This issue was reported by: `joelostraat`.
joelostraat said at 2016-09-29 06:59:55
>Running "scons --tree=status" with a simple SConstruct and SConscript raises an exception (rel_2.5.0):
> 
>mkdir -p scons-tree/src
>cd scons-tree/
>echo "SConscript( 'src/SConscript', variant_dir='build', duplicate=0 )" > SConstruct
>touch src/SConscript # This can have a simple Program( 'hello.c' ) or whatever or be empty.
>~/scons/bootstrap.py --tree=status
> 
>[E b   C  ]+-.
>[E     C  ]  +-SConstruct
>[  b   C  ]  +-build
>scons: done building targets.
>AttributeError: 'NoneType' object has no attribute 'get_contents':
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 1346:
>    _exec_main(parser, values)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 1309:
>    _main(parser)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 1091:
>    nodes = _build_targets(fs, options, targets, target_top)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 1283:
>    jobs.run(postfunc = jobs_postfunc)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Job.py", line 111:
>    self.job.start()
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Job.py", line 218:
>    task.postprocess()
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 288:
>    tp.display(t)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Script/Main.py", line 419:
>    SCons.Util.print_tree(t, func, prune=self.prune, showtags=s)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Util.py", line 286:
>    print_tree(C, child_func, prune, idx, margin, visited)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Util.py", line 288:
>    print_tree(children[-1], child_func, prune, idx, margin, visited)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Util.py", line 260:
>    tags.append(' C'[IDX(root.is_up_to_date())])
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Node/FS.py", line 3286:
>    if not self.changed(r):
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Node/FS.py", line 3241:
>    has_changed = SCons.Node.Node.changed(self, node)
>  File "/home/joelo/scons/bootstrap/src/engine/SCons/Node/__init__.py", line 1462:
>    contents = self.get_executor().get_contents()
> 
>This was introduced in a8570fab2b7b: I get this error in a8570fab2b7b and do not get the error in its 
>parent, c576ba64f060.
> 
>Looking into it a little, I think that SCons.Node.FS.File.executor should never be None.  The uses of 
>get_executor() prior to this change seem to expect it to return either a valid Executor object, or raise 
>an exception leaving the executor attribute non-existent.
> 
>I was able to prevent the problem by changing the line 
>https://bitbucket.org/scons/scons/commits/a8570fab2b7b2f3f1ce520528908904b9584e1f9#Lsrc/engine/SCons/Nod
>e/FS.pyT2786 to self.reset_executor() and removing a few other checks for "self.executor is None" also 
>added in that commit.  But I don't know if that's the right solution.
> 
>Perhaps there is some extra meaning meant to be conveyed when that executor attribute is be None.  If 
>that's true, then there are many other places where the return value of get_executor() should be checked 
>against None.
> 
>Thanks!

joelostraat said at 2016-09-29 07:56:08
>Created an attachment (id=969)
>Proposed fix, using reset_executor() instead of setting executor to None

joelostraat attached [scons-tree-fix.diff](https://github.com/SCons/tigris-issue-attachments/blob/master/3033/969/scons-tree-fix.diff) at 2016-09-29 07:56:08.
>Proposed fix, using reset_executor() instead of setting executor to None

**Comment by mwichmann** [comment]
Just tried this (git master, which is 3.1.1+), and it doesn't seem to fail. Perhaps the problem has been fixed? Setup as above,
```
$ python3 ../../src/script/scons.py --tree=status
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
 E         = exists
  R        = exists in repository only
   b       = implicit builder
   B       = explicit builder
    S      = side effect
     P     = precious
      A    = always build
       C   = current
        N  = no clean
         H = no cache

[E b   C  ]+-.
[E     C  ]  +-SConstruct
[  b   C  ]  +-build
[ R    C  ]  | +-src/SConscript
[E b   C  ]  +-src
[E     C  ]    +-src/SConscript
scons: done building targets.
```

**Comment by bdbaddog** [comment]
Marking fixed per @mwichmann -try to reproduce failing with current master version
