### ISSUE TITLE
Building versioned shared library fails when using MinGW

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3035]
This issue was originally created at: 2016-11-15 18:47:49.
This issue was reported by: `yarmond`.
yarmond said at 2016-11-15 18:47:49
>Specifying a value for SHLIBVERSION in order to generate a versioned shared 
>library fails when compiling with MinGW. A minimal SConstruct:
> 
```
env = Environment(tools=['mingw'])
lib = env.SharedLibrary('foo', ['foo.cpp'], SHLIBVERSION='2.4')
env.AlwaysBuild(lib)

```
> 
>Generates the following output:
> 
```
scons: Reading SConscript files ...
scons: *** A shared library should have exactly one target with the suffix: .dll
    File "<...>\SConstruct", line 2, in <module>


```

**Comment by mwichmann** [comment]
Just came across this one, and tested since there have been shlib-versioning changes - and it still fails, though the failure is different now.
```
scons: Reading SConscript files ...

scons: *** Multiple ways to build the same target were specified for: foo.dll
File "C:/users/mats/Documents/github/scons/exp/issue3035/SConstruct", line 2, in <module>
```

**Comment by bdbaddog** [comment]
Hmm. sounds like other issues which popped up and got fixed with the new logic.. 
I should probably stick some debug output in there similar to msvc test logic..
