### ISSUE TITLE
scons install doc doesn't mention pip install

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3037]
This issue was originally created at: 2017-02-22 22:28:30.
This issue was reported by: `diekhans`.
diekhans said at 2017-02-22 22:28:30
>http://scons.org/doc/production/HTML/scons-user/ch01s02.html
> 
>Does not mention that scons is on pypi and pip installable.  This is a very attractive install 
>method and the word should be spread

bdbaddog said at 2017-02-24 21:38:17
>Please follow the bug process listed on both the web site and on the
>scons.tigris.org site which is to bring your issues to the users mailing list first.
> 
>That helps us keep from having duplicate and invalid bugs entered into the bug
>tracking system.
> 
>http://scons.org/bugs.html
> 
>Also note that this is not a bug, but actually an enhancement request.
>And not on SCons but on the documentation.

**Comment by mwichmann** [comment]
See #3249 - this got covered as part of some general cleanup I'm proposing.

**Comment by mwichmann** [comment]
I think we can close this now.
