### ISSUE TITLE
JobsTest.py fails intermittantly in the Appveyor and Travis CI environments

### ISSUE THREAD

**Issue by dmoody256** [SCons/scons#3102]
JobsTest.py will intermittently fail in the CI environments. This is believed to be caused by the use of virtual machines used by the different CI's. 

The failure comes from not executing in parallel when it should have:

```
8/292 (2.74%) C:\\Python35\\python.exe -tt src\engine\SCons\JobTests.py
F......
======================================================================
FAIL: runTest (__main__.ParallelTestCase)
test parallel jobs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src\engine\SCons\JobTests.py", line 255, in runTest
    "the tasks were not executed in parallel")
AssertionError: False is not true : the tasks were not executed in parallel
```

However if the exact same code is run again, then it may pass in the consecutive run. An example of this happening is in this build:
https://travis-ci.org/SCons/scons/jobs/341249882

An example of this failing in Travis is here:
https://travis-ci.org/SCons/scons/jobs/343424806

An example of this failing in Appveyor is here:
https://ci.appveyor.com/project/SCons/scons/build/1.0.38/job/3eikkc3jes5v8s0m

Currently the work around is to retry the test a certain number of times, but this does not always workaround the issue.

**Comment by dmoody256** [comment]
This could be related to the VM's not presenting completely accurate information about the number of cpu cores in the environment. More info here:
https://github.com/travis-ci/travis-ci/issues/4696

**Comment by bdbaddog** [comment]
Does it pass consistantly if you hardcode the # of cpus as 2 in travis?

-Bill

**Comment by dmoody256** [comment]
I haven't tried anything related to hard coding the number of CPUs, but where specifically are you referring to perform this hard-coding?

**Comment by bdbaddog** [comment]
Somewhere here:

https://github.com/SCons/scons/blob/master/src/engine/SCons/JobTests.py#L66

**Comment by dmoody256** [comment]
I'll give it a shot on one of my branches and post the build here

**Comment by bdbaddog** [comment]
might try something like:

if os.environ.get('SCONS_TEST_NUMJOBS',0):
   num_jobs = os.environ['SCONS_TEST_NUMJOBS']

And then specify that in the travis.yml ?

**Comment by dmoody256** [comment]
Number of failures increased with 2 as the num_jobs:
https://travis-ci.org/dmoody256/scons/builds/343653865

This made me curious if the opposite affect is true with increased num_jobs (num_jobs = 1000):
https://travis-ci.org/dmoody256/scons/jobs/343654840

**Comment by bdbaddog** [comment]
I just looked at the failing test in detail.

So here's the task which is getting run:

class RandomTask(Task):
def _do_something(self):
# do something that will take some random amount of time:
for i in range(random.randrange(0, num_sines, 1)):
x = math.sin(i)
time.sleep(0.01)

taskmaster keeps track of the launch order and finish order of all the
tasks run and decides they weren't run in parallel if the orders match.

But.. This task seems like a test which could lead to sequential ordering.
Maybe just sleep some random amount of time would be a better test?

Though honestly we may have surpassed the reasonable amount of time spent
trying to make this work on travisci..

Maybe just let this one fail without failing the run and that's good enough
for now?
