### ISSUE TITLE
Update website and docs to remove reference to windows .exe installer

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3115]
Update website and docs to remove reference to windows .exe installer.
We stopped producing this starting with 3.0.1

**Comment by mwichmann** [comment]
#3249 should address the docs part of this.

**Comment by mwichmann** [comment]
Install docs should now no longer mention, after PR #3249. There may still be website/wiki mentions.

**Comment by bdbaddog** [comment]
This should now be resolved.
