### ISSUE TITLE
Strange wording in releases page

### ISSUE THREAD

**Issue by johnthagen** [SCons/scons#3124]
From the [releases page](https://scons.org/tag/releases.html):

# SCons 3.0.0 is available

SCons release 3.0.0 now available from the download page at SourceForge. This release should be used instead of 2.5.1. This release fixes several issues. **This will be the first release to support Python versions earlier than 2.7** as well as 3.5+.

# SCons 2.5.1 is available

SCons release 2.5.1 now available from the download page at SourceForge. This release should be used instead of 2.5.0. This release fixes several issues. **This will be the last release to support Python versions earlier than 2.7,** as we begin to move toward supporting Python 3.

__________

For 3.0.0 did you mean:

This will be the first release to support Python 2.7 as well as 3.5+.

It looks like Travis doesn't test against anything older than 2.7.

**Comment by bdbaddog** [comment]
Fixed.
