### ISSUE TITLE
traceback if BufferedReader used on Win/Py3

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3136]
On Windows (engine:Platform/win32.py), for the Python 3 case, several Python classes are fiddled so they point to the SCons file class.  The sequence looks like this:

    import io
    for io_class in ['BufferedReader', 'BufferedWriter', 'BufferedRWPair',
                     'BufferedRandom', 'TextIOWrapper']:
        _builtin_file = getattr(io, io_class)
        class _scons_file(_builtin_file):
            def __init__(self, *args, **kw):
                _builtin_file.__init__(self, *args, **kw)
                win32api.SetHandleInformation(msvcrt.get_osfhandle(self.fileno()),
                    win32con.HANDLE_FLAG_INHERIT, 0)
        setattr(io, io_class, _scons_file)

However, this fails if a sequence is actually triggered that would use one of the classes in what is not really an scons context. This has been observed setting up a socket (through use of urllib/http modules to download an external file via URL) - the socket makefile method contains a condition sequence which hits most of them (socket.py):

    if reading and writing:
        buffer = io.BufferedRWPair(raw, raw, buffering)
    elif reading:
        buffer = io.BufferedReader(raw, buffering)
    else:
        assert writing
        buffer = io.BufferedWriter(raw, buffering)
    if binary:
        return buffer
    text = io.TextIOWrapper(buffer, encoding, errors, newline)

The code for those classes is in C and we end up in code for generic descriptors (Objects/descrobject.c) which has careful checks for a compatible "self":

Signature: (PyMethodDescrObject *descr, PyObject *args, PyObject *kwds)

    /* Make sure that the first argument is acceptable as 'self' */
    ... some lines skipped here
    self = PyTuple_GET_ITEM(args, 0);
    if (!PyObject_IsInstance(self, (PyObject *)(descr->d_type))) {
        PyErr_Format(PyExc_TypeError,
                     "descriptor '%.200s' "
                     "requires a '%.100s' object "
                     "but received a '%.100s'",
                     descr_name((PyDescrObject *)descr),
                     descr->d_type->tp_name,
                     self->ob_type->tp_name);
        return NULL;

and, in fact, that is the error we get (the traceback indicating the error line was the one setting reading mode from above):

    TypeError: descriptor '__init__' requires a '_io.TextIOWrapper' object but received a '_scons_file'

**Comment by tfncp** [comment]
I experience the very same problem on windows using python 3.6.6 and SCons 3.0.1.
Any news for a possible fix?

**Comment by mwichmann** [comment]
I haven't pursued a solution because I don't (yet?) understand why the code is doing this; was hoping someone else would pipe up with an explanation. A workaround would be what is noted in the reference just above (from @HexDecimal): if it breaks a piece of Python, run that code in its own process, rather than inside the scons process, so it's not being handed the broken io classes.

**Comment by bdbaddog** [comment]
Honestly I'd advise (as I always do), from adding any logic to python
builders which could block or take much runtime.
You're going to hold the GIL and/or  add to the potential for race
conditions.

The logic you're referencing is to ensure that child threads do not inherit
open file handles.

It may be that this logic is not necessary on python > 3.4
https://docs.python.org/3/library/os.html#fd-inheritance
Opinions?

-Bill

**Comment by HexDecimal** [comment]
I think it's possible to put the io_class code in an `if sys.version_info < (3, 4):` block, since it seems like the modification is redundant in the latest versions of Python.

It'd also be nice to add a test that verifies that sockets are working.

**Comment by bdbaddog** [comment]
Added PR with code change. Still need to create test.

Suggestion on how to do that?

-Bill

**Comment by mwichmann** [comment]
Is this still open because of missing test? Because #3245 was merged and claimed to fix.

**Comment by bdbaddog** [comment]
Closing. Fixed in #3245
