### ISSUE TITLE
sconf.TryAction throws UnicodeDecodeError when output contains non-ascii characters

### ISSUE THREAD

**Issue by lightmare** [SCons/scons#3141]
* Version of SCons : 3.0.1-198-g68865f9
* Version of Python : 2.7.6
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc) : n/a
* How you installed SCons : haven't, used bootstrap.py
* What Platform are you on? (Linux/Windows and which version) : Linux Mint 17
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
* Link to SCons Users thread discussing your issue. -- n/a

```sh
$ cat "x/SConstruct"
```

```py
def CheckTwoCents(context):
  stat, out = context.TryAction(r"printf '2\302\242\n' > $TARGET")
  context.Result(stat)
  return stat

env = Environment()
cfg = Configure(env)
cfg.AddTest('CheckTwoCents', CheckTwoCents)
cfg.CheckTwoCents()
env = cfg.Finish()
```

```sh
$ python bootstrap.py -C "x" .

/usr/bin/python ~/scons/bootstrap/src/script/scons.py .
scons: Reading SConscript files ...
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1: ordinal not in range(128):
  File "~/scons/x/SConstruct", line 36:
    cfg.CheckTwoCents()
  File "~/scons/bootstrap/src/engine/SCons/SConf.py", line 659:
    ret = self.test(context, *args, **kw)
  File "~/scons/x/SConstruct", line 29:
    stat, out = context.TryAction(r"printf '2\302\242\n' > $TARGET")
  File "~/scons/bootstrap/src/engine/SCons/SConf.py", line 817:
    return self.sconf.TryAction(*args, **kw)
  File "~/scons/bootstrap/src/engine/SCons/SConf.py", line 612:
    outputStr = self.lastTarget.get_contents().decode()
```

The problem occurs when the action produces a file with non-ascii characters ("2¢" in this case) and [this line](https://github.com/SCons/scons/blame/381cd3a385330d03df615aa6aed205ba9aa40ae4/src/engine/SCons/SConf.py#L612) blows.

This issue is similar to #2773 and #3093, but those are specifically about methods other than `TryAction`, that's why I created this one.

Apart from the issue itself, I have a question loosely related to it. In [mapnik](https://github.com/mapnik/mapnik/), `TryAction` is used to check only the return status of a command, without writing any output file, for example:
```py
ret = context.TryAction("pkg-config --exists cairo")[0]
```
And this sometimes leads to the same error as above. I figured it happens when I bring substantial `SConstruct` changes from upstream, such that the numbering of `.sconf_temp/conftest_NN` files changes, and then non-writing configure tests attempt to return the contents of some "random" binary compiled by a different test in an older version of `SConstruct`.

Is this a misuse of `TryAction` (meaning we should always write something to `$TARGET`), or is it something SCons is supposed to handle gracefully?

**Comment by bdbaddog** [comment]
We ask that users bring the discussion to the users mailing list before filing a bug per:
https://scons.org/bugs.html

**Comment by lightmare** [comment]
Well, I haven't skipped that part by accident. After looking through open issues, seeing some similar but no exact fit, I started a new one and there of course saw the note "# please send a mail first". I realize not complying may be perceived as disrespectful, but am simply not going to discuss \[code residing here\] somewhere else, and then come back and repeat the effort. You may have good reasons why you request that, or it's just a matter of continuity, but for me mailing lists are no-go.

If I knew how to fix this properly without breaking assumptions about what should be the output of `TryAction`, I'd make a PR. But I don't quite see into SCons internals, and the commit that added the `.decode()` call says only "fix broken tests" with no pointers as to why the decode was needed.

**Comment by bdbaddog** [comment]
The reason we ask people bring the bugs to the user mailing list are:
1. to prevent duplicate filings
2. To get more eyes on the issue quicker
3. To prevent user errors from filling up the bug tracker.

If you're going to be a user of scons, joining the mailing list does have value and also it's not high traffic with very little junk emails.  There would be no duplication of discussion.

Our process is to discuss it on the mailing list.  And then just file the repeater and details here.

And indeed you saw the request and decided I'm not going to follow community norms for this project.

I have a fix. In the future please follow the requested procedure and shoot an email to the users mailing list.

**Comment by mwichmann** [comment]
@bdbaddog - this seems to be fixed.

**Comment by bdbaddog** [comment]
> @bdbaddog - this seems to be fixed.

in 3.0.4? Or earlier?

**Comment by mwichmann** [comment]
3.0.4 passed the test. My system installed scons (Fedora 29, 3.0.1) did not.

**Comment by bdbaddog** [comment]
@mwichmann  can you add a test for this and shoot a PR?
