### ISSUE TITLE
Python 3.7 and multiple threads

### ISSUE THREAD

**Issue by rickrankin** [SCons/scons#3145]
SCons version: 3.0.1
Python version: 3.7
Python distribution: homebrew
SCons installed via pip
Platform: OS X 10.13.6
How to reproduce: run scons on any project

Description:
I recently got forcibly upgraded on my Mac to Python 3.7 via homebrew. After I went through and reinstalled all my packages, including SCons, I started seeing the following message when I run scons:

```
scons: warning: parallel builds are unsupported by this version of Python;
	ignoring -j or num_jobs option.
```

SCons seems to work fine with Python 3.7, it just emits this warning message. I did a little digging, and It seems that the `WITH_THREAD` config variable that SCons is using to test whether Python was configured with multiple threads is no longer supported, i.e., `sysconfig.get_config_var('WITH_THREAD')` used in Script/Main.py returns None even though multithreading *is* supported on the homebrew build.

I tried reverting to Python 3.6 through homebrew, but that doesn't seem to be supported, at least not directly based on what I could find via Google. I also tried using a build of Python 3.6 that I downloaded from python.org, but that build didn't seem to work very well. Scripts that worked fine with the homebrew build of Python 3.6 didn't seem to work correctly with the python.org build.

Based on what I'm reading on scons.org, it doesn't appear to me that SCons is supposed to directly support Python 3.7, yet; however, since I'm definitely running into fewer issues using Python 3.7 than I am with non-homebrew versions of Python 3.6, I'll continue using it. I'm just filing this issue as a heads-up for an issue that will probably arise when you begin testing on Python 3.7.

While I did not post this issue to the users list, I did look through all the archives back to the first of the year, and saw nothing obvious relating to Python 3.7. I would be nice if there were a search function for the archives. A google search pinned to site:scons.org didn't yield anything useful.

**Comment by bdbaddog** [comment]
The users mailing list is pretty much for exactly what you put in this bug filing, and thus why we ask that people bring their issues there first.

Regardless, we're aware of the issue and likely have a simple fix which should make it into the next release. You can see a discussion of such in the IRC channel log. https://botbot.me/freenode/scons/2018-07-10/?msg=101945959&page=1

**Comment by rickrankin** [comment]
Thank you for the response. If it matters, I don't participate on email lists any more because I've had my address harvested by spammers too many times and ended up with, in one case, over 10,000 spam messages in the course of about two weeks. I swore off email lists not long after that. If that means I'm not welcome to participate here, then so be it.

**Comment by bdbaddog** [comment]
Indeed that is not the case.  And of course the bug is valid. So please go ahead and reopen.  (that said I've thus far not had such a problem with mailing lists or google's spam filters is good enough I never see them)

**Comment by rickrankin** [comment]
Ah, I interpreted your first response to mean that there was already a ticket open and I just missed it when I searched. That's why I closed this one. It's now been reopened.

To be fair, the email issue happened a long time ago. It wasn't until much later that I realized I made the horrible mistake of using my work email address to subscribe to a few lists, so I couldn't just close the account or abandon it. Still, it really soured me on email lists.

**Comment by bdbaddog** [comment]
@rickrankin  - indeed few work emails have spam protection as good as google.. Another trick is use + emails.. (so userid+tag@gmail.com is always routed to userid@gmail.com, but you can filter it via userid+tag).  Regardless, there's utility in scons' user mailing list, high signal to noise ratio and not a huge volume of email.

I'll try to get a pull request together by end of week for this. But for now, you could probably get away with 

` python_has_threads = True`

instead of:

` python_has_threads = sysconfig.get_config_var('WITH_THREAD') or is_pypy`

**Comment by rickrankin** [comment]
I had tried that, but there seems to be a little more to it. I haven't added any print statements to verify it, but it appears that SCons.Job.Jobs(...) is returning an object with num_jobs set to one, so the condition below `elif jobs.num_jobs == 1 ...` is still failing and I still see the message.

```python
    python_has_threads = True
    global num_jobs
    num_jobs = options.num_jobs
    jobs = SCons.Job.Jobs(num_jobs, taskmaster)
    if num_jobs > 1:
        msg = None
        if sys.platform == 'win32':
            msg = fetch_win32_parallel_msg()
        elif jobs.num_jobs == 1 or not python_has_threads:      # <--- failing here
            msg = "parallel builds are unsupported by this version of Python;\n" + \
                  "\tignoring -j or num_jobs option.\n"
```

At this point, `python_has_threads` has been hardcoded to True, so the only possibility is that `jobs.num_jobs == 1`. I haven't had time to try to see why `jobs.num_jobs` is being set to 1.

**Comment by bdbaddog** [comment]
What's the command line you're using?

**Comment by rickrankin** [comment]
I'm just typing `scons`, but I have SCONSFLAGS set to "-Qu -j4". If I unset SCONSFLAGS and run `scons`, then I don't see the message. Of course, then I don't get into the if condition at all, since `options.num_jobs`, and therefore global `num_jobs` will just be 1.

**Comment by garyo** [comment]
I just built Python 3.7 on my Linux box, and as you've noticed, Python 3.7 is _always_ built with threading support. In fact non-thread platforms are explicitly desupported in Python 3.7 per https://www.python.org/dev/peps/pep-0011/. So I don't think we have to do this test on 3.7 or later.

However, in my tests, setting python_has_threads to True on Python 3.7 works fine. I don't get `jobs.num_jobs==1`. I will try this on homebrew on Mac to see if there's something different happening there, but @rickrankin is it possible when you tested setting it to True you weren't actually using that version or something? (Try adding a print() to make sure, if you don't mind.)
I also found a couple of other Python 3.7 things while testing this, e.g. "async" is now a reserved keyword.

**Comment by garyo** [comment]
My fix also seems to work with Homebrew python 3.7 on Mac. Could you try my version at https://github.com/garyo/scons?

**Comment by bdbaddog** [comment]
@garyo  - async is in part of the test framework as a parameter which is never used inside the method it's in if I remember correctly.

**Comment by rickrankin** [comment]
Crap, I just realized I have 2 different scons installations. One in /usr/local/lib/python3.7/site-packages/scons-3.0.1 and one in /usr/local/lib/scons-3.0.1. I was modifying the one in site-packages. It never occurred to me that there would be one in /usr/local/lib; however, that seems to be the one being used.

Anyway, after hardcoding `python_has_thread = True` in the version in /usr/local/lib, I'm now able to run with and without the -j option and not see the message.  It also appears to be running jobs in parallel just fine.

@garyo I haven't had a chance to try your version, yet. Is there still a reason to try?

**Comment by garyo** [comment]
@rickrankin no, that's exactly what I expected -- confirms my testing. Thanks!
