### ISSUE TITLE
Textfile / Substfile not available in the default environment

### ISSUE THREAD

**Issue by ali1234** [SCons/scons#3147]
Textfile and Substfile builders are not available in the default environment. They should either be loaded by default or the docs should say they need to be explicitly loaded.

scons --version:
```
SCons by Steven Knight et al.:
	script: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
	engine: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
	engine path: ['/usr/lib/scons/SCons']
Copyright (c) 2001 - 2017 The SCons Foundation
```

python --version: `Python 2.7.15rc1`

Scons was installed using the Ubuntu 18.04 package.

SConstruct:
```
env = Environment()

env.Textfile('somefile', Value("123"))
```
Output:
```
scons: Reading SConscript files ...
AttributeError: 'SConsEnvironment' object has no attribute 'Textfile':
  File "/home/al/testscons/SConstruct", line 3:
    env.Textfile('somefile', Value("123"))
```

SConstruct file which works:
```
env = Environment(tools=['default', textfile'])

env.Textfile('somefile', Value("123"))
```

Report requested on IRC by @bdbaddog .

**Comment by bdbaddog** [comment]
Probably want to bounce this off the users mailing list. I think we generally load all the builders included in the distribution by default if they apply. If that's the case then we should probably also load these rather than have them not loaded by default..

**Comment by mwichmann** [comment]
Hmmm, this should have closed since the associated PR was merged. I can't close it....

**Comment by bdbaddog** [comment]
Closing
