### ISSUE TITLE
Last but not List in depends user guide doc xml file

### ISSUE THREAD

**Issue by cyril-marpaud** [SCons/scons#3149]
Here's a typo (wrote 'list' instead of 'last' i guess) :

https://github.com/SCons/scons/blob/932c577395cf646a82581afeb9fd1c9faf4d4999/doc/user/depends.xml#L586

**Comment by mwichmann** [comment]
Oh, that's cute, I fat-fingered the summary line in the commit (3194 instead of 3149); anyway this is addressed now.
