### ISSUE TITLE
Please update wiki TestingMethodology page

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3163]
The page https://github.com/SCons/scons/wiki/TestingMethodology is out of date. The page contains this claim:

> Note: This text is a copy of the file `QMTest/test-framework.rst` in the source repository. Please synch your changes/additions to this page accordingly.

That file no longer exists, having been replaced by / renamed to `testing/framework/test-framework.rst`. Since most of us cannot make edits to the wiki directly nor does GitHub appear to have a provision for a PR on the wiki, a maintainer will need to do the update.

**Comment by bdbaddog** [comment]
I've removed the restriction on the wiki. Please feel free to edit.

**Comment by mwichmann** [comment]
the files in git are reST; after the wiki transfer those pages are in github markdown (not always 100% cleanly converted, I think, but that's not a huge problem).

**Comment by mwichmann** [comment]
Okay, I asked for it, and I updated it, so I guess I should close it :)
