### ISSUE TITLE
packaging tests fail on newer rpm

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3164]
A set of packaging tests which build rpm packages - obviously due to availability only run on systems which have an `rpm`/`rpmbuild` command - fail on "new" rpm. Fail as in the `rpmbuild` itself fails to complete. There are multiple issues.

    test/packaging/option--package-type.py
    test/packaging/rpm/cleanup.py
    test/packaging/rpm/internationalization.py
    test/packaging/rpm/multipackage.py
    test/packaging/rpm/package.py
    test/packaging/rpm/tagging.py

The error looks like this:

    error: Empty %files file /tmp/testcmd.247674.0oeSTZ/rpmtemp/BUILD/foo-1.2.3/debugsourcefiles.list

I don't have a precise definition for "new", but certainly current Fedora instances (26/27/28) do this and now I recognize what is happening I know it goes back a lot further than that.  Package building in the Red Hat / Fedora / Centos world wants to build separate debug support packages by default now, and runs, behind the scenes, a script which tries to extract things, building file lists which are used, again behind the scenes, in building additional packages besides ones you thought you were asking for (that is, beyond the base package name plus any subpackages you define with `%package` directives - the specfile has no hint these extra packages are being built). All this is stuff the packaging tests in scons do not expect.  `debugsourcefiles.list`?  How to deal with that?

So you can turn off debug building. I am not clear if it is the right thing to do unconditionally; certainly the tests as written need to do so, or else be reworked a lot, risking not working on systems which do not have this rpm implementation. It could be done conditionally - other rpm settings exist in defined construction environment variables, one could add another to control debug-package generation, letting the tests avoid it but packages actually being built which might expect these extra packages can leave it undisturbed.

More fun - packages may also have unexpected contents. In the test code, the generated specfile contains a deduced files section:

    %files
    %defattr (-,root,root)
     /bin/main
(the initial space is probably a bug in the code which deduces the files). But running `rpm -qlp` on the package generated during the same test shows these contents:

    $ rpm -qlp ./foo-1.2.3-0.x86_64.rpm
    /bin/main
    /usr/lib/.build-id
    /usr/lib/.build-id/05
    /usr/lib/.build-id/05/3cbb2cec927c20f70df854a21b3cf1d17e4c34

so the test which tries an exact match with what has been generated in scons, namely the single line `"/bin/main"` still fails, even after you make fixes to make the package build.  There is a different test routine to make sure it contains that line, but could contain other things - the test can easily use this routine.

An additional problem is that there is code purporting to allow specifying an alternate build architecture, by setting a value for the (documented) `ARCHITECTURE` key in the construction envirionment. While this value is used in constructing the target filename, it is never actually given to `rpmbuild` - it has to either be a command-line argument `--target ARCHITECTURE`, or added as a line `BuildArch: ARCHITECTURE` in the specfile, scons does neither.   This is an actual scons problem, not a test problem; probably the alternate-architecture stuff (with 'noarch' being the interesting one) has only lightly been exercised.

This issue is scons version-agnostic (confirmed on 3.0.1) and python version-agnostic (confirmed on 2.7 and 3.6); not certain the rpm-build version but definitely a problem on 4.14 and the Fedora versions mentioned.

Reproducer: given a suitable Linux host such as Fedora 27, just run one of the tests above:

    python runtest.py test/packaging/rpm/package.py

**Comment by bdbaddog** [comment]
O.k. so sounds like a couple action items
1) determine which version of rpmbuild introduced the new behavior and add conditional logic to cover that, and probably an RPMBUILDVERSION env variable so users can likewise do "smart" things
2) Given a "new" version of rpmbuild, change the tests to disable the generation of debug packages

Does that sound like a reasonable first couple steps?

**Comment by bdbaddog** [comment]
Can you check the build results on travis and also on buildbot.scons.org ot see if we have a machine running those tests?

**Comment by mwichmann** [comment]
I can't currently find any evidence that these tests are being run, the linux builders all seem to be Ubuntu and the test logs show rpm not found, so tests skipped.

**Comment by mwichmann** [comment]
I do however have a local VM where the tests work as written... Centos 7 (uses rpm-build 4.11.3). Modified code still passes without adding any version-specific logic.
