### ISSUE TITLE
add ARM support for recent Windows Visual Studio and Build Tools

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3182]
`SCons/Platform/win32.py` lists processor targets supported for Windows in `SupportedArchitectureList`. The list includes Itanium (IA64) which has not been supported since Windows Server 2008 by Microsoft; extended support for 2008 R2 ended July 2018 but in practice much earlier. Meanwhile, ARM is not listed in `SupportedArchitectureList` and thus an error is given if someone requests ARM.

In contrast, `SupportedVSList` in `SCons/Tool/MSCommon/vs.py` shows VS2015 and VS2017 supporting ARM targets.

We should add ARM and drop IA64.

Further, I believe bugs in `vs.py` will cause problems and need to be addressed before ARM support will work. The `get_supported_arch` method refers to `self.supported_arch`, which is never set in the instance (there is a class of similar problems - attributes of various VS versions never being set in the VisualStudio instance - causing me to think maybe `vs.py` is not actually in use)

**Comment by mwichmann** [comment]
Oh, to add - this is the support table for Windows 10, showing ARM on Window 10 1709 and 1803:

https://docs.microsoft.com/en-us/windows-hardware/design/minimum/windows-processor-requirements

**Comment by bdbaddog** [comment]
I'd say add arm, but don't remove Itanium yet.  If nothing else it needs to go through a deprecation cycle. 
People do build for "dead" systems for a while after they're no longer supported.

Can you add a link to lines in the repo for the vs.py items?

Actually probably better to make this bug about properly adding ARM support and deprecating IA64 and another issue for other items. Otherwise we can't mark this issue resolved until all the above which includes some general issues rather than specific?

**Comment by mwichmann** [comment]
Hmmm, I forgot to act on this.  The changes to the architecture tables appears in PR #3230, although in current form the entries including ARM are commented out.  I did not yet split the issues.  Do we know if `vs.py` is actually used?  That might make the "extra issues" moot.

**Comment by mwichmann** [comment]
Okay, only _some_ of the changes are in the PR, I will have that one reference here on next update.

**Comment by bdbaddog** [comment]
Is this ressolved by #3264

**Comment by mwichmann** [comment]
Well, to the extent that it should no longer complain about unsupported target.  Since the PR I originally submitted had these commented out I didn't really do any testing.  I suspect we'll find some issues once people start trying to build for ARM.

**Comment by dmoody256** [comment]
I built for arm and arm64 with vs2017 on my local win10 machine after I set
the TARGET_ARCH, and it was building arm binaries. Thats about as much
testing as i could do.

**Comment by bdbaddog** [comment]
Great so master should be able to build arm with your patch then?
We should make a bigger note in CHANGES.txt

**Comment by bdbaddog** [comment]
I'm marking this as resolved by #3264
