### ISSUE TITLE
Failed to change install prefix

### ISSUE THREAD

**Issue by majioa** [SCons/scons#3191]
When building the project cbang, it is failed to install the project not ito local dir but prefixed with /usr
     build_function(["build/build_info.cpp"], [])
     scons: *** [/usr/local/include/cbang] /usr/local/include/cbang: Permission denied

   
* Version of SCons
        script: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
        engine: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
        engine path: ['/usr/lib/python2.7/site-packages/SCons']
* Version of Python
2.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
altlinux

* How you installed SCons
apt-get intall scons

* What Platform are you on? (Linux/Windows and which version)
linux
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.

* Link to SCons Users thread discussing your issue.

**Comment by bdbaddog** [comment]
Looks like this is an issue with how cbang https://github.com/CauldronDevelopmentLLC/cbang/blob/master/SConstruct uses SCons and not scons itself. Please file a bug on their repo.
