### ISSUE TITLE
"pip install scons" when NOT using virtualenv results in a broken installation

### ISSUE THREAD

**Issue by samfux84** [SCons/scons#3215]
Based on a discussion in the SCons mailing list

https://pairlist4.pair.net/pipermail/scons-users/2018-October/007321.html

I would like to report an issue with Scons, when being installed with pip, not using a virtual environment.

- **SCons version**: 3.0.1
- **Python version**: 2.7.14
- **Python distribution**: Manually compiled from source code downloaded on Python.org
- **Installation procedure**: pip install scons
- **Plattform**: CentOS Linux release 7.5.1804 (Core)
- **How to reproduce the issue issue?**:
Issue can be reproduced by running the 2 commands below:

1. pip install scons 
2. scons

```
[sfux at lo-login-02 ~]$ pip install scons
Collecting scons
Installing collected packages: scons
Successfully installed scons-3.0.1
[sfux at lo-login-02 ~]$ scons
SCons import failed. Unable to find engine files in:
  /cluster/apps/python/2.7.14_cpu/bin/../engine
  /cluster/apps/python/2.7.14_cpu/bin/scons-local-3.0.1
  /cluster/apps/python/2.7.14_cpu/bin/scons-local
  /cluster/apps/python/2.7.14_cpu/lib64/python2.7/site-packages/lib/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib/python2.7/site-packages/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib/python2.7/site-packages/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib64/scons-3.0.1
  /cluster/apps/python/2.7.14_cpu/lib64/python2.7/site-packages/lib/scons
  /cluster/apps/python/2.7.14_cpu/lib/scons
  /cluster/apps/python/2.7.14_cpu/lib/scons
  /cluster/apps/python/2.7.14_cpu/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14_cpu/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14_cpu/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14_cpu/lib64/scons
Traceback (most recent call last):
  File "/cluster/apps/python/2.7.14_cpu/bin/scons", line 192, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
[sfux at lo-login-02 ~]$
```

- **How you invoke scons ?** just running scons without specifying any option

**Analysis of the problem and proposal of a solution**:

SCons searches it own files in

`$PYTHONHOME/lib64/python2.7/site-packages/lib/scons-3.0.1`

instead of

`$PYTHONHOME/lib64/python2.7/site-packages/scons-3.0.1`

One workaround is to set `$SCONS_LIB_DIR` to `$PYTHONHOME/lib64/python2.7/site-packages/scons-3.0.1`, but it would be better to solve the root cause of the problem.

It arises from `$PYTHONHOME/bin/scons`. The "/lib" is added on line 157 of the script:

`temp = [os.path.join(x, 'lib') for x in prefs]`

If I change this line to

`temp = [os.path.join(x, '') for x in prefs]`

then the error does no longer occur.

I will use this workaround as it avoids setting environment variables. It is clear to me, that this only fixes the problem on our system, and maybe for other sites there is a different solution required.

The guessing of the paths is in general difficult,  since it is OS dependent. Would using **site** package might be a good idea for getting the installation directory of the SCons module ?

```
[sfux@lo-login-01 ~]$ python
Python 2.7.14 (default, Apr 10 2018, 16:12:16) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> print site.PREFIXES
['/cluster/apps/python/2.7.14_cpu', '/cluster/apps/python/2.7.14_cpu']
>>> print site.USER_SITE
/cluster/home/sfux/.local/lib64/python2.7/site-packages
>>> print site.getsitepackages()
['/cluster/apps/python/2.7.14_cpu/lib64/python2.7/site-packages', '/cluster/apps/python/2.7.14_cpu/lib64/site-python']
>>> print site.getusersitepackages()
/cluster/home/sfux/.local/lib64/python2.7/site-packages
```

instead of using sys.prefix with some additional guessing ?

```
        prefs.append(sys.prefix)

    temp = [os.path.join(x, '') for x in prefs]
    temp.extend([os.path.join(x,
                                           'lib',
                                           'python' + sys.version[:3],
                                           'site-packages') for x in prefs])
```

Could you please consider fixing this in a future SCons release, as it seems that many people are facing this problem ?

  *   https://github.com/FPGAwars/apio/issues/143
  *   https://github.com/Homebrew/legacy-homebrew/issues/5794
  *   https://stackoverflow.com/questions/24897687/import-failed-unable-to-find-scons-files-import-scons-script
  *   http://scons.1086193.n5.nabble.com/SCons-can-t-correctly-install-via-pip-when-not-in-a-virtualenv-td42715.html
  *   https://pairlist4.pair.net/pipermail/scons-users/2017-December/006589.html

Thank you.

Best regards

Sam

**Comment by bdbaddog** [comment]
Please try a package I just built from master and uploaded to testpypi
pip install --index-url https://test.pypi.org/simple/ scons==3.1.0.alpha.20181011

This issue is fixed in master.
It will be resolved with the next release.

The patch for this was merged in May
https://github.com/SCons/scons/pull/3134

**Comment by samfux84** [comment]
Still the same issue:


```
[sfux@lo-login-01 ~]$ pip install --index-url https://test.pypi.org/simple/ scons==3.1.0.alpha.20181011
Looking in indexes: https://test.pypi.org/simple/
Collecting scons==3.1.0.alpha.20181011
Installing collected packages: scons
Successfully installed scons-3.1.0a20181011
[sfux@lo-login-01 ~]$ scons
SCons import failed. Unable to find engine files in:
  /cluster/apps/python/2.7.14/bin/../engine
  /cluster/apps/python/2.7.14/bin/scons-local-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/bin/scons-local
  /cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib/python2.7/site-packages/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib/python2.7/site-packages/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib64/scons-3.1.0.alpha.20181011
  /cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/scons
  /cluster/apps/python/2.7.14/lib/scons
  /cluster/apps/python/2.7.14/lib/scons
  /cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14/lib/python2.7/site-packages/scons
  /cluster/apps/python/2.7.14/lib64/scons
Traceback (most recent call last):
  File "/cluster/apps/python/2.7.14/bin/scons", line 192, in <module>
    import SCons.Script
ImportError: No module named SCons.Script
[sfux@lo-login-01 ~]$
```

**Comment by mwichmann** [comment]
Whether or not using non-versioned install locations improves the situation, scons itself (`src/script/scons.py`) is still generating a bunch of dodgy paths that will never match, and should be cleaned up. The single most promising path to try if you are not running a local install or source copy is the one that comes from a query of the Python packaging support. For the example in the previous comment, that path is `/cluster/apps/python/2.7.14/lib64/python2.7/site-packages` and if suffixed by `/scons` and `/scons-version` would have almost certainly succeeded. Instead it has been transformed into these four failing paths from the listing, none of which would work on any installation I have ever seen, that is, trying to use a `lib` subdirectory of the `site-packages` directory.
```
/cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/scons-3.1.0.alpha.20181011
/cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons-3.1.0.alpha.20181011
/cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/scons
/cluster/apps/python/2.7.14/lib64/python2.7/site-packages/lib/python2.7/site-packages/scons
```
I can easily supply a PR to take care of that issue, it just involves reserving that first path  and not subjecting it to one of the transformations.

**Comment by mwichmann** [comment]
PR #3218 proposes a new scons.py. I didn't set it up to reference this issue since technically it's closed already, but it would be useful to know if it helps this situation.
