### ISSUE TITLE
Support Visual Studio 2017 Build Tools

### ISSUE THREAD

**Issue by rryan** [SCons/scons#3222]
* Version of SCons
3.0.1
* Version of Python
2.7 and 3.7
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
python.org 64-bit for Windows 10
* How you installed SCons
scons-local zip
* What Platform are you on? (Linux/Windows and which version)
Windows 10
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.

1. Install Visual Studio 2017 Build Tools.
2. from a vanilla cmd.exe prompt, run `c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat amd64`
3. invoke SCons. (my SConscript uses `MSVC_USE_SCRIPT = None`)

SCons prints 
`No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly`
and then proceeds to use gcc/g++, which happen to be on my PATH.
https://github.com/SCons/scons/blob/0c20ae2e5d1e093a3993f94eba454ca110cf1dd3/src/engine/SCons/Tool/MSCommon/vc.py#L542

I use `MSVC_USE_SCRIPT`, but this error happens before SCons gets to that logic.

If I install Visual Studio 2017 Community, everything works fine.

The issue seems to be that `vswhere`'s default product is Visual Studio, and [BuildTools is considered a separate product](https://github.com/Microsoft/vswhere/issues/22). To get the location of a BuildTools installation, you have to use `-products Microsoft.VisualStudio.Product.BuildTools -property installationPath`.

* How you invoke scons (The command line you're using "scons --flags some_arguments")
scons

**Comment by bdbaddog** [comment]
Why would one install Build tools instead of visual studio? Is it just a lighter weight install? Or other reason? 

Might you have both VS 2017 and build tool VS 2017 installed? Would they be in different locations?

**Comment by rryan** [comment]
Right, the build tools are a good option for headless builders (lighter weight install) and CI services. For example, Travis CI just announced [Windows support](https://blog.travis-ci.com/2018-10-11-windows-early-release) and AFAICT it only supports the build tools, and doesn't have a full Visual Studio install.

Community and hte Build tools can be co-installed, they go to these paths by default:
* `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC`
* `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC` 

Sorry about ignoring the scons-users request. I still can't get a confirmation email for my gmail account, and I have checked spam folders / etc.

**Comment by rryan** [comment]
I also emailed scons-users-owner@scons.org about the confirmation email issue on 9/18/2018 and received no response.

**Comment by bdbaddog** [comment]
I'll have to check with the other project co-manager as he's handled
mailing list admin duties thus far.
We'll get you sorted as soon as possible.

**Comment by rryan** [comment]
It was rryan@mixxx.org. Thanks!

**Comment by mwichmann** [comment]
Right, `choco install microsoft-build-tools`  should in theory be enough to build stuff, you're not supposed to need the whole "Visual" part.

**Comment by mwichmann** [comment]
Maybe `vswhere /all /property installationPath`  and dig through the results?

**Comment by rryan** [comment]
From memory, I tried `vswhere /all` and it didn't show anything. Because [build tools is considered a separate product](https://github.com/Microsoft/vswhere/issues/22) and `-all` refers to the default product (visual studio), I believe you may have to run it twice, once with `-products Microsoft.VisualStudio.Product.BuildTools -property installationPath`

**Comment by mwichmann** [comment]
Fair enough, so it's more likely the `-products *` approach mentioned (but apparently not pursued) in that vswhere issue?  Haven't tested yet.

**Comment by mwichmann** [comment]
So on a system with only the build tools installed, this stanza gets me an answer:
```
vswhere -products * -property installationPath
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
```
The same gets me an answer on a system that has 2017 Community and 2015 Pro installed:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
```
Doing this through Chocolatey, I found that "Build Tools" alone didn't get me any C/C++ compiler, needed to add something else, so the stanza was this:
```
choco install -y visualstudio2017buildtools
choco install -y visualstudio2017-workload-vctools
```

Hoping all this helps a bit....
The "package" `microsoft-build-tools is` just a redirect to `visualstudio2017buildtools`.

**Comment by mwichmann** [comment]
Gah, there's more to this story. With the change of adding `-products *` we get a little further: the first step of the search finds something, but the second does not:
```
DEBUG:root:trying to find VC 14.1
DEBUG:root:find_vc_dir(): found VC in registry: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC
DEBUG:root:found VC 14.1
DEBUG:root:find_vc_pdir no cl.exe found 14.1
```
The second step is the function continuing here after the `VC_DIR = find_vc_pdir(ver)` line:
```
def get_installed_vcs():
    installed_versions = []
    for ver in _VCVER:
        debug('trying to find VC %s' % ver)
        try:
            VC_DIR = find_vc_pdir(ver)
            if VC_DIR:
                debug('found VC %s' % ver)
                # check to see if the x86 or 64 bit compiler is in the bin dir
                if (os.path.exists(os.path.join(VC_DIR, r'bin\cl.exe'))
                    or os.path.exists(os.path.join(VC_DIR, r'bin\amd64\cl.exe'))):
```
The problem here being the 2017 family - VS as well as the plain Build Tools - have the binaries much deeper down (exact same set of paths found in `2017/Community/VC` on other machine)
```
/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC
$ find * -name cl\.exe
Tools/MSVC/14.15.26726/bin/Hostx64/x64/cl.exe
Tools/MSVC/14.15.26726/bin/Hostx64/x86/cl.exe
Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
```

**Comment by mwichmann** [comment]
See PR #3230

**Comment by bdbaddog** [comment]
Can you check if this is fixed by #3264 ?

**Comment by dmoody256** [comment]
I uninstalled Visual Studio 2017 Community, verified the latest scons didn't find it, then installed the 2017 build tools and scons picked it up on my local win10 machine.

I am wondering about older build tools though, specifically because for older versions, scons prefers to use the registry, and not vswhere. It will only use vswhere if there is not a registry key in these two locations:
https://github.com/SCons/scons/blob/f3739c4f655b26b96e82945c07bc3c5d51edd2f8/src/engine/SCons/Tool/MSCommon/vc.py#L340-L344
https://github.com/SCons/scons/blob/f3739c4f655b26b96e82945c07bc3c5d51edd2f8/src/engine/SCons/Tool/MSCommon/vs.py#L80-L82

**Comment by bdbaddog** [comment]
What are you wondering about pre vs2017 build tools? I know we have logic for VC for python installs.
Likely if SCons didn't support pre vs2017 build tools and it was needed we'd hear?

**Comment by dmoody256** [comment]
I meant for earlier build tools, they had separate build tools for the last few versions. I don't know if the build tools setup the registry keys the same way as the real Visual Studio install.

If that is the case, yeah we would probably have heard by now.

**Comment by wiedemannc** [comment]
I still have problems with visual 2017 build tools. I have multiple versions of Visual Studio and MSVC Build Tools installed. This is the SConstruct file (using scons 3.0.5 iwth python 3.7.2):

```
env1 = Environment(tools = ["default"])
env1.Command(["version1"], [], "$CC 2> version1")
print("default: MSVC_VERSION=", env1["MSVC_VERSION"])
print("         PATH=", env1["ENV"]["PATH"])
                   
env2 = Environment(tools = ["default"],
                   MSVC_VERSION="14.1")
env2.Command(["version2"], [], "$CC 2> version2")
print("force 14.1: MSVC_VERSION=", env2["MSVC_VERSION"])
print("            PATH=", env2["ENV"]["PATH"])

env3 = Environment(tools = ["default"],
                   MSVC_USE_SCRIPT = r"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat")
env3.Command(["version3"], [], "$CC 2> version3")
print("force script: MSVC_VERSION=", env3["MSVC_VERSION"])
print("              PATH=", env3["ENV"]["PATH"])
```

gives me this output

```
scons: Reading SConscript files ...
default: MSVC_VERSION= 14.0
         PATH= C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\WINDOWS\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64\;C:\WINDOWS\System32;C:\WINDOWS\System32\Wbem

scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: ['14.0', '12.0', '11.0']
File "C:\Projects\iCV-Algo\nexT\workspace\SConstruct", line 8, in <module>

scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: ['14.0', '12.0', '11.0']
File "C:\Projects\iCV-Algo\nexT\workspace\SConstruct", line 8, in <module>

scons: warning: VC version 14.1 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: ['14.0', '12.0', '11.0']
File "C:\Projects\iCV-Algo\nexT\workspace\SConstruct", line 8, in <module>
force 14.1: MSVC_VERSION= 14.1
            PATH= C:\WINDOWS\System32
force script: MSVC_VERSION= 14.0
              PATH= C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\;C:\WINDOWS\System32;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
scons: done reading SConscript files.
scons: Building targets ...
cl 2> version2
scons: *** [version2] Error 1
scons: done building targets (errors occurred during build).
```

As you can see, using the default leads me to Visual Studio 2015 (these are also build tools). Trying to force Visual Studio 2017 with MSVC_VERSION="14.1" gives me an error message and finally forcing the vcvars64 script seems to work somehow, but still the wrong Visual Studio version is reported (14.0 instead of 14.1).

**Comment by bdbaddog** [comment]
This is a known issue.
Currently if info on the install isn't found in the registry and is found
via use of vswhere, the version is hard coded as 14.0.
There's a fix in the works.

-Bill
