### ISSUE TITLE
Update website FAQ to correct Python version range

### ISSUE THREAD

**Issue by jeremydouglass** [SCons/scons#3243]
The scons.org FAQ is out of date, and needs to be updated:

> What version of Python do I need?  
> SCons is written to work with any Python version >= 2.4 and \< 3.0. Versions 3.0 and above are not supported at this time. Extensive tests are used to ensure that SCons works on all supported versions.  
> https://scons.org/faq.html#What_version_of_Python_do_I_need.3F

but according to the github repo:

> Running SCons requires Python version 2.7.* and Python 3.5 or higher. 
> https://github.com/SCons/scons

**Comment by bdbaddog** [comment]
Fixed. Good catch.
