### ISSUE TITLE
InstallVersionedLib should respect SONAME variable

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3246]
As discussed on the mailing list, InstallVersionedLib doesn't respect SONAME when set, and probably should.

* Link to SCons Users thread discussing your issue.
https://pairlist4.pair.net/pipermail/scons-users/2018-November/007441.html

* Version of SCons
All that offer InstallVersionedLib

* What Platform are you on? (Linux/Windows and which version)
Mac/Linux. Windows doesn't really have these concepts.

**Comment by acmorrow** [comment]
@bdbaddog - I think it is worth trying to fix this for 4.0. The `SONAME` is a documented SCons Variable, and it shouldn't become ignored just because you use `SHLIBVERSION` with `InstallVersionedLib`. I think we can probably live without #3247 for 4.0. While unfortunate, there is a user-facing workaround. However, this issue does not have one that I can see.

**Comment by acmorrow** [comment]
@bdbaddog - I think this is worth fixing for 4.0 too. It makes using InstallVersionedLibrary impossible if you are using a SONAME scheme where ABI is versioned independently of release versioning.

**Comment by bdbaddog** [comment]
Fixed by #3635
