### ISSUE TITLE
Introduce new variable SOVERSION to improve on SONAME

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3247]
* Link to SCons Users thread discussing your issue.
Mentioned, though not discussed here: https://pairlist4.pair.net/pipermail/scons-users/2018-November/007441.html

* Version of SCons
All offering SONAME support

Right now, if you use `SONAME`, you need to put the `LIBPREFIX` and `LIBSUFFIX` on yourself. That is fragile. It would be better to introduce a `SOVERSION` option that would then get properly interpolated into the filename used for `SOVERSION`.

**Comment by bdbaddog** [comment]
Can you include a small example sconstruct?

**Comment by acmorrow** [comment]
@bdbaddog - As this is an enhancement (there is currently no `SOVERSION` variable), I don't think this is something urgent to get done for SCons 4.0. I think #3246 is something we should see in 4.0 though.

**Comment by acmorrow** [comment]
@bdbaddog - Could we queue this up for a 4.1? I don't think it is hard.

**Comment by dmoody256** [comment]
I would assume that if the two are used together in the same environment, the SONAME takes precedence (assuming the end user may really want to make a weirdly named library symlink)?

**Comment by acmorrow** [comment]
I think maybe it should just be an error to have both set. If you set `SONAME` explicitly then you get what you asked for, and also setting `SOVERSION` doesn't make sense.

One nice way to handle this might be to introduce a `SONAME_GENERATOR` configurable. The default implementation would work like if `SONAME` is set in the environment, then `SONAME_GENERATOR` just returns that. Otherwise, if `SOVERSION` is set, then it does the platform appropriate interpolation.

**Comment by bdbaddog** [comment]
@acmorrow @dmoody256 - Isn't this resolved in 4.1.0? With the versioned shared library rewrite to pull in also the changes from @dmoody256 's PR for SOVERSION

**Comment by dmoody256** [comment]
@bdbaddog yeah this is done we can close it

**Comment by bdbaddog** [comment]
Closing
