### ISSUE TITLE
How improved DAG traversal performance?

### ISSUE THREAD

**Issue by ttllyy** [SCons/scons#3253]
From scanning sconscript to compiling, It takes a long time. I see "Greg Noel had made a push for something called TNG taskmaster". so I ask a few questions:
1. what is TNG taskmaster? What are the improvement points? Detailed description of how TNG taskmaster is implemented?
2. Is there a better way to improve?

**Comment by bdbaddog** [comment]
This is not an issue. Bring it to the users mailing list.

https://pairlist4.pair.net/mailman/listinfo/scons-users
