### ISSUE TITLE
VC2017(ver 14.1) not found due to "no cl.exe found"

### ISSUE THREAD

**Issue by yumiaosg** [SCons/scons#3268]
My VC2017 Community installation is not detected by scons due to "no cl.exe found" error. My cl.exe path is: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64

Possible fix: modify function "get_installed_vcs" in vc.py, use os.walk to find cl.exe

**Comment by bdbaddog** [comment]
We ask that you bring such issues to scons users mailing list before filing.

**Comment by bdbaddog** [comment]
There's currently a pull request in progress to resolve.  Expect a 3.0.4 release in the not too distant future.

**Comment by yumiaosg** [comment]
Thanks, I'll close my pull request then.

**Comment by bdbaddog** [comment]
Fixed in #3264 will be in 3.0.4
