### ISSUE TITLE
Add -[rR] support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#327]
This issue was originally created at: 2002-12-06 01:14:07.
This issue was reported by: `stevenknight`.
stevenknight said at 2002-12-06 01:14:07
>Clear out (don't use) default environment/objects. These two  meant different things to Gnu Make, but they're probably the same for us. Or should we separate them somehow?

issues@scons said at 2002-12-06 01:14:07
>Converted from SourceForge tracker item 649400

gregnoel said at 2008-04-02 13:15:18
>Release team triage.

gregnoel said at 2008-04-18 18:47:28
>We shouldn't have UNCONFIRMED issues; changing them to NEW.

gregnoel said at 2008-12-26 13:20:21
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

**Comment by mwichmann** [comment]
Make `-r`, `--no-builtin-rules` - eliminate use of built-in implicit rules. Also clear out the default list of suffixes for suffix rules.

Make `-R`, `--no-builtin-variables` - Don't define any built-in variables.

Why would we want these?

**Comment by bdbaddog** [comment]
Yeah. 20 years noone has missed them. Closing.
