### ISSUE TITLE
Appveyor VS 2015 image fails some Java tests

### ISSUE THREAD

**Issue by dmoody256** [SCons/scons#3276]
The test/Repository/Java.py and test/Repository/JavaH.py fail on the Appveyor Visual Studio 2015 image.

The where_java calls report getting javac 1.7 and java 1.6, which leads to the version mismatch exception when java 1.6 tries to run the class files compiled with javac 1.7.

This could be from an issue in the test framework or a discrepancy with the appveyor environment. The [documentation](https://www.appveyor.com/docs/windows-images-software/#java) states it has jdk 1.6 installed, which means the javac should be there, but our test framework fails to find it. The documentation also says that as far as java goes its the same setup for 2017 image, which those same tests pass, which makes it seem more likely their image is not exactly as the documentation states. 

Example of the tests failing: https://ci.appveyor.com/project/SCons/scons/builds/21755506/job/9utlkrl9n6s1hppm

A possible workaround which sweeps the issue under the rug is to use the javac version to select the java version:
https://github.com/SCons/scons/compare/master...dmoody256:java_repository_appveyor_workaround?expand=1

**Comment by bdbaddog** [comment]
That code change you linked to seems like a reasonable one.
I wouldn't describe it as sweeping the problem under the rug.
It's possible you have jdk and jre's installed and one is found first in path for each yielding a mismatch if you don't specify a version.

**Comment by dmoody256** [comment]
The issue is that when you have multiple paths in the "PATH" that have the same binaries, the java tools (others are subject to this issue as well) will call AppendENVPath, and move the first version to the back so then when you check your path for the first instance of the binary, you actually get a different version.

Example:
env = Environment(ENV=test.javaENV())
PATH = 'C:\Program Files\Java\jdk1.6.0;C:\Program Files\Java\jdk1.7.0;C:\Program Files\Java\jdk1.8.0;'
javac's generate finds 1.6, and pushes it to the back
PATH = 'C:\Program Files\Java\jdk1.7.0;C:\Program Files\Java\jdk1.8.0;C:\Program Files\Java\jdk1.6.0;'
jar's generate find 1.7 and pushes it to the back
PATH = 'C:\Program Files\Java\jdk1.8.0;C:\Program Files\Java\jdk1.6.0;C:\Program Files\Java\jdk1.7.0;'
etc. etc.

The tests pass on Appveyor Visual Studio 2017, because it has 4 32 bit java 1.X versions and there are 4 java tools to push the java versions back so you end back at java 1.6, but 64 bit, and it works with the javac 1.6 32 bit.

This fails on Appveryor Visual Studio 2015 because it has one less java version, so you end up at java 1.7 (64 bit) in front most position of the "PATH", which fails with javac's 1.6 32 bit.

A possible fix is that all of the AppendENVPath for tools should use delete_existing=0, to not move existing paths to the end. That makes sense from user perspective too, because if I put a path in the front of the "PATH" manually, the tool better not move it to the back.

**Comment by bdbaddog** [comment]
So AppendENVPath is adding to the beginning of PATH? Because that shouldn't be moving existing paths to the end.. it should be appending..

**Comment by dmoody256** [comment]
If you don't set delete_existing=0, AppendENVPath, will move it to the end as implied by the comments:
https://github.com/SCons/scons/blob/e44c771cb3c0c5bd82ef3cd99d56cb47b2c4dc2c/src/engine/SCons/Util.py#L910-L911

Maybe the default of delete_existing=1 is a bit aggressive. Not sure if changing that would break other functionality or tests that relies on it.

**Comment by mwichmann** [comment]
Sorry if I'm re-explaining what's already clear... append appends, except if it doesn't need to: delete_existing evaluates false and path is already there; while if delete_existing is true, then you've effectively moved it to the end, by adding one and deleting one.  Feels to me also like the default should be to not change what you've got, and the unusual case should be add a path and remove a path.

**Comment by bdbaddog** [comment]
Agree.. is there anywhere in the codebase you didn't change?
Do we need to add deprecation message? and go through a cycle?
or Just release note...

**Comment by dmoody256** [comment]
>Agree.. is there anywhere in the codebase you didn't change?

There we several other places, but I don't think those cases were expecting delete_existing either. There probably is a test or 2 that will fail with the new changes. See EnvironmentTests.py in #3281, that test would need to be changed to support changing the default.

> Do we need to add deprecation message? and go through a cycle?

I think its a pretty rare case where its going to make a difference. Also only recently did some of the tools start using AppendENVPath for windows. I don't think it needs to be a big thing, plus its an option so it can easily be set to work as it did before.

**Comment by dmoody256** [comment]
This can be closed now that #3281 is merged
