### ISSUE TITLE
Couldn't resolve environment subkeys

### ISSUE THREAD

**Issue by DjoniD** [SCons/scons#3295]
## Detail info:
* Version of SCons: 3.0.1
* Version of Python: 2.7.15
* Install SCons: setup.py install
* Version of Platform: Windows10 x64, build 1809

```python
env = Environment()
print env['LIBLINKSUFFIX']
```
```bash
>scons
```
```bash
scons: Reading SConscript files ...
$LIBSUFFIX (not a".lib")
```

**Comment by bdbaddog** [comment]
I'm not sure what you think this should do.
That code is performing exactly as it should.

If you want the value to be printed, you should probably use

print env.subst("$LIBLINKSUFFIX")
(see manpage for subst)
Please bring your question to the scons users mailing list.

https://pairlist4.pair.net/mailman/listinfo/scons-users

**Comment by DjoniD** [comment]
This is good, thanks. But I think it is not correct. Interface is not uniform...(

**Comment by bdbaddog** [comment]
If you set a value to another value it needs to be evaluated.
(Make does the same)

if you say env['x']='$y'  then when you retrieve x, you get $y.
If you want the end value (which could be y=$z, z=$a,....), then you need to fully evaluate using subst().

If it were not this way how would you ever retrieve "$y" when you didn't want to evaluate it fully.

Do you have another proposed implementation?
Remember it's implemented in Python.

**Comment by DjoniD** [comment]
So, this makes sense.

> If it were not this way how would you ever retrieve "$y" when you didn't want to evaluate it fully.

May be:
```python
env['x']='$y'
# ($y=z)
env['$x']=z
```
But, i'm not sure...

**Comment by bdbaddog** [comment]
Nope. Environment is supposed to be accessable like a dictionary. No mucking with []..
