### ISSUE TITLE
SCons docs do not build with Python 3

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3300]
This is a work tracker issue for getting the documentation build to work with Python 3.

Currently, on releasing an scons version, you would follow these steps, various of which don't work if Python 3 is used. I have made this a task list so can check off the ones which do work.

- [X] `python bin/docs-validate.py ` to sanity check that nothing has left the XML invalid
- [x] `python bin/docs-update-generated.py`  to produce the pieces which are extracted from various files in the source tree (this runs the validation step first, so it may not be necessary run it separately)
- [x] `python bin/docs-create-example-outputs.py`  to extract the samples and capture the output of running them
- [x] `python bootstrap.py doc`

Typical errors:
```
  File "/home/mats/github/scons/bin/SConsDoc.py", line 303, in writeTree
    encoding="UTF-8", pretty_print=True))            
TypeError: write() argument must be str, not bytes
```
and
```
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

In addition to "porting problems" with the tools, need to also check whether the docs can be built with `python-lxml`, because the direct binding `python-libxslt` is no longer supported and can't be found in a Python 3 version in modern distributions (it is possible to build your own still).

It should also be noted that `epydoc` is used to build the API documents, and the packaged versions don't work with Python 3 - there is a github repo at https://github.com/nltk/epydoc which is attempting to make it work for Py3 so that should be a starting point for builds.  Long term it would be better to transition to another system (Sphinx most likely), but that's not part of this issue.

**Comment by mwichmann** [comment]
So I'm inclined to close this.  The docs build using Python3, even the API docs. Something does abort at the end (assuming I use Ubuntu, it's much worse on Fedora), and I can't quite tell if the API docs end up incomplete, but that seems to be part of the epydoc problem (see #3121) and not a problem of building with Python 3.  Any objections?

**Comment by bdbaddog** [comment]
Closing. Built fine for me on macOS with python 3.7.
