### ISSUE TITLE
SCons incremental build with relative paths

### ISSUE THREAD

**Issue by aohoyd** [SCons/scons#3302]
Hello,

I'm using SCons 3.0.1 with python 2.7.15 and I have a question about incremental build.
Looks like SCons uses absolute paths for build signatures, so when I'm trying to build something incrementally on another server I need to use the same path for it.
Is there possibility to use relative paths to compute signatures for objects and linked libraries to make incremental builds more flexible and portable?

**Comment by bdbaddog** [comment]
Please bring your question to the users mailing list as requested in the issue template.
This is not a bug, you are asking questions about functionality.
Or try our IRC channel #scons on freenode
