### ISSUE TITLE
SDK version '10.0A' is not supported

### ISSUE THREAD

**Issue by ghost** [SCons/scons#3329]
scons: *** SDK version '10.0A' is not supported
File "./platform/windows\detect.py", line 146, in setup_msvc_auto

this problem come for no reason !?

**Comment by bdbaddog** [comment]
Greetings!
Apparently you didn't read the request that you bring your issues to the scons users mailing list.
This is a known issue and will be fixed in the next release.

SCons explicitly whitelists versions of MS tools it knows how to use.
V10.0A is a new version.

**Comment by mwichmann** [comment]
Well, now that an issue exists, let's cross-tag it to https://github.com/godotengine/godot/issues/26485.

I'd like to see a better understanding of what the "SDK" entries are for, and how to find them - manual inspection suggested code as it is now might miss some current stuff and possibly misidentify some non-essential "SDK" entries as being crucial to the build when they maybe aren't.  Windows has a *lot* of things called SDK, and it stuffs references to them in the registry (Azure interfaces, sql server interfaces, .NET interfaces, etc.).  Adding v10.0A seems to be a quick fix, yes, but maybe more research would be better?

**Comment by ghost** [comment]
ok dudes i fix it just by using VS commend line , i hope you can improve scons more and fix all of its problems

**Comment by bdbaddog** [comment]
> ok dudes i fix it just by using VS commend line , i hope you can improve scons more and fix all of its problems

Users are always free to contribute pull requests to resolve issue they run into..

I think this issue was already raised in godot's own issue tracker and I floated a temporary fix there.

**Comment by bdbaddog** [comment]
Fixed in #3332
