### ISSUE TITLE
Linking large amount of files with mslink fails

### ISSUE THREAD

**Issue by kayhayen** [SCons/scons#3350]
* Version of SCons

3.04

* Version of Python

2.7 trough 3.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)

* How you installed SCons

Nuitka inline copy of 3.0.4

* What Platform are you on? (Linux/Windows and which version)

Windows with VS 2017 and earlier.

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.

Again no none, sorry.

We have had to make a change, because while Scons avoids one limit, namely the OS limit of command line length, the mslink parser also has a line length limit. Scons joins the files with spaces, producing a single line with, which then mslink.exe can refuse. Our change avoid this:

```
-        os.write(fd, bytearray(" ".join(args) + "\n",'utf-8'))
+        # Nuitka: Avoid super long lines beyond the parser limit of the MS tool.
+        os.write(fd, bytearray("\n".join(args) + "\n",'utf-8'))

```

With this, a single filename is put per line, and that works perfectly. No scalability limit is known on Windows with MSVC. Seen my other issue #3348 for MinGW64 issue.

**Comment by bdbaddog** [comment]
tagged wrong bug from PR 3354 should have been 3349

**Comment by bdbaddog** [comment]
Is this mslink and also msvc? (new line better than space)
Or other tools that you are aware of as well.
I'm going to default it to space and then only change it for tools which work with newlines.

**Comment by kayhayen** [comment]
Ich have used this with MSVC 2008 and earlier. Not sure now what distinction you are drawing.

**Comment by bdbaddog** [comment]
mslink (link.exe) and msvc (cl.exe) are separate tools and executables.
Safe to assume that all tools on all platforms do not accept newlines in their command files.
So ideally we'd only make this change for tools which do.

**Comment by kayhayen** [comment]
Oh @bdbaddog I might be confused, but this is not at all about command line length anymore. I think there is already a tempfile employed to be passed to `link.exe` and the issue is with that input file of the linker.

Seems the linker parses the file line wise, and in that has a length limit for the line, which Nuitka users hit with large compilations, when all filenames are put on a single line. Separating filenames with new line in that file is working dramatically better than spaces.

Has nothing to do with `cl.exe` and command line at all. Or so I am thinking.

It just gives `link.exe` an easier time in its parser, which seems line oriented. To me, this patch we have given should be absolutely uncritical.

Yours,
Kay

**Comment by mwichmann** [comment]
I find this quote on the internet, not an official doc but no real reason to doubt:

> The command file is parsed for directives line by line, for as long as lines can be read. It is a fatal error (LNK1170) for a command file to have too long a line. The present limit is 128KB. 

from https://www.geoffchappell.com/studies/msvc/link/cmdfiles.htm

Microsoft's own docs contain this:

> In the command file, arguments can be separated by spaces or tabs (as on the command line) and by newline characters.

from https://docs.microsoft.com/en-us/cpp/build/reference/linking?view=vs-2019

**Comment by bdbaddog** [comment]
> I find this quote on the internet, not an official doc but no real reason to doubt:
> 
> > The command file is parsed for directives line by line, for as long as lines can be read. It is a fatal error (LNK1170) for a command file to have too long a line. The present limit is 128KB.
> 
> Microsoft's own docs contain this:
> 
> > In the command file, arguments can be separated by spaces or tabs (as on the command line) and by newline characters.

Can you add URL's for such?

TEMPFILE is used or can be used on any platform for any tool.
So making a universal change from space to newline may not be valid.
As such making a per-tool change seems reasonable.
That's why I'm asking which tools you've tried your change with.

**Comment by mwichmann** [comment]
I added the URLs.  GNU linker scripts have their own syntax anyway, and I don't see that scons generates them: lines of the form INPUT(file1, file2, file3,...)

**Comment by bdbaddog** [comment]
O.k. pull request to resolve this available.
Please take a look.
I can prepare a pre-release test pypi package if that's helpful.
