### ISSUE TITLE
[website] changes to dev guidelines

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3406]
For tracking purposes (was mentioned on discord channel): on https://scons.org/guidelines.html a couple of minor things could stand cleanup

1.2: "all later versions of 2.x" -> 3.x
1.8.1: Mercurial -> git
1.9: QMTest is gone.
5.1  "may, but need not" be registered on github - can you actually do anything on gh without being a user?

**Comment by bdbaddog** [comment]
Should be fixed on website now.
