### ISSUE TITLE
[question] Python API to run scons target ?

### ISSUE THREAD

**Issue by SafeteeWoW** [SCons/scons#3407]
Suppose I create a simple Python scripts similar to the following (Imports not shown)
```
env = Environment()   # Create an environmnet
env.Program(target = "helloworld", source = ["helloworld.c"])
```
Is there a way that I can execute ```env``` or the target ```helloworld``` from this python script?
I do not want to use subprocess to call ```scons```.
Is there a scons Python API to do this?

**Comment by bdbaddog** [comment]
Which do you want to do?
1) use some python API to run scons?
2) Run helloworld from within a sconstruct/sconscript?

**Comment by SafeteeWoW** [comment]
use some python API to run scons.
I do not want to use subprocess to call scons or call "scons" directly in terminal. Is that possible?

Sth like the following:
```
env = Environment()   # Create an environmnet
env.Program(target = "helloworld", source = ["helloworld.c"])

scons.RUN_ENV(env)
soncs.RUN_TARGET(env, "helloworld")
```

**Comment by bdbaddog** [comment]
Not currently supported.
Why do you want to avoid subprocess?

**Comment by SafeteeWoW** [comment]
Test a deep learning compiler, written in C++, whose input is generated from Python scripts of deep learning framework. The compiler we are developing consists of multiple executables, and testing for it is done in multiple stages, similar to "compile source code/link object file/run executable" when testing standard C compiler.

Currently, the whole test framework is based on Makefile & bash script & Python script.
But Makefile is hard to track dependencies of Python script, and multiple scripting language
is hard to maintain and understand.

I plan to switch to pytest as the test framework, and try to use Python only.
but I need a package to track file dependencies, otherwise incremental tests takes long time.
I do not want to write separate SConstruct file, I just want to track file dependency
when running c++ program in Python in pytest test function.

If scons does not support using Python API to run targets. Do you know any other Python based build system which supports this feature?

**Comment by bdbaddog** [comment]
Seems like you could have scons run the deep learning compiler?
sounds like:
files -> DLC (deep learning compiler) -> c++ & python (?) -> run with pytest?

**Comment by SafeteeWoW** [comment]
Is there any Python API in scons to determine if target is update to date?

**Comment by bdbaddog** [comment]
No. SCons is not designed to be embedded.
Though if there is a way to have SCons wrap your process that could solve your issue.

**Comment by mwichmann** [comment]
you're going to have to write some set of sconscripts.  the only way scons can figure out the dependencies is for you to tell it what things matter so it can examine those and work out the dependency graph.  You seem to know this, based on your initial message:

> Suppose I create a simple Python scripts similar to the following (Imports not shown)

```
env = Environment()   # Create an environmnet
env.Program(target = "helloworld", source = ["helloworld.c"])
```

> Is there a way that I can execute env or the target helloworld from this python script?

Let me try an explanation here, hopefully this will make some sense as to how to look at this: 

Many specialized tools have what's called a Domain-Specific Language (DSL) used to instruct them what to do.  In the case of SCons, the DSL is the SCons API (the stuff you read on the manpage) and the full syntax of the Python language.  So what you have written should be thought of as an scons congfiguration script (sconscript) written in that language, rather than a general-purpose Python script. You need scons to execute that script.

I'd suggest move this discussion to the scons-users mailing list.

**Comment by bdbaddog** [comment]
Please use either scons IRC, discord, or users mailing list for this discussion. It will allow more real time.

**Comment by SafeteeWoW** [comment]
Thanks. I would consider wrapping the entire application in a SConstruct file.

I hope SConstruct can support this feature in the future, but
I think it takes a lot of effort. I assume this can be implemented by
constructing a Python class which represents a sconscript.
It requires Scons to be able to interpret two independent sconscript in the Same Python project.
And such class should be able to handle scons commandline options though arguments of its constructor.

**Comment by bdbaddog** [comment]
> Thanks. I would consider wrapping the entire application in a SConstruct file.
> 
> I hope SConstruct can support this feature in the future, but
> I think it takes a lot of effort. I assume this can be implemented by
> constructing a Python class which represents a sconscript.
> It requires Scons to be able to interpret two independent sconscript in the Same Python project.
> And such class should be able to handle scons commandline options though arguments of its constructor.

not that simple. sconscript is not run. sconscript sets up internal data structures which are then processed after all sconstruct/sconscript are processed.
