### ISSUE TITLE
move all the metadata from setup.py to setup.cfg

### ISSUE THREAD

**Issue by KOLANICH** [SCons/scons#3452]
https://github.com/gvalkov/setuptools-py2cfg should be helpful. setup.cfg allows to read some file too, using `file: `.

**Comment by bdbaddog** [comment]
Why is setup.cfg better than having the info in setup.py?

**Comment by chasinglogic** [comment]
https://docs.python.org/3/distutils/configfile.html

The gist is that you can consume the information in packaging / other scripts whereas the information in the setup.py is opaque to anything outside setup tools.

**Comment by bdbaddog** [comment]
@chasinglogic  - Gotcha.

**Comment by KOLANICH** [comment]
Here is the better docs about setup.cfg: https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

**Comment by bdbaddog** [comment]
@KOLANICH  Please take a look at the setup.cfg in  #3603

**Comment by KOLANICH** [comment]
Looks fine. But some more points. We can fetch the version automatically from git using `setuptools_scm` and also we should create a `pyproject.toml` saying that the build is done using setuptools to allow building with `python3 -m pep517.build`. Feel free to take https://github.com/KOLANICH/RichConsole.py/blob/master/pyproject.toml as a boilerplate.

**Comment by bdbaddog** [comment]
Fixed in #3603
