### ISSUE TITLE
SConf subsystem's conftest file naming mechanism is non-deterministic

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3469]
**Describe the bug**
If a command line option can cause a different sequence of configure checks to run, or to run in a different order, SCons can become confused about which tests are cached, or about which actions are associated with a given numbered configure check. This can lead to either re-running configure checks that should have still been cached, only because the numbering changed, or, in worse cases, to a misconfigured build. See https://jira.mongodb.org/browse/SERVER-23208 for an example.

**Required information**
* Link to SCons Users thread discussing your issue.
N/A, discussed on slack.

* Version of SCons
3.1.1, but probably applies to older versions as well.

* Version of Python
3.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
N/A

* How you installed SCons
Vendored into MongoDB repo

* What Platform are you on? (Linux/Windows and which version)
Linux/MacOS/Windows, multiple versions

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
See repro instructions in linked MongoDB ticket.

* How you invoke scons (The command line you're using "scons --flags some_arguments")
See above.

**Comment by acmorrow** [comment]
The fundamental issue here is the global incrementing counter. I have an in-flight solution that uses the hash of the test body to differentiate configure tests. It isn't perfect, but I'll put up my WIP code in a PR that references this issue.

**Comment by bdbaddog** [comment]
This fixed by merged Pull Request #3543
