### ISSUE TITLE
Util.py: to_str() typo

### ISSUE THREAD

**Issue by lmnts** [SCons/scons#3488]
While looking through the Util.py file for other reasons, I came across this definition:
```
def to_str(s):
    if s is None:
        return 'None'
    if bytes is str or is_String(s):
        return s
    return str (s, 'utf-8')
```
I believe **bytes** should instead be **s** in the second `if` statement here.

**Comment by bdbaddog** [comment]
Nope. The test is to see if bytes and str are the same type.
If they are then s can be returned, otherwise s would need to be encoded.

**Comment by lmnts** [comment]
Thank you for clarifying, bdbaddog.

**Comment by bdbaddog** [comment]
This why we ask people to bring issues to the users mailing list before filing bugs.
To avoid bugs which are either not bugs, or duplicates of existing bugs filling up our issue tracker.
