### ISSUE TITLE
scons build with "Error 309"

### ISSUE THREAD

**Issue by tangMans** [SCons/scons#3499]
scons: done reading SConscript files.
scons: Building targets ...
cl /Fo3rd\agge\agge\math.obj /c 3rd\agge\agge\math.cpp /TP -DWIN32 -D_WIN32 -DWI
NDOWS /EHsc -D_CONSOLE /DEBUG /Od /FS /Z7 -DWITH_64BIT_CPU -DTK_ROOT="F:\awtk
\awtk\awtk" -DSTBTT_STATIC -DSTB_IMAGE_STATIC -DWITH_STB_IMAGE -DWITH_SOCKET -
DWITH_VGCANVAS -DWITH_UNICODE_BREAK -DWITH_DESKTOP_STYLE -DSDL2 -DHAS_STD_MALLOC
-DWITH_SDL -DWITH_FS_RES -DHAS_STDIO -DHAVE_STDIO_H -DWITH_STB_FONT -DWITH_BITM
AP_BGRA -DWITH_NANOVG_SOFT -DWITH_FB_BGR565=1 -DWITH_NANOVG_AGGE -D_WIN64 -DSDL_
REAL_API -DSDL_HAPTIC_DISABLED -DSDL_SENSOR_DISABLED -DSDL_JOYSTICK_DISABLED -D_
_STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -D_HAS_EXCEPT
IONS=0 -D_HAS_ITERATOR_DEBUGGING=0 -D_ITERATOR_DEBUG_LEVEL=0 -D_SCL_SECURE=0-D_S
ECURE_SCL=0 -D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO
_DEPRECATE /I. /Isrc /I3rd /Isrc\ext_widgets /I3rd\pixman /I3rd\cairo /I3rd\bgfx
\bgfx\include /I3rd\bgfx\bx\include /I3rd\bgfx\bimg\include /I3rd\agge /I3rd\agg
\include /I3rd\nanovg /I3rd\nanovg\gl /I3rd\nanovg\base /I3rd\nanovg\agge /I3rd
nanovg\bgfx /I3rd\SDL\src /I3rd\SDL\include /I3rd\agge\src /I3rd\agge\include /I
3rd\gpinyin\include /I3rd\libunibreak /I3rd\gtest\googletest /I3rd\gtest\googlet
est\include /Itools
scons: *** [3rd\agge\agge\math.obj] Error 309
scons: building terminated because of errors.

think you for reply!

**Comment by bdbaddog** [comment]
Please bring your issue to the users mailing list, IRC channel (#scons on freenode)  or the discord server https://discord.gg/bXVpWAy . (Per the pre-filled information when you opened this issue).

You've provide no information on the environment you're building in or any version information.
Closing this issue.

**Comment by sosotan** [comment]
Win 10 bugs, reinstall vc_redist.x64.exe, vc_redist.x86.exe, 
or fix the setup item in control panel

use cmd.exe run scons shows more error detial

**Comment by mwichmann** [comment]
Looks like missing dlls? https://stackoverflow.com/questions/27808849/what-does-error-309-mean

**Comment by sosotan** [comment]
yes, miss vc runtime dll
you will see the info when run scons with cmd.exe

**Comment by bdbaddog** [comment]
@soyzhc - no we won't we test with all recent MSVC versions and this issue doesn't come up. So likely there's something unusual about your build environment.

**Also:**
**Please bring your issue to the users mailing list, IRC channel (#scons on freenode) or the discord server https://discord.gg/bXVpWAy . (Per the pre-filled information when you opened this issue).

You've provide no information on the environment you're building in or any version information.**
