### ISSUE TITLE
Confusing paragraph should be deleted from User Guide

### ISSUE THREAD

**Issue by leonbloy** [SCons/scons#3519]
The User Guide, in the "Dependencies" chapter has a paragraph 

**6.2. Older Functions for Deciding When an Input File Has Change** ([link]( https://scons.org/doc/production/HTML/scons-user.html#idm1032))

that reads 

> SCons still supports two functions that used to be the primary methods for configuring the decision about whether or not an input file has changed. These functions have been officially deprecated as SCons version 2.0, and their use is discouraged, mainly because they rely on a somewhat confusing distinction between how source files and target files are handled. These functions are documented here mainly in case you encounter them in older SConscript files.

The reader is left wondering if those functions ("described here") are in the following sections, or what... 
Actually (I guess) they are now NOT "described here" anymore, so that paragraph should be deleted.

**Comment by mwichmann** [comment]
Yup, you're right.  Those deprecated methods were removed recently, and I missed fixing up this section because it didn't match a grep for the method names, as you've noted!
