### ISSUE TITLE
Visual Studio Express 2017 not detected due to HOST_ARCH default (most likely)

### ISSUE THREAD

**Issue by gganssauge** [SCons/scons#3530]
# Visual Studio Express 2017 not detected

I discussed the issue with @bdbaddog on the #scons-help channel on discord and he asked me to add a bug report here.

## Table of Contents

* [Problem statement](#problem)
* [Environment](#environment)
* [Analysis](#analysis)
* [Workaround](#workaround)
* [Conclusion](#conclusion)
* [Reproducing the bug](#reproducing)

<a name="problem"></a>
## Problem statement

Consider the following SConstruct

~~~~python
Program('hello', 'hello.c')
~~~~

And the classical hello, world program

~~~~C
# include <stdio.h>

int main(int ac, char *av[]) {
    printf("Hello, world\n");
    return 0;
}
~~~~

When this is run, I get the following output:

~~~~text
(scons) c:\Users\ganss\appdata\local\Temp\scons>scons
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\ganss\appdata\local\Temp\scons\SConstruct", line 1, in <module>
scons: done reading SConscript files.
scons: Building targets ...
cl /Fohello.obj /c hello.c /nologo
Der Befehl "cl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
scons: *** [hello.obj] Error 1
scons: building terminated because of errors.

(scons) c:\Users\ganss\appdata\local\Temp\scons>
~~~~

<a name="environment"></a>
## Environment

~~~~text
(scons) c:\Users\ganss\appdata\local\Temp\scons>

(scons) c:\Users\ganss\appdata\local\Temp\scons>ver

Microsoft Windows [Version 10.0.18363.592]

(scons) c:\Users\ganss\appdata\local\Temp\scons>python --version
Python 3.8.1

(scons) c:\Users\ganss\appdata\local\Temp\scons>scons --version
SCons by Steven Knight et al.:
        script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
        engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
        engine path: ['c:\\users\\ganss\\appdata\\local\\temp\\scons\\lib\\site-packages\\scons\\SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
~~~~

The machine has a Visual Studio Express 2017 installed and no other versions of visual studio

~~~~text
(scons) c:\Users\ganss\appdata\local\Temp\scons>"c:\Program Files (x86)\Microsoft Visual Studio\Installer"\vswhere -products "*"
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 4e83d1f0
installDate: 27.12.2019 23:46:12
installationName: VisualStudio/15.9.18+28307.960
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress
installationVersion: 15.9.28307.960
productId: Microsoft.VisualStudio.Product.WDExpress
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\Common7\IDE\WDExpress.exe
isPrerelease: 0
displayName: Visual Studio 2017 für Desktop Express
description: Eine IDE, die die Entwicklung von Desktopanwendungen ermöglicht. Testen Sie Visual Studio Community als erweiterbare Alternative mit vollständigem Funktionsumfang.
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.18
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-12-27T22:46:12.4666321Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.960
catalog_id: VisualStudio/15.9.18+28307.960
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.18
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 18
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.18+28307.960
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId:
properties_channelManifestId: VisualStudio.15.Release/15.9.18+28307.960
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe
~~~~

<a name="analysis"></a>
## Analysis

The issue obviously got something to do with tool detection. On @bdbaddog's proposal I let the following three scenarios run:

1. SConstruct is only a single statement: `DefaultEnvironment()`
   The environment variable _SCONS_MSCOMMON_DEBUG_ is set to _mstrace.log_.
   The resulting logfile is available as https://pastebin.com/e4kqhPDU

2. SConstruct is only a single statement: `DefaultEnvironment(MSVC_VERSION="14.1", TARGET_ARCH='x86')`
   The environment variable _SCONS_MSCOMMON_DEBUG_ is set to _mstrace-without-host_arch.log_.
   The resulting logfile is available as https://pastebin.com/eW56Pnud

3. SConstruct is only a single statement: `DefaultEnvironment(MSVC_VERSION="14.1", TARGET_ARCH='x86', HOST_ARCH='x86')`
   The environment variable _SCONS_MSCOMMON_DEBUG_ is set to _mstrace-without-host_arch.log_.
   The resulting logfile is available as https://pastebin.com/SZCE8Hp9

<a name="workaround"></a>
## Workaround
Setting the _HOST_ARCH_ variable to _x86_ makes the detection work, this SConstruct file
works on the machine:

~~~~python
DefaultEnvironment(HOST_ARCH='x86')
Program('hello', 'hello.c')
~~~~

<a name="conclusion"></a>
## Conclusion

As the visual studio express versions come without the AMD64 tools, the detection logic should not only consider the visual studio directories mandated by the detected host architecture but additionally should consider at least the _x86_ directories.

Not sure about _arm_ here - I don't even know if there are visual studio versions out that are running on more than one arm architecture.

<a name="reproducing"></a>
## Reproducing the bug

see [Problem statement](#problem)

**Comment by gganssauge** [comment]
Here are the logs mentioned as attachments
[mstrace.log](https://github.com/SCons/scons/files/4104643/mstrace.log)
[mstrace-with-host-arch.log](https://github.com/SCons/scons/files/4104644/mstrace-with-host-arch.log)
[mstrace-without-host-arch.log](https://github.com/SCons/scons/files/4104645/mstrace-without-host-arch.log)

**Comment by bdbaddog** [comment]
See: https://visualstudio.microsoft.com/vs/express/ to download VS2017 express.

**Comment by mwichmann** [comment]
Yeah, this analsys looks basically correct, and I can reproduce the behavior.  We see multiple snips like this in the msvc trace file:
```
00076ms:pid19904:MSCommon/vc.py:trying to find VC 14.1
00138ms:pid19904:MSCommon/vc.py:find_vc_pdir_vswhere(): VC found: '14.1'
00138ms:pid19904:MSCommon/vc.py:found VC 14.1
00138ms:pid19904:MSCommon/vc.py:get_host_target()
00138ms:pid19904:MSCommon/vc.py:get_host_target() req_target_platform:None
00138ms:pid19904:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): host platform amd64, target platform amd64 for version 14.1
00139ms:pid19904:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): checking for cl.exe at C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
00140ms:pid19904:MSCommon/vc.py:find_vc_pdir no compiler found 14.1
```
So - found it via `vswhere`, but then checking for the actual compiler, and it isn't there.  Note the "`checking for cl.exe`" message above.  On my system we do find `cl.exe`, and these are the paths found when starting from `c:/Program Files (x86)/Microsoft Visual Studio`"
```
./2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/arm/cl.exe
./2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/arm64/cl.exe
./2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
./2017/WDExpress/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
```

**Comment by mwichmann** [comment]
Oh, this is cute.  You can update the check in `_check_cl_exists_in_vc_dir`, and get it to pass:
```
00125ms:pid04196:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): host platform amd64, target platform amd64 for version 14.1
00125ms:pid04196:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): checking for cl.exe at C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe
00125ms:pid04196:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): checking for cl.exe at C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x64\cl.exe
00125ms:pid04196:MSCommon/vc.py:_check_cl_exists_in_vc_dir(): found cl.exe!
```
and it makes no difference, because this was just a yes/no question, and there's still somewhere else that relies on the same logic, and the net result is still no compiler found.

**Comment by mwichmann** [comment]
Tracing further, everything seems okay, then at the very end of `msvc_setup_env` there is a final sanity-check call:
```
    # final check to issue a warning if the compiler is not present
    msvc_cl = find_program_path(env, 'cl')
    if not msvc_cl:
        debug("msvc_setup_env() did not find 'cl'")
        SCons.Warnings.warn(SCons.Warnings.VisualCMissingWarning,
            "Could not find MSVC compiler 'cl', it may need to be installed separately with Visual Studio")
```
And the paths set in `env` don't include one where `cl.exe` is found.  I don't get this, because it has actually found and run `vcvarsall.bat` and that's what it gives back....

**Comment by mwichmann** [comment]
Okay, one more poke: gack. `vcvarsall.bat` doesn't fail if given a dodgy combination, it just doesn't set enough of the env up.  So we have a list of things to try:
```
00203ms:pid07832:MSCommon/vc.py:msvs_find_valid_batch_script(): host_platform: amd64 try_target_archs:['amd64', 'x86_amd64', 'x86']
```
The magic target we want is `x86_amd64` - this was put in to deal with other express versions, but it's still valid for 2017. If I manually run `vcvarsall.bat x86_amd64`, it does the right stuff - `cl` is in the PATH now. But first scons tries `vcvarsall.bat amd64` which by all indications succeeds, so there's no reason to go on and try the other targets, but there's no path to the compiler in PATH. Here's running it manually - showing no signs of a problem:
```
c:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build>vcvarsall.bat amd64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.19
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
```
So I don't know yet how to handle this case.

**Comment by mwichmann** [comment]
Wow, these scripts are ugly.  I have a fix pending.

**Comment by mwichmann** [comment]
Can you check if https://github.com/SCons/scons/pull/3538.patch makes it work for you?

**Comment by gganssauge** [comment]
I used the git-patch plugin in VS-Code to apply your patch - and it runs fine without HOST_ARCH and without TARGET_ARCH.

When I specify TARGET_ARCH='x86', though, it fails again :(

SConstruct:

~~~~python
DefaultEnvironment(TARGET_ARCH='x86')
Program('hello', 'hello.c')
~~~~

running that yields

~~~~text
C:\Users\ganss\AppData\Local\Temp\scons>python %sc%\script\scons.py
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fohello.obj /c hello.c /nologo
Der Befehl "cl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
scons: *** [hello.obj] Error 1
scons: building terminated because of errors.
~~~~

**Comment by gganssauge** [comment]
My workaround (setting HOST_ARCH='x86') still works

**Comment by mwichmann** [comment]
okay, thanks for that update. presumably one more little logic twist. I should be able to take another pass at it without too much delay.

**Comment by bdbaddog** [comment]
@gganssauge - can you try devel build I just posted on testpypi? (note py3.5+ is now required)

`pip install --index-url https://test.pypi.org/simple/ scons==3.1.3.dev20200205165450`

**Comment by gganssauge** [comment]
Works perfectly - with or without HOST_ARCH and with or without TARGET_ARCH.

Cheers,

Gottfried

Am 06.02.2020 um 02:16 schrieb William Deegan:
