### ISSUE TITLE
['SUBSTFILEPREFIX', 'TEXTFILESUFFIX']

### ISSUE THREAD

**Issue by garyemiller** [SCons/scons#3540]
**Describe the bug**
From git head, just now.  
File: src/engine/SCons/Tool/textfile.py
Line 165:
_text_varlist = _common_varlist + ['TEXTFILEPREFIX', 'TEXTFILESUFFIX']

Line 174:
_subst_varlist = _common_varlist + ['SUBSTFILEPREFIX', 'TEXTFILESUFFIX']

Looks like a cur/paste/edit error.  My guess, from the rest of the code, is that
 'TEXTFILESUFFIX' should be  'SUBSTFILESUFFIX' on line 174

**Comment by mwichmann** [comment]
that looks a reasonable conclusion.

**Comment by bdbaddog** [comment]
So if I understand this correctly.  A change to TEXTFILESUFFIX would cause Substfile()'s to rebuild when they shouldn't?

**Comment by garyemiller** [comment]
I'm still struggling with Substfile(), but my guess would be that since Substfile might be using the wrong suffix (TEXTFILESUFFIX instead of SUBSTFILESUFFIX) that it would not find the files required for the target.

**Comment by bdbaddog** [comment]
@garyemiller - so the line you found doesn't impact the naming of the file or the logic which is run to build the file. 

varlist argument to Action() is used to tell SCons "Hey if any of these Environment() values change, you need to rebuild".

**Comment by garyemiller** [comment]
@bdbaddog Fair enough.  I have a lot left to learn on scons.

**Comment by bdbaddog** [comment]
@garyemiller - hop on the discord server if you'd like some help with anything. or the users mailing list (low volume)
