### ISSUE TITLE
SCons should use %ProgramFiles(x86)% to locate base dir for vswhere location

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3542]
When the user has MSVS installed on any non C: drive SCons fails to find vswhere as the path we use to locate it is hardcoded to the C: drive.

According to:
https://github.com/microsoft/vswhere/wiki/Installing
and
https://devblogs.microsoft.com/setup/vswhere-is-now-installed-with-visual-studio-2017/

We should be using 

> vswhere.exe is installed in %ProgramFiles(x86)%\Microsoft Visual Studio\Installer (use %ProgramFiles% in a 32-bit program prior to Windows 10). 

This should fix GoDot Issue
https://github.com/godotengine/godot/issues/35446

**Comment by mwichmann** [comment]
A simple fix for this is to pull the paths to program files out of `os.environ`, as in:
```
    for pf in (os.environ["ProgramFiles(x86)"], os.environ["ProgramFiles"]):
        vswhere_path = os.path.join(
            pf,
            'Microsoft Visual Studio',
            'Installer',
            'vswhere.exe'
```

I just hacked this together and it seems to work for the "normal" case - would be good to know if the user's `os.environ["ProgramFiles(x86)"]` actually does return the D: drive before pushing out a PR though.

**Comment by bdbaddog** [comment]
@mwichmann - Yes. I asked him in the godot issue and he responded yes. Probably need to gracefully handle when there's on ProgramFiles(x86) environment variable (32 bit windows install).

**Comment by mwichmann** [comment]
that's the second entry - `os.environ["ProgramFiles"]`

**Comment by bdbaddog** [comment]
Right but the first one will raise a KeyErrror exception if on 32bit windows right?

**Comment by mwichmann** [comment]
Possibly. Don't have a 32-bit windows to test on, but could still be conservative about it... use `os.environ.get`, and probably don't have to loop if doing so.

**Comment by mwichmann** [comment]
Yikes, the result of those may also depend on the bit-ness of the Python interpreter.
