### ISSUE TITLE
How to link a staticlib ? (There are both .so and .a in the folder)

### ISSUE THREAD

**Issue by ywsswy** [SCons/scons#3544]
There are both libconfig.so and libconfig.a in the folder, i only want to link the static lib(libconfig.a)，
so i add 'static' in my SConstruct：
```
Program('main', 'main.cc', parse_flags='-L . -static -lconfig')
```
BUT, it link the .so lib. WHY, Please help me O(∩_∩)O

**Comment by bdbaddog** [comment]
You failed to follow the directions to bring this issue to the SCons users mailing list, IRC channel, or discord server.

You've also not stated which platform, compiler, version of SCons.
Not sure why you're using parse_flags with your program.

Also do you build the config library? or is built by another build system or an installed package.

Please bring this information to one of the methods listed above.
See:
https://scons.org/contact.html
