### ISSUE TITLE
Why is there no highlight in compiler output when running SCons

### ISSUE THREAD

**Issue by ywsswy** [SCons/scons#3564]
Why there is NOT highlight in scons ?
There is highlight when i use g++ only:
![image](https://user-images.githubusercontent.com/25153243/75048905-4095a300-5504-11ea-8886-c2742ea3a6cb.png)
But scons:
![image](https://user-images.githubusercontent.com/25153243/75049017-70dd4180-5504-11ea-8182-99e5bb16ff07.png)

**Comment by bdbaddog** [comment]
You failed to follow any of the requests when filing an issue...

Did you see this when you clicked on "New Issue"
## Please bring your feature request to the SCons users mailing list before filing an issue here
## See: https://scons.org/bugs.html
## or join our Discord server : https://discord.gg/bXVpWAy


**Required information**
* Link to SCons Users thread discussing your issue.
* Version of SCons
* Version of Python
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
* How you installed SCons
* What Platform are you on? (Linux/Windows and which version)
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
* How you invoke scons (The command line you're using "scons --flags some_arguments")

If not, then it's understandable why you didn't provide that information. (and let us know so we can resolve that)

If you did, please stop and provide that information.
An ideally connect with the community on the users mailing list, or discord channel, or IRC before filing a new issue as requested.

Remember you're not paying for SCons, or SCons support, so you're asking others who volunteer their time to help you with an issue you've run into. The very least you can do is to provide the basic information needed to help you.

Also, you're issue title is not informative. I've changed it.

**Comment by mwichmann** [comment]
gcc is "smart" - it figures if the error stream doesn't look like a terminal, you may be sending the output to a file, or to another program, and the chars which provide the highlighting would be confusing in that context so it leaves them out (and believe me they are - it's a real pain if you capture things to a file and then there's all this extra "stuff").  when running through scons, the output and error streams are pipes back to scons, so it doesn't look like a terminal.  you may be able to force the behavior you want by giving an argument to gcc.

From the gcc manpage it looks like the thing you want to try is:

`-fdiagnostics-color`

which is a synonym for `-fdiagnostics-color=always`

Gentle nudge: this wasn't really the sort of thing to write a bugreport on (did you see the issue guidelines?). Bringing it to the mailing list would have been better.

**Comment by ywsswy** [comment]
I'm sorry that I didn't follow any of the requests when filing an issue...
Thank you very much for the question, and i will correct my mistake.

**Comment by mwichmann** [comment]
A simple `SConstruct` shows that adding the flag does let the color show:
```
env = Environment(CCFLAGS="-fdiagnostics-color")
env.Program(source="foo.c")
```
(for some `foo.c` with broken contents)

**Comment by bdbaddog** [comment]
> I'm sorry that I didn't follow any of the requests when filing an issue...
> Thank you very much for the question, and i will correct my mistake.

Did you know that you can also edit the description section after you file an issue?
