### ISSUE TITLE
Java builder fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by datalogics-robb** [SCons/scons#3567]
Under Python 2.7, the Java builder doesn't care how the java files are encoded, but for a project that's currently building with SCons 3.1.1 using Python 2.7, it fails when running Python 3.x.
Java files are being opened as text, assuming the default encoding, which is different from OS to OS.  Under Windows, this causes a new failure for an old project:

10:42:40 UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1807: character maps to <undefined>:
10:42:40   File "C:\Jenkins\CI\DLE18_special\32\dle-sandbox\DLE\SConstruct", line 1697:
10:42:40     libraries = swigenv.SConscript('SWIG.scons', exports={'env': swigenv}, variant_dir="$BUILDDIR", duplicate=0)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Script\SConscript.py", line 597:
10:42:40     return _SConscript(self.fs, *files, **subst_kw)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Script\SConscript.py", line 286:
10:42:40     exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
10:42:40   File "C:\Jenkins\CI\DLE18_special\32\dle-sandbox\DLE\SWIG.scons", line 260:
10:42:40     classes = javaenv.Java('classes', javaenv.Dir('$SOURCEPATH.abspath/../'))
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Environment.py", line 219:
10:42:40     return self.method(*nargs, **kwargs)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Tool\javac.py", line 196:
10:42:40     result.extend(b(t, s, *args, **kw))
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Environment.py", line 255:
10:42:40     return MethodWrapper.__call__(self, target, source, *args, **kw)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Environment.py", line 219:
10:42:40     return self.method(*nargs, **kwargs)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Builder.py", line 651:
10:42:40     return self._execute(env, target, source, OverrideWarner(kw), ekw)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Builder.py", line 563:
10:42:40     tlist, slist = self._create_nodes(env, target, source)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Builder.py", line 525:
10:42:40     target, source = self.emitter(target=tlist, source=slist, env=env)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Tool\javac.py", line 98:
10:42:40     pkg_dir, classes = parse_java_file(f.rfile().get_abspath(), version)
10:42:40   File "c:\jenkins\ci\dle18_special\32\dle-sandbox\python-env-win10-apdfl18\lib\site-packages\scons\SCons\Tool\JavaCommon.py", line 408:
10:42:40     data = f.read()
10:42:40   File "C:\Python36\lib\encodings\cp1252.py", line 23:
10:42:40     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
10:42:40 Build completed with status 2

**Required information**
* breifly discussed on dischord 2/20/2020 in \#scons-help
* Version of SCons: 3.1.1
* Version of Python: 3.6, 3.7 (any 3.5+)
* How you installed SCons: via pip
* What Platform are you on?: Windows 10 (Mac & Linux work properly in this case)
* How to reproduce your issue?: Build
* How you invoke scons: scons VAR=value

**Comment by mwichmann** [comment]
Is this fixed? GIven that PR #3568 which referenced it is merged?

**Comment by datalogics-robb** [comment]
@mwichmann Yes the problem has been fixed.

**Comment by bdbaddog** [comment]
closing
