### ISSUE TITLE
When windows installed non-english Visual Studio 2019 16.4 initialization/detection fails due to text locale.

### ISSUE THREAD

**Issue by lukaszgo1** [SCons/scons#3572]
**Describe the bug**
When Sconscript requires VS 2019 and you are still on Windows 7 it cannot be used. There are two problems:

- vcvarsall.bat calls powershell to send telemetry, however on Windows 7 Scons for some reason cannot find Powershell folder in the path, so it cannot be invoked. This causes popup letting the user know about this to appear.
- The message about Powershell not found is also written to sys.stderr or at least tries to be written there. On Python 3 sys.stderr requires string but subprocess returs bytes so the attempt at writing results in:

```console
TypeError: write() argument must be str, not bytes:
  File "D:\test\SConstruct", line 1:
    env = DefaultEnvironment(MSVC_VERSION="14.2", TARGET_ARCH="x86")
  File "c:\python37\lib\site-packages\scons\SCons\Defaults.py", line 88:
    _default_env = SCons.Environment.Environment(*args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 990:
    apply_tools(self, tools, toolpath)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 102:
    env.Tool(tool)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 1810:
    tool(self)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\__init__.py", line 303:
    self.generate(env, *args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\default.py", line 41:
    SCons.Tool.Tool(t)(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\__init__.py", line 303:
    self.generate(env, *args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\mslink.py", line 314:
    msvc_setup_env_once(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 695:
    msvc_setup_env(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 814:
    d = msvc_find_valid_batch_script(env,version)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 762:
    d = script_env(vc_script, args=arg)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 621:
    stdout = common.get_output(script, args)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\common.py", line 238:
    sys.stderr.write(stderr)
```

Curiously the same SConscript executed on Windows  10 with the same version of VS, Python and SCons works correctly. It is quite strange, because on both systems Powershell is located at C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

**Required information**
* Link to SCons Users thread discussing your issue.
https://pairlist4.pair.net/pipermail/scons-users/2019-December/007920.html
* Version of SCons
```console
SCons by Steven Knight et al.:
        script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
        engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
```
* Version of Python
Python 3.7.5 32-bit

* How you installed SCons
python -m pip install scons
* What Platform are you on? (Linux/Windows and which version)
Windows 7 and Windows 10, both x64
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.

```python
env = DefaultEnvironment(MSVC_VERSION="14.2", TARGET_ARCH="x86")
config_context = Configure(env)
```

* How you invoke scons (The command line you're using "scons --flags some_arguments")
just scons in the folder where my SConscript is located

**Comment by bdbaddog** [comment]
Did you try the latest dev build?
Try:
`pip install -i https://test.pypi.org/simple/ scons==3.9.9.dev20200227135436`

**Comment by lukaszgo1** [comment]
Still reproducible with latest dev version.

**Comment by mwichmann** [comment]
we were aware of some permutation of this problem - the irritating telemetry effort that apparently just turned up in one of the most recent VS2019 updates. Well, you've already quoted the mailing list mention of that.

Windows' idea of putting every executable in its own path, leading to endless amounts of path twiddling, is... unfortunate.  There's no point in my being further impolite about it, it is what it is.

The information scons mostly uses is obtained by asking - running a vcvars* batch script.  Suppose it's possible that somehow yields different answers on Win7? What else could be different? We'll need to lean on you for some help, I certainly don't have access to any Win7 machines...

**Comment by bdbaddog** [comment]
Try this:
at the top of c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\common.py
`from SCons.Util import to_String`

The at line 238 change to:
` sys.stderr.write(to_String(stderr))`

**Comment by bdbaddog** [comment]
Also sounds like we should have SCons define ```VSCMD_SKIP_SENDTELEMETRY```

**Comment by bdbaddog** [comment]
Adding URL from MS on this:
https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-experience-improvement-program?view=vs-2019
And this:
http://forum.doom9.org/showthread.php?t=177090

**Comment by lukaszgo1** [comment]
@bdbaddog wrote:
> Try this:
> at the top of c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\common.py
> `from SCons.Util import to_String`
> 
> The at line 238 change to:
> ` sys.stderr.write(to_String(stderr))`



This prevents typeError from occurring, however the error is still written as a binary. The following seems to produce the  actual string in a more readable form:
At the top of c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\common.py:
from ctypes import windll
and in line 238:
sys.stderr.write(stderr.decode("cp{}".format(windll.kernel32.GetConsoleOutputCP())))


Perhaps there is a more Pythonic way of getting current console code page that I do not know about?

**Comment by bdbaddog** [comment]
If you add `env['ENV']['VSCMD_SKIP_SENDTELEMETRY'] = 1` does this avoid the problem?

**Comment by bdbaddog** [comment]
@lukaszgo1 try running this when you're in powershell:

```
python -c "import sys; print(sys.stdout.encoding)"
(python -c "import sys; print(sys.stdout.encoding)")
python -c "import sys; print(sys.stderr.encoding)"
(python -c "import sys; print(sys.stderr.encoding)")
```

**Comment by bdbaddog** [comment]
also try adding `universal_newlines=True` to both `SCons.Action._subproc()` calls on line 213 and 220. And see if that helps.

**Comment by lukaszgo1** [comment]
@bdbaddog wrote:
> If you add `env['ENV']['VSCMD_SKIP_SENDTELEMETRY'] = 1` does this avoid the problem?


No, it does not. I've modified my SConscript as follows:

~~~
env = DefaultEnvironment(MSVC_VERSION="14.2", TARGET_ARCH="x86")
env['ENV']['VSCMD_SKIP_SENDTELEMETRY'] = 1
config_context = Configure(env)
~~~

I hope it is what you've asked for - I do not have much experience with SCons.

**Comment by lukaszgo1** [comment]
@bdbaddog wrote:
> @lukaszgo1 try running this when you're in powershell:
> 
> ```
> python -c "import sys; print(sys.stdout.encoding)"

The output is utf-8

> (python -c "import sys; print(sys.stdout.encoding)")

The output is cp1250

> python -c "import sys; print(sys.stderr.encoding)"

The output is utf-8

> (python -c "import sys; print(sys.stderr.encoding)")

The output is utf-8


None of these gives a real  code page of my console which is cp852, whereas the windll based solution does.

**Comment by lukaszgo1** [comment]
@bdbaddog wrote:
> also try adding `universal_newlines=True` to both `SCons.Action._subproc()` calls on line 213 and 220. And see if that helps.



The error about Powershell not being found is printed to the console, however the characters from outside ASCI are damaged. after that the following error is displayed:
```console
AttributeError: 'str' object has no attribute 'decode':
  File "D:\test\SConstruct", line 1:
    env = DefaultEnvironment(MSVC_VERSION="14.2", TARGET_ARCH="x86")
  File "c:\python37\lib\site-packages\scons\SCons\Defaults.py", line 86:
    _default_env = SCons.Environment.Environment(*args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 990:
    apply_tools(self, tools, toolpath)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 102:
    env.Tool(tool)
  File "c:\python37\lib\site-packages\scons\SCons\Environment.py", line 1810:
    tool(self)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\__init__.py", line 266:
    self.generate(env, *args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\default.py", line 41:
    SCons.Tool.Tool(t)(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\__init__.py", line 266:
    self.generate(env, *args, **kw)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\mslink.py", line 312:
    msvc_setup_env_once(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 743:
    msvc_setup_env(env)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 887:
    d = msvc_find_valid_batch_script(env,version)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 835:
    d = script_env(vc_script, args=arg)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 685:
    stdout = common.get_output(script, args)
  File "c:\python37\lib\site-packages\scons\SCons\Tool\MSCommon\common.py", line 248:
    output = stdout.decode("mbcs")
```

**Comment by mwichmann** [comment]
I suspect this applies: https://www.python.org/dev/peps/pep-0528/ (implemented since 3.6).

The section "Code that may break" specifically calls out examples, one of which is the same code as the failure just above. We have three places in SCons where we call out *mbcs* explicitly:
```
src/engine/SCons/Tool/MSCommon/common.py:        raise IOError(stderr.decode("mbcs"))
src/engine/SCons/Tool/MSCommon/common.py:    output = stdout.decode("mbcs")
src/engine/SCons/Tool/MSCommon/vc.py:        lines = cp.stdout.decode("mbcs").splitlines()
```

**Comment by mwichmann** [comment]
For more Windows code-page problems, see also the recent #3529. These may well be related - if nothing else than in indicating mishandling of test to/from commands via subprocess.

**Comment by mwichmann** [comment]
Just to confirm there may be a version-dependent aspect to some of this, since SCons still supports Python 3.5:
```
PS C:\WINDOWS\system32> py -3.5
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.stderr.encoding
'cp437'
>>> sys.stdout.encoding
'cp437'
>>> sys.stdin.encoding
'cp437'
>>> ^Z

PS C:\WINDOWS\system32> py -3.6
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> sys.stderr.encoding
'utf-8'
>>> sys.stdout.encoding
'utf-8'
>>> sys.stdin.encoding
'utf-8'
>>> ^Z
```

**Comment by bdbaddog** [comment]
You should do this:
`env = Environment(MSVC_VERSION="14.2", TARGET_ARCH="x86")`

Not this:
`env = DefaultEnvironment(MSVC_VERSION="14.2", TARGET_ARCH="x86")`

**Comment by bdbaddog** [comment]
Which location was set when you installed windows?

**Comment by bdbaddog** [comment]
Try this:

```
DefaultEnvironment(tools=[])
env = Environment(tools=[]MSVC_VERSION="14.2", TARGET_ARCH="x86")
env['ENV']['VSCMD_SKIP_SENDTELEMETRY'] = 1
env.Tool('msvc')
env.Tool('mslink')
config_context = Configure(env)
```

Your sample code was setting `VSCMD_SKIP_SENDTELEMETRY` after msvc had already been initialized.

**Comment by lukaszgo1** [comment]
@bdbaddog wrote:
> Which location was set when you installed windows?

My Windows is in Polish

**Comment by lukaszgo1** [comment]
The SConscript from your last commend does not help unfortunately - the error is the same as in my initial comment.

**Comment by mwichmann** [comment]
It would be interesting to experiment with #3576 and see if it helps - that change will propagate `VSCMD_SKIP_SENDTELEMETRY` if it is already set in the environment.

**Comment by lukaszgo1** [comment]
If i set VSCMD_SKIP_SENDTELEMETRY before executing SCons with code from #3576 everything works as it should, i.e no errors about Powershell being not found.

**Comment by bdbaddog** [comment]
> If i set VSCMD_SKIP_SENDTELEMETRY before executing SCons with code from #3576 everything works as it should, i.e no errors about Powershell being not found.

What if you don't set it in the shell before trying #3576 ?

**Comment by lukaszgo1** [comment]
@bdbaddog  wrote:
> > If i set VSCMD_SKIP_SENDTELEMETRY before executing SCons with code from #3576 everything works as it should, i.e no errors about Powershell being not found.
> 
> What if you don't set it in the shell before trying #3576 ?



The popub about Powershell being not found is displayed, the error  is also shown on the console, but the build continues.

**Comment by lukaszgo1** [comment]
I now know why it is not failing under Windows 10 but fails on Win 7.  (vcvarsall.bat is not calling Powershell directly when  VSCMD_DEBUG is not set but does it via start Command. For whatever reason if Powershell is not in the path start is still able to find it under Windows 10 but not on W7. For me  adding Powershell folder (that is C:\Windows\System32\WindowsPowerShell\v1.0\ ) to normalize_env fixes the problem. @mwichmann Would you be able to do this as part of #3576?  That and change of encoding for stderr from MBCS to OEM would fix this issue completely.

**Comment by mwichmann** [comment]
I'm pushing an update with the former (powershell path). The latter seems to suggest more should be done... there are several other instances where `mbcs` is used - I gather `mbcs` is not itself an encoding, but means use whatever the current multi-byte encoding is.   You'd think that would come out right, because whatever that encoding is, would be the one MSVC is emitting its messages in, and there should be no discrepancy.  I happen to believe this is the wrong approach anyway - subprocess defaults to bytes in the streams, I think we'd better off using text, then there would be no decoding, and thus no decoding to get wrong.

**Comment by lukaszgo1** [comment]
@mwichmann wrote:

> 
> I'm pushing an update with the former (powershell path). The latter seems to suggest more should be done... there are several other instances where `mbcs` is used - I gather `mbcs` is not itself an encoding, but means use whatever the current multi-byte encoding is. You'd think that would come out right, because whatever that encoding is, would be the one MSVC is emitting its messages in, and there should be no discrepancy.


The assumption that this is encoding in which MSVC emits its messages is wrong. MBCS is an alias to encoding used for non-Unicode programs in Windows, however it is not used in console at all. As MSVC emits its messages to the console OEM (which is an alias for currently set console code page) should be used IMO.

>  I happen to believe this is the wrong approach anyway - subprocess defaults to bytes in the streams, I think we'd better off using text, then there would be no decoding, and thus no decoding to get wrong.


Could you clarify what you're proposing here? Are you perhaps planning to replace subprocess calls with some other way of  calling these .bat files??

**Comment by mwichmann** [comment]
> Could you clarify what you're proposing here? Are you perhaps planning to replace subprocess calls with some other way of calling these .bat files??

`subprocess` called with text mode (which would be spelled `universal_newlines=True` since only the newest Pythons provide the `text=True` versions), so that Python doesn't deliver us bytes over the pipes.

**Comment by lukaszgo1** [comment]
Unfortunately universal_newlines decodes the text by default using MBCS under the hood so even though we would get string instead of bytes it still would be decoded with the wrong encoding.

**Comment by mwichmann** [comment]
Darn. So string handling remains completely broken on Python. Just broken differently than Python 2. ??

**Comment by bdbaddog** [comment]
> Darn. So string handling remains completely broken on Python. Just broken differently than Python 2. ??

I'm blaming this mess on Microsoft..

**Comment by lukaszgo1** [comment]
Given the fact how much of a mess this is I still believe that using OEM as an encoding in this case is a acceptable choice. It fixes the problem at hand, and other encoding problems  an be dealt with separately.

**Comment by bdbaddog** [comment]
The fix has been merged to master.
Closing.
If you find that the fix isn't sufficient please reopen with more info.
