### ISSUE TITLE
KeyError while trying to build ffado

### ISSUE THREAD

**Issue by sadko4u** [SCons/scons#3579]
**Describe the bug**
While trying to build ffado with latest SCons script, I get the following error:
```
KeyError: 'LIBRAW1394_FLAGS':
  File "/home/sadko/tmp/lv2/ffado/libffado/SConstruct", line 925:
    env.SConscript( dirs=subdirs, exports="env" )
  File "/usr/lib/python3.6/site-packages/scons/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib/python3.6/site-packages/scons/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/sadko/tmp/lv2/ffado/libffado/src/SConscript", line 287:
    libenv.MergeFlags( env['LIBRAW1394_FLAGS'].decode() )
  File "/usr/lib/python3.6/site-packages/scons/SCons/Environment.py", line 405:
    return self._dict[key]
```

**Required information**
* Version of SCons 
```
python3 `which scons` --version
SCons by Steven Knight et al.:
        script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
        engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
        engine path: ['/usr/lib/python3.6/site-packages/scons/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
```
* Version of Python
```
python3 --version
Python 3.6.10
```
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)

Standard python3 package from openSUSE repository

* How you installed SCons
```
pip3 install --upgrade scons
```
* What Platform are you on? (Linux/Windows and which version)
```
openSUSE Linux 15.1
```
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
```
svn checkout http://subversion.ffado.org/ffado/trunk/libffado
mv build.sh libffado/
cd libffado
./build.sh
```
* How you invoke scons (The command line you're using "scons --flags some_arguments")
```
cat build.sh 
#!/bin/bash

export SCONS="python3 `which scons`"

echo $SCONS

export LIBRAW1394_FLAGS=-O2

$SCONS -c
$SCONS --config=force -j 8 \
    PREFIX=/usr \
    LIBDIR=/usr/lib64 \
    MANDIR=/usr/share/man \
    UDEVDIR=/usr/lib/udev/rules.d \
    ENABLE_GENERICAVC=yes \
    SERIALIZE_USE_EXPAT=no \
    DEBUG=no \
    ENABLE_ALL=yes \
    PYPKGDIR=/usr/lib/python3.6/site-packages \
    ENABLE_OPTIMIZATIONS=yes \
    ENABLE_SETBUFFERSIZE_API_VER=auto \
    BUILD_TESTS=yes \
    ENABLE_DICE=true \
    COMPILE_FLAGS='-O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -fno-strict-aliasing -ggdb -Wno-deprecated-declarations --std=gnu++11' \
    LIBRAW1394_FLAGS=-O2 \
    CUSTOM_ENV=True
```

**Comment by bdbaddog** [comment]
This is not a SCons bug. Please check with whatever project produces ffado.

Here's a pointer to their mailing lists.. http://ffado.org/?q=contact

**Comment by sadko4u** [comment]
It seems that scons changed behaviour of this piece of code:
```
env = conf.Finish()
```

FFADO developers admit that on their build system previously defined environment variables keep living in the build system. In my case, not. Here's detailed description of the problem sent to the FFADO mailing list from my side:

Let me explain again why this line is illegal.
Let's look into SConstruct script. Here we're detecting C++ flags to use for specific libraries:
```
     pkgs = {
         'libraw1394' : '2.0.5',
         'libiec61883' : '1.1.0',
         'libconfig++' : '0'
         }

     if env['REQUIRE_LIBAVC']:
         pkgs['libavc1394'] = '0.5.3'

     if not env['SERIALIZE_USE_EXPAT']:
         if conf.CheckPKG('libxml++-3.0'):
             pkgs['libxml++-3.0'] = '3.0.0'
         if not('libxml++-3.0' in pkgs):
             pkgs['libxml++-2.6'] = '2.13.0'
```

Then, we're saving these flags into environment variables:
```
     for pkg in pkgs:
         name2 = pkg.replace("+","").replace(".","").replace("-","").upper()
         env['%s_FLAGS' % name2] = conf.GetPKGFlags( pkg, pkgs[pkg] )
         print('%s_FLAGS = %s' % (name2, env['%s_FLAGS' % name2].decode())) # This line added by me for debug
         if env['%s_FLAGS'%name2] == 0:
             allpresent &= 0
```

The code below outputs the line:
```
 LIBRAW1394_FLAGS = -lraw1394
```

And then we're omitting these flags just by rewriting environment:
```
config_guess = conf.ConfigGuess()

env = conf.Finish()
```

Then we call the nested src/SConstruct script:
```
 subdirs=['src','libffado','support','doc']
 if env['BUILD_TESTS']:
     subdirs.append('tests')

 print("!!!!!!!! %s\n" % (env.Dump())) # Added by me for debug

 env.SConscript( dirs=subdirs, exports="env" )
```

The code shows that there is no LIBRAW1394_FLAGS variable in environment more.
And in src/SConstruct we try to reuse it:
```
 libenv = env.Clone()
 #...
 if not env.GetOption( "clean" ):
     libenv.MergeFlags( "-lrt -lpthread" )
     libenv.MergeFlags( env['LIBRAW1394_FLAGS'].decode() ) # BOOM!
     libenv.MergeFlags( env['LIBIEC61883_FLAGS'].decode() )
     libenv.MergeFlags( env['LIBCONFIG_FLAGS'].decode() )
```

Finally, the build crashes with error:
```
 KeyError: 'LIBRAW1394_FLAGS':
   File "/home/sadko/tmp/lv2/ffado/libffado/SConstruct", line 925:
     env.SConscript( dirs=subdirs, exports="env" )
   File "/usr/lib/python3.6/site-packages/scons/SCons/Script/SConscript.py", line 597:
     return _SConscript(self.fs, *files, **subst_kw)
   File "/usr/lib/python3.6/site-packages/scons/SCons/Script/SConscript.py", line 286:
     exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
   File "/home/sadko/tmp/lv2/ffado/libffado/src/SConscript", line 287:
     libenv.MergeFlags( env['LIBRAW1394_FLAGS'].decode() )
   File "/usr/lib/python3.6/site-packages/scons/SCons/Environment.py", line 405:
     return self._dict[key]
```
So we have improperly working build script with ridiculous behaviour.

@bdbaddog Any suggestions from your side?

**Comment by mwichmann** [comment]
Certainly you can stop crashing by doing `env.get(key, default`) rather than `env[key]`.  But presumably you actually care about why the key isn't in the env any longer.

What is `ConfigGuess`?

And why all the `.decode()`?

**Comment by sadko4u** [comment]
> Certainly you can stop crashing by doing `env.get(key, default`) rather than `env[key]`.

I did it first, the code didn't compile because C++ was lacking additional compilation keys that define location of libraries and headers because... these environment variables vere empty.

> But presumably you actually care about why the key isn't in the env any longer.

It should be there. Because key are initialized in the root script and then removed by this call:
```
env = conf.Finish()
```

> What is `ConfigGuess`?

I don't know. I believe it is a standard API? Anyway, it doesn't affect the result. The problem is in the ```conf.Finish()``` which returns enviromnent with removed keys.

**Comment by mwichmann** [comment]
`context.ConfigGuess` isn't part of the scons API. Presumably it's part of FFADO?  Wondering if that's the cause of any of the issues?

**Comment by sadko4u** [comment]
I need to check it. Will write a bit later about results.

**Comment by sadko4u** [comment]
Ah, no. I don't need to check. When I commented out ```env = conf.Finish()``` line yesterday, the build worked without any problems.

**Comment by bdbaddog** [comment]
Whatever the issue is with ConfigGuess should be resolved and pushed back to ffado.
Also as @mwichmann said.. why all the .decode()'s?

**Comment by sadko4u** [comment]
@bdbaddog @mwichmann 
Are you kidding? Here's the code from the repository I've provided in the first post:
```
def ConfigGuess( context ):
    context.Message( "Trying to find the system triple: " )
    ret = check_output(("/bin/sh", "admin/config.guess")).rstrip()
    context.Result( ret )
    return ret.decode()
```
I doubt that it should crash the build script.

By the other side, I see the real cause of the problem:
```
env = conf.Finish()
```

Before this call **env** variable contained **LIBRAW1394_FLAGS** key, after - __NOT__.
**REMOVING** this line from the build script **HAS SOLVED** the issue and ffado has been built successfully.

> why all the .decode()

Please don't engage me into nit picking. I'm not an FFADO developer. Moreover, I'm not a python developer. I'm a regular FFADO user who felt the whole bunch of pain after upgrading the system which replaced python2 with python3 and scons2 with scons3. Anyway, this code with '.decode()' works. The code line I've mentioned **THREE** times in different posts to this topic - not.

**Comment by bdbaddog** [comment]
@sadko4u - You're welcome for the help we've provided you in debugging a build system created by another project. Good luck with your future usage.

**Comment by mwichmann** [comment]
Okay, this makes more sense now: when you create a configure context, you give it the environment that should be modified within the context.  When you call Finish on it, it returns the (possibly) modified environment.  The line in question replaces the original `env` with the returned environment, so the original `env` is lost:
```
env = conf.Finish()
```
So I guess the problem is somebody doesn't understand that if you're going to modify the configure context's environment manually during the configure steps, you need to write to *it* - the snips you originally included show it writing to `env` rather than `conf.env`, and of course those changes go away when `env` is rewritten with the return from `Finish`.

**Comment by sadko4u** [comment]
@bdbaddog @mwichmann 
Your help is useless. You even didn't try to reproduce the case or look at the build command. You even didn't try to look into **YOUR** ```conf.Finish()``` method or find the regression version or even tell what's wrong in my build call.

The solution:
>I've found that regression occurred when changing from 3.0.4 version to 3.0.5. I've inspected the changes in the SConf.py::_shutdown method and **ONLY THEN** found that the option ```--config=force``` was the case. Removing it solved the problem.

Instead of doing right job, you:
1. Immediately closed the topic without any try to check/reproduce the problem or even performing any code review of the build call.
2. Blamed the build script which has not changed since first FFADO releases (at least, problem part).
3. Both tried to involve me into nit picking and discussing about necessity of the **.decode()** call instead of solving the actual problem I've described.

I will recommend FFADO (and any other projects using scons) to drop scons build system from the code tree since it has inadequate maintenance and support.

Shame on you.

**Comment by bdbaddog** [comment]
@sadko4u - First you didn't follow the instructions in the issue template to contract us on the mailing list and follow our requested bug flow..

```## Please bring your issue to the SCons users mailing list before filing an issue here
## See: https://scons.org/bugs.html
```

Also we ask for a **"Please include a small self contained reproducer."** which is never meant to be download this entire project and try to build it.  Small is the active word.
No where did you indicate that scons was being called with the ```--config=force``` command.

Note the CHANGES.txt does indicate some changes related to --config=force here: 
https://github.com/SCons/scons/blob/master/src/CHANGES.txt#L274

Second we sent you back to the project who's implemented the build. (would you file a bug against gcc if you had a problem compiling their source code?)

Now you're berating the project for sending you to the sources which are most likely to understand the build you're having problems with?

**NO ONE ON THIS PROJECT GETS PAID TO SUPPORT.**

We have limited time to support and fix bugs and add new features and work on performance and work on infrastructure for the project.  

The amount of time it takes to look at any non-trivial projects SCons implementation is.. NON-TRIVIAL. 

That's why we ask for a **SMALL** reproducer.

In the end the issue is that the ffado project hasn't tried a newer version of SCons and resolve the issue found.   

Sounds like they passed env to Configure(), altered env, then assigned env the value returned from Configure() and expected the value set in the middle to not be overwritten. 

And people ask why open source maintainers burn out..

By and large we do the best we can and try to prioritize how we spend the time we have available to do the most good for the project.

Regardless good luck with your software endeavors.
