### ISSUE TITLE
Provide Docker containers for building/releasing and testing SCons

### ISSUE THREAD

**Issue by dirkbaechle** [SCons/scons#3585]
This issue adds Dockerfiles to a new top-level folder `docker`. Based on a current Ubuntu 19.10, each image shall have the required packages installed as given in the setup script `bin/scons_dev_master.py`.

The idea here is **not** to push these Docker images to _Docker Hub_ (hub.docker.com) directly, but that each developer creates and keeps them local on his machine.
As an addition to the `bin/scons_dev_master.py` script, these Docker containers can provide clean and reproducible environments for the tasks of building and testing an SCons version during the development process.

In order to make this all easier for people that are new to Docker, a short quickstart document and READMEs for the single images `build` and `test` are added.

The basics of this feature request were also discussed on the Discord channel "devel".

**Comment by techtonik** [comment]
Hi Dirk. I haven't seen SCons in a long time. Is it still self-contained Python that I can just drop into my repo without any additional `pip install` and stuff?

**Comment by mwichmann** [comment]
@techtonik you can run it right from the scons source tree (`python3 scons/src/script/scons.py`) if you use a git checkout, or from an unpacked local-install release (`python3 scons-local/scons-local-3.1.2/scons.py`), both without doing any kind of "install" stuff.

**Comment by bdbaddog** [comment]
> Hi Dirk. I haven't seen SCons in a long time. Is it still self-contained Python that I can just drop into my repo without any additional `pip install` and stuff?

Yes. the scons-local distribution (unpack and run in place) package is still and will be supported going forward.
