### ISSUE TITLE
Port to Jython

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#359]
This issue was originally created at: 2002-12-06 02:03:04.
This issue was reported by: `stevenknight`.
stevenknight said at 2002-12-06 02:03:04
>Support running SCons under Jython, ideally from the
>same code base (that is, not a separate version).

issues@scons said at 2002-12-06 02:03:04
>Converted from SourceForge tracker item 649449

garyo said at 2008-03-17 18:37:15
>nice project for someday.  GSoC maybe.

**Comment by mwichmann** [comment]
This seems quite unlikely now. SCons is irrevocably Python 3+, and Jython shows no signs of a 3.x version actually happening. Maybe close and let someone reopen to show if there's actual demand?

**Comment by bdbaddog** [comment]
Jython's a non-started currently for python 3.x. so closing.
Please re-open if there's a viable 3.x Jython, and someone is interested in doing the work..
