### ISSUE TITLE
Ship LICENSE.txt and name the license in PKG-INFO

### ISSUE THREAD

**Issue by stuertz** [SCons/scons#3598]
The package distributed via pypi does not contain any license information.

* The `LICENSE.txt` from the repo is missing in the .tar.gz from pypi
* The PKG-INFO files (2)  lists `UNKNOWN` as license

**Comment by jakirkham** [comment]
Maybe it’s a typo? There is [a `LICENSE` file]( https://github.com/SCons/scons/blob/master/LICENSE )

**Comment by stuertz** [comment]
Yep.  I have seen that and wondered myself. But the tar.gz from pypi doesn't have that file. They missed to pack it via MANIFEST or setup.py or ...

I tried using the tar.gz from github scons releases, but this is outdated: https://github.com/SCons/scons/releases

And i wonder whether the conda update mechanisms would work if we chose any other ource for the package.

**Comment by stuertz** [comment]
OTOH we could make a copy of that LICENSE file - But i'm not sure wheter this is a good idea. As mentioned in the issue above, the pypi metadata is alos misleading, saying that license is unknown.

**Comment by mwichmann** [comment]
The packaging is being uplifted to use modern Python technologies, and there's a proposed `setup.cfg` that fillis in the missing bits of metadata. Don't know if that's pushed as a PR yet, but it's coming.

**Comment by bdbaddog** [comment]
I'll push one today to testpypi and add a note here when I do.

**Comment by bdbaddog** [comment]
Please take a look at the packages here:
https://test.pypi.org/project/SCons/3.9.9a99/

**Comment by jakirkham** [comment]
It looks like the wheel (`.whl`) has it, but the `sdist` ( `.tar.gz`  ) doesn't.

Is there a particular PR you used to make this change? If so, might be able to advise over there on how to package the license file in both cases.

**Comment by bdbaddog** [comment]
No PR yet..  It's a work in progress branch.
Here's the branch.
https://github.com/bdbaddog/scons/tree/revamp_scons_build

**Comment by jakirkham** [comment]
Thanks. Would suggest adding `include src/LICENSE.txt` to `MANIFEST.in` [like so]( https://github.com/pypa/sampleproject/blob/d09af3dbd851d385e56f0aed29875bfa3d3df230/MANIFEST.in#L6-L7 ). That should include it in the `sdist` 🙂

**Comment by bdbaddog** [comment]
Try:
https://test.pypi.org/project/SCons/3.9.9a991/

**Comment by jakirkham** [comment]
LGTM. Thanks! 😄

**Comment by bdbaddog** [comment]
No problemo. 
If you see any other issues with the packaging, please let us know!

**Comment by bdbaddog** [comment]
Will be fixed in 4.0.0 release

**Comment by mwichmann** [comment]
Looking at the link, https://test.pypi.org/project/SCons/3.9.9a991/, I'm happy to see the classifiers showing up like they don't for the released versions: https://pypi.org/project/scons/.

Is there anything missing that should be here?

**Comment by bdbaddog** [comment]
This fix has been merged to master. Closing.
