### ISSUE TITLE
Programmatically expose all SConstruct/SConscript files used in the build.

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3625]
**Describe the Feature**

This request is driven by work on our Ninja builder for SCons. The Ninja builder needs to declare that the generated build.ninja file have a dependency on SConstruct and all the SConscripts, so that we can detect when the build.ninja file should be regenerated, because the structure of the build as described by SCons has changed.

Currently, we do this by globbing for such files, but this is not a great long term solution. In particular, env.SConscript allows the scripts to be named something other than SConscript, so if we want our Ninja tool to be truly generic, it shouldn't rely on filenames and globbing to do this work.

There are some tricky questions with this one, specifically, with how the phases of SCons execution would populate this vs when the Ninja backend would need access to the list.

Still, if there is still general interest in moving forward with getting the MongoDB Ninja generator upstreamed into SCons, some more robust solution to identifying the SCons files in play will be needed.

**Required information**
* Link to SCons Users thread discussing your issue.
https://pairlist4.pair.net/pipermail/scons-users/2020-April/008072.html

**Comment by bdbaddog** [comment]
Does this include site_scons files as well?

**Comment by acmorrow** [comment]
It is a great question and I can see arguments both ways. For SCons builds, any site_scons changes only cause a rebuild if they actually lead to a change in what/how things should be built. Ditto any changes to SConscripts or SConstruct. For Ninja, we just hard cause a regeneration if any of these files are out of date, but if the newly generated Ninja file doesn't change how any targets would be built, Ninja will consider them up to date. So I think that it would be preferable if site_scons loaded files were considered. This would, in effect, result in all of the built-in SCons tools being considered as well, right? So it would also probably capture a SCons upgrade as triggering a rebuild, which seems desirable.

**Comment by bdbaddog** [comment]
Fixed in #3670
