### ISSUE TITLE
Scons Documentation: ARCOMSTR

### ISSUE THREAD

**Issue by lurobi** [SCons/scons#3636]
In the [Scons User documentation Appendix A](https://scons.org/doc/latest/HTML/scons-user/apa.html#cv-ARCOMSTR)

The text describing ARCOMSTR seems to be a near-copy of the ASCOMSTR, while infact ASCOM is for compiling assembly and ARCOM is for building a library form object files.

The following is more consistent with ARCOM's description:

```
The string displayed when a static library is
generated from object files. If this is not set,
then $ARCOM (the command line) is displayed.
```

**Comment by mwichmann** [comment]
you're undoubtedly right. I've fixed more than one other copypasta of this type over the last few months.
