### ISSUE TITLE
Importing SCons is hard

### ISSUE THREAD

**Issue by shouldsee** [SCons/scons#3644]
Version: 3.0.5a2

As a pytthon module, I cannot `import SCons` directly after package installation. This is because the weird pacakge hierarchy after `pip install`
```
scons
└── SCons
    ├── __init__.py
```

My current workaround is to link the `SCons` folder back to the same level as SCons, but this seems a dirty solution. Is there a plan for improvement? I would like to write pure python script using scon as a module instead of scon-runnable python scripts.

After linking:
```
scons
└── SCons
    ├── __init__.py
SCons
└──  __init__.py
``````

**Comment by bdbaddog** [comment]
Importing SCons and using that way is not supported.

**Comment by shouldsee** [comment]
> Importing SCons and using that way is not supported.

is there a good reason?

**Comment by bdbaddog** [comment]
It was never designed to be used that way.
And so is not reasonably easy to support that usage.
Also why even try using 3.0.5a2 <- a2 = alpha release.

We have high enough support needs as is without adding other use models.

**Comment by shouldsee** [comment]
Got you! Basically this would create too much maintainence burden right?

Used a2 because it's the highest in the releases

**Comment by bdbaddog** [comment]
It's not the highest. 3.1.2 was released a while back.
Where are you looking for releases.
Did you look at the scons.org website?
If you have further questions. Please go to our discord channel. https://discord.gg/bXVpWAy
I

**Comment by shouldsee** [comment]
I looked at github releases page. 

I will go ahead to `import SCons` and write my build scripts for now. Don't worry about supporting. Such usage should help with the API documentatoin anyway since python-script will be more verbose than scon-script.

**Comment by bdbaddog** [comment]
Here's the official release page: https://scons.org/tag/releases.html
We don't release through github.
Also it's available through pypi (pip install)

SConscripts' are python.

**Comment by shouldsee** [comment]
Thanks for the info. It'd be great to add  https://scons.org/tag/releases.html to README.md. 

From a *personal* view, if one cannot run a script through `python SConscript`, then it's difficult to claim it is a python script. Free to discuss on this.

**Comment by mwichmann** [comment]
It's not a Python module. It's a program written in Python which is configured (and extended) using a scripting language which happens to be Python. An sconscript is not a Python program; it's a script which is evaluated in the context of SCons.  That said, you _can_ import scons - the manpage lists examples of doing so for some cases where it is necessary - when a Python script will be called without being in the context of SCons:
```
from SCons.Script import *
```
It might be helpful to understand what you are trying to do that requires importing it.

**Comment by shouldsee** [comment]
I was really just trying to use `scons` for clang before following the guide carefully. The result is a somewhat runable `build.py`

```python
import sys
from SCons.Script import (Program,Environment)
import SCons.Script

def _main_scons():
	if '--file' not in sys.argv:
		sys.argv.extend(['--file',__file__])
	SCons.Script.main()	

### use Action to create new node?
env = Environment(CC='gcc',)
Program('bar','foo.c')

if __name__ == '__main__':
	_main_scons()
```

And I was also trying to understand the `Environment(tools=['clang','link'])` statement in one of the example, by looking at the traceback. The concoulsion is that `tools` is somewhat synonymous to `plugin`, because "link" get intepreted and expanded to a Builder in `SCons.Tool`. 

The biggest difficulty I am getting is the fact that the number of keywords/vocabulary that needs to be learned before I can write SConscript, such as `Program`, `Environment`, `Action`. Each of this is almost a small program on its own with interwined dependency between modules, though at the very end of the day they get expanded into some kind of shell expression. I am basically struggling because the deep blackbox layer between `domain-specific keywod <--> shell expression`, that is, I know what shell expression to write, but I don't know what keyword I should pick to get expanded into what I want.

The original motivation is to find a python alternative to gnu-make to manage compilation flags and source files and do tests. After 1.5hr of twiddling with SCons I decided the amount of exttra keyword cannot be easily managed quickly. Thus I switched to write some adaptor class for `luigi` and mimic the gnu-make behaviour in a light-weight monkey package https://github.com/shouldsee/luck . I hope that repo would explain my intention. I did not understand the intention of SCons at the first glance and assumed it to be similar to gnu-make. That proves wrong. SCons appear to be a massive templating and expansion machine with many presets, and its function is more high-level than Makefile statements.

Anyway, good luck with the package! It's good to see at least people are actively using and maintaining this package. I am looking forward to a shiny new documentation that would reintroduce SCons.

Good Luck!
Feng

**Comment by bdbaddog** [comment]
62 thousand downloads a month say it's usable.
Good luck with your pursuits.
If you would take the time to read the users guide, perhaps you'd see it's not really that complicated.

**Comment by shouldsee** [comment]
Second thought: does SConscript eliminated the `import` statements for portability?

**Comment by mwichmann** [comment]
Not sure understanding the question.  An SConscript doesn't need to import scons, because it is run in the context of scons - all the scons symbols are already in the namespace, and those of the sconscript are then added.  Any other python modules the sconscript wants to use, it does have to import. The example you wrote above would make a two-line SConstruct because of that:
```
env = Environment(CC='gcc',)
Program('bar','foo.c')
```

**Comment by shouldsee** [comment]
@mwichmann  You are absolutely right. Learning SCons is about learning the effect of invoking `Environment` and `Program` and other things, which are embedded deep down in the source code.

**Comment by bdbaddog** [comment]
This is not the channel to ask for non-recommended usage. Please read the docs and the source and good luck to you.
