### ISSUE TITLE
Remove 'python' tool from default tool list. Add docs.

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3646]
**Describe the bug**
While the python tool is new and useful, it's likely to break existing builds which are currently functional.
For now remove from default tool list.
Also there's no info on the python builder in the manpage.

**Comment by mwichmann** [comment]
The manpage info should just be a regen issue, there's a python.xml which has the <secs tool> incantation.

**Comment by mwichmann** [comment]
Indeed, confirmed: there is generated content in `doc/generated/tools.{gen,mod}` if you build the generated docs from current sources. That will appear in both the manpage and the user guide. I see a slight tweak needed to the wording (it says "scanner scanner")

**Comment by mwichmann** [comment]
See #3647 - should address this.

**Comment by bdbaddog** [comment]
Yes. PR #3647 resolves this.
