### ISSUE TITLE
Users callables can have silent TypeError exceptions

### ISSUE THREAD

**Issue by dmoody256** [SCons/scons#3654]
Users are able to supply there own callable classes and put them into environment commands as expandable strings. If a user expereinces a TypeError exception in there __call__ method, it will silently be passed over, because scons is catching the TypeError to determine if the callable is not matching the function signature expected.

Example SConstruct:
```
import os
class TestPathIssue(object):
    def __init__(self, thing, makePathsRelative = True, debug = False):
        pass
    def __call__(self, target, source, env, for_signature):
        class FakeClass(object):
            pass
        # simulate the exception
        fake = FakeClass()
        os.path.splitdrive(fake)

env = Environment()
env["TESTCLASS"] = TestPathIssue
env["CCCOM"] = "$CC $_CCCOMCOM $CCFLAGS -o ${TESTCLASS('$TARGET')} -c ${TESTCLASS('$SOURCES')}"

env.Program(target='foo', source='foo.c')
```
results in this failure:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o <SCons.Script.TestPathIssue object at 0x7fa562bfada0> -c <SCons.Script.TestPathIssue object at 0x7fa562bfaa90>
sh: 1: Syntax error: end of file unexpected
scons: *** [foo.o] Error 2
```

I would expect to see my exception from my callable.

**Required information**
* Link to SCons Users thread discussing your issue.
https://pairlist4.pair.net/pipermail/scons-users/2020-May/008149.html

* Version of SCons
3.1.2

* Version of Python
2.7 and 3.6

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)\
python.org

* How you installed SCons
pip

* What Platform are you on? (Linux/Windows and which version)
Linux

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
See example at top

* How you invoke scons (The command line you're using "scons --flags some_arguments")
scons

**Comment by acmorrow** [comment]
@dmoody256 - Thanks for fixing this. It has burned me several times and I always failed to follow through with a ticket.
