### ISSUE TITLE
stale link on wiki to old scons_csharp repo

### ISSUE THREAD

**Issue by hernot** [SCons/scons#3681]
It seems as if the link to the repo of the scons_csharp project ([https://bitbucket.org/russel/scons_csharp](https://bitbucket.org/russel/scons_csharp)) mentioned on the corresponding scons wiki pages is stale.

[https://github.com/SCons/scons/wiki/ToolsIndex](https://github.com/SCons/scons/wiki/ToolsIndex)
[https://github.com/SCons/scons/wiki/CsharpBuilder](https://github.com/SCons/scons/wiki/CsharpBuilder)
 
The project initially started and maintained by russel but his BitBucket page does not contain anymore any repo called scons_scharp. seems as if the repo was moved to either other maintainer or other versioning system but the links were never updated.

**Comment by bdbaddog** [comment]
@russel - Do you still have the repo somewhere? Can we put it in scons-contrib? Or a separate SCons owned repo

**Comment by russel** [comment]
@bdbaddog Of course I have a local copy of the repository! I was awaiting doing anything about the repositories "lost" due to the destruction of BitBucket on requests to do so simply to find out which ones were really valuable. Given this request it makes sense to do something about this one.

Clearly the material could go into scons-contrib or it could go into a GitLab (or GitHub?) repository. In either case it is probably best that I not be the sole owner. Personally I'd be up for it being a separate Git repository owned by the SCons organisation.

**Comment by bdbaddog** [comment]
@russel - would adding them to https://github.com/SCons/scons-contrib make the most sense?

I'm not sure if there's useful history in your repo or if you think just adding a snapshot of the current code is good enough?
You should be able to make pull requests against that repo

**Comment by russel** [comment]
I'll get this sorted tomorrow adding the latest version into scons-contrib – I can't think of anything useful in the history.

**Comment by bdbaddog** [comment]
@russel - can you push all your various scons builders there? I know bitbucket's mercurial repos are gonna get wiped out before too long.

**Comment by russel** [comment]
As an experiment I have started with the C# builder. If this works reasonably, I'll progress with all the others. See https://github.com/SCons/scons-contrib/pull/4

**Comment by bdbaddog** [comment]
@russel  - do you have a readme for the c# builder?

**Comment by bdbaddog** [comment]
@hernot Links are updated on the two wiki pages. Please confirm and then close this issue

**Comment by russel** [comment]
@bdbaddog  The README that was there is so focused on the BitBucket repository I chose not to add it at this stage. Is there a sample README to follow in style and structure?
BTW In the end I never did any C# work so I am not a good maintainer for this SCons tool.

**Comment by bdbaddog** [comment]
@russel - no worries. at least the code is a starting point for anyone who wants to move it forward.  If you have a readme, maybe add it, and just put a big Bold banner at the top that this info is obsolete.

**Comment by hernot** [comment]
Ok thanks for the quick response and solution. Now i can proceed in evaluating Scons for my purposes and hopefully contribute back something in not so short time.
