### ISSUE TITLE
What is the SConstruct file?

### ISSUE THREAD

**Issue by domgutier** [SCons/scons#3689]
After running python scons/scons.py
I see
scons: *** No SConstruct file found.
File "/data1/user/scons/scons-local-3.1.1/SCons/Script/Main.py", line 933, in _main

**Comment by bdbaddog** [comment]
This is not an issue. 
Please bring your requests for help to:

- discord server https://discord.gg/bXVpWAy 
- IRC channel (#scons on freenode
- or the users mailing list. https://scons.org/lists.html#users
