### ISSUE TITLE
CompilationDatabase tool emits a field called `target` which should be called `output`

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3693]
**Describe the bug**
With the new integrated SCons compilation database support, there is a field called `target` in the resulting file:

```
"target": "build/cached/third_party/s2/base/int128.dyn.o"
```

Per the compilation database documentation, it seems this field should instead be called `output`:

https://clang.llvm.org/docs/JSONCompilationDatabase.html#format

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed directly with @bdbaddog 

* Version of SCons
master

* Version of Python
3.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
* How you installed SCons
Using it from source

* What Platform are you on? (Linux/Windows and which version)
macOS, but it shouldn't matter.

**Comment by bdbaddog** [comment]
@ivankravets - Thoughts on naming of target field. I think this came from PlatformIO's code?

**Comment by ivankravets** [comment]
@bdbaddog No, we don't use `output` field. See

- https://github.com/platformio/platformio-core/blob/develop/platformio/builder/tools/compilation_db.py#L138
- https://github.com/mongodb/mongo/blob/master/site_scons/site_tools/compilation_db.py#L128
