### ISSUE TITLE
CompilationDatabase tool emits paths into variant directories for source files when not using absolute paths.

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#3694]
**Describe the bug**
When using the CompilationDatabase tool with `COMPILATIONDB_USE_ABSPATH` == False, the `file` field appears to refer into the variant directory, not the source directory:

`"file": "build/cached/third_party/s2/base/int128.cc",`

Instead of 

`"file": "src/third_party/s2/base/int128.cc"`

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed directly with @bdbaddog 

* Version of SCons
master

* Version of Python
3.7

* How you installed SCons
source

* What Platform are you on? (Linux/Windows and which version)
macOS, but shouldn't matter.

**Comment by bdbaddog** [comment]
@acmorrow  - So you'd expect the source file to point to source of variantdir, but target to point to variant dir itself?

**Comment by acmorrow** [comment]
@bdbaddog - I'm not following you there. The error is in the `file` field of the JSON result. It is referring to a source file by a path into the variant directory. That would only be true if you were building with `duplicate=1` or similar. The `file` field should have the path to the source file where it lives on disk. I'm not sure what you mean by "target to point to variant dir itself".

**Comment by bdbaddog** [comment]
@acmorrow like this
```
% cat compile_commands.json
[
    {
        "command": "/Users/bdbaddog/.virtualenvs/scons37/bin/python mygcc.py cc -o build/test_main.o -c build/test_main.c",
        "directory": "/private/var/folders/ng/48pttrpj239fw5rmm3x65pxr0000gn/T/testcmd.32413.myyo97s5",
        "file": "src/test_main.c",
        "output": "build/test_main.o"
    }
]%
```

**Comment by acmorrow** [comment]
Yes, that looks like what I would expect for `command`, `directory`, and `file`. If you provide a fix that adjusts that, I'll re-run my experiment to A/B compare against the MongoDB one and see that the output is now aligned.

Regarding the `output` field: I wonder. I'm not sure if it is actually supposed to be a path or not. The "spec" doesn't really say: it says it should be "The name of the output created by this compilation step". Does that include the path? Who knows?

**Comment by bdbaddog** [comment]
I'm sure once we release it we'll get feedback.. ;)
Adding a test for variant_dir with duplicate = True and False..

**Comment by acmorrow** [comment]
@bdbaddog - I pulled this and redid the A/B test vs the MongoDB version. Looks great! As discussed elsewhere, the `output` field is new and I'm not sure the spec really tells us enough to know what ought to go there: a filename or a path. Either way, if there is someone out there for whom it matters, I think they will let us know if we have it wrong.
