### ISSUE TITLE
Code in SCons.Node.FS.File.get_csig() checking md5_chunksize is not correct

### ISSUE THREAD

**Issue by grossag** [SCons/scons#3726]
A coworker noticed today that the code:

`if self.get_size() < File.md5_chunksize:`

is not correct because md5_chunksize is in kilobytes, not bytes. I don't have a good test case, but I'm filing this against myself to track fixing it after finding a good test case.

**Comment by bdbaddog** [comment]
You ignored the request to bring the issue to the discord/irc/mailing list before posting..
