### ISSUE TITLE
Test run on AIX fails with 'f95 not found`

### ISSUE THREAD

**Issue by datalogics-robb** [SCons/scons#3740]
## Test failures under AIX 6.1 and 7.1

https://gist.github.com/datalogics-robb/3e431b5569cf52566595ec33f86b6dec

**Required information**
* Link to SCons Users thread discussing your issue.
* Version of SCons: [PR 3739](https://github.com/SCons/scons/pull/3739)
* Version of Python: 3.7.6
* How you installed SCons - test run from git checkout
* What Platform are you on? AIX 6.1 and 7.1 both demonstrated the issue
* How to reproduce your issue? 
  1) Clone my fork of Scons, check out the branch for PR 3739
  2) Run `python3 runtest.py test/CPPFLAGS.py` on an AIX platform

[full log](https://gist.github.com/datalogics-robb/3e431b5569cf52566595ec33f86b6dec)

```
robb@nepal:/raid/checkouts-raid/robb/AIX-scons/scons (unix_py3_str)$ git fetch upstream
robb@nepal:/raid/checkouts-raid/robb/AIX-scons/scons (unix_py3_str)$ python3 runtest.py test/CPPFLAGS.py 
1/1 (100.00%) /opt/Python-3.7/bin/python3 test/CPPFLAGS.py
/raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py returned 2
STDOUT =========================================================================
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/opt/Python-3.7/bin/python3 mygcc.py cc -o test1.shobj -c -x test1.c
/opt/Python-3.7/bin/python3 mygcc.py c++ -o test2.shobj -c -x test2.cpp
f95 -o test3.shobj -c -x test3.F
scons: building terminated because of errors.

STDERR =========================================================================
sh: f95:  not found
scons: *** [test3.shobj] Error 127

FAILED test of /raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py
        at line 621 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestCommon.py (_complete)
        from line 724 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestCommon.py (run)
        from line 427 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestSCons.py (run)
        from line 124 of test/CPPFLAGS.py
```

**Comment by datalogics-robb** [comment]
It's only the second run that generates "shobj" files that fails.

```
robb@nepal:/raid/checkouts-raid/robb/AIX-scons/scons (master)$  python3 runtest.py --verbose=3 test/CPPFLAGS.py 
1/1 (100.00%) /opt/Python-3.7/bin/python3 test/CPPFLAGS.py
/opt/Python-3.7/bin/python3 /raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py .
============ STATUS: 0
============ BEGIN STDOUT (len=416):
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/opt/Python-3.7/bin/python3 mygcc.py cc -o test1.obj -c -x test1.c
/opt/Python-3.7/bin/python3 mygcc.py c++ -o test2.obj -c -x test2.cpp
/opt/Python-3.7/bin/python3 mygcc.py g77 -o test3.obj -c -x test3.F
/opt/Python-3.7/bin/python3 mylink.py -o foo.exe test1.obj test2.obj test3.obj
scons: done building targets.
============ END STDOUT
============ BEGIN STDERR (len=0)
============ END STDERR
/opt/Python-3.7/bin/python3 /raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py .
============ STATUS: 2
============ BEGIN STDOUT (len=322):
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/opt/Python-3.7/bin/python3 mygcc.py cc -o test1.shobj -c -x test1.c
/opt/Python-3.7/bin/python3 mygcc.py c++ -o test2.shobj -c -x test2.cpp
f95 -o test3.shobj -c -x test3.F
scons: building terminated because of errors.
============ END STDOUT
============ BEGIN STDERR (len=55)
sh: f95:  not found
scons: *** [test3.shobj] Error 127
============ END STDERR
/raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py returned 2
STDOUT =========================================================================
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/opt/Python-3.7/bin/python3 mygcc.py cc -o test1.shobj -c -x test1.c
/opt/Python-3.7/bin/python3 mygcc.py c++ -o test2.shobj -c -x test2.cpp
f95 -o test3.shobj -c -x test3.F
scons: building terminated because of errors.

STDERR =========================================================================
sh: f95:  not found
scons: *** [test3.shobj] Error 127

FAILED test of /raid/checkouts-raid/robb/AIX-scons/scons/scripts/scons.py
        at line 621 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestCommon.py (_complete)
        from line 724 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestCommon.py (run)
        from line 427 of /raid/checkouts-raid/robb/AIX-scons/scons/testing/framework/TestSCons.py (run)
        from line 127 of test/CPPFLAGS.py
robb@nepal:/raid/checkouts-raid/robb/AIX-scons/scons (master)$ 
```

**Comment by datalogics-robb** [comment]
If I take the second SConstruct in the test, and replace FORTRAN with SHFORTRAN the test completes successfully.

**Comment by mwichmann** [comment]
(as noted on discord) - this looks like a correct change to me. The test is already setting `SHLINK` and `SHLINKFLAGS` instead of `LINK` and `LINKFLAGS`, and `SHOBJSUFFIX` instead of `OBJSUFFIX` in anticiaption of trying a shared object build. I'm guessing it strictly should also set `SHCC` and `SHCXX` in addition to setting `SHFORTRAN`. 

It should perhaps be noted that in tool setup, `SHCC` and `SHCXX` are always set to `$CC` and `$CXX` while only some of the Fortran setups do this - the ones which start with 'f' set it to the detected/default command name instead of to the substitutable. I don't know if this is any particular issue. In other words, to this comment from Discord:
>  should eliminate the assumption that SHFORTRAN = $FORTRAN because that is not always true.

*should* that actually always be true? The cases where it isn't, it is still set to the same thing `$FORTRAN` is set to, just not to `$FORTRAN`.

**Comment by datalogics-robb** [comment]
Would it be a surprise to a user that setting FORTRAN would have no effect on a shared library input?
Am I correct in assuming that the `SH` prefix is to denote shared library input, and that the most common difference would be flags to generate position-independent code?

**Comment by mwichmann** [comment]
I think the split between COMPILER and SHCOMPILER is to _allow_ using a different tool, but no config in the code seems to do that (well, I didn't look terribly hard).  The flags would be represented in COMPILERFLAGS and SHCOMPILERFLAGS, which is used, indeed. And I think indeed, if you set FORTRAN and it didn't affect the compilation of shared objects (assuming it's generally supported to build objects for eventual inclusion in a shared library from Fortran sources - I have no actual idea if that's true, my Fortran usage dates back to a relative stone age, Fortran II and Fortran IV and is utterly inapplicable) would be somewhat surprising: hey, I changed the compiler, why didn't it work?

**Comment by datalogics-robb** [comment]
Yes, a fortran compiler can be used to build shared libraries much like a C compiler.
Under AIX/PPC there are ONLY pic objects.  In the aixf77 tool it seems as though 'xlf77' is used for `F77` and xlf77_r is used for `SHF77` - but the distinction is not PIC, it's support for threading (the tools with '_r' postfixed generate thread-safe code).

I'm happy with whatever change you'd prefer, just want to understand all the trade-offs.

**Comment by mwichmann** [comment]
I'm missing too much original context, will wait for @bdbaddog.

I'm deducing the concept is the Tool that's applied should set both to suitable default-as-modified-by-platform-detection. If the user sets either FORTRAN or SHFORTRAN it should override what that did.  If the user sets FORTRAN and not SHFORTRAN, it feels to me like SHFORTRAN should pick up what the user set FORTRAN to, but not vice versa.  But maybe that's not the design intent, maybe it's to be more explicit and you always set the two separately: there's some commentary on some of these vars to "see also" the other variable of the pair, just not for the Fortan ones, e.g.:

> SHCXX -   The C++ compiler used for generating shared-library objects. See also $CXX for compiling to static objects.

If the latter approach, then just updating the test should be sufficient.

Just so it stays consistent throughout scons...

**Comment by bdbaddog** [comment]
So it looks like the f* tools are the only(?) tools where they don't do something like this:
```
    env['FORTRAN'] = fcomp
    env['SHFORTRAN'] = '$FORTRAN'

```

Seems like the right fix is to change the f* tools?
The only danger though would be that someone is depending on the old behavior.
Though that seems pretty unlikely.
If you float a PR with that change and also add a big BLURB in RELEASE.txt and something notable in the CHANGES.txt I think we should be o.k.

**Comment by bdbaddog** [comment]
May need to wrap with:

```
if 'FORTRAN' not in env:..
if 'SHFORTRAN' not in env:..

```
So it doesn't stomp on user settings.. (as cc.py does)

**Comment by mwichmann** [comment]
This is open despite the related PR #3745 having been merged. Is there something still pending?

**Comment by datalogics-robb** [comment]
@mwichmann not to my  knowledge

**Comment by mwichmann** [comment]
Okay, then, closing. Feel free to reopen if needed.
