### ISSUE TITLE
Scons custom dependency scanner constructor returns NONE object

### ISSUE THREAD

**Issue by pvimal816** [SCons/scons#3747]
**Required information**
* Link to SCons Users thread discussing your issue. - [here](https://stackoverflow.com/q/62946778/8272206)
* Version of SCons - `3.0.1`
* Version of Python - `2.7.17`
* Which python distribution if applicable - [python.org](python.org)
* How you installed SCons - `ubuntu package manager(apt)`
* What Platform are you on? - `ubuntu-18.04`

* How you invoke scons (The command line you're using "scons --flags some_arguments") -> `scons -Q`
___________
Consider following snippet which belongs to `SConscript` file:

```
...

def dependency_add(node, env, path):
    print("scanner invoked.")
    return [env.File('src/sanitizer_blacklist.txt')]

dscanner = Scanner(function = dependency_add, skeys=['.c'])

print(dscanner)
...

```

Last line prints `None`.

**Comment by mwichmann** [comment]
We'd request that you bring topics such as this to the scons-users mailing list, or the Discord channel, before filing an issue.

In fact, you're being at least partially fooled by scons trying to be helpful: `Scanner` doesn't return `None`, but when you try to print what it does return, it doesn't know how to make a useful string representation so it returns `None`.  If you try printing `type(dscanner)` I think you'll get something like `SCons.Scanner.Base object`.

**Comment by mwichmann** [comment]
Checked: in fact. it prints the name supplied when `Scanner` is called, which defaults to `NONE` (all-caps)... if you supply a name, you should get that back. Try:
```
dscanner = Scanner(function = dependency_add, skeys=['.c'], name="MyScanner")
```

**Comment by mwichmann** [comment]
> We'd request that you bring topics such as this to the scons-users mailing list, 

aploogies for this: didn't see that this originated in a stackoverflow thread and you were asked to file an issue.

**Comment by bdbaddog** [comment]
Hmm.. Maybe we should print out something other than NONE, "Unnamed Scanner" ? 
NONE is easy to confuse with None.

**Comment by mwichmann** [comment]
Pending doc update will at least describe it.  Changing it might be even more useful :)
