### ISSUE TITLE
scons .tar.gz package does not include manpages

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3759]
For 4.0/4.0.1, the source tarball is not complete for the purpose of distribution packaging of scons - it is confirmed not to contain the manpages `scons.1`, `sconsign.1` and `scons-time.1`.  (reported on IRC channel)

**Comment by akien-mga** [comment]
>  it is confirmed not to contain the manpages `scons.1`, `sconsign.1` and `scons-time.1`. 

Note that the 4.0/4.0.1 tarballs also no longer build and install the `scons-time` binary at all. I assumed that it was dropped in 4.0, so if that's the case, its manpage should also be left out.

**Comment by mwichmann** [comment]
Asking around, it seems like scons-time was never actually intended for external release.  Someone will update if I'm wrong, I'm sure.
