### ISSUE TITLE
No module named Scons error when running scons

### ISSUE THREAD

**Issue by ozata** [SCons/scons#3782]
I run scons --version but it gives me error.

![scons](https://user-images.githubusercontent.com/33320778/90616972-cc1f9080-e216-11ea-8ed3-cb3fe0be746d.png)

**Comment by bdbaddog** [comment]
Apparently you ignored the instructions in the issue template

## Please bring your issue to the SCons users mailing list before filing an issue here
## See: https://scons.org/bugs.html
## or join our Discord server : https://discord.gg/bXVpWAy


Please try:
```
pip uninstall scons
pip install scons
```

4.0.0 fixed a long standing issue with the case of SCons.
If you're upgrading from lower version, you should uninstall first.

Note this is explicitly explained in the RELEASE.txt for 4.0.0

https://scons.org/scons-400-is-available.html

**Comment by bdbaddog** [comment]
Also as a general rule, **please don't post screenshots of text**.
**It's very hard to read.**
Copy/paste the text into the issue/pull request.
