### ISSUE TITLE
Allow runtest to rerun tests based on a logfile

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3797]
Sometimes it would be very convenient to be able to tell `runtest.py` "please rerun all the tests that failed in this journal from a previous run" - while debugging, if you make an error or introduce a regression it's nice to quickly be able to figure out "did I fix that"?

The current standard journal format is more human-readable and maybe not well suited to having runtest parse, but maybe the xml format is, or maybe we could define an optional journal format specifically for it's ability to be parsed by a tool.

**Comment by bdbaddog** [comment]
So maybe runtest.py writes out failed_tests.txt and then `--rerun` or `--failed` automatically reads and runs those?

**Comment by mwichmann** [comment]
that could be a nice simple way to progress, I guess I was thinking too generally.  if it can just spit out the file - it already knows the list because it's generated there for the summary - then that can immediately be the input to `runtest -f`

**Comment by mwichmann** [comment]
After letting things sink in for a while, the suggestion is nice and simple, so let's zero in on a few options before generating a PR.

- [ ] Should the test failures be saved automatically, without asking? (I favor this approach)
- [ ] If no, what option name should be added to request this?
- [ ] Should there be a single invariant name for the error log, or should it be stamped somehow? (I'd suggest invariant)
- [ ] If invariant name, we can have `--rerun` effectively be `-f failed_tests.txt` as a convenience, but don't *need* such an option. Add, or not?
- [ ] If stamped name, should runtest emit the name after a run, as in `Failed tests stores in failed_tests.20200211.0733`?  In this form, it doesn't seem to make sense to add a convenicence option, although it could mean "rerun the latest found". Thoughts on this?

**Comment by bdbaddog** [comment]
1 - yes
2 - should be able to disable this
3 - no, but a reasonable default
4 - hmm so reuse -f. I like that, with a default file name if not specified? (can we do that)?
5 - not in favor of stamped name. user can specify non-default if they want such?

**Comment by mwichmann** [comment]
"can we do"..  if I push the conversion to argparse, then easily...

**Comment by mwichmann** [comment]
Closed by #3822
