### ISSUE TITLE
pywin32 dependency in >=4.0.0 breaks MinGW targets

### ISSUE THREAD

**Issue by FyiurAmron** [SCons/scons#3806]
**Describe the bug**
while trying to install SCons on MinGW32/64 (MSYS2), `pip3 install scons` fails for versions 4.0.0 & 4.0.1 due to
```
Collecting pywin32>=1.0; platform_system == "Windows" (from scons==4.0.1)
  Could not find a version that satisfies the requirement pywin32>=1.0; platform_system == "Windows" (from scons==4.0.1) (from versions: )
No matching distribution found for pywin32>=1.0; platform_system == "Windows" (from scons==4.0.1)
```
Project description on https://pypi.org/project/SCons/ clearly states that
>There should be no other dependencies or requirements to run SCons, although the pywin32 Python package is strongly recommended if running on Windows systems.

Either the dependency should be removed (preferred, since PyWin32 support on MinGW is problematic), or the docs fixed to reflect this change.

3.1.2 and previous versions work as intended and install correctly.

**Required information**
applies to 4.0.0, 4.0.1.

related: https://github.com/SCons/scons/issues/2291

**Comment by bdbaddog** [comment]
So is the problem installing scons 4.0.0 (or higher) in python installed via msys2?

**Comment by FyiurAmron** [comment]
@bdbaddog basically, yes, although I guess the dependency by itself can manifest in other similar setups too (Win-like platforms without PyWin32).

**Comment by bdbaddog** [comment]
@FyiurAmron - I understand about the added dependency. I added that.
Just curious in what environment it's causing an issue.

I'm not sure how to conditionally add pywin32 only for non mingw python installs.

**Comment by mwichmann** [comment]
Setuptools, pip, and the PEP (508) that describe the package format don't provide any way to surface that a dependency works for Windows, but not for msys/mingw in Windows.  You can't detect the mingw piece at al at the level of pip's dependency resolution, as far as I can see.

**Comment by bdbaddog** [comment]
Removed pywin32 entirely in current master branch..
Will be in 4.0.2 release when that comes out.
