### ISSUE TITLE
Possibility to set the file suffix for the object files when using the SharedLibrary function

### ISSUE THREAD

**Issue by yali25** [SCons/scons#3828]
Hi,

I'm using the SharedLibrary function provided by scons. This function works fine, however recently I 
started to use the Fujitsu compiler family (rather exotic) and now I'm facing some issues with the internal file suffixes
scons is using for the object files.

My scons setup file includes this call:
`env.SharedLibrary(target='my_lib',source=["./src_for/func.c","./src_for/func1.for"])`

The output is:
`frtpx -o build/src_for/func1.os -c  -O3 -fPIC src_for/func1.for`
`frtpx: fatal: "build/src_for/func1.os": Invalid file suffix.`

When I manually copy the compile call generated by scons and change the file suffixes from **.os** to **.o** it 
works.
Is there a way to instruct scons to use **.o** instead of **.os**? I searched the documentation but couldn't find
anything. 

Thank you for your help

**Comment by bdbaddog** [comment]
Seems you ignored the request to check the mailing list, IRC, or our discord server before posting an issue here.

Here's the answer:
https://scons.org/doc/production/HTML/scons-man.html#cv-SHOBJSUFFIX

**Comment by yali25** [comment]
Thanks works fantastic! 
Understood, next  time I will post at the mailing list.
