### ISSUE TITLE
Make it possible to redefine 'ar' tool through AR env var (similar to CC etc.)

### ISSUE THREAD

**Issue by kanavin** [SCons/scons#3838]
Here:

https://github.com/SCons/scons/blob/master/SCons/Tool/ar.py

'ar' seems to be hardcoded as the archiver tool. 

In cross-compiling environments such as Yocto it is often re-defined through AR environment variable, but SCons does not pick it up (unlike CC, which is properly picked up as the compiler to use).

**Comment by bdbaddog** [comment]
@kanavin  - you've ignored our request that you bring this issue to the users mailing list, IRC Channel or discord server.

SCons doesn't ever pick up tools from shell environment variables.
If you'd like to discuss further please use one of the channels I've just listed.

**Comment by bdbaddog** [comment]
https://scons.org/faq.html#Why_doesn.27t_SCons_find_my_compiler.2BAC8-linker.2BAC8-etc..3F_I_can_execute_it_just_fine_from_the_command_line.
