### ISSUE TITLE
Invalid value for option platform: .

### ISSUE THREAD

**Issue by anzhi0708** [SCons/scons#3841]
Hi, I know this question was probably already brought up by someone else but I'm running into it anyway... I apologize for that.
I'm running Linux Mint x11 64bit, scons 3.1.1, it throws me this error.
```
 scons: *** Invalid value for option platform: .  Valid values are: ('x11-64', 'x11-32', 'windows-64', 'windows-32', 'osx-64')

```
How should I fix this?
Sorry for (potentially) re-opening this issue.

**Comment by mwichmann** [comment]
That's a message from the build scripts for whatever it is you're trying to build, not intrinsically from scons itself.

**Comment by bdbaddog** [comment]
Closing. Not a SCons issue.
Please check with whatever package you're trying to build.
Also, next time please follow the instructions to bring your issues to our support channels prior to filing an issue.
