### ISSUE TITLE
Add timestamp override to Zip builder

### ISSUE THREAD

**Issue by dholth** [SCons/scons#3843]
Zip should have an option to override the timestamp on files in the archive instead of taking it from the file system. This can be useful for repeatable builds or for anonymizing the archive.

**Comment by bdbaddog** [comment]
I'm not sure we can do this when we use pure python zipfile unless the floor for this is Python 3.6
https://docs.python.org/3.6/library/zipfile.html#zipinfo-objects

Can you modify zipinfo in py 3.5?
Thoughts @dholth

**Comment by dholth** [comment]
I was planning to submit an implementation when I get time,

Wouldn't it be okay for this to only work when Python > 3.6

I don't think any of my target audience uses 3.5

**Comment by mwichmann** [comment]
not an official answer, but py35 is out of support so a >3.5 answer isn't a completely unusable one, just might take a bit to get integrated?

**Comment by bdbaddog** [comment]
Historically SCons has supported all functionality on all supported versions of Python.
SCons currently supports Python 3.5+

Might make sense to just issue a warning that it's not supported when user is running Python < 3.6?

**Comment by djh82** [comment]
This works on py35+:

```python
def zip(target, source, env):
    files = []
    for s in source:
        if s.isdir():
            for dirpath, dirnames, filenames in os.walk(str(s)):
                for fname in filenames:
                    path = os.path.join(dirpath, fname)
                    if os.path.isfile(path):
                        files.append(path)
        else:
            files.append(str(s))
    
    compression = env.get('ZIPCOMPRESSION', 0)
    zip_root = str(env.get('ZIPROOT', ''))

    with zipfile.ZipFile(str(target[0]), 'w', compression) as zf:
        for fname in files:
            with open(fname, "rb") as f:
                arcname = os.path.relpath(fname, zip_root)
                zf.writestr(zipfile.ZipInfo(arcname, date_time=(1980,1,1,1,1,1)), f.read())
```

**Comment by mwichmann** [comment]
Probably better if that function gets renamed since `zip` is also a Python built-in function (I realize that's an existing decision, not introduced by @davidhart82 proposal)

**Comment by bdbaddog** [comment]
@davidhart82 - would you be up for creating a PR.. you'd just need to add a test.

**Comment by djh82** [comment]
@bdbaddog sure thing, I have time this week for open source contributions. How do you want the date to be specified by the user? A string? With an optional format specifier? Or something simpler?

**Comment by bdbaddog** [comment]
@davidhart82 - how about ZIP_OVERRIDE_TIMESTAMP
Contents should be the tuple which wouldmap right to datetime?
https://docs.python.org/3.5/library/datetime.html#datetime-objects

Thoughts?

**Comment by djh82** [comment]
@bdbaddog sure, sounds good. Will try and get that done tomorrow.

**Comment by djh82** [comment]
@bdbaddog I've given it a pop; let me know what you think.  I've extracted a function which should allow for a simple replacement with `ZipFile.from_file` when that becomes available.
