### ISSUE TITLE
Documentation for CompilationDatabase lacks important information

### ISSUE THREAD

**Issue by roblub** [SCons/scons#3845]
> Please bring your issue to the SCons users mailing list before filing an issue here

Sorry, the list does not allow non-subscribes to send mails there, and I am not willing to subscribe the list.
Here is a content of e-mail I tried to send:

Hi

I was going to file the following bug via GitHub, and it told me to send
email here instead. The bug is:

I upgraded our scons installation to 4.01 to have support for
CompilationDatabase. Then I copied&pasted the env.Tool and
env.CompilationDatabase lines from
https://scons.org/doc/production/HTML/scons-user/ch28.html to my
SConscript, then run 'scons' command and... it did not work, i.e. the
compile_commands.json was not created at all 

After some investigation I've learned that I need to run 'scons .'
command instead. It is because our scons installation contains
aliases and redefines the default target like this:
```
 env.Alias('our-app', ['our_app_src_dir'])
 env.Alias('unit-tests', ['tests_dir'])
 env.Alias('all', ['our-app', 'unit-tests'])
 Default('our-app')
```
In fact we never actually run 'scons .', and to be honest I didn't even
know that it exists. I think the above documentation for Compilation
Database should explicitly mention that running 'scons' might not work
when the default target is redefined, and in such cases 'scons .' is
required - it would save me some time.

Anyway I've ended with the following function that simply adds new
target called compilation-db, what allows us to run it only when it is
needed (for example on jenkins). Maybe the functionality of specyfing
target name could be added to the CompilationDatabase Tool itself?
```
def handle_compilation_db_target(builddir):
    target_name='compilation-db'
    out_file_name=os.path.join(builddir, 'compile_commands.json')

    if target_name not in BUILD_TARGETS:
        return

    env.Tool('compilation_db')
    env.CompilationDatabase(out_file_name)
    env.Alias(target_name, out_file_name)
    Scons.Script.NoCache(out_file_name)
    Scons.Script.NoCache.AlwayBuild(out_file_name)
```
Regards,
Robert

**Comment by mwichmann** [comment]
The CompilationDatabase stuff is very new, and I don't find it surprising that the docs are not well fleshed out yet, since it hasn't had a lot of exposure. As such - thanks for the report!

> I think the above documentation for Compilation Database should explicitly mention that running 'scons' might not work when the default target is redefined

Not sure whether that's a doc or implementation problem, but that sounds kind of dodgy - we'll look into it. Keep an eye out here, there may be some questions once the right people get a chance t look.

**Comment by bdbaddog** [comment]
@roblub - this behavoir is not specific to CompilationDatabase(). it is true of any and all builders.
If you specify Default() and don't specify any target on the command line, then only those defaults and things they depend on will be built.

If you read the manpage entry on Default(), you will see that information is there. I've bolded that section.

Please join the mailing list of come on our discord or IRC channel for future support.
The users mailing list is fairly low traffic.

See: https://scons.org/contact.html

> Default(targets...)
> env.Default(targets...)
> **This specifies a list of default targets, which will be built by scons if no explicit targets are given on the command line.** Multiple calls to Default are legal, and add to the list of default targets. As noted above, both forms of this call affect the same global list of default targets; the construction environment method applies construction variable expansion to the targets.
> 
> Multiple targets should be specified as separate arguments to the Default method, or as a list. Default will also accept the Node returned by any of a construction environment's builder methods.
> 
> Examples:
> 
> Default('foo', 'bar', 'baz')
> env.Default(['a', 'b', 'c'])
> hello = env.Program('hello', 'hello.c')
> env.Default(hello)
> An argument to Default of None will clear all default targets. Later calls to Default will add to the (now empty) default-target list like normal.
> 
> The current list of targets added using the Default function or method is available in the DEFAULT_TARGETS list; see below.

Closing this issue as it is really just a support request.
We won't be adding explicit info about Default()'s functionality on any other builder's or constructs manpage entries.

**Comment by roblub** [comment]
To be honest I do not really care how much traffic is on the list, I'm not interested in joining it at all, as I won't be reading those e-mails anyway. So if you want me to send e-mails to the list, please re-configure the list appropriately. Otherwise if you don't want me to support your work by using tools that are designed for it (like this web tool for reporting issues), I'm OK with it.

And no, the issue wasn't support request, because as I wrote there I managed to solve the issue by myself. It was rather a suggestion what I think could be improved at your site. But if you think the current doc is perfect, I'm OK with it as well.

**Comment by bdbaddog** [comment]
> To be honest I do not really care how much traffic is on the list, I'm not interested in joining it at all, as I won't be reading those e-mails anyway. So if you want me to send e-mails to the list, please re-configure the list appropriately. Otherwise if you don't want me to support your work by using tools that are designed for it (like this web tool for reporting issues), I'm OK with it.
> 
> And no, the issue wasn't support request, because as I wrote there I managed to solve the issue by myself. It was rather a suggestion what I think could be improved at your site. But if you think the current doc is perfect, I'm OK with it as well.

The issue template does suggest other ways to contact the project before filing an issue.

The reason we ask that people contact the project first before filing is to ensure we don't fill up the tracker with user errors, duplicates, etc. And also to get people solutions as quickly as possible.

It's a courtesy we ask in return for supporting the users.

**Comment by roblub** [comment]
I've re-read my previous comment, and I think  it might be seen as rude. Sorry about that.

I dismissed the other option of contacting, as I simply didn't know what the discord is, and my intention was to file a bug, not to learn new services.

Returning back to the original topic, could you please at least consider adding to the chapter sample command line that would work regardless of Default target (i.e. 'scons .' or 'scons compile_commands.json') together with the 'Generating ...' line the command is expected to output?  I really think doing this might be beneficial to other users, especially that there is no really too much information in google about how this new compilation db stuff works with scons.

I

**Comment by bdbaddog** [comment]
I guess I don't understand.
You're using Default() in your SConstruct, so when that was put in place someone had to understand what it did.

Then later someone added the CompilationDatabase() and wasn't aware of the Default()'s in place.
So your organization lost that information and then ran into an issue.  Clearly had some difficulty figuring it out.

Something which would have been far quicker to resolve if you'd reached out to the community (Do I sound like a broken record here? It's because this happens TOO much.  People burn weeks of time trying to figure out something rather than shoot an email to the users mailing list, or hop  on the discord channel (notice why the suggestion is in the issue template?))
Can you see why it would be frustrating to have this offer for help dismissed out of hand?
The mailing list, IRC, and discord server (think modern version of IRC, or if you're familiar Slack equivalent) are a great mechanism for getting and sharing knowledge about SCons.
Don't struggle with these issues in private when we're here to help.
We just ask that you use the methods which are designated for such.

This is not an issue specific to CompilationDatabase(), this is about the use of Default()

To me, two updates might be best to help with this
1. Add an item on the FAQ something like "a target I added isn't getting built", though the FAQ already has [this](https://scons.org/faq.html#How_do_I_install_files.3F_The_Install.28.29_method_doesn.27t_do_anything._In_general.2C_how_do_I_build_anything_outside_my_current_directory.3F), it's not as general as what I"m suggesting.
2. Add a larger notice on Default() the potential downside of using it.  While the information is there, it's not highlighted.

But if we add a separate section to CompilationDatabase()'s docs, then shouldn't' we add it to all other builders? See the problem here.

The solution is to make the problem easier to solve, not the specific solution you've proposed. IMHO.

**Comment by roblub** [comment]
I think you got it right: someone introduced scons into our project several years ago, and now someone else (i.e. me) added CompilationDatabase, because wants to run clang-based tools on the project's code.

Please note that I work for commercial company, and I cannot share the code outside of the company. This means that before asking external communities for help, I still need to investigate if the issue lies in scons itself (i.e. external code), or in our customizations/configurations (our code). 

From my perspective, after reading https://scons.org/doc/production/HTML/scons-user/ch28.html I had the impression that it would be enough to add those two lines (env.Tool and env.CompilationDatabase) and everything will simply work, regardless of what options/targets I pass to scons.  This means that I can run 'scons foo' and it will create 'compile_command.json' anyway. **There is absolutely nothing in the chapter that would suggest otherwise**.
The only think I did not know was if 'scons foo' will create compile_commans.json for 'foo' or for the whole project.  

Instead of pointing me to any other points of your documentation or FAQs, **please just read the Chapter 28 from the user perspective, not from your, developer, perspective**. Then please answer yourself the following questions:
-  How should you as a user know from the chapter that  Tools&CompilationDatabase lines will add  'compilation_command.json' target to scons, and not for example 'compilation_db' target? 
- How should you as a user know, still from that chapter, that the lines will actually add any target to scons, i.e. how should you as a user know  that the json file is not generated always just by existence of the two lines in SConscript? 

IMHO all the uses of the word 'target' in this chapter seem to refer to the contents of generated json file, not to scons itself...

**Comment by mwichmann** [comment]
Not disagreeing with you that this could be more descriptive, as I said before - I'll take a further look at this.  Yes, the implementation causes the compilation DB itself to become a target, but that's perhaps not useful information from a user viewpoint (unless you need to so something with that target explicitly). I'll leave it up to @bdbaddog as to whether to reopen.  Feel free, of course, to propose any helpful wording improvements yourself :)

**Comment by bdbaddog** [comment]
@roblub - if you pick any chapter on it's own later in the users guide and don't read the previous base level chapters you probably won't understand them. You can't take the chapter on it's own.  That's true of any users guide or tutorial. Later material adds on to information introduced earlier.

Furthermore details of commands are typically located in manpages, not users guides. The two should be used hand in hand.

That said it'd probably be useful to label the content of the output file so it's clearer from that example.  @mwichmann  - thoughts?

**Comment by bdbaddog** [comment]
@roblub - re commercial company. Many users are in the same position (work on commercial product built with SCons)  and will still reach out for help on where to look. That would've saved you a ton of time, please reach out next time.

**Comment by mwichmann** [comment]
I'm going to reopen this and propose a few simple doc changes, a link to the PR should show up here in the next day or so.
