### ISSUE TITLE
Feature Request: not copying intermediate files from cache

### ISSUE THREAD

**Issue by roblub** [SCons/scons#3846]
> Please bring your feature request to the SCons users mailing list before filing an issue here

As in the other issue, I'm not willing to subscribe, and the list reject non-subscribes. Here is mail I've tried to send there:

Hi

It would be great if I could tell scons to neither recompile given
object nor to take it from the cache if it is not really needed (for
example for local linking in case the outcome of linking is not in the
cache).

For example let's assume that my_app is build from main.c and utility.c
files. So after the very first compilation the cache stores three files:
main.so, utilty.so and my_app.

I would like have to have an option to tell scons that main.o and
utility.o are intermediate files, and they not need to be updated from
the cache when I update main.c and utility.c from repository, and
pre-built my_app for the updated *.c files already exists in the cache.
In such a case I would like scons to update only my_app from the cache,
without updating the *.o files (oh, I think they might be removed
instead, just in case tools like gdb wanted to use them).

Obviously when I modify for example main.c, then scons would need to
retrieve the utility.os from the cache anyway in order to link my_app
with it, so you may think my feature request has a little or no sense.
But this was only example. In reality we have quite a big project that
uses shared libraries, and users usually modify files within belonging
to one or two libraries. So they do not really need to have the *.o
files from other libraries to link final application, they only need the
libraries instead to link final app.

I think the option I request here would be similar to the no_cache
option described in
https://scons.org/doc/production/HTML/scons-user/ch24s03.html (which
btw. is a bit bizzare, as it boasts about scons performing compilation
of source file, but then is does not use the outcome of the compilation;
it would be nice to have more realistic example there).

As the intermediate files may be needed sometime (for example debuggers
might need the *.o files), scons should have some command line option to
force retrieval of those files from cache.

Do you think it would be possible to implement such a functionality in
scons?

Regards,
Robert

**Comment by bdbaddog** [comment]
Please bring such issue to any of our support channels listed here:
https://scons.org/contact.html

As I said in the other issue you filed, please reconsider joining the users mailing list, it's fairly low traffic, but does get a reasonalby large number of experienced scons users eyes, where these issues are primarily only reviewed by maintainers.

I'm going to say it would be pretty complicated to identify which intermediate targets shouldn't be pulled from the cache.
Additionally some tools depend on file naming, so a file without the proper name would now work with some tools, and identifying such would be unmanagable.
So no, we won't be implementing this.

**Comment by roblub** [comment]
What would be benefit of joining the list? Do the "experienced scons users eyes" would help me with a feature that is not in scons, and as you wrote you're not going to implement anyway? 

Identifying which intermediate targets shouldn't be pulled from the cache, should be left to users. I mean just like currently the user can write 'no_cache(target)', it could also write 'cache_but_not_retrieve_and_not_recreate_when_it_is_not_needed_as_a_direct_dependency_of_another_target_that_needs_to_be_rebuilt(target)' (actually the name should be a bit less verbose, I guess)

**Comment by bdbaddog** [comment]
Experienced users may already have a way to do whatever you're trying to do.

Is the goal to save disk space?
Or is it time to copy?
Or both?

**Comment by bdbaddog** [comment]
Hmm if we enabled GitHub discussions would you engage there prior to filing ask requested?

**Comment by roblub** [comment]
The intention was to do both. To get you some background we use NFS storages, which are big (but already filled in above threshold that makes our admins to complain about), and pretty much slow (at least comparing to local disks, which are not an option).

I really would prefer to have built-in support for this in scons than trying to put yet another customization into our usage of scons (which was highly customized several years ago by a colleague who is no longer  in the project, and now nobody really knows how it all works).

I wouldn't expect it would be easy to implement. I agree there is no much sense in continuing discussion here, especially that the decision about my feature request has already been made.  So it is EOT from my side.

Thanks,
Robert

**Comment by bdbaddog** [comment]
Ideally SCons users would engage with the community to help drive forward use model and contribute code.

If you're willing to do the work and engage the community to move this enhancement forward, then perhaps it's viable. But as is, there's no resources to make it happen. 

Again, please engage with the community. (And this is not the primary forum for doing so, the best way to interact (of late) is the discord server.
