### ISSUE TITLE
scons 4.1.0 sdist on PyPI install fails

### ISSUE THREAD

**Issue by dtrodrigues** [SCons/scons#3868]
`pip install --no-binary :all: scons==4.1.0` is failing with  `error: can't copy 'build/doc/man/scons.1': doesn't exist or not a regular file`

It worked on 4.0.1.

See logs in https://github.com/Homebrew/homebrew-core/pull/69371

Installation attempted via Python 3.9 from homebrew on macOS.

**Comment by bdbaddog** [comment]
@dtrodrigues  - Investigating.. I saw in that link something about adding license as well?

**Comment by dtrodrigues** [comment]
Homebrew didn't have the license for SCons noted until just now. Is MIT the correct one? https://github.com/SCons/scons/blob/master/LICENSE

**Comment by bdbaddog** [comment]
> Homebrew didn't have the license for SCons noted until just now. Is MIT the correct one? https://github.com/SCons/scons/blob/master/LICENSE

Yes.
Do you need us to do anything upstream to make that "stick" ?

**Comment by dtrodrigues** [comment]
Nope -- it never was included in the formula description and now that it is, it'll remain there.

**Comment by bdbaddog** [comment]
O.k. Reproduced. I'll see if I can spin a 4.1.1 in the next day or so to resolve.

**Comment by bdbaddog** [comment]
@dtrodrigues - can you try with testpypi ? 

`pip install --no-binary :all: -i https://test.pypi.org/simple/ SCons==4.1.0.post1`

Seems to work for me.

**Comment by bdbaddog** [comment]
pushed 4.1.0.post1 to pypi.
Please try and let us know.

**Comment by dtrodrigues** [comment]
Yep it worked, thanks for the quick turnaround: https://github.com/Homebrew/homebrew-core/pull/69390
