### ISSUE TITLE
variables.Add confusion about aliases

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3869]
This was discussed on discord (reported by @acmorrow), and there's a fairly simple possible fix - but wanted to capture it in an issue first as there's some room for discussion.   This was mentioned in the context of a pre-4.1 release but exists in the just released 4.1 as well; python versions irrelevant.

If you pass a tuple of strings to `Add` as the key value, instead of a single string (see the example later in this description to see what it looks like), the tuple is unpacked and the first string used as the key name, the additional ones as aliases.  This isn't actually promised in the docs in words, but a comment in the code says so, and the unit tests definitely test for this alias behavior.

The problem is that for `Add`, this doesn't work (this is the "issue").  `Add` and `AddVariables` share a call to `_do_add`, which implements actual variable setup, _but_ `Add` has additional logic that if a tuple alone is passed, it's the result of one of the `*Variable` functions, and it unpacks this and calls `_do_add` in a way that doesn't allow the key alias tuple to be recognized. 

So three questions for discussion before proposing a PR:
1. Does `Add` need to support this behavior of accepting a packed tuple of arguments like `AddVariables` does instead of passing the positional/keyword arguments that are documented for `Add`?  The docs don't promise this behavior explictly (although it can be inferred by looking at examples, esp. in the user guide), and it could be disallowed by saying "if you want to pass the result of calling `ListVariable` (for example). then use `AddVariables` instead. The overloading of the `key` parameter so it's both a positional variable and packed set of arguments is, well, awkward. A different approach might be to provide an "alternate constructor" (like providing both `Add` and `Add_as_tuple` or some such) - but it's quite possible there is dependence on the existing dual-nature behavior "in the wild" and a change would break things, so that would come with implications.
2. Should we indeed promote to documented/supported the behavior of passing the key tuple to set up aliases? As noted, the presence of unit tests does suggest it was intended to be considered supported behavior, but one could argue "we never said so, so don't count on it".
3. At the moment in `_do_add`, the behavior is that if you pass a key tuple, it behaves as described above, but if you pass a key string, the value is used as the key *and* the alias - that is, the key is part of the alias list in only one path through the code. The unit tests in fact expect this so it appears semi-intentional, but seems logically odd - I'd expect either the key to always be in the alias list or never. The actual code:
```
        if SCons.Util.is_List(key) or SCons.Util.is_Tuple(key):
            option.key = key[0]
            option.aliases = key[1:]
        else:
            option.key = key
            option.aliases = [key]
```

Problem reproducer:

In `VariablesTests.py` in `VariablesTestCase` add a third setup that uses a tuple for the key:
```
        opts.Add(('QUESTION', 'FAQ', 'Q'),
                 help='THE frequently asked question',
                 default="37",
                 validator=check)
```
and then test for the results:
```
        # a key which is a tuple should set up aliases
        o = opts.options[2]
        assert o.key == 'QUESTION', o.key
        assert o.help == 'THE frequently asked question', o.help
        assert o.default == "37", o.default
        assert len(o.aliases) == 2
        assert 'FAQ' in o.aliases
        assert 'QUESTION' not in o.aliases
```

**Comment by acmorrow** [comment]
Well, first, I think the Variable Aliases thing is actually really handy. Maybe not needed that often, but I found it crucial when doing some renaming, so that even if a user specified something on the command line via the old name, the setting got re-routed to the new name. I was actually more or less astounded that such a handy feature was right there when I needed it. So, I'd be sad to see it simply dropped.

I'd also be a little disappointed to see this whole thing resolved by saying that I need to use the `AddVariables` function. I sort of dislike that it would force me to declare all these variables within one function call. It would mean, for the MongoDB build, a function call with close to 100 arguments.

On the other hand, since this variable aliases thing seems to be wholly undocumented, maybe the answer is just to introduce a new keyword argument for `Add`. I'll muddle through with `_do_add` until the real `Add` takes an `aliases=` argument which takes a list of aliases.

**Comment by mwichmann** [comment]
So that's an interesting idea - don't propagate the "use a tuple to define aliases" behavior and introduce a new kwarg.  That would make for a cleaner solution, methinks.  Further thoughts on that?

**Comment by bdbaddog** [comment]
So if we added an `aliases` kw arg, then it won't break any existing logic right?
That sounds like the way to go.

**Comment by mwichmann** [comment]
I don't find that an objectionable approach... I didn't originally raise the issue, but @acmorrow seems to be okay with it too.
