### ISSUE TITLE
Bug using AutoConfigBuilder from wiki.

### ISSUE THREAD

**Issue by zhongchengyong** [SCons/scons#3897]
**Describe the bug**
I want to use scons to cooperate with a GNU configure&make project which used as part of my scons-build project, then I find a AutoConfigBuilder here: https://github.com/SCons/scons/wiki/AutoConfigBuilder, but error occurs by following the guide. ErrorInfo:  

**TypeError: Tried to lookup Dir '/xxx/my_extern_dir' as a File.**

**So if this Builder not work, does anyone have a better solution?**

**Required information**
* Link to SCons Users thread discussing your issue.
* Version of SCons
4.1
* Version of Python
3.8
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
python
* How you installed SCons
pip install scons
* What Platform are you on? (Linux/Windows and which version)
Linux
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
1. Add the AutoConfig script to site_scons/site_tools: https://github.com/SCons/scons/wiki/AutoConfigBuilder
2. Use 'env.AutoConfig(my_extern_dir)
* How you invoke scons (The command line you're using "scons --flags some_arguments")
just 'scons'

**Comment by mwichmann** [comment]
Hmmm, interesting. I wonder if something has gotten stricter in SCons since that was written. 

You can always issue the configure command manually with `Execute` in your SConscript in order to get going.

**Comment by bdbaddog** [comment]
@zhongchengyong Please run again but add `--debug=stacktrace` and post the full build output you get with the stacktrace?

As `${target_dir}'` doesn't appear in the AutoConfigBuilder, likely it's something in your usage thereof..

How are you specifying `my_dir`?

A full simple reproducer would help here.

**Comment by mwichmann** [comment]
I pasted an updated version to the end of the wiki page, it doesn't work either.  https://github.com/SCons/scons/wiki/AutoConfigBuilder

**Comment by zhongchengyong** [comment]
@bdbaddog 
1. Sorry I can't post the full stacktrace since the offline environment now, I'll build a simple project and reproduce this problem then   post stacktrace here. But now, I can post some critical backtrace and hope it help:

```
TypeError: Tried to lookup Dir '/xxx/my_extern_dir' as a File.  
File "/home/project/SConstruct', line 1050:   
SConscript(os.path.join(tg, 'SConscript'),   
File "/home/path_to_python/Scons/Script/Sconscript.py", line 654:  
  return method(*args, **kw)  
......  
File "/home/path_to_python/Scons/Node/Fs.py", line 612:  
  raise TypeError(“Tried to lookup %s ‘%s' as a %s.” %\  
```

2. '${target_dir}' and 'my_dir' is the external configure&make project directory, I have revised to 'my_extern_dir' in the issue.
Thanks.

**Comment by bdbaddog** [comment]
I asked for the full stacktrace, but you truncated it.
Please post the full stacktrace.

**Comment by mwichmann** [comment]
Well, I can include what I get, which does look a bit different, but ultimately is still an error of "directory-where-file-expected". My testcase was simply a directory (EXP) where I had unpacked an old zlib tarball I had lying around, and the SConstruct file is trivial - just like the one from the wiki page:

```
env = Environment(tools=['default', 'AutoConfig'])
configured = env.AutoConfig(source='zlib-1.2.8')
```

```
scons: Reading SConscript files ...
TypeError: Directory /home/mats/Downloads/EXP/zlib-1.2.8 found where file expected.:
  File "/home/mats/Downloads/EXP/SConstruct", line 2:
    configured = env.AutoConfig(source='zlib-1.2.8')
  File "/home/mats/github/scons/scripts/../SCons/Environment.py", line 237:
    return super().__call__(target, source, *args, **kw)
  File "/home/mats/github/scons/scripts/../SCons/Util.py", line 658:
    return self.method(*nargs, **kwargs)
  File "/home/mats/github/scons/scripts/../SCons/Builder.py", line 650:
    return self._execute(env, target, source, OverrideWarner(kw), ekw)
  File "/home/mats/github/scons/scripts/../SCons/Builder.py", line 560:
    tlist, slist = self._create_nodes(env, target, source)
  File "/home/mats/github/scons/scripts/../SCons/Builder.py", line 487:
    slist = env.arg2nodes(source, source_factory)
  File "/home/mats/github/scons/scripts/../SCons/Environment.py", line 473:
    v = node_factory(self.subst(v, **kw))
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 1398:
    return self._lookup(name, directory, File, create)
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 1377:
    return root._lookup_abs(p, fsclass, create)
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 2402:
    result.diskcheck_match()
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 2635:
    diskcheck_match(self, self.isdir,
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 388:
    return self.func(*args, **kw)
  File "/home/mats/github/scons/scripts/../SCons/Node/FS.py", line 409:
    raise TypeError(errorfmt % node.get_abspath())
```

**Comment by bdbaddog** [comment]
try changing the source to be the configure file in that directory..

**Comment by mwichmann** [comment]
well, one can try, but that's modified in flight, so then the "target" will come out wrong...
```
TypeError: Tried to lookup File 'zlib-1.2.8/configure' as a Dir.
```
