### ISSUE TITLE
`--site-dir` has precedence over `--no-site-dir`, order should be swapped

### ISSUE THREAD

**Issue by DeeeeLAN** [SCons/scons#3904]
@bdbaddog requested this ticket

Currently, if you run `scons --site-dir=xyz --no-site-dir`, SCons will ignore the `--no-site-dir` flag due to the order of the code below:
```
if options.site_dir:
    _load_site_scons_dir(d.get_internal_path(), options.site_dir)
elif not options.no_site_dir:
    _load_all_site_scons_dirs(d.get_internal_path())
```
However, I think it makes sense to reverse these and let `--no-site-dir` take precedence. That way, you can specify an arbitrary `--site-dir` using `SCONSFLAGS` or a shell alias, but still override that if needed. Currently you can override one site-dir with another by appending a second flag, but there is no way to disable the site-dir once it is on the command line. 

The one reverse argument is if you had `SCONSFLAGS='--no-site-dir'` and appended a site-dir locally, it would not get read in. I would expect that to be an extremely uncommon situation, since it would be easier to just rename the local site-dir to something other than `site_scons` and avoid needing the `--no-site-dir` flag at all.

**Comment by mwichmann** [comment]
It should be based on order in the command line, the current oddity is it's treated as two different variables during options processing, more logically the same variable would be updated, that way you easily get "last one wins".

**Comment by mwichmann** [comment]
The attached diff illustrates what I'm thinking of. 

[3904.txt](https://github.com/SCons/scons/files/6175993/3904.txt)

**Comment by DeeeeLAN** [comment]
That was similar to what I was thinking, but I wasn’t certain if multiple options could store to the same variable or not. If they can then yes that is the easiest way to go for sure.

**Comment by mwichmann** [comment]
Yes, optparse allows multiple options to have the same variable to store to.  It's not cumulative unless you use `action="append"`, which is sometimes useful, though doesn't seem to be required here.
