### ISSUE TITLE
Error: Can't find a working Python installation

### ISSUE THREAD

**Issue by HaFred** [SCons/scons#3911]
## or join our Discord server : https://discord.gg/bXVpWAy

**Describe the bug**
I tried both python pypi and scons==4.0.1 under python==3.7 of anaconda environment. By issuing scons, it ended up with `Error: Can't find a working Python installation`.
Linux version.
```
$ scons
scons: Reading SConscript files ...
Checking for linker -Wl,--as-needed support... yes
Checking for pkg-config package protobuf... yes
Checking for compiler -gz support... no
Warning: Can't enable object file debug section compression
Checking for linker -gz support... no
Warning: Can't enable executable debug section compression
Info: Using Python config: python3-config
Checking for C header file Python.h... yes
Checking for C library python3.7m... yes
Checking for C library crypt... yes
Checking for C library pthread... yes
Checking for C library dl... yes
Checking for C library util... yes
Checking for C library rt... yes
Checking for C library m... yes
Checking Python version... no
Error: Can't find a working Python installation
```

**Comment by mwichmann** [comment]
Will gently point out that the template has left a very prominent notice in this issue requesting you come to the mailing list or the discord chat first....

What is this coming from?  We don't know what check is being performed to determine if Python is "working" (it's probably missing header files, but could be something else).  There's certainly a working Python on your system since it's busy running scons in the first place...

**Comment by HaFred** [comment]
Thank you for the reply. Sorry that I did not join the mailing list first…
I wonder is it possible to somehow add the PYTHONPATH into scons such that it could detect the socalled ‘python installation’? By entering python directly, I can activate python no problem.

Best Regards,
HaFred

**Comment by mwichmann** [comment]
Will ask again - what is the actual check?  This isn't scons telling you it can't find Python, because it's using it.  There's something in your sconscripts that is trying to "detect" Python's usability for some purpose.

**Comment by mwichmann** [comment]
By the way, the guess off this limited information is you don't have the Python development package installed (e.g. python3-devel or some similar name) and whatever configuration check is running is looking for that.

**Comment by HaFred** [comment]
Hi Mats,
Actually I am using scons for gem5 build. I found that the error came from the sconstruct file, line560 where the py_version stays as false.

This may be not a scons issue. Thank you for the help.

On 26 Mar 2021, at 23:45, Mats Wichmann ***@***.***> wrote:

﻿

By the way, the guess off this limited information is you don't have the Python development package installed (e.g. python3-devel or some similar name) and whatever configuration check is running is looking for that.

**Comment by bdbaddog** [comment]
This is not a SCons issue, but rather an issue with gem5.

Here's the function which fails and issues that message:
https://gem5.googlesource.com/public/gem5/+/refs/heads/stable/site_scons/gem5_scons/configure.py#89

Likely you don't have the python development packages, or they're installed but not in the default location.

Furthermore. It looks like you can specify a non-default location for python-config on the command line.


Have you read: http://www.gem5.org/documentation/general_docs/building

Also gem5 has a mailing list where you can ask about this issue.
https://www.gem5.org/mailing_lists/

Good luck.
I'll close this bug.

**Comment by xueruini** [comment]
https://www.gem5.org/documentation/learning_gem5/part1/building/
> We support GCC Versions >=7, up to GCC 11We support GCC Versions >=7, up to GCC 11

please check whether you're using gcc 11 and above.
