### ISSUE TITLE
CacheDir hiding error messages, and silently rebuilding on cache retrieve fail

### ISSUE THREAD

**Issue by dmoody256** [SCons/scons#3935]
**Describe the bug**
Sometimes when retrieving files from the cache we seem to get stale file handle OSError exceptions from our filesystem. SCons catches this and then proceeds to build the file it failed to pull from the cache. This still produces a correct build, but we have a hard time understanding what was going on because scons was not printing more information about what had happened.

When I have time I will add a reproducer and get more info, but my current theory is that we are landing here and getting through the exception silently: https://github.com/SCons/scons/blob/master/SCons/Action.py#L1285-L1308

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed with @bdbaddog in mongodb standup
* Version of SCons
mongodb vendored scons ~= 3.1.2
* Version of Python
3.7, 3.9 (with opt enabled)
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
N/A
* How you installed SCons
local source
* What Platform are you on? (Linux/Windows and which version)
Redhat linux 6 and 7
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
I will add one when I have time to write it up
* How you invoke scons (The command line you're using "scons --flags some_arguments")
various ways, I will add this when I write up a repro

**Comment by mwichmann** [comment]
Hmmm, I wonder if line 1635 was supposed to be `SConsEnvironmentError` - that one got renamed a while back to try to not conflict with Python's `EnvironmentError` ... which is now merged into `OSError`. And that irritating comment about backwards compat and "don't have time to fix"...
