### ISSUE TITLE
setup.py install: error: can't copy 'build/doc/man/scons.1': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by smcpeak** [SCons/scons#3950]
Following the instructions at https://scons.org/doc/production/HTML/scons-user.html , I downloaded http://prdownloads.sourceforge.net/scons/scons-4.1.0.tar.gz and, after unpacking, ran:

```
$ python setup.py install --prefix=$HOME/opt/scons-4.1.0
[...]
installing package data to build/bdist.cygwin-3.2.0-x86_64/egg
running install_data
error: can't copy 'build/doc/man/scons.1': doesn't exist or not a regular file
$
```

This looks like the same issue as #3881.  I am filing a new issue because the reporter of that issue didn't provide all the requested information (specifically where they got their tarball) and stopped responding, so I can't be sure it is the same.

I understand that #3812 is the presumed fix.  However, months later, the distribution tarball on Sourceforge is not fixed.  Meanwhile, the documentation continues to direct people there and to run a command that does not work.

I also understand that running `setup.py` is not the suggested method of installation.  Let me explain why I went this route and why I think it is important to fix.  I've never used SCons, but I found the description in the documentation appealing, so I wanted to try it.  But I've been repeatedly burned by Python package installations with `pip` that broke my Python install.  I imagine that being on Windows (with zillions of variables in play) contributes to these issues.  So when SCons offered me the chance to install itself in a way that appeared safe and easily reversible, I took it.  I think some other potential SCons users will do the same, so I suggest either fixing the tarball on Sourceforge or not sending people there.

For the benefit of those who might run into the same issue and find my report, a better download source is https://pypi.org/project/SCons/#files , which has [SCons-4.1.0.post1.tar.gz](https://files.pythonhosted.org/packages/be/d0/bf4e7003369c6d8a6e490741c54791c7918d9ef10b56aec201e76706f1d7/SCons-4.1.0.post1.tar.gz).  That tarball does not have this bug.

**Required information**
* SCons Users thread discussing your issue: none.  (It seems clear this is a bug, so I am reporting it.)
* Version of SCons: scons-4.1.0
* Version of Python: Python 3.8.10
* Which python distribution if applicable: cygwin
* How you installed SCons: The installation itself failed: `python setup.py install`.
* What Platform are you on? Windows 10 Home, version 20H2, OS build 19042.985
* How to reproduce your issue?  Download the above linked tarball and run the command above.
* How you invoke scons: I did not get that far.

**Comment by mwichmann** [comment]
Indeed, it looks like the tarball was updated for PyPi but not SourceForge.

**Comment by bdbaddog** [comment]
@smcpeak - that's why we recommend installing SCons into a virtualenv. You won't affect your python install.
(And if you're not using it regularly.. I highly recommend it.. especially in conjunction with virtualenvwrapper)

Just pushed 4.1.0.post1 to sourceforge and updated the website.
Please try again and let us know if that resolves it.

**Comment by smcpeak** [comment]
I just now went to https://scons.org/pages/download.html and followed the links to the new [scons-4.1.0.post1.tar.gz](http://prdownloads.sourceforge.net/scons/scons-4.1.0.post1.tar.gz).  With this new tarball, the `setup.py` command I originally tried worked--thank you!  So I confirm the fix and am closing this issue.

However, I'll note this tarball is not identical to the [scons-4.1.0.post1.tar.gz on pypi.org](https://files.pythonhosted.org/packages/be/d0/bf4e7003369c6d8a6e490741c54791c7918d9ef10b56aec201e76706f1d7/SCons-4.1.0.post1.tar.gz).  The differences look unimportant, being timestamps and changes in `PKG-INFO` files.

For completeness, I will also note that installing `scons` this way does not produce an installation that works in the way the manual suggests because it will say `PackageNotFoundError: SCons`.  One must set `PYTHONPATH` as well, in my case to `$HOME/opt/scons-4.1.0/lib/python3.8/site-packages/SCons-4.1.0.post1-py3.8.egg`.  (If this is not intentional, let me know and I'll file another issue.)

> @smcpeak - that's why we recommend installing SCons into a virtualenv.

That sounds appealing (maybe it would eliminate the need to set `PYTHONPATH`?) but I don't see that recommendation in [scons-user.html](https://scons.org/doc/production/HTML/scons-user.html).

**Comment by mwichmann** [comment]
Interesting.  I'll add this to a list of doc things to look at.

(and yes, a virtualenv with pip should eliminate any PYTHONPATH problem, as it will bave been installed through python, which thus knows where the installation is )

**Comment by barracuda156** [comment]
Still broken with 4.3.0.
```
running install_data
creating /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_scons/scons/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.10/share
creating /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_scons/scons/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.10/share/man
creating /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_scons/scons/work/destroot/opt/local/Library/Frameworks/Python.framework/Versions/3.10/share/man/man1
error: can't copy 'scons.1': doesn't exist or not a regular file
Command failed:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_scons/scons/work/scons-4.3.0" && /opt/local/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 setup.py --no-user-cfg install --prefix=/opt/local/Library/Frameworks/Python.framework/Versions/3.10 --root=/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_scons/scons/work/destroot 
Exit code: 1
```

**Comment by smcpeak** [comment]
@barracuda156 This issue was filed for a problem with the 4.1.0 tarball on Sourceforge, and closed when a fixed 4.1.0 tarball was published there.  If there is a problem with the 4.3.0 tarball, even if the symptom appears identical, a new issue should be opened, with a link to the specific tarball that has a problem.

**Comment by bdbaddog** [comment]
@barracuda156 - As @smcpeak suggests, please open a new issue and include where downloaded (URL) the tarball for scons 4.3.0? Are you using python 3.10 from macports? (other?) Which version of MacOS?

**Comment by barracuda156** [comment]
> @barracuda156 - As @smcpeak suggests, please open a new issue and include where downloaded (URL) the tarball for scons 4.3.0? Are you using python 3.10 from macports? (other?) Which version of MacOS?

GitHub version fails with being unable to copy `scons.1`. PyPi version installs fine though.

Yes, Macports environment, macOS 10.6.

**Comment by bdbaddog** [comment]
> > @barracuda156 - As @smcpeak suggests, please open a new issue and include where downloaded (URL) the tarball for scons 4.3.0? Are you using python 3.10 from macports? (other?) Which version of MacOS?
> 
> GitHub version fails with being unable to copy `scons.1`. PyPi version installs fine though.
> 
> Yes, Macports environment, macOS 10.6.

If you download the github repo, it doesn't contain a built tree and so setup.py won't work.  You'd have to install the required document tools on your system, run `scripts/scons.py` and let it build a tree. Or you can just download it from sourceforge where there are built packages for download. Or you can use pypi. So your problem is not a bug, it is expected.

**Comment by mwichmann** [comment]
To be a little more precise, `setup.py install` is what won't work.  If you build first, as @bdbaddog says, you might be okay. The "build" is, in fact, the rather complex generation of the documentation.

**Comment by bdbaddog** [comment]
If you have further questions, please bring them to the [users mailing list](https://scons.org/lists.html#users), IRC channel, or our [discord server](https://discord.gg/bXVpWAy).
I'm locking this issue.
