### ISSUE TITLE
SCons  $( $) in command when linking shared object due to _LIBDIRFLAGS content.

### ISSUE THREAD

**Issue by augfab** [SCons/scons#3955]
**Describe the bug**
When linking a shared object (from C or C++ sources, on Ubuntu), the command printed by SCons still contains the `$( $)` of `_LIBDIRFLAGS`. When `LIBPATH` is not empty, all `-L/path/to/libs` appear between `$(` and `$)`. When `LIBPATH` is empty, a bare `$( $)` is printed.
This is a problem because the command can't be copied-and-pasted as-is in a shell for debug purposes.
This doesn't happen when creating a static object or an executable (`Program`).
See reproducer below (or [here](https://gist.github.com/augfab/3968d42c876f2188548fc5d2154a9551)).

**Required information**

* Link to SCons Users thread discussing your issue.
Discussed with @mwichmann and @bdbaddog in ircs://irc.libera.chat:6697/#scons on 2021-06-09 and 2021-06-10.

* Version of SCons
```
$ scons --version
SCons by Steven Knight et al.:
	SCons: v4.1.0.post1.dc58c175da659d6c0bb3e049ba56fb42e77546cd, 2021-01-20 04:32:28, by bdbaddog on ProDog2020
	SCons path: ['/home/augfab/.local/lib/python3.6/site-packages/SCons']
Copyright (c) 2001 - 2021 The SCons Foundation
```
 
* Version of Python
```
$ python3 --version
Python 3.6.9
```

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
Python installed with:
```
# apt install python3
```
* How you installed SCons
```
$ python3 -m pip install --upgrade SCons
```
* What Platform are you on? (Linux/Windows and which version)
```
$ uname -a
Linux *** 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
```c
/* foo.c */
int foo(void) { return 42; }
```
```c++
// bar.cc
int bar() { return 42; }
```
```c++
// baz.cc
extern int bar();
int main() { return bar(); }
```
```python
# SConstruct
SharedLibrary("foo.c")
SharedLibrary("bar.cc", LINKPATH=["."])
Program("baz.cc", LIBS=["bar"], LIBPATH=["."])
```

* How you invoke scons (The command line you're using "scons --flags some_arguments")
```$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o bar.os -c -fPIC bar.cc
g++ -o baz.o -c baz.cc
g++ -o libbar.so  -shared   bar.os $( -L. $) 
g++ -o baz baz.o -L. -lbar
gcc -o foo.os -c -fPIC foo.c
gcc -o libfoo.so  -shared   foo.os $(  $) 
scons: done building targets.
```

**Comment by bdbaddog** [comment]
@augfab - Thanks for the thorough and complete issue report! Makes it much easier for us poor maintainers to address!!
