### ISSUE TITLE
Move Linux CI builds off travis-ci.org

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3960]
This change was anticipated, but our builds are no longer running:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 

We need to move those to either .com, where we think we'll run out of free minutes pretty quickly; or to github actions; or to some other free CI - circleci has a "free credits" system, like travis-ci now has.

**Comment by bdbaddog** [comment]
Hmm. Let's try travis-ci.com and see if the "free minutes is sufficient"?

**Comment by mwichmann** [comment]
Sure. There's AppVeyor too... we didn't pursue them further because they already limited stuff more than the old travis-ci

**Comment by mwichmann** [comment]
This is done, right?

**Comment by bdbaddog** [comment]
Yup!
