### ISSUE TITLE
remove $TEMPFILEPREFIX or replace with a space

### ISSUE THREAD

**Issue by moaheux** [SCons/scons#3964]
**Describe the Feature**

There is no way to remove the default  `TEMPFILEPREFIX` of `@` from the `TEMPFILE` invocation name. White spaces are not recognized by scons. Calling `env['TEMPFILEPREFIX'] = ' ' `is not taken into account.
I'm using C2000 compiler and put all of my object files into a temp file to get over the limit of characters in mingw.  
Using
`c2000 --run_linker _tempfile_ `
the _tempfile_ must be called with no prefix.

I managed to find a workaround modify `Platform/__init__.py`
line 239 replace
```python
        prefix = env.subst('$TEMPFILEPREFIX')
        if not prefix:
            prefix = '@'
```

with 

```python
        prefix = env.subst('$TEMPFILEPREFIX')
        if not prefix and "False" == prefix.isspace():
            prefix = '@'
```

It's not pretty but does the job.

**Required information**
* Link to SCons Users thread discussing your issue.
https://github.com/SCons/scons/issues/2284
* Version of SCons
 SCons: v4.1.0.post1.12f24df0004ced8b91e758f29cd6396e60f37f5a

* Version of Python
 Python 3.9.0
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
 python.org
* How you installed SCons
 Sourceforge repo
* What Platform are you on? (Linux/Windows and which version)
 Windows 10
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
env['TEMPFILEPREFIX'] = ' '
${TEMPFILE("time to test it")}

the ouput will display the call of the temp file with a @ as first character
* 
* How you invoke scons (The command line you're using "scons --flags some_arguments")
scons some_arguments

**Additional context**

**Comment by mwichmann** [comment]
I think we call this a bug, as the docstring for `TempFileMunge` includes an example of the usage that doesn't work:
```
    By default, the name of the temporary file used begins with a
    prefix of '@'.  This may be configured for other tool chains by
    setting the TEMPFILEPREFIX variable. Example::

        env["TEMPFILEPREFIX"] = '-@'        # diab compiler
        env["TEMPFILEPREFIX"] = '-via'      # arm tool chain
        env["TEMPFILEPREFIX"] = ''          # (the empty string) PC Lint

```
