### ISSUE TITLE
WINDOWS_INSERT_DEF does not behave as documented

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3968]
scons-users thread: https://pairlist4.pair.net/pipermail/scons-users/2021-July/008576.html

The manpage (using generated file from original `SCons/Tool/mslink.xml`) makes this claim:

> When this is set to true, a library build of a Windows shared library (`.dll` file) will also build a corresponding `.def` file at the same time, if a `.def` file is not already listed as a build target. The default is `0` (do not build a `.def` file). 

but there is no indication that code actually intended to *build* the module-definition file. Instead if the construction var evaluases true, a `.def` filename is generated from the library name, and added to the source list.  A different routine looks for a `.def` file in the source list and turns it into the appropriate commandline option. 

Tagging this as a documentation problem as there doesn't look like there was ever any intent to try to generate the file, just to include it. Reviewers may of course feel free to disagree.

**Comment by mwichmann** [comment]
For reference, this ithe cmake feature that tries to generate the file, that would clearly require significant development work: https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html

**Comment by bdbaddog** [comment]
So cmake uses an external executable to extract this info from the object files.
Source here: https://github.com/Kitware/CMake/blob/209daa20b2bd2ee2a76e70af58e895647f7e284f/Source/bindexplib.cxx
Whose logic was originally copied from cern root..
```Portions of this source have been derived from the 'bindexplib' tool
  provided by the CERN ROOT Data Analysis Framework project (root.cern.ch).
  Permission has been granted by Pere Mato <pere.mato@cern.ch> to distribute
  this derived work under the CMake license.```

**Comment by mwichmann** [comment]
Dp we want to track a feature request to generate the .def file (I'm inclined to say no)?
