### ISSUE TITLE
missing example code on SCons wiki

### ISSUE THREAD

**Issue by jatin837** [SCons/scons#3990]
# code example is missing [on the tutorial page](https://github.com/SCons/scons/wiki/SconsTutorial1)
![Screenshot from 2021-08-02 14-10-35](https://user-images.githubusercontent.com/63631162/127831479-57930937-8ed9-40e0-bd7f-12f8101fdffa.png)
![Screenshot from 2021-08-02 14-12-43](https://user-images.githubusercontent.com/63631162/127831676-09fec110-00d8-4c34-b4aa-dc086e884bfa.png)

**Comment by mwichmann** [comment]
The conversion to Github's wiki has not been smooth.  The tutorial is still where it used to be, but github flattens local links on the way through, so because it points to a file in a subdirectory there's no way to reach it.  We'll figure out how to fix it up.

**Comment by mwichmann** [comment]
That should be resolved now. Please reopen if it isn't.

**Comment by jatin837** [comment]
Is there a possibility for me to understand and fix this issue.
I mean some directory where this issue might have arose.
Thanks

**Comment by mwichmann** [comment]
For this one, I put the full URL in as the link, and it turns out the old link was actually not a wiki link (the usual problem), but was pointing to an address on the previous wiki site (which is no longer available).  So the relevant part of the diff looks like this - probably not very interesting to you (looks like this case was missed in the wiki conversion):
```
-Code: [sconstutorial2.tar.gz](https://bitbucket.org/scons/scons/wiki/SconsTutorial2/sconstutorial2.tar.gz) 
+Code: [sconstutorial2.tar.gz](https://github.com/SCons/scons/wiki/SconsTutorial12/sconstutorial2.tar.gz) 
```

**Comment by mwichmann** [comment]
well, this was for the second tutorial, which had the same problem, but you get the idea...

**Comment by mwichmann** [comment]
It also looks like the downloadable files may be partly corrupt - I get `gzip: sconstutorial1.tar.gz: unexpected end of file` when trying to unpack...

**Comment by bdbaddog** [comment]
Hmm. It's possible I have those sitting somewhere from the initial migration from the wiki hosted on scons.org.
I'll see if I can dig it up.
I found 5 copies so far but they're all corrupt.
