### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ghost** [SCons/scons#4011]
Why i get error if type help command?
Python 3.8.10
Scons 4.2.0
![Безымянный](https://user-images.githubusercontent.com/64489444/131680807-3b5b91f2-32f5-428b-ae24-39e820ce0c88.png)

**Comment by bdbaddog** [comment]
Can you paste the output of `gcc --version` ?

**Comment by ghost** [comment]
![Безымянный](https://user-images.githubusercontent.com/64489444/131846980-f363dd50-10aa-4539-aada-3236939094d9.png)
I use TDM on windows. In linux all works. I install SCons from pip and github rep (setup.py) but all of it not works

**Comment by bdbaddog** [comment]
> ![Безымянный](https://user-images.githubusercontent.com/64489444/131846980-f363dd50-10aa-4539-aada-3236939094d9.png)
> I use TDM on windows. In linux all works. I install SCons from pip and github rep (setup.py) but all of it not works

Please copy and paste the text and not a screenshot.
The text will help us debug the issue. 
Maybe redirect the output to a file and attach that.

**Comment by ghost** [comment]
[gcc.txt](https://github.com/SCons/scons/files/7101547/gcc.txt)
This archive contained scons script, simple C++ program and scons output txt: [test.zip](https://github.com/SCons/scons/files/7101665/test.zip)

**Comment by bdbaddog** [comment]
What locale/language is your computer set up with?

**Comment by mwichmann** [comment]
If you're up for trying a patch to your SCons installation, I'd be curious the effect of this (only changes one line):
```python
diff --git a/SCons/Tool/gcc.py b/SCons/Tool/gcc.py
index 6470002f1..7e3859987 100644
--- a/SCons/Tool/gcc.py
+++ b/SCons/Tool/gcc.py
@@ -88,7 +88,8 @@ def detect_version(env, cc):
         line = SCons.Util.to_str(pipe.stdout.readline())
         # Non-GNU compiler's output (like AIX xlc's) may exceed the stdout buffer:
         # So continue with reading to let the child process actually terminate.
-        while SCons.Util.to_str(pipe.stdout.readline()):
+        # We don't need to know the rest of the data, so don't bother decoding.
+        while pipe.stdout.readline():
             pass
 
 
```

As to "why do I get this if I ask for help":  if you use `scons --help`, scons will try to print any locally defined help as well, which means it has to read the sconscript files, which means the compiler and other tool detection gets done.  If you do `scons -H` (capital letter) it will just print the help without any processing and would not trip across this issue.

**Comment by ghost** [comment]
> 
> 
> What locale/language is your computer set up with?

I use Russian lang: chcp 1251
Also i set 65001 code page but error didn't fix

**Comment by bdbaddog** [comment]
Did @mwichmann 's sugguested fix above work?

If not try changing SCons/Util.py's `to_str()` to the following

```
def to_str(s) -> str:
    if s is None:
        return 'None'
    if is_String(s):
        return s
    return str(s, 'utf-8', errors='ignore')
```

**Comment by ghost** [comment]
Thank u, this works!

**Comment by bdbaddog** [comment]
Glad that worked!

Reopening. This change is not yet in the code.
We'll close this when we fix it and it will be noted in the release notes.

**Comment by mwichmann** [comment]
I'll push the change presently, have it sitting here.
