### ISSUE TITLE
Generator functions in Textfile subst expansion are being called with for_signature=True

### ISSUE THREAD

**Issue by acmorrow** [SCons/scons#4037]
**Describe the bug**
The following program used to write `val` to `target`, but with current HEAD, it now writes `sig`:

```python
env = Environment()

def generator(source, target, env, for_signature):
    if for_signature:
        return "sig"
    return "val"

env['GENERATOR'] = generator

env.Textfile(
    target="target",
    source=[
        "@generated@",
    ],
    SUBST_DICT={
        '@generated@' : '$GENERATOR',
    },
)
```

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed on discord with @bdbaddog and @mwichmann.

* Version of SCons
HEAD

* Version of Python
N/A

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
N/A

* How you installed SCons
Clone of master

* What Platform are you on? (Linux/Windows and which version)
Linux, but I'm pretty sure this is platform independent

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
See the above repo. With SCons 4.2 and older the file `target` will be produced and contain `val`, but on HEAD at f6cefb239a24f4662b4b06307d1c9099583a130e it now contains `sig`. This broke one of the MongoDB custom tools.

* How you invoke scons (The command line you're using "scons --flags some_arguments")
You can run the above reproducer just by running `scons`.

**Comment by bdbaddog** [comment]
Likely this is coming to light due to pr #4021  where `env.subst()` is now called with `env.subst(value, raw=1)` to avoid incorrectly subst'ing `$$(`

**Comment by mwichmann** [comment]
Okay, after getting a headache going through needless recursion, it's pretty clear where this comes from: in `StringSubber`'s `expand` method: 
```python
                s = s(target=lvars['TARGETS'],
                     source=lvars['SOURCES'],
                     env=self.env,
                     for_signature=(self.mode != SUBST_CMD))
```
The mode comes straight down from how we were called into this chain - the value of `raw` to the `env.subst` call (which is made by the Textfile action) is eventually saved as `self.mode`.  My tenous grasp of logic suggests that last kwarg should maybe be `for_signature=(self.mode == SUBST_SIG)`.  Wonder how much stuff that would break...

**Comment by mwichmann** [comment]
surprisingly, it breaks nothing in the testsuite, and fixes the case in this report.

**Comment by bdbaddog** [comment]
Yup. Seems like the right solution to me!
That codes from 2005.. :)
