### ISSUE TITLE
unicode paths break SCons

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#589]
This issue was originally created at: 2003-07-23 11:17:12.
This issue was reported by: `issues@scons`.
issues@scons said at 2003-07-23 11:17:12
>(submitted by: Steve Christensen, 
>stnchris@xmission.com) 
> 
>On XP, if I have a path in my INCLUDE/LIB/PATH 
>environment variables that include extended 
>characters, I get the following exception: 
> 
> ... 
>  File 
>+"..\..\..\SoftwareCM_admin_vob\scons\scons-local-0.90\SCons\Tool\mslink.py", 
>+line 176, in generate 
>      env.PrependENVPath('INCLUDE', include_path) 
>  File 
>+"..\..\..\SoftwareCM_admin_vob\scons\scons-local-0.90\SCons\Environment.py", 
>+line 292, in PrependENVPath 
>      nv = SCons.Util.PrependPath(orig, newpath, 
>sep) 
>  File 
>"..\..\..\SoftwareCM_admin_vob\scons\scons-local-0.90\SCons\Util.py", 
>+line 866, in PrependPath 
>      if path and not normpath in normpaths: 
>UnicodeError: ASCII decoding error: ordinal not in 
>range(128) 
> 
> 
> 
>I modified util.py::PrependPath() to catch the 
>exception and print the variables, which pointed to 
>the following as the cause: 
> 
>normpath: 
>  
>m:\myview_latest\pub_inhouse_vob\include\gui\wtl\bjarke 
>viks°e 
> 
>normpaths: 
>[u'c:\\program files\\microsoft visual studio .net 
>2003\\vc7\\include', 
>u'c:\\program files\\microsoft visual studio .net 
>2003\\vc7\\atlmfc\\include', 
>u'c:\\program files\\microsoft visual studio .net 
>+2003\\vc7\\platformsdk\\include\\prerelease', 
>u'c:\\program files\\microsoft visual studio .net 
>+2003\\vc7\\platformsdk\\include', 
>u'c:\\program files\\microsoft visual studio 
>.net\\frameworksdk\\include', 
>'c:\\program files\\microsoft visual studio .net 
>2003\\sdk\\v1.1\\include', 
>'c:\\program files\\microsoft visual 
>studio\\vc98\\atl\\include', 
>'c:\\program files\\microsoft visual 
>studio\\vc98\\mfc\\include', 
>'c:\\program files\\microsoft visual 
>studio\\vc98\\include'] 
> 
> 
>If I run python in that directory, I can reproduce the 
>problem: 
> 
>M:\myview_latest\pub_inhouse_vob\include\GUI\WTL\Bjarke 
>Viksøe>python 
>ActivePython 2.2.2 Build 224 (ActiveState Corp.) 
>based on 
>Python 2.2.2 (#<span></span>37, Nov 26 2002, 10:24:37) [MSC 32 
>bit (Intel)] on win32 
>Type "help", "copyright", "credits" or "license" for 
>more information. 
>>>> import os 
>>>> import os.path 
>>>> cwd = os.path.abspath('.') 
>>>> print cwd 
>M:\myview_latest\pub_inhouse_vob\include\GUI\WTL\Bjarke 
>Viks°e 
>>>> cwd 
>'M:\\myview_latest\\pub_inhouse_vob\\include\\GUI\\WTL\\Bjarke 
>Viks\xf8e' 
>>>> unicode(cwd) 
>Traceback (most recent call last): 
>   File "<stdin>", line 1, in ? 
>UnicodeError: ASCII decoding error: ordinal not in 
>range(128) 
>>>> unicode(cwd,'mbcs') 
>u'M:\\myview_latest\\pub_inhouse_vob\\include\\GUI\\WTL\\Bjarke 
>Viks\xf8e' 
>>>> 
> 
> 
>What's the correct way to handle this exception? And 
>how widespread is 
>the problem going to be?

issues@scons said at 2003-07-23 11:17:12
>Converted from SourceForge tracker item 776434

gregnoel said at 2008-03-16 20:40:24
>To do this properly requires sys.getfilesystemencoding() which isn't available
>until Python 2.3 and sys.getdefaultencoding() which isn't available until 2.0. 
>Both methods are implemented in C.
> 
>It's probably not possible to write a sys.getdefaultencoding() method in pure
>Python, but for Python 2.0 and greater, a sys.getfilesystemencoding() method can
>probably be written that does the right thing for M$-DOS and Mac, then hopes
>that the system default encoding is used on *NIX.  That would work in virtually
>all cases; the exception can be documented.
> 
>Getting all the conversions right will take almost a line-by-line reading of the
>code to find all the needed places.

garyo said at 2008-03-17 20:28:03
>Milestone: 2.x.

Votes for this issue: 4.

**Comment by ajf58** [comment]
SCons 3.0.1 with Python 3.5+ on Windows demonstrates good Unicode support. I suggest closing this as fixed.

**Comment by bdbaddog** [comment]
Closing. This issue should be resolved by using py3.5+.
